### ISSUE TITLE
event not opened in ios

### ISSUE THREAD

**Issue by mario35** [mattlewis92/angular-bootstrap-calendar#100]
Your calendar is awesome, modern, and works great.

I have a problem with my own code and your demo exemple on ios I can't open event 

Thanks in advance !

**Comment by mattlewis92** [comment]
It's because of the 300ms click delay on touch devices. If you include the [ngTouch](https://docs.angularjs.org/api/ngTouch) module it will fix the problem for you. I'll add a note to this in the docs later :)

**Comment by mario35** [comment]
thanks a lot I going to try that.

**Comment by mario35** [comment]
It work very well thank you
