### ISSUE TITLE
Day View not rendering in firefox 38.0.5

### ISSUE THREAD

**Issue by nttheist** [mattlewis92/angular-bootstrap-calendar#101]
set the calendarView = 'day' , chrome renders correctly, firefox renders nothing. No errors in console.

**Comment by mattlewis92** [comment]
It works ok for me in firefox, please can you provide me with a reproduceable plunker or something similar please

**Comment by nttheist** [comment]
Due to my situation I cannot, however if i view vm.changeView it is undefined. Unsure of why it would render correctly in chrome and not ff. Sorry for this, at least I know its an issue on my end.

**Comment by mattlewis92** [comment]
Unless you can share some sample code with me that replicates your error there's not much I can do to help. Sorry.
