### ISSUE TITLE
Preview Events

### ISSUE THREAD

**Issue by stanleygomesdasilva** [mattlewis92/angular-bootstrap-calendar#102]
Hi!

I would like to know if there's any way to preview events like fullcalendar.

Thanks.

![wall](https://cloud.githubusercontent.com/assets/5298153/8458221/3766c270-1fec-11e5-8f64-fd324e44d66a.jpg)

**Comment by mattlewis92** [comment]
Other than by using the tooltip, there isn't a way to do this. Your best bet is to use some custom CSS and override [this template](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthEventsList.html). It's something I might add one day as an option.

**Comment by stanleygomesdasilva** [comment]
Thanks @mattlewis92 I'll try it.

**Comment by mattlewis92** [comment]
I had a look into this as it's not easy to add due to event spanning multiple days. I hope you managed to find a suitable solution from what I suggested before :)
