### ISSUE TITLE
Month view is collapsed when there is not any pre-defined event

### ISSUE THREAD

**Issue by hudsonabtahi** [mattlewis92/angular-bootstrap-calendar#106]
Hi,
Your calendar is awesome and modern.
But I have a problem with the calendar as it is initially collapsed when there is no event defined for the month. If view switches to year and returns to month, or going to the next month and returning back it will be showed up. Any mistake in my initialization?

**Comment by mattlewis92** [comment]
It's intentional - I didn't see any point in showing an empty black box if there were no events.

**Comment by hudsonabtahi** [comment]
My case is that at first show an empty calendar and then user inserts its own events.
before inserting any event is like following:
![image](https://cloud.githubusercontent.com/assets/11538414/8559058/58da2518-254c-11e5-87d2-4a00aad65c54.png)
after inserting events:
![image](https://cloud.githubusercontent.com/assets/11538414/8559223/d9c6656e-254d-11e5-84e7-58f0dc8f1c64.png)

**Comment by mattlewis92** [comment]
Ah ok I see your point, I'll put out a fix soon :)

**Comment by mattlewis92** [comment]
Fixed in https://github.com/mattlewis92/angular-bootstrap-calendar/commit/7193e6c8ffc5e9bbf4c7934fe48af650b23a4a7e, will release 0.12.1 momentarily

**Comment by NisanurBulut** [comment]
hi thanks your calendar is perfect but ı have been  a problem for along time in calendar day week is responsive but in year segment, months are not responsive how can ı fix this problem ?
