### ISSUE TITLE
Question regarding loading events

### ISSUE THREAD

**Issue by debasreedash** [mattlewis92/angular-bootstrap-calendar#108]
Hi,

I am pulling in my event data from my server and since I have a lot of events, I would like to pull them in batches. I was wondering if there was a way to pull in events related to each month as they are loaded. For example when the page with the calendar is loaded for this month of July, I would only like to pull in July events. Then when the Next button is clicked I'd like to pull in august events. I have already written a function to pull my data in batches for the dates I want, but I don't know if there is a way to apply this. This would be to improve performance as over time, my data would increase a lot. 

Thanks,

Debbie

**Comment by mattlewis92** [comment]
That's easy enough to add. Setup a watcher in your controller on the date object you pass to the current-day attribute like so:
```
$scope.$watch(function() {
    return moment($scope.calendarDay).month();
}, function(month) {
    fetchEvents({month: month}).then(function(events) {
        $scope.events = events;
    });
})
```

**Comment by debasreedash** [comment]
oh cool. i will try that out.

**Comment by mattlewis92** [comment]
Closing as no action is required to make any fixes to the calendar. If you still need help though I'm happy to help! :)
