### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by licarus** [mattlewis92/angular-bootstrap-calendar#11]
Hi,
This seems to be the best angular based calendar to fit my need. But I'm having a trouble getting it to work. I followed exactly the instructions 3 times now and still can't get it to work. I copied all the folders and the files in them (dist, docs, src, templates) into my solution.
I wonder if you could help me out.

The initial problem I had was that it can't load the templates. So, I changed the templateUrl in angular-bootstrap-calendar.js to have the correct path. But then it doesn't show anything. I'm using latest chrome and the console doesn't show any errors. I copied and pasted the <mwl-calendar> in the markup and $scope.events in the script.

I got other calendar directive to work but it's not as good as yours. So, I hope you can help me.
Thanks

ps. I'm new with posting at github. So, I'm not sure if there's a better way to communicate with you besides opening a new issue.

**Comment by mattlewis92** [comment]
Sorry, there was an error in the docs. Make sure you are loading this js file instead:
angular-bootstrap-calendar-tpls.min.js

This one has the templates bundled in it which should solve your problem.

p.s. You can use [bower](http://bower.io/) to manage your frontend dependencies instead of manually downloading the files :)

**Comment by licarus** [comment]
Matt,
Thanks for the reply.
I changed the file loaded to use the tpls one. It did help with the template issue.
But I still can’t see it.

This is what it shows:

[cid:image001.png@01D02F4A.22A83A00]

I tried to change the “calendarView” in calender-view attribute to year, month, week, or day and still nothing.

Maybe the screenshot above indicates something I’m missing?

Thanks,
Latif
Ps. I do use bower to grab the files. But I copied the folders from bower_components folder into the my folder structure. Hopefully this doesn’t mess it up.

**Comment by mattlewis92** [comment]
Is there anything in the console? I can't see the image you sent in the email, can you send it via the github comments. Thanks.

**Comment by licarus** [comment]
Sorry, here's the image:
![image](https://cloud.githubusercontent.com/assets/10506886/5730178/b0c6ee26-9b3d-11e4-87d5-5086c88075a1.png)

**Comment by licarus** [comment]
Nothing in the console.

**Comment by mattlewis92** [comment]
Can you show me your index.html file

**Comment by licarus** [comment]
I tried to send you a file but it this doesn't take any file ther than jpg, gif or png.
I'm pasting the source file of the page I'm trying to work on. Sorry, it's a bit cluttered as I have something else on that page as well. let me know if this helps

<!doctype html>
<html xmlns:ng="http://angularjs.org" lang="en" id="ng-app" ng-app="ProviderApp">
<head>
    

    <meta charset="utf-8">
    <title>PWP</title>
    <meta name="viewport" content="user-scalable=yes, minimum-scale=0.75, maximum-scale=3.0">
    <meta name="description" content="">
    <meta name="author" content="Wonderbox Technologies LLC">

    
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>

    
    <script src="/Scripts/jquery-2.1.3.js?bundleVirtualPath=%7e%2fbundles%2fjquery"></script>
<script src="/Scripts/jquery-ui-1.11.2.js?bundleVirtualPath=%7e%2fbundles%2fjquery"></script>

    

    
    <link href="/Content/4221790.css" rel="stylesheet"/>

    
    <script src="/Scripts/bootstrap.js?bundleVirtualPath=%7e%2fbundles%2fbootstrap"></script>
<script src="/Scripts/select2.js?bundleVirtualPath=%7e%2fbundles%2fbootstrap"></script>
<script src="/Scripts/bootbox.js?bundleVirtualPath=%7e%2fbundles%2fbootstrap"></script>
<script src="/Scripts/respond.js?bundleVirtualPath=%7e%2fbundles%2fbootstrap"></script>

    <link href="/Content/site.css?bundleVirtualPath=%7e%2fContent%2fcss" rel="stylesheet"/>
<link href="/Content/font-awesome-4.2.0/css/font-awesome.min.css?bundleVirtualPath=%7e%2fContent%2fcss" rel="stylesheet"/>
<link href="/Content/select2/select2.css?bundleVirtualPath=%7e%2fContent%2fcss" rel="stylesheet"/>
<link href="/Content/css/fullcalendar.css?bundleVirtualPath=%7e%2fContent%2fcss" rel="stylesheet"/>
<link href="/Scripts/angular-bootstrap-calendar/dist/css/angular-bootstrap-calendar.min.css?bundleVirtualPath=%7e%2fContent%2fcss" rel="stylesheet"/>

    
    <script src="/Scripts/angular-file-upload-shim.js?bundleVirtualPath=%7e%2fbundles%2fangularjs"></script>
<script src="/Scripts/angular.js?bundleVirtualPath=%7e%2fbundles%2fangularjs"></script>
<script src="/Scripts/angular-file-upload.js?bundleVirtualPath=%7e%2fbundles%2fangularjs"></script>
<script src="/Scripts/angular-route.js?bundleVirtualPath=%7e%2fbundles%2fangularjs"></script>
<script src="/Scripts/angular-resource.js?bundleVirtualPath=%7e%2fbundles%2fangularjs"></script>
<script src="/Scripts/angular-cookies.js?bundleVirtualPath=%7e%2fbundles%2fangularjs"></script>
<script src="/Scripts/angular-select2.js?bundleVirtualPath=%7e%2fbundles%2fangularjs"></script>
<script src="/Scripts/ui-bootstrap-tpls-0.12.0.min.js?bundleVirtualPath=%7e%2fbundles%2fangularjs"></script>
<script src="/Scripts/ng-password-strength.js?bundleVirtualPath=%7e%2fbundles%2fangularjs"></script>

    <script src="/Areas/PWP/Scripts/App.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/WelcomeCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Dental/DentalClaimDashboardCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Dental/DentalClaimEntry.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/CatalogCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/ClaimStatusCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/ContactEditCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/ContactsCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/EligSearchCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/FooterCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/FrameEditCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/FramesCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/HistoryCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/HomeCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/LensCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/MemberCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/NavCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/PrescriptionCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/QueueCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/RegisterCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/ReviewCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/ServiceCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/SetupCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/SLCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/SubaccountCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/SubNavCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Vision/SupplierCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Shared/PatientManagementCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Areas/PWP/Scripts/Controllers/Shared/WelcomeCtrl.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>
<script src="/Scripts/SharedDirectives.js?bundleVirtualPath=%7e%2fbundles%2fpwp-angularjs"></script>

    <link href="/Content/less/wbxstyle.less?bundleVirtualPath=%7e%2fbundles%2fless" rel="stylesheet"/>

    
    <script src="/Scripts/jquery.placeholder.min.js"></script>

    
    <link href="/Content/validationEngine.jquery.css" rel="stylesheet" />

    <script src="/Scripts/moment.min.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/idle-timer.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/jquery.blockUI.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/jquery.validationEngine.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/jquery.validationEngine-en.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/jquery.maskMoney.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/autoNumeric.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/jquery.ba-throttle-debounce.min.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/underscore.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/underscore.string.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/angular-drag-and-drop-lists.min.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/angular-ui-calendar/calendar.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/angular-ui-calendar/fullcalendar.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>
<script src="/Scripts/angular-ui-calendar/gcal.js?bundleVirtualPath=%7e%2fbundles%2fglobal-js"></script>

    <script src="/Scripts/Controllers/DocumentsCtrl.js?bundleVirtualPath=%7e%2fbundles%2fcontrollers"></script>
<script src="/Scripts/Controllers/HomeCtrl.js?bundleVirtualPath=%7e%2fbundles%2fcontrollers"></script>
<script src="/Scripts/Controllers/LandingCtrl.js?bundleVirtualPath=%7e%2fbundles%2fcontrollers"></script>
<script src="/Scripts/Controllers/SetupCtrl.js?bundleVirtualPath=%7e%2fbundles%2fcontrollers"></script>

    <script src="/Scripts/jquery.inputmask/jquery.inputmask.js?bundleVirtualPath=%7e%2fbundles%2finputmask"></script>
<script src="/Scripts/jquery.inputmask/jquery.inputmask.extensions.js?bundleVirtualPath=%7e%2fbundles%2finputmask"></script>
<script src="/Scripts/jquery.inputmask/jquery.inputmask.date.extensions.js?bundleVirtualPath=%7e%2fbundles%2finputmask"></script>
<script src="/Scripts/jquery.inputmask/jquery.inputmask.numeric.extensions.js?bundleVirtualPath=%7e%2fbundles%2finputmask"></script>
<script src="/Scripts/jquery.inputmask/jquery.inputmask.phone.extensions.js?bundleVirtualPath=%7e%2fbundles%2finputmask"></script>
<script src="/Scripts/jquery.inputmask/jquery.inputmask.regex.extensions.js?bundleVirtualPath=%7e%2fbundles%2finputmask"></script>
<script src="/Scripts/angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls.min.js?bundleVirtualPath=%7e%2fbundles%2finputmask"></script>



</head>
<body>
    <div class="container">
        
    </div>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                        
<li><a href="/PWP/Dental" id="linkHome">Home</a></li>
<li>
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Claims<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="/PWP/Dental/ClaimEntry" id="linkDentalClaimEntry">Enter Dental Claim</a></li>
        <li><a href="/PWP/Dental/ClaimDashboard" id="linkClaimDashboard">Claim Dashboard</a></li>
        <li><a href="#">Search Claims</a></li>
    </ul>
</li>
<li><a href="/PWP/Dental/PatientManagement" id="linkPatientManagement">Patient Management</a></li>
<li ng-class="getClass('accountmanagement')"><a href="#">Account Management</a></li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Setup<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/Setup">User Profile</a></li>
                                <li><a href="/PWP/Setup/ManageSubAccounts">Manage Subaccounts</a></li>

                                </ul>
                            </li>
                            <li><a href="/Account/LogOff">Logout</a></li>
                        

                </ul>



            </div>
        </div>
    </nav>

    <div class="container">


        

<div ng-controller="PatientManagementCtrl" ng-init="Init()">
    <div class="row">
        <div class="col-xs-12">
            <h3>Patient Management <i class="fa fa-info-circle wbx-clickable-darker small" title="What's this?" ng-click="Info()"></i></h3>
        </div>
    </div>
    <div class="row wbx-drag-and-drop">
        <div class="col-xs-5">
            <div ng-repeat="(rosterType, rosterTypeList) in buckets.rosters">
                <h3>{{rosterType}} Roster</h3>
                <div ng-repeat="rosters in rosterTypeList">
                    <div ng-repeat="(rosterName, list) in rosters">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">{{rosterName}}</h3>
                            </div>
                            <div class="panel-body wbx-no-padding-right wbx-no-padding-left">
                                <div class="wbx-grid-header" ng-show="list.length > 0">
                                    <div class="wbx-div-column-subscriberid">Sub. ID</div>
                                    <div class="wbx-div-column-name">First Name</div>
                                    <div class="wbx-div-column-name">Last Name</div>
                                    <div>&nbsp;</div>
                                </div>
                                <ul dnd-list="list" class="wbx-grid-striped wbx-roster-body-scrollable">
                                    <li ng-repeat="patient in list"
                                        dnd-draggable="patient"
                                        dnd-effect-allowed="copy"
                                        dnd-selected="buckets.selected = patient"
                                        class="wbx-grid-data-row"
                                        ng-class="{'selected': buckets.selected === patient}">
                                        <div class="row">
                                            <div class="wbx-div-column-subscriberid wbx-table-column-ellipsis" title="{{patient.SUBSCRIBER_ID}}">
                                                {{patient.SUBSCRIBER_ID}}
                                            </div>
                                            <div class="wbx-div-column-name wbx-table-column-ellipsis" title="{{patient.FIRST_NAME}}">
                                                {{patient.FIRST_NAME}}
                                            </div>
                                            <div class="wbx-div-column-name wbx-table-column-ellipsis" title="{{patient.LAST_NAME}}">
                                                {{patient.LAST_NAME}}
                                            </div>
                                            <div class="wbx-custom-column pull-right">
                                                <a href="#">Select</a>
                                                <i class="fa fa-remove fa-lg"></i>
                                            </div>
                                        </div>
                                    </li>
                                </ul>

                                
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-1"></div>
        <div class="col-xs-6">
            <div class="wbx-container-info">
                <div class="wbx-container-title">Patient Calendar</div>
            </div>
            

            <button class="btn btn-default" ng-click="isCollapsed = !isCollapsed">Toggle collapse</button>
            <hr>
            <div collapse="isCollapsed">
                <div class="panel-body wbx-no-padding-right wbx-no-padding-left">
                    <div class="wbx-grid-header" ng-show="list.length > 0">
                        <div class="wbx-div-column-subscriberid">Sub. ID</div>
                        <div class="wbx-div-column-name">First Name</div>
                        <div class="wbx-div-column-name">Last Name</div>
                        <div>&nbsp;</div>
                    </div>
                    <ul dnd-list="list" class="wbx-grid-striped wbx-roster-body-scrollable">
                        <li ng-repeat="patient in buckets.rosters.System[0].System1"
                            dnd-draggable="patient"
                            dnd-effect-allowed="copy"
                            dnd-selected="buckets.selected = patient"
                            class="wbx-grid-data-row"
                            ng-class="{'selected': buckets.selected === patient}">
                            <div class="row">
                                <div class="wbx-div-column-subscriberid wbx-table-column-ellipsis" title="{{patient.SUBSCRIBER_ID}}">
                                    {{patient.SUBSCRIBER_ID}}
                                </div>
                                <div class="wbx-div-column-name wbx-table-column-ellipsis" title="{{patient.FIRST_NAME}}">
                                    {{patient.FIRST_NAME}}
                                </div>
                                <div class="wbx-div-column-name wbx-table-column-ellipsis" title="{{patient.LAST_NAME}}">
                                    {{patient.LAST_NAME}}
                                </div>
                                <div class="wbx-custom-column pull-right">
                                    <a href="#">Select</a>
                                    <i class="fa fa-remove fa-lg"></i>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

            
        </div>
    </div>

    <mwl-calendar calendar-events="events"
                      calendar-view="calendarView"
                      calendar-current-day="calendarDay"
                      calendar-control="calendarControl"
                      calendar-event-click="eventClicked($event)"
                      calendar-edit-event-html="'<i class=\'glyphicon glyphicon-pencil\'></i>'"
                      calendar-delete-event-html="'<i class=\'glyphicon glyphicon-remove\'></i>'"
                      calendar-edit-event-click="eventEdited($event)"
                      calendar-delete-event-click="eventDeleted($event)"
                      calendar-auto-open="true"
        ></mwl-calendar>
</div>

<script type="text/ng-template" id="modalContent.html">
    <div class="modal-header">
        <h3 class="modal-title">Event action occurred!</h3>
    </div>
    <div class="modal-body">
        <p>Action: <pre>{{ action }}</pre></p>
        <p>Event: <pre>{{ event | json }}</pre></p>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" ng-click="$modalInstance.close()">OK</button>
    </div>
</script>



    </div>


    <div><p style="text-align: center">
 <strong>Footer</strong></p>
</div><div class='block-divider'></div>


            <script>
                $(document).ready(function () {
                    window.modalActive = false;

                    function countdown() {
                        var secondsLeft = parseInt($('#idle-countdown').html());
                        if (secondsLeft == 0) {
                            window.location = "/Account/AutoLogout";
                        }
                        $('#idle-countdown').html(secondsLeft - 1);
                    }

                    $(document).idleTimer(1000 * 60 * 10); // start the timer

                    $(document).on("idle.idleTimer", function () {
                        if (!$.support.leadingWhitespace) {
                            //ie8
                            alert("You will now be logged out due to idle activity.");
                            window.location = "/Account/AutoLogout";
                            // end ie8
                        } else {
                            if (!window.modalActive) {
                                window.modalActive = true;
                                
                                window._timer = window.setInterval(countdown, 1000);

                                var timeVal = 60
                                $('.modal').modal('hide');
                                //$($('#auto-loggout').modal('show'));
                                $('#auto-loggout').modal('show');

                                $('#idle-countdown').html(timeVal);
                            }
                        }
                    });

                    $(document).on("active.idleTimer", function () {
                        //console.log("active");
                    });

                    $(document).on('click', '#cancel-auto-loggout', function () {

                        window.modalActive = false;

                        window.clearInterval(window._timer);
                        $('#auto-loggout').modal('hide');



                    });

                    $('#auto-loggout').on('hidden', function () {
                        window.modalActive = false;

                        window.clearInterval(window._timer);
                    });

                });
            </script>
            <div class="modal fade" role="dialog" id="auto-loggout">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            
                            <h3>Auto Log Out in <span id="idle-countdown"></span> seconds</h3>
                        </div>
                        <div class="modal-body">
                            <p>You have been idle for more than 10 minutes.  If you would like to continue working please select "Continue Working"</p>
                        </div>
                        <div class="modal-footer">

                            <span id="cancel-auto-loggout" class="btn btn-primary">Continue Working</span>
                            <a href="/Account/AutoLogout" class="btn">Log Out</a>
                        </div>
                    </div>
                </div>
            </div>
        




            
                <script type="text/javascript" src="/Scripts/jquery.md5.js"></script>
            


    <script type="text/javascript">
                
        $(document).ready(function () {
            generateIds();
        });

        function generateIds() {
            $(".btn, input[type=text], a, table, select").each(function (idx, element) {
                var hash = $.md5($(this)[0].outerHTML);
                if (this.id == "") {
                    $(this).attr("id", hash);
                }
            });
        }
        



        $(document).ready(function () {


            $("a[href^='http://']:not([href*='" + location.hostname + "']), [href^='https://']:not([href*='" + location.hostname + "'])")
                .attr("target", "_blank")
                .click(function (e) {
                    e.preventDefault();
                    bootbox.confirm('You are now leaving this secured website', function (selection) {
                        if (selection) {
                            window.location = e.currentTarget.href;
                        } else {
                            return true;
                        }
                    });
                });
        });
    </script>


<script type="application/json" id="__browserLink_initializationData">
    {"appName":"Chrome","requestId":"efe5bb5b6e5c45c79e96e5114c33abcc"}
</script>
<script type="text/javascript" src="http://localhost:63261/bbd1a82720dd4a3eafa1825d07e5d83f/browserLink" async="async"></script>


</body>
</html>

**Comment by licarus** [comment]
Sorry, didn't realize this page renders it like that. let me know if there's a better way to show you the file.

**Comment by mattlewis92** [comment]
Try setting these variables in the controller:
```
$scope.calendarView = 'month';
$scope.calendarDay = new Date();
```

See the demo controller for an example of what I mean:
http://mattlewis92.github.io/angular-bootstrap-calendar/docs/scripts/controllers/main.js

**Comment by licarus** [comment]
It worked. Yay!!!!
Didn't realize main.js is the demo controller. Silly me.
Thank you so much.

**Comment by mattlewis92** [comment]
NP :)
