### ISSUE TITLE
interact.js is not a good name for dependency?

### ISSUE THREAD

**Issue by pkeuter** [mattlewis92/angular-bootstrap-calendar#110]
Love your calendar! One little thingy: I use require.js to do AMD-loading. It appears that I'm unable to set paths when the name "interact.js" is used. Require.js then always tries to find the file in my servers root dir, where my .js files obviously aren't located. It all works fine though, when I change this to "interact".

I am not sure if I'm doing something wrong here. But I can imagine require.js has a hard time understanding the .js ending. So if this could be changed, that would be nice. If it cannot, please elaborate :-)

Thanks!

**Comment by mattlewis92** [comment]
Webpack makes this really easy to fix: https://github.com/mattlewis92/angular-bootstrap-calendar/commit/0b46553f237f9da45615e4c06705912edd7eb87a :)

I'll release it in 0.14.x which should come out in the next few days once I find the time to close the last few issues.

**Comment by pkeuter** [comment]
That's quick. Thanks!

**Comment by tam19** [comment]
I use "angular-bootstrap-calendar" of version 0.28.1. I do face this problem still. Require JS tries to find "interact.js" in the project root directory. Please help on the same.

**Comment by mattlewis92** [comment]
There is no usage of `interact.js` anywhere in this project anymore - it was all changed a while ago to use [`interactjs`](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/webpack.config.build.js#L46-L50). I'd recommend creating a minimal repo that reproduces your problem and posting it on stackoverflow where someone with better knowledge of require.js will be able to help you 😄
