### ISSUE TITLE
$compile error although calendar works fine

### ISSUE THREAD

**Issue by pkeuter** [mattlewis92/angular-bootstrap-calendar#111]
When I load the calendar, I get this message:

https://docs.angularjs.org/error/$compile/nonassign?p0=undefined&p1=mwlCalendar

The calendar works fine, and I have no idea why this doesn't work. Using Angular 1.3.17. The stacktrace doesn't tell anything very interesting. If you need more information, just shout :-)

**Comment by mattlewis92** [comment]
What does your <mwl-calendar> element look like (i.e. what attributes are you passing in)

**Comment by pkeuter** [comment]
<mwl-calendar view='calendarView' current-day="calendarDay" events="events" on-drill-down-click="calendarDrilldown">

All these items are bound to $scope

**Comment by mattlewis92** [comment]
Damn github, sorry I meant what options are you passing in like so:
```
<mwl-calendar
            events="vm.events"
            view="vm.calendarView"
            view-title="vm.calendarTitle"
            current-day="vm.calendarDay"
            on-event-click="vm.eventClicked(calendarEvent)"
            on-event-times-changed="vm.eventTimesChanged(calendarEvent); calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
            edit-event-html="'<i class=\'glyphicon glyphicon-pencil\'></i>'"
            delete-event-html="'<i class=\'glyphicon glyphicon-remove\'></i>'"
            on-edit-event-click="vm.eventEdited(calendarEvent)"
            on-delete-event-click="vm.eventDeleted(calendarEvent)"
            auto-open="true"
            day-view-start="06:00"
            day-view-end="22:00"
            day-view-split="30"
            cell-modifier="vm.modifyCell(calendarCell)">
          </mwl-calendar>
```

**Comment by pkeuter** [comment]
Yes, you are too fast ;-) I've added it in my previous post  but forgot to add the code tags, so it was invisible.

**Comment by mattlewis92** [comment]
Try adding the `view-title` attribute. I should probably make that optional :)

**Comment by pkeuter** [comment]
Ah yeah, you're right. That solves it. In your readme it doesn't say it's mandatory though. So you have to make it mandatory in your readme, or optional, like you said :-)

Thanks again!
