### ISSUE TITLE
Use tooltip-html or tooltip-template instead of tooltip-html-unsafe.

### ISSUE THREAD

**Issue by anthonyvialleton** [mattlewis92/angular-bootstrap-calendar#112]
Hi Matt,

Using **angular-bootstrap version 0.13.0** I get a deprecated warning : "tooltip-html-unsafe is now deprecated. Use tooltip-html or tooltip-template instead.".

Thanks you!

**Comment by mattlewis92** [comment]
That's intentional as ui-bootstrap 0.13 doesn't work properly with ng 1.4, so you have to use ui-bootstrap 0.12.x which doesn't have tooltip-html.

**Comment by anthonyvialleton** [comment]
yes I upgrade to angular 1.4.2 too and for my needs I didn't find lot of bugs (just one with tab element) but great to get this feeback. To keep your compatibilty I think to go back to ui-bootstrap 0.12.x.

Thanks

**Comment by mattlewis92** [comment]
AFAIK the modal and carousel are completely broken in ui-bootstrap 0.13.x, I'd say stick with 0.12 for now until they can release a version that's compatible.
