### ISSUE TITLE
Date validation [enhancement]

### ISSUE THREAD

**Issue by javenosa** [mattlewis92/angular-bootstrap-calendar#114]
First of all, thanks for your time and work. The plugin is very good.

I was using the demo for a while and I noted the lack of validations, for example, putting an end date lower than starter date. 

Simple example:
Start date: 07/07/2015
End date: 07/06/2015

If you can add this feature it will be amazing.

**Comment by mattlewis92** [comment]
I will make it discard any invalid events and log them to the console, but again the validation should be up to you. For example on the date picker input create a custom directive to validate that the end date is after the start date using something like [this](http://angularjs.io/how-to-create-a-custom-input-validator-with-angularjs/).

**Comment by javenosa** [comment]
Matt, again, thanks for your time and work.

I understand your point, but I don't think this feature is related to any specific business logic (as the other issue about event overlap), in my opinion this feature are extremely related to a calendar with events.

From my point of view these two features would add value to the plugin, maybe these features can be included in a future release. Anyway I understand your point.

Thanks
