### ISSUE TITLE
Event overlap [enhancement]

### ISSUE THREAD

**Issue by javenosa** [mattlewis92/angular-bootstrap-calendar#115]
The idea is configure the calendar to accept or avoid event overlap.
This feature will be good if the idea is use the calendar as reservation or booking system.

Thanks

**Comment by mattlewis92** [comment]
All adding and changing of events is purposefully not handled by the calendar so that you can perform validations like this yourself and alert the user etc. The calendar is deliberately designed not to contain any business logic like this to keep it as simple as possible.
