### ISSUE TITLE
Unable to use edit-event-html and delete-event-html

### ISSUE THREAD

**Issue by pkeuter** [mattlewis92/angular-bootstrap-calendar#116]
When I try to add your example code for edit and delete-event-html

```
edit-event-html="'<i class=\'glyphicon glyphicon-pencil\'></i>'" delete-event-html="'<i class=\'glyphicon glyphicon-remove\'></i>'"
```

I get the following error:

https://docs.angularjs.org/error/$parse/syntax?p0=glyphicon&p1=is%20an%20unexpected%20token&p2=12&p3=%27%3Ci%20class%3D%27glyphicon%20glyphicon-pencil%27%3E%3C%2Fi%3E%27&p4=glyphicon%20glyphicon-pencil%27%3E%3C%2Fi%3E

Also the calendar doesn't load with the following error message:
The value passed to current-day attribute of the calendar is not set

**Comment by mattlewis92** [comment]
Please can you provide me with a plunker or a codepen etc which reproduces your issue. Thanks.

**Comment by pkeuter** [comment]
This is my bad. Sorry. I found out that jade tries to html encode the tags, so that won't work. I've got that fixed now :-)
