### ISSUE TITLE
Removing time stamp from event tool-tip

### ISSUE THREAD

**Issue by hudsonabtahi** [mattlewis92/angular-bootstrap-calendar#118]
Hi again Matt,

Thank you for fixing the issue number 106.
I have used your calendar for showing the staff leave for the project managers in my company. everybody likes it and it comes up with more enhancement. First of all is there any way to remove time stamp from event tool tip? something like following: 
![image](https://cloud.githubusercontent.com/assets/11538414/8791535/8156a11c-2f9f-11e5-9dcd-6a847c829bf9.png)

the second one is a way to insert holidays and using different css class to make them bold in the calendar as following:
![image](https://cloud.githubusercontent.com/assets/11538414/8791582/1027f06c-2fa0-11e5-9409-46f21ff92d90.png)

Thanks in advance.

**Comment by mattlewis92** [comment]
Both issues can be solved by using a custom template. Override the `calendarMonthEventsList.html` template for the first issue and the `calendarMonthDay.html` for the second.

**Comment by hudsonabtahi** [comment]
Thanks Matt,

I tried to do but there is a problem. I have switched from angular-bootstrap-calendar.tpls.js to angular-bootstrap-calendar.js  however I got an error as "Cannot find module "./../templates/calendar.html" while the templates are there and even I copied the template folders to all other folders but it still cannot locate it.

**Comment by mattlewis92** [comment]
Try now with 0.14.3 :)

**Comment by hudsonabtahi** [comment]
Thanks Matt,
but it is the same and even does not show any error in the console while the previous version does

**Comment by mattlewis92** [comment]
If using the template free version the template is just set to an empty string. You will need to use decorators to modify the directives to set your own templateUrl property and delete the template property. I'm away on holiday so can't give a proper example, but if you google it you should find some tutorials on how to decorate directives.

**Comment by hudsonabtahi** [comment]
I have overridden the calendarSlideBox.html successfully with decoration technique. however I can not do the same for calendarMonthEventsList.html and calendarMonthDay.html since they are not directives. Any suggestion?

**Comment by mattlewis92** [comment]
Just something like:
```
$http.get('/path/to/custom/template').then(function(result) {
  $templateCache.put('calendarMonthEventsList.html', result.data);
});
```

I will work on a way to make this easier by just passing an attribute in 0.15.
