### ISSUE TITLE
Seems to be missing tooltips

### ISSUE THREAD

**Issue by openciti** [mattlewis92/angular-bootstrap-calendar#12]
Failed to load template: template/tooltip/tooltip-popup.html

**Comment by mattlewis92** [comment]
Have you loaded the https://github.com/angular-ui/bootstrap project as well? Make sure you are loading the ui-bootstrap-tpls.min.js file

**Comment by openciti** [comment]
you the man

**Comment by mattlewis92** [comment]
Happy to help :)

**Comment by openciti** [comment]
Hello,

sorry to bug you again,

should I copy the templates to my www/templates, which is where it seems to
be needed?

currently its in bower_components/angular-bootstrap-calendar/template

Thanks, Eli.

**Comment by mattlewis92** [comment]
If you use the angular-bootstrap-calendar-tpls.min.js file then this has the templates bundled so you don't need to copy them :)
