### ISSUE TITLE
Overflow of content in month view

### ISSUE THREAD

**Issue by cyberdemon8** [mattlewis92/angular-bootstrap-calendar#120]
some advice? :smile: 
![overflow appuntamenti](https://cloud.githubusercontent.com/assets/1280470/8823264/c06d269c-306b-11e5-942c-b8ae588cdc48.png)

**Comment by mattlewis92** [comment]
It's probably fixable via CSS, will try and find the time tonight to sort it.

**Comment by mattlewis92** [comment]
This is a fundamental design flaw in the CSS from the original project, consequently it'll require an overhaul of the CSS for the month view which I don't have time to do right now. The best thing I can offer is to use a custom template for the `calendarMonthEventsList.html` template with something like this:
```
<div class="events-list" ng-show="day.events.length > 0">
  <a
    ng-repeat="event in day.events | orderBy:'startsAt' | limitTo:16 track by event.$id"
    href="javascript:;"
    ng-click="vm.onEventClick({calendarEvent: event})"
    class="pull-left event"
    ng-class="'event-' + event.type + ' ' + event.cssClass"
    ng-mouseenter="vm.highlightEvent(event, true)"
    ng-mouseleave="vm.highlightEvent(event, false)"
    tooltip-append-to-body="true"
    tooltip-html-unsafe="{{ (event.startsAt | calendarDate:'time':true) + ' - ' + event.title }}"
    mwl-draggable="event.draggable === true"
    drop-data="{event: event}">
  </a>
  <a href="javascript:;">
    <small ng-show="day.events.length - 16 > 0" class="pull-left">+ {{ day.events.length - 16 }} more</small>
  </a>
</div>
```

Or change your UX to give your user an option to filter the events shown on the calendar - displaying dozens of events on one day isn't particularly readable to a user.

**Comment by cyberdemon8** [comment]
Ok, thank you very much :smile:
