### ISSUE TITLE
Dragged and resized elements don't return to their original position correctly when using jQuery in the project.

### ISSUE THREAD

**Issue by wawyed** [mattlewis92/angular-bootstrap-calendar#121]
This is caused by:

https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlDraggable.js#L111

https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlResizable.js#L109

To blank/remove a css property it needs to be assigned to the empty string not to null.

From http://api.jquery.com/css/:

>Setting the value of a style property to an empty string — e.g. $( "#mydiv" ).css( "color", "" ) — removes that property from an element if it has already been directly applied, whether in the HTML style attribute, through jQuery's .css() method, or through direct DOM manipulation of the style property.

I will submit a pull request to fix the issue.

**Comment by pkeuter** [comment]
Thanks for finding this. I was struggling with the same issue, but couldn't find the solution.

**Comment by mattlewis92** [comment]
Great, another undocumented difference between jqlite and jquery. Thanks for the fix :)
