### ISSUE TITLE
Events don't update in the calendar view if you assign a new object reference to the passed event array

### ISSUE THREAD

**Issue by wawyed** [mattlewis92/angular-bootstrap-calendar#122]
This is caused by:

https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendar.js#L82

https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarMonth.js#L15

$broadcast is a synchronous operation so the property vm.events hasn't been updated yet since the $digest cycle hasn't finished.

I'll submit a pull request with the fix shortly.

**Comment by mattlewis92** [comment]
Wrapping it in a $timeout should be enough, unless you can think of a cleaner way?

**Comment by wawyed** [comment]
I have actually I just haven't had time to do the PR.

**Comment by mattlewis92** [comment]
I'll do it now :)
