### ISSUE TITLE
Previous, today, Next

### ISSUE THREAD

**Issue by eduardomanski** [mattlewis92/angular-bootstrap-calendar#124]
I think it should be better if these labels change when selecting "Day", "Week", "Month" and so on.

When selecting Day, it should display "Yesterday", "Today", "Tomorrow", and for month and year, "Previous", "Current" ,"Next".

I tried, but didn't figured out how to do it.

BTW, congratulations for the great job!

**Comment by mattlewis92** [comment]
These buttons aren't part of the calendar so you can easily implement this logic yourself if you want.

```html
 <button
      class="btn btn-primary"
      mwl-date-modifier
      date="vm.calendarDay"
      increment="vm.calendarView">
      <span ng-show="vm.calendarView !== 'day' && !vm.isTomorrow(vm.calendarDay)">Next</span>
      <span ng-show="vm.calendarView === 'day' && vm.isTomorrow(vm.calendarDay)">Tomorrow</span>
</button>
```

and then in your controller:

```javascript
vm.isTomorrow = function(date) {
  return moment(date).startOf('day').isSame(moment().add(1, 'day').startOf('day'));
};
```

**Comment by luisbajana** [comment]
Hi Matt, one question, how do I increment, decrement months from my controlller?

**Comment by mattlewis92** [comment]
If you read the [source](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlDateModifier.js#L15), you'll see it's pretty simple
```
moment(vm.calendarDay).add(1, 'month').toDate();
```

**Comment by luisbajana** [comment]
Thank you @mattlewis92 Got it!

Best,
Luis.
