### ISSUE TITLE
On mobile devices, modal isn't working properly

### ISSUE THREAD

**Issue by eduardomanski** [mattlewis92/angular-bootstrap-calendar#125]
Bootstrap modal with a form isn't working properly with the calendar. It does not focus the input. To solve this, I had to add a directive, which is <a href="https://github.com/angular-ui/bootstrap/issues/2017#issuecomment-39515923">here</a>

In some devices, when scrolling the modal, actually it scrolls the background and it's not possible to work with. With Chrome or Firefox, everything works fine.

**Comment by mattlewis92** [comment]
Modals are provided by ui-bootstrap, this has absolutely nothing to do with this calendar.
