### ISSUE TITLE
Event handler for on-timespan-click not getting called

### ISSUE THREAD

**Issue by phyllisbi** [mattlewis92/angular-bootstrap-calendar#126]
Hi, I am using on-timespan-click so I can detect when user click on a day of the month. However my event handler is not getting called

// in angular-bootstrap-calendar-tpls.js
```
	        vm.onTimespanClick({
	          calendarDate: day.date.toDate()
	        });
```
// This is what the .html looks like, vm is my controller
```
                <mwl-calendar events="vm.events"
                              view="vm.selectedCalendarView"
                              current-day="vm.currentDay"
                              on-drill-down-click="vm.onDrillDownClicked"
                              on-timespan-click="vm.onTimeSpanClicked">
                </mwl-calendar>
```
// in my controller type script file
```
        onTimeSpanClicked() {
            console.log(arguments);
        }
```
However onTimeSpanClicked in my controller function will get called *IF* I change the binding to on-timespan-click="vm.onTimeSpanClicked()", note the extra parenthesis, but then I am getting empty arguments, how can I get the calendarDate from angular-bootstrap-calendar-tpls?

Thanks

**Comment by mattlewis92** [comment]
This is an area of angular that is really confusing, calendarDate is passed as a variable that is available in the expression you pass to `on-timespan-click`, so you use it like so:

`on-timespan-click="vm.onTimeSpanClicked(calendarDate)"`

Hope this helps :)
