### ISSUE TITLE
Allow events to recur weekly

### ISSUE THREAD

**Issue by sam2x** [mattlewis92/angular-bootstrap-calendar#127]
Hey, 

Thx for this angular module, he totally fits my needs. Is this possible to add recursOn for week ? Actually it supports only month and years :/ (despite the typo in the error message):

      Error: Invalid value (week) given for recurs on. Can only be year, month or week.

Regards.
S

**Comment by mattlewis92** [comment]
Do you mean for it to recur on a certain day of the week e.g. every sunday, every monday etc?

**Comment by sam2x** [comment]
Yes exactly.

**Comment by mattlewis92** [comment]
OK, will add it tomorrow.

**Comment by sam2x** [comment]
Thx!

**Comment by zunit** [comment]
Yea the week feature would be great! Is it available right now? 

Thanks for this Angular module, its very nice to work with =).

**Comment by mattlewis92** [comment]
It's not implemented yet as I've not had the time.

**Comment by zunit** [comment]
aw ok, I can try to implement it and send you the code snippet (if u want), can you give me any tips of how to. =)

**Comment by mattlewis92** [comment]
I've started work on this, but it still has a few bugs that need sorting first, it's really difficult to implement as you have to clone events to display them multiple times.

https://github.com/mattlewis92/angular-bootstrap-calendar/tree/feat-recurs-weekly

**Comment by mattlewis92** [comment]
I can't find a good way of implementing this with the current architecture, I don't like the current work I have done as it involves modifying the events array and has loads of bugs and will just cause loads of problems. The best way to do this would be to duplicate the event yourself every time the current view or calendar date changes with something like:

```javascript
vm.addWeeklyEvent = function() {

      vm.events = vm.events.filter(function(event) {
        return !event.weekly;
      });

      var start = moment(vm.calendarDay).startOf(vm.calendarView);
      var end = moment(vm.calendarDay).endOf(vm.calendarView);
      while(start.isBefore(end)) {
        vm.events.push({
          title: 'Weekly event',
          type: 'info',
          startsAt: moment(start).day(1).toDate(),
          weekly: true
        });
        start.add(1, 'week');
      }

    };
```

**Comment by subbaramireddy** [comment]
recurrent weekly event  with start and end time I have tried in my project, but current month only repeating every week on monday.
 In other months not displaying recurrent weekly please tell me what's the problem

**Comment by subbaramireddy** [comment]
My project using angular node.js

**Comment by subbaramireddy** [comment]
Could you please tell me, How to set Recurring event Repeats On end date after some occurrences?
