### ISSUE TITLE
[question] How to find correct css class for customization ? 

### ISSUE THREAD

**Issue by sam2x** [mattlewis92/angular-bootstrap-calendar#128]
Hey,

I would like to customize cells colors/backgrounds-color and week-ends, unfortunally the documentation doesnt provide information, and i must try "each" class name that may match my need, but i got a little 'success'.
So i would like to know if it's possible to provide some 'details' to modify standard theme. 

Actually i'm looking for the following modification (in month view) :

* Background-color of current day
* Background-color of :hover rows
* Color days out of the month
* Color days in the month
* Color days of the week-end

I tried to modify the following classes : 

    .cal-day-outmonth // works 
    .cal-row-fluid:hover // works (:hover of row week) 
    .cal-day-weekend // doesnt works 
    .cal-day-today // works for current day background-color

Is that the correct way to 'override' these values ? cause i had to use '!important' marker for some of them.

Regards,
S

**Comment by sam2x** [comment]
.cal-day-weekend span[data-cal-date] // working

**Comment by sam2x** [comment]
finally got all of them!

**Comment by mattlewis92** [comment]
For future reference if anyone else comes across this ticket, all available classes are listed here:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthDay.html#L5

**Comment by Blair2004** [comment]
Page 404

**Comment by burtek** [comment]
Updated link.
