### ISSUE TITLE
Cannot read toDate() when dropping event

### ISSUE THREAD

**Issue by clmntfrndz** [mattlewis92/angular-bootstrap-calendar#129]
Using interact.js, when I drop an event on another cell it causes a `Uncaught TypeError: Cannot read property 'toDate' of undefined` in `angular-bootstrap-calendar.tpls-min.js:574`.

The problem is present on both touch and desktop devices.

EDIT: The problem occurs when trying to drag n drop elements without a endsAt property. I guess the `if (!oldEnd) return oldEnd` from lines 18-19 in calendarHelper.js causes this.

**Comment by mattlewis92** [comment]
Should be fixed in 0.14.6, thanks for reporting! :)
