### ISSUE TITLE
Day start and end times

### ISSUE THREAD

**Issue by joshsadler** [mattlewis92/angular-bootstrap-calendar#13]
The jQuery plugin has an option for setting the start time and end time. Any plans to support all hours in a day? Thanks!

![example](http://cl.ly/image/101g0C1U2n33/Screen%20Shot%202015-01-15%20at%205.49.06%20PM.png)
![example](http://cl.ly/image/0t400x2k1A1V/Screen%20Shot%202015-01-15%20at%205.49.42%20PM.png)

**Comment by mattlewis92** [comment]
Sure thing, I'll add that in over the weekend :)

**Comment by joshsadler** [comment]
https://github.com/mattlewis92/angular-bootstrap-calendar/pull/17

**Comment by mattlewis92** [comment]
The start and end time of the day view is now configurable.
