### ISSUE TITLE
Change date in datepicker

### ISSUE THREAD

**Issue by boyarskiy** [mattlewis92/angular-bootstrap-calendar#131]
Hi,

When I add new event and then tried to change the day in datepicker it doesn't change in calendar.
Actually, you can see it in your demo - https://mattlewis.me/angular-bootstrap-calendar/

Could you please fix this?

**Comment by mattlewis92** [comment]
The datepicker is provided by ui-bootstrap and has nothing to do with this calendar. It looks like an issue with that library, as downgrading to 0.13.1 fixed it.

**Comment by boyarskiy** [comment]
Yep, thank you. It is really problem with ui-bootstrap.
