### ISSUE TITLE
Add event end time to calendar

### ISSUE THREAD

**Issue by boyarskiy** [mattlewis92/angular-bootstrap-calendar#132]
I have another question.
How can I add event end time to calendar?
http://dl2.joxi.net/drive/0004/1007/275439/150807/e24267848e.jpg

**Comment by jozsinakhivnak** [comment]
Hello!

I'm interested in this one, too. I'd like to have end times of events at day view.

**Comment by boyarskiy** [comment]
Hi! 
Anybody here?

**Comment by mattlewis92** [comment]
Sorry I'm super busy with work atm and don't have a lot of time right now, your best bet for now is to add a custom template, I will try and find some time to add an option to display end dates as well.

**Comment by jozsinakhivnak** [comment]
Hi,

Mattlewis92, You've mentioned adding a custom template would solve the problem. I'd need another functions too, so I'd like to do it, but I'm not an experienced web developer. How can I make angular calendar use the templates given in the src/templates dir?

Thanks for your reply.

**Comment by mattlewis92** [comment]
You can use a [decorator](http://angular-tips.com/blog/2013/09/experiment-decorating-directives/) to change the day view template url like so:

```javascript
app.config(function($provide) {
  $provide.decorator('mwlCalendarDayDirective', function($delegate) {
    var directive = $delegate[0];
    directive.templateUrl = 'URL_TO_YOUR_DAY_VIEW_TEMPLATE.html';
    return $delegate;
  });
});
```

Then just copy [the template](https://raw.githubusercontent.com/mattlewis92/angular-bootstrap-calendar/master/src/templates/calendarDayView.html) into your project to the path you set with the decorator and change whatever you want :)

**Comment by jozsinakhivnak** [comment]
Thank you, with your help I've successfully managed to get it work. I really appreciate your fast response and this great product you've made. Thanks a lot!!
