### ISSUE TITLE
Events with 0 duration are missing in "day" view

### ISSUE THREAD

**Issue by phyllisbi** [mattlewis92/angular-bootstrap-calendar#133]
We have a couple of events that has 0 duration (aka startsAt is same as endsAt), they all show up fine in "month" and "week" view, but in "day" view, the events don't show up.

**Comment by mattlewis92** [comment]
Just remove the endsAt property then and a default height will be used in the day view. The calendar gives each day it's height based off it's duration in minutes, so if it is 0 minutes long it will be 0 pixels high.
