### ISSUE TITLE
Add on-timespan-click functionality to the day view

### ISSUE THREAD

**Issue by marcoj** [mattlewis92/angular-bootstrap-calendar#135]
Hi,
I'd like to add a listener to a click in the hour elements. Is it possible? I want to catch the current day + hour I've clicked on the day view.

Thanks!

**Comment by mattlewis92** [comment]
It's not possible yet but it's really easy to add. I'll try and find some time soon to add it.

**Comment by marcoj** [comment]
great, thanks!
