### ISSUE TITLE
Width of day view has a maximum

### ISSUE THREAD

**Issue by pkeuter** [mattlewis92/angular-bootstrap-calendar#136]
When I put the day-view in a col-md column and there are more events than can be made visible at that time, a nice horizontal scrollbar appears, I like that. The only thing is that the grid doesn't seem to scale, so I get a white background behind the events.

It would be nice if the background would stretch with the number of events.

**Comment by mattlewis92** [comment]
I just had a look and I couldn't find a way to do this unfortunately with the current way the calendars html / css is written. If you fancy forking the code and sending PR then be my guest :)

**Comment by mattlewis92** [comment]
Closing to keep issues clean.
