### ISSUE TITLE
Splice an item after delete

### ISSUE THREAD

**Issue by cvcv01** [mattlewis92/angular-bootstrap-calendar#137]
Hi, i'm using the demo.js trying to splice an item from my list after a delete. The delete works, but the splice doesn't. 

Not sure if "event" in "vm.events.splice(event, 1);" is wrong. Anyone have an idea?

    vm.eventDeleted = function(event) {
		$http.delete('api/events/' + event.eventid).success(function(eventsuccess){
			vm.events.splice(event, 1);
		}).error(function(err){
			/* do something with errors */
		});
    };

Thanks

**Comment by cvcv01** [comment]
This request can be closed, I found my problem:

I needed to pinpoint the specific event id to splice.

Changed from : 

        vm.events.splice(event, 1);

to:

        vm.events.splice(event.$id, 1);

Hopefully, it can help someone else.

**Comment by mattlewis92** [comment]
That only works by coincidence as the id is the index of the item in the array and could break in the future. As per the [javascript API](http://www.w3schools.com/jsref/jsref_splice.asp) it should be:
```
var index = vm.events.indexOf(event);
vm.events.splice(index, 1);
```

**Comment by cvcv01** [comment]
Super, thanks!
