### ISSUE TITLE
ng-click inside a modal window

### ISSUE THREAD

**Issue by cvcv01** [mattlewis92/angular-bootstrap-calendar#138]
I've added the ability to edit the start/end datetimes (using datepicker) of a single event when clicking on the edit event link.

I display the event in a modal, it displays fine but the ng-click doesn't seem to have any effect when I click on it to display the datepicker inside the modal.

Should   ng-click="vm.toggle($event, 'startOpen', event)"   syntax be different when in a modal?

Anyone encountered this problem?

Thanks

html

	<script type="text/ng-template" id="modalEventContent.html">
	<div class="modal-body" style="height:600px;">
	<table class="table table-bordered">

	<thead>
	  <tr>
		<th>Title</th>
		<th>Type</th>
		<th>Starts at</th>
		<th>Ends at</th>
		</tr>
	</thead>

	<tbody>

		<td><input type="text" class="form-control" ng-model="vm.event.title"></td>
		<td>
		  <select ng-model="vm.event.type" class="form-control">
			<option value="important">Important</option>
			<option value="warning">Warning</option>
			<option value="info">Info</option>
			<option value="inverse">Inverse</option>
			<option value="success">Success</option>
			<option value="special">Special</option>
		  </select>
		</td>
		<td>
		  <p class="input-group" style="max-width: 250px">
			<input type="text" class="form-control" readonly datepicker-popup="medium" ng-model="vm.event.startsAt" is-open="event.startOpen" close-text="Close" />
			<span class="input-group-btn">
			  <button type="button" class="btn btn-default" ng-click="vm.toggle($event, 'startOpen', event)"><i class="glyphicon glyphicon-calendar"></i></button>
			</span>
		  </p>
		  <timepicker ng-model="vm.event.startsAt" hour-step="1" minute-step="15" show-meridian="true"></timepicker>
		</td>
		<td>
		  <p class="input-group" style="max-width: 250px">
			<input type="text" class="form-control" readonly datepicker-popup="medium" ng-model="vm.event.endsAt" is-open="event.endOpen" close-text="Close" />
			<span class="input-group-btn">
			  <button type="button" class="btn btn-default" ng-click="vm.toggle($event, 'endOpen', event)"><i class="glyphicon glyphicon-calendar"></i></button>
			</span>
		  </p>
		  <timepicker ng-model="vm.event.endsAt" hour-step="1" minute-step="15" show-meridian="true"></timepicker>
		</td>

	</tbody>

	</table>
	</div>
	</script>
		  
		  
code added to demo.js

	function showEventModal(action, event) {
      $modal.open({
        templateUrl: 'modalEventContent.html',
        controller: function() {
          var vm = this;
          vm.action = action;
          vm.event = event;
        },
        controllerAs: 'vm'
      });
    }  
	
	
	vm.eventEdited = function(event) {

	 $http.get('/api/events/' + event.eventid).success(function(eventsuccess){

	 showEventModal('Edited', event);
    }).error(function(err){
       /* do something with errors */
    });
      //console.log("eventEdited");
    };

**Comment by mattlewis92** [comment]
```
<button type="button" class="btn btn-default" ng-click="vm.toggle($event, 'startOpen', event)"><i class="glyphicon glyphicon-calendar"></i></button>
```

should be:
```
<button type="button" class="btn btn-default" ng-click="event.startOpen = true;"><i class="glyphicon glyphicon-calendar"></i></button>
```

The `is-open` attribute controls if the datepicker is visible or not hence you need to set it to true when clicking the button next to it as `event.startOpen` is what you have set as the `is-open` attribute.

Please note anything to do with the modal, datepicker etc has absolutely nothing to do with this calendar and any issues with those components should be raised with the folks at [ui-bootstrap](https://github.com/angular-ui/bootstrap)
