### ISSUE TITLE
Getting the Month, Week, Day, Hour you clicked on in each respective view. 

### ISSUE THREAD

**Issue by mmccook** [mattlewis92/angular-bootstrap-calendar#139]
So I don't know if this is something that can't be done currently or if I just am glossing over it in the documentation but I'm starting initially on the Year view, I want to allow the calendar to drill down but I need to also set a state using the UI router so the user can go back to a previous view using the browsers back button but I can't figure out how to grab the month that was clicked. I've tried the on-drill-down-click and on-timespan-click but I don't know what I'm doing wrong but I don't get anything from those, the only thing I've been able to manage is getting it to not drill down deeper. 

Any help is appreciated. Thanks.

**Comment by mmccook** [comment]
Fixed it, didn't read fully. 

calendarDate passed to the function gets me the correct month / day i clicked on.

**Comment by mattlewis92** [comment]
Sorry the docs weren't very obvious about this, I've updated the readme with a bit more clarity on it :)
