### ISSUE TITLE
Events on the same row in week views

### ISSUE THREAD

**Issue by zunit** [mattlewis92/angular-bootstrap-calendar#140]
<img width="920" alt="screen shot 2015-08-18 at 9 23 40 pm" src="https://cloud.githubusercontent.com/assets/5455937/9346856/e3b51f3a-45ef-11e5-8f1c-c4dfff604181.png">

Hey Matt!

instead of the picture above, just curious would I be able to make the events on the same row if they are separate events? if not is there a quick fix I can do?

Again thanks for building this! 

=)

**Comment by mattlewis92** [comment]
Unfortunately this is a design flaw in the original architecture of the calendar and not something that is particularly simple to do. If you can find a way and want to send a PR then be my guest :)

Related issues: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/99
