### ISSUE TITLE
Event List Dots Overlapping in Monthly Day Grid

### ISSUE THREAD

**Issue by GauravP77** [mattlewis92/angular-bootstrap-calendar#143]
Hi Matt,

Thanks for this awesome angular component. Looks great but the only issue i'm facing is when there are more than 30-40 events per day the dots in the monthly day grid is overlapping, Is there a option to restrict number of event dots appearing in the monthly calendar day grid. 

![calendar issue](https://cloud.githubusercontent.com/assets/13979236/9490674/28a78728-4c07-11e5-84cf-ee15ce2598c4.PNG)

Thanks,
Gaurav

**Comment by mattlewis92** [comment]
Unfortunately that's a limitation with the original CSS from the calendar, I've tried to fix it before but didn't have much luck. You can however easily use CSS to limit the number of the dots visible, for example to show only the first 10 dots:
```css
.events-list > a:nth-child(n+11) {
  display: none;
}
```

Hope this helps :)

**Comment by GauravP77** [comment]
That worked! Thanks a lot for your help @mattlewis92

**Comment by nischalbc** [comment]
I Have 3 types of events Pending(blue) , Inprogress(yellow) and completed (green) so can we group the dots i.e For example, if there are 10 pending tasks available for the day then just display “one blue dot”.   When a day has all three statuses, then 3 dots with appropriate color. This will give a visible display of what to expect on that day.

Thanks ,
NIschal

**Comment by GauravP77** [comment]
You can modify the below line in angular_bootstrap_calendar_tpls.js to group on unique attributes from to-do list

ng-repeat=\"event in day.events | unique:'fieldname'\"
