### ISSUE TITLE
Properties required for event object

### ISSUE THREAD

**Issue by jmsherry** [mattlewis92/angular-bootstrap-calendar#144]
Hi Matt,
Great plugin! There's a line in the readme that may require a bit of clarification:

"The 4 properties listed are required for all events."

(this is for the evens array objects)

Can you indicate which 4? (as there are quite a few in the code snippet above that statement).

Thanks

James

**Comment by mattlewis92** [comment]
Sorry that line is very out of date, it's now 3 properties which are `title`, `type` and `startsAt`. I've updated the read me to reflect this :)

**Comment by jmsherry** [comment]
Awesome! Thanks Matt... :)
