### ISSUE TITLE
Drop event on calendar

### ISSUE THREAD

**Issue by Xainu31** [mattlewis92/angular-bootstrap-calendar#145]
I want to create an object that would be behind a, lets say label. I can drag this label around my page but when i Drag this label on to a calendar date then it should create an event on that date containing the data of the label object. Need help regarding this functionality

**Comment by mattlewis92** [comment]
You should be able to do this with the internal directives. Include interact.js on the page and create an element like so:
```
<div mwl-draggable="true" drop-data="{event: aValidCalendarEventOnTheScope}">Drag me</div>
```
