### ISSUE TITLE
Question regarding loading the calendar

### ISSUE THREAD

**Issue by rodolfoortiz** [mattlewis92/angular-bootstrap-calendar#146]
I am currently using your calendar. Just wondering, is there a way to know when the calendar finished loading the events?

Thank you!

**Comment by mattlewis92** [comment]
Sorry I don't quite get what you mean? As soon as you pass an array of events to the calendar it will update, there is nothing asynchronous going on

**Comment by rodolfoortiz** [comment]
Thanks for the quick response. I want to make some changes to the calendar DOM, that's why I want to know when the events finished rendering in the calendar.

**Comment by mattlewis92** [comment]
It should be one digest after the events array is passed. So after you update the events array just do:
```
$timeout(function() {
  //events are loaded
});
```

**Comment by rodolfoortiz** [comment]
Thanks a lot! That kind of worked, I ended up doing this:

$timeout(function () {
   //events are loaded
}, 2000);
