### ISSUE TITLE
Error:: Multiple directives [mwlCalendarDay, mwlCalendarDay]

### ISSUE THREAD

**Issue by sanket-qp** [mattlewis92/angular-bootstrap-calendar#147]
pretty new to angular and front end development. I tried to decorate the day directive and I am getting this error. please help. 
```
app.config(function($provide) {
  $provide.decorator('mwlCalendarDayDirective', function($delegate) {
    console.log($delegate);
    var directive = $delegate[0];
    directive.templateUrl = 'views/calendarDayView.html';
    return $delegate;
  });
});
```
here is the trace
```
Error:: Multiple directives [mwlCalendarDay, mwlCalendarDay] asking for template on: <mwl-calendar-day events="vm.events" current-day="vm.currentDay" on-event-click="vm.onEventClick" on-event-times-changed="vm.onEventTimesChanged" day-view-start="vm.dayViewStart" day-view-end="vm.dayViewEnd" day-view-split="vm.dayViewSplit" ng-switch-when="day">
```

**Comment by mattlewis92** [comment]
The calendar uses the template property which takes precedence over templateUrl, so you need to delete the template property.
```
app.config(function($provide) {
  $provide.decorator('mwlCalendarDayDirective', function($delegate) {
    console.log($delegate);
    var directive = $delegate[0];
    delete directive.template;
    directive.templateUrl = 'views/calendarDayView.html';
    return $delegate;
  });
});
```

**Comment by sanket-qp** [comment]
thanks @mattlewis92 , it works now.

**Comment by sanket-qp** [comment]
@mattlewis92 another stupid question, how does compilation work in this project ? I copied all the templates to my views/ directory and I don't see the modifications I made in 'calendarMonthEventsList.html'. how does angular-bootstrap-calendar-tpls.min.js know to use the new templates ?

**Comment by mattlewis92** [comment]
That template is a bit special, if you update to the latest version you just pass in the path as an attribute to the directive:
https://github.com/mattlewis92/angular-bootstrap-calendar#month-cell-template-url

**Comment by sanket-qp** [comment]
thanks @mattlewis92  works now.
