### ISSUE TITLE
Allow specifying a custom template for the slide box

### ISSUE THREAD

**Issue by dawiong** [mattlewis92/angular-bootstrap-calendar#148]
Hi, the recent cell customization updates are really helpful. As they go hand in hand with slide boxes, can we consider providing the template-url config for those too?

**Comment by mattlewis92** [comment]
The slidebox is [a directive](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarSlideBox.js#L26) not just a template, thus you need to use a decorator to override the slide box template like so:
```
app.config(function($provide) {
  $provide.decorator('mwlSlideBoxDirective', function($delegate) {
    var directive = $delegate[0];
    delete directive.template;
    directive.templateUrl = 'path/to/my/slide/box/template.html';
    return $delegate;
  });
});
```

**Comment by dawiong** [comment]
Oh I see. I missed that. Thanks! :+1:

**Comment by alexjohnson505** [comment]
For any future readers. I ran into a few issues with the code snippet above. The following code snippet is what worked in my project:

```javascript
app.config(function($provide) {
  $provide.decorator('mwlCalendarSlideBoxDirective', function($delegate) {
    var directive = $delegate[0];
    delete directive.template;
    directive.templateUrl = 'path/to/my/slide/box/template.html';
    return $delegate;
  });
});
```

Note the directive name ***mwlCalendarSlideBoxDirective***

**Comment by mattlewis92** [comment]
oops, fixed now, thanks!

**Comment by dchi1** [comment]
@alexjohnson505  What happens if a variable is declared in my new template {{vm.my_text}} declared that this?, i was testing my driver but does not take the value
