### ISSUE TITLE
Question: odd/even class for days on week view.

### ISSUE THREAD

**Issue by F3L1X79** [mattlewis92/angular-bootstrap-calendar#149]
Hello mattlewis92 and thank you so much for the hard work!

I have small question concerning the week view - do you think it would be possible to add an odd/even class to the days in order to make a delimiter between days, when you scroll the page?

Best regards,
Felix.

**Comment by mattlewis92** [comment]
Just use CSS: http://www.w3.org/Style/Examples/007/evenodd.en.html :)

**Comment by F3L1X79** [comment]
It's fine, but the problem seems like I can't use CSS to add vertical lines on the week view to separate the days.
The divs you made are only horizontals - do you think there is a way to override the template to make this possible? Or will it just takes too much time?
Thank you for the fast answer anyway!

**Comment by mattlewis92** [comment]
You can use a decorator to change the week view template like so:
```
app.config(function($provide) {
  $provide.decorator('mwlWeekViewDirective', function($delegate) {
    var directive = $delegate[0];
    delete directive.template;
    directive.templateUrl = 'path/to/my/custom/week/view/template.html';
    return $delegate;
  });
});
```

It might be tricky to add though as the calendar is made up of divs not tables.
