### ISSUE TITLE
not respecting curent monent locale

### ISSUE THREAD

**Issue by edgar0011** [mattlewis92/angular-bootstrap-calendar#15]
when moment.locale(key) called, with dow and doy set, the calendar event after mont or day view rendered anew

dow and doy is not respected

**Comment by mattlewis92** [comment]
Are you calling moment.locale correctly, like so:
```
moment.locale('en', {
    week : {
        dow : 1 // Monday is the first day of the week
    }
});
```

**Comment by edgar0011** [comment]
Sorry my bad, yes now it works, but only after re-rendering, like going from week to month an back, can I enforce the re rendering somehow?

**Comment by mattlewis92** [comment]
Try setting the calendar-use-iso-week attribute to true as per the docs.

**Comment by edgar0011** [comment]
well, that works ok, but I expected that after changing momet locale (fow dow) and $locale it would be reflected in the calendar, but one has force it to redraw, by changing calendar-view for example

**Comment by mattlewis92** [comment]
Where are you setting the moment.locale? If you're doing it in the controller maybe try doing it in the run() section of your app instead so it is set before the calendar page is loaded.

**Comment by edgar0011** [comment]
thats is the point, i want to be able change locale on the run, it works with angular-translate, and angular-dynamic-locale

**Comment by mattlewis92** [comment]
OK, I get what you mean now. I'll try and sort something this weekend.

**Comment by edgar0011** [comment]
great, the calendar works great, and is much better then angular ui calendar....thanks a lot

**Comment by mattlewis92** [comment]
Sorry about the delay with this, fixed in https://github.com/mattlewis92/angular-bootstrap-calendar/commit/0dbd3dc62ef4ba7cae44c1d226781b939335b9b7 :)
