### ISSUE TITLE
Custom Templates

### ISSUE THREAD

**Issue by alexjohnson505** [mattlewis92/angular-bootstrap-calendar#150]
Hey mattlewise92,

Thanks for putting together this Angular directive for the bootstrap calendar! Would it be possible to get additional custom template support for more than just "month-cell-template-url" and "month-cell-events-template-url". I'd love to use my own template for the "mwl-calendar-slide-box"?

Thanks!

 - Alex

**Comment by mattlewis92** [comment]
I really need to get around to adding this in the docs, the other templates are all used as directives so you can use decorators to change the template like so: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/148
