### ISSUE TITLE
TypeError: e.$watchGroup is not a function when trying to set the calendar up

### ISSUE THREAD

**Issue by dbajramovic** [mattlewis92/angular-bootstrap-calendar#151]
Hey there!

I am currently trying to get the calendar to work in my MEAN stack website, however, I am having bad luck doing so. After installing everything trough npm, I am getting the "The value passed to current-day attribute of the calendar is not set" error message, with the above mentioned one in the console.

I have added moment.js as a dependency, inserting the script tag you provided in an earlier issue similar to this one right before the js of the calendar itself, which changed the type of error, but not the issue it seems. I have also added the demo code for the controller and set the variables as instructed in the HTML code. What am I missing?

Thank You in advance!

**Comment by mattlewis92** [comment]
Are you using angular 1.2 by any chance?

**Comment by dbajramovic** [comment]
Silly me, for some reason I had the updated version of AngularJS that the calendar uses... but not in the public/lib folder but the node_modules one. In that one was 1.2, which I have now corrected, and the calendar works! Guess the lesson is to check for double version as often as possible.

**Comment by GopinathKaliappan** [comment]
Hi i am getting this error

TypeError: e.$watchGroup is not a function
    at new <anonymous> (angular-bootstrap-calendar-tpls.min.js:7)
    at invoke (ionic.bundle.js:11591)
    at Object.instantiate (ionic.bundle.js:11602)
    at ionic.bundle.js:14906
    at ionic.bundle.js:14295
    at forEach (ionic.bundle.js:7957)
    at nodeLinkFn (ionic.bundle.js:14282)
    at ionic.bundle.js:14538
    at ionic.bundle.js:15737
    at wrappedCallback (ionic.bundle.js:19197)

Any Solution ??

Thanks ...

**Comment by mattlewis92** [comment]
Looks like you're using angular 1.2, this directive only supports 1.3+
