### ISSUE TITLE
How to generate angular-bootstrap-calendar-tpls.js after modifying the code

### ISSUE THREAD

**Issue by sanket-qp** [mattlewis92/angular-bootstrap-calendar#154]
Hi @mattlewis92 , I want to make some changes to calendarHelper.js and not sure how can I build new JS file ? 

Thanks

**Comment by mattlewis92** [comment]
It's all in [the readme](https://github.com/mattlewis92/angular-bootstrap-calendar#development).

tl;dr:
 `npm run build`
