### ISSUE TITLE
Adding more types

### ISSUE THREAD

**Issue by calvinKG** [mattlewis92/angular-bootstrap-calendar#155]
Hi, 

I would like to add more type of events with colors  and use them as filters on the calendar. 

The type of the event (determines its color). Can be important, warning, info, inverse, success or special 

Please help

**Comment by mattlewis92** [comment]
The event types just add an `event-TYPE` class to events, so you just need to define additional CSS classes like these:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/less/events.less#L25

So for example:
```css
.event-custom {
  background-color: pink;
}
```

And then just set the event type as `custom`. I hope that helps :smile:

**Comment by calvinKG** [comment]
What about the events type it's self, those it have a function where i can edit this directive and add more events then apply this CSS?

**Comment by mattlewis92** [comment]
All the calendar does is add a class to the event with `event-type` as you can see here:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthCellEvents.html#L7

Type can be anything you want it to be, but you have to define the CSS class yourself.

**Comment by calvinKG** [comment]
So the main thing I need to add is the css class. I get it thanks.

**Comment by calvinKG** [comment]
My goal is to create filter with type. When a specific type is selected, all events with that type are displayed on the calendar.

**Comment by mattlewis92** [comment]
Use the [default angular filter](https://docs.angularjs.org/api/ng/filter/filter) to filter the events that you pass to the calendar:
`events="vm.events | filter: {type: 'success'}"`

**Comment by calvinKG** [comment]
Hi, 

Need your help again, I am so lost on how to implement this method. Do you mind giving me an example?

**Comment by calvinKG** [comment]
I have the following and I got an error. 

<mwl-calendar
                    events="vm.events | filter: {type: 'success'}"
                    view="vm.calendarView"

Error : Error: $rootScope:infdig
Infinite $digest Loop

10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]},{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]}],[{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]},{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]}],[{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]},{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]}],[{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]},{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]}],[{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]},{"msg":"fn: function (c,d,e,f){e=a(c,d,e,f);return b(e,c,d)}","newVal":[],"oldVal":[]}]]

**Comment by calvinKG** [comment]
I also tried using the standard filters and I get the following error 

My code: 
 <input ng-model="event.type">
 <mwl-calendar
                    events="vm.events | filter: eventss"
                    view="vm.calendarView"
                    view-title="vm.calendarTitle"

Error: 

Error: $compile:nonassign
Non-Assignable Expression
Expression 'vm.events | filter: event.type' used with directive 'mwlCalendar' is non-assignable

https://docs.angularjs.org/error/$compile/nonassign?p0=vm.events%20%7C%20filter:%20event.type&p1=mwlCalendar

**Comment by calvinKG** [comment]
Hi Matt, 

I managed to create my own filter, but I get the following error when filtering. 

Code
Filter method (controller): 
$scope.$watch('type', function() {
        $scope.filteredEvents = $filter("filter")($scope.events,{type: $scope.type},false);
    });

Html: 
 <input ng-model="type">

  <mwl-calendar
                    events="filteredEvents"
                    view="calendarView"
             .............................................
             .............................................
 </mwl-calendar>

Error : 
TypeError: Cannot redefine property: $id
    at Function.defineProperty (native)
at http://localhost:63342/app/lib/angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls.min.js:7:28527

Please assist.
