### ISSUE TITLE
The value passed to current-day attribute of the calendar is not set

### ISSUE THREAD

**Issue by kuroware** [mattlewis92/angular-bootstrap-calendar#156]
I have been wrestling with this problem for hours. I have included moment.js (the minified version) into my script before loading the calendar. Here it my html code:

    <script type="text/javascript" src="bower_components/moment/min/moment.min.js"></script>
    
    <script type="text/javascript" src="/bower_components/angular/angular.min.js"></script>
    <script type="text/javascript" src="/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>

My controller in Angular looks like this:

    var app = angular./**
    * app Module
    *
    * Description
    */
    module('app', ['mwl.calendar', 'ui.bootstrap'])

    $scope.data.calendarView = 'month';
    $scope.data.calendarDay = new Date();
    $scope.data.events = [
      {
        title: 'My event title', // The title of the event
        type: 'info', // The type of the event (determines its color). Can be important, warning, info, inverse, success or special
        startsAt: new Date(2013,5,1,1), // A javascript date object for when the event starts
        endsAt: new Date(2014,8,26,15), // Optional - a javascript date object for when the event ends
        editable: false, // If edit-event-html is set and this field is explicitly set to false then dont make it editable.
        deletable: false, // If delete-event-html is set and this field is explicitly set to false then dont make it deleteable
        draggable: true, //Allow an event to be dragged and dropped
        resizable: true, //Allow an event to be resizable
        incrementsBadgeTotal: true, //If set to false then will not count towards the badge total amount on the month and year view
        recursOn: 'year', // If set the event will recur on the given period. Valid values are year or month
        cssClass: 'a-css-class-name' //A CSS class (or more, just separate with spaces) that will be added to the event when it is displayed on each view. Useful for marking an event as selected / active etc
      }
    ];

I have read a few solutions online and they asked me to include `moment.js`, but I am! For more specific error, the error I get in the console is:

TypeError: e.$watchGroup is not a function
    at new <anonymous> (mwlCalendar.js:93)
    at d (angular.js:3965)
    at Object.instantiate (angular.js:3976)
    at $get (angular.js:7315)
    at angular.js:6711
    at r (angular.js:332)
    at J (angular.js:6698)
    at g (angular.js:6146)
    at g (angular.js:6149)
    at angular.js:6042

Does anybody know what's going on?

**Comment by mattlewis92** [comment]
Looks like you're using angular 1.2, this directive only supports 1.3+

See: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/151

**Comment by brayansdt** [comment]
@kuroware and @mattlewis92 I'm using this lib in my job and we are currently using angular 1.0.7, so I made a lot of changes (including implementing track by as a directive) to make it run. If you want, I can make a fork to publish it.
