### ISSUE TITLE
Irregular week view event

### ISSUE THREAD

**Issue by archieMZ** [mattlewis92/angular-bootstrap-calendar#157]
Hi! First of all, cool control, great job!!
I'd like to report the following issue:
I've created an event "Except Saturday", starting on Sunday 06-09-15 00:00, ending on Saturday 12-09-15 00:00.
The event is correctly shown in month view and in day view from Sunday to Friday (it's not shown on Saturday). But in week view, the event is shown the whole week (including Saturday!!!). So the event is shown irregularly in week view!
Would you please care about this!

**Comment by mattlewis92** [comment]
If an event occurs at any point on a day then it will be shown on that day on the week view, so in your case make the event end date Friday 11th September 11:59:59 and it will work as expected.

**Comment by archieMZ** [comment]
Okay, thanks!
I will consider this!
I was just confused, because week view and month view behave different in that case.

**Comment by mattlewis92** [comment]
You're right, an event at exactly midnight doesn't appear on that day, I will push a new version that fixes that
