### ISSUE TITLE
Error: $compile:nonassign Non-Assignable Expression when adding filter 

### ISSUE THREAD

**Issue by calvinKG** [mattlewis92/angular-bootstrap-calendar#160]
Hi, 

I want filter all the calendar events using the types 

Matt Lewis gave me the following code but I get an error when implementing it. 

Code : events="vm.events | filter: {type: 'success'}"

My code : <mwl-calendar
events="vm.events | filter: event.type"
view="vm.calendarView"
view-title="vm.calendarTitle"

Error:

Error: $compile:nonassign
Non-Assignable Expression
Expression 'vm.events | filter: event.type' used with directive 'mwlCalendar' is non-assignable

https://docs.angularjs.org/error/$compile/nonassign?p0=vm.events%20%7C%20filter:%20event.type&p1=mwlCalendar\

Please help

**Comment by mattlewis92** [comment]
Maybe just do the filter in the controller instead with something like:
```
vm.updateEvents = function(eventType) {
  vm.events = vm.allEvents.filter(function(event) {
    return event.type === eventType;
  });
};
```

**Comment by calvinKG** [comment]
Hi Matt, 

I did and it those filter but only the first element type in the events and when I try filter or search for other types I get the following error. 

Code
Filter method (controller): 
$scope.$watch('type', function() {
$scope.filteredEvents = $filter("filter")($scope.events,{type: $scope.type},false);
});

Html: 
events="filteredEvents"
view="calendarView"
.............................................
.............................................
Error : 
TypeError: Cannot redefine property: $id
at Function.defineProperty (native)
at http://localhost:63342/app/lib/angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls.min.js:7:28527

**Comment by mattlewis92** [comment]
Ah that is a bug with the calendar, until I have the time to push a fix your best bet is to delete the $id property from the events when you update the list.
```
$scope.filteredEvents = $filter("filter")($scope.events,{type: $scope.type},false).map(function(event) {
  delete event.$id;
  return event;
});
```

**Comment by calvinKG** [comment]
Thanks Matt, I will test the provided code and get back to you.

**Comment by calvinKG** [comment]
Unfortunately the delete method those not work. I get the following Error   

TypeError: Cannot delete property '$id' of #<Object>

**Comment by mattlewis92** [comment]
I had some more time to look into this, I think I've already fixed this in a newer version of the calendar - what version are you currently using?

**Comment by calvinKG** [comment]
"angular-bootstrap-calendar": "~0.11.2",


Kind Regars,

KC MASHISHI

**Comment by mattlewis92** [comment]
Ah that'll be why, if you upgrade to 0.15.0 then it should work. The changelog with breaking changes is here:
https://github.com/mattlewis92/angular-bootstrap-calendar/releases

**Comment by calvinKG** [comment]
Are you busy with the repo, i get this error when I try to run bower

bower angular-bootstrap-calendar#~0.15.0          ECMDERR Failed to execute
"git ls-remote --tags --heads
https://github.com/mattlewis92/angular-bootstrap-calendar.git", exit code
of #128 fatal: unable to access '
https://github.com/mattlewis92/angular-bootstrap-calendar.git/': Failed to
connect to 160.48.234.129 port 80: Timed out


Kind Regars,

KC MASHISHI

**Comment by mattlewis92** [comment]
Looks like an error with github or your connection to the internet

**Comment by calvinKG** [comment]
Hi Matt, 

As always, thank you very much for your prompt reply and the very helpful information. 

It's not working.
