### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by FirstSamurai** [mattlewis92/angular-bootstrap-calendar#161]
Hi, the calendar that you built is amazing. However I cant find good documentation that will help.
I wanted to know, how can add an onlick event to a day in the month view?

**Comment by mattlewis92** [comment]
All the docs are in the readme, you want this option:
https://github.com/mattlewis92/angular-bootstrap-calendar#on-timespan-click

**Comment by FirstSamurai** [comment]
Oh yeah...sorry missed it.
Thanks Matt. May be you can add that in the demo..its pretty common use
case.

Thanks again.

**Comment by mattlewis92** [comment]
You're right, that demo was created when there were hardly any options available on the calendar, and it should be updated accordingly. I have created a separate issue here: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/162
