### ISSUE TITLE
Unexpected token error in JS files

### ISSUE THREAD

**Issue by ksharifbd** [mattlewis92/angular-bootstrap-calendar#163]
I am getting this error [see image] in my console. I've added all the dependencies. 

![error](https://cloud.githubusercontent.com/assets/7776002/9870624/79d981b6-5baf-11e5-8cc7-a846cf74fe48.png)

**Comment by mattlewis92** [comment]
Have you actually clicked on those errors to see what they mean? Looks like the path to the script files is wrong.

**Comment by ksharifbd** [comment]
Yes you are right the paths were wrong but still getting  '$injector:modulerr' error.  We are using angular version 1.4.4.

**Comment by mattlewis92** [comment]
Click the error in the link and it will give you more info.
