### ISSUE TITLE
Prevent show calendar by day when click on day number on month view

### ISSUE THREAD

**Issue by SakyaStelios** [mattlewis92/angular-bootstrap-calendar#164]
How can I prevent show calendar by day when click on day number on month view? I only want the feature that display on a box all events under the calendar on month view. If I click on enmpty space in calendar day, I see the bow with all events on the same month view, but if I clicked in the number of day, I go to the day view and I want to prevent this.

I am aplying this feature to mobile calendar and I can write a separate CSS for this showcase after.

**Comment by mattlewis92** [comment]
This is the option you want:
https://github.com/mattlewis92/angular-bootstrap-calendar#on-drill-down-click

So in your controller define something like:
```
vm.onDrilldownClick = function() {
  return false;
};
```

and then pass it to the calendar like so:
```
<mwl-calendar on-drilldown-click="vm.onDrilldownClick()"></mwl-calendar>
```

Hope this helps :smiley:

**Comment by SakyaStelios** [comment]
I'm writing this for ionic. I write in the view:

<mwl-calendar
view="calendarView"
current-day="calendarDay"
events="events"
view-title="calendarTitle"
on-event-click="eventClicked(calendarEvent)"
on-drilldown-click="onDrilldownClick()"
auto-open="false">


And in the controller:

$scope.onDrilldownClick = function() {
        console.log("maldito numero");
        return false;
 };

But it doesn't works

**Comment by SakyaStelios** [comment]
Hi, I read the source code and find that  is <mwl-calendar on-drill-down-click="vm.onDrilldownClick()"></mwl-calendar>

The problem is done.

Many thanks, this calendar is a great help for me.
