### ISSUE TITLE
Show day list view in month's days slide box

### ISSUE THREAD

**Issue by peineDT** [mattlewis92/angular-bootstrap-calendar#165]
Hi,

I'm new to angularjs, and I need some help here. I realized to modify the templates and compiling them, however I'm having problems trying to do some dirty hack.

My goals is to have the calendarDayview.html contents inside the calendarSlideBox.html contents, so when I click a day in the month view instead of displaying a list showing the events it shows the regular day view, all inside the month just below the selected day.

I tried copy-pasting the calendarDayview inside calendarSlideBox but, due to my lack of angular understanding I'm having nothing here. Any light on this topic, please? Thanks.

**Comment by mattlewis92** [comment]
You need to go a bit higher level and use the calendar day directive rather that just it's template, as can be seen here:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendar.html#L50

However using it in the slidebox won't be easy as a lot of the day view options aren't available in the slideboxes isolate scope. There's probably a better UX pattern you could use anyway, maybe launching it in a modal when you click the day view instead.
