### ISSUE TITLE
Add an event in each cell of the month

### ISSUE THREAD

**Issue by achraftalbi** [mattlewis92/angular-bootstrap-calendar#167]
Hi, 

 I appreciate a lot this conception and actually i think this is the best angular calendar.

 I integrate this calendar in my application and i want to see a popup to add an event in each cell of the month when this cell is clicked. 

 I tried many solutions but it doesn't work. Can you help me ?

 Thanks

**Comment by mattlewis92** [comment]
This is possible with the `on-timespan-click` option. You would pass it to the calendar like so:
`on-timespan-click="vm.cellClicked(calendarDate)"`

Then just define the vm.cellClicked function like so:
```
vm.cellClicked = function(date) {
  // Show modal etc to add a new event. date is the start of the month, day, hour etc depending on which view you're on. 
};
```

I hope this helps! :smile:

**Comment by achraftalbi** [comment]
Thanks for your quick reply.

 I will try to implement it.
