### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by achraftalbi** [mattlewis92/angular-bootstrap-calendar#168]
Hi,

 How can we change language in your calendar ?

 Thanks
  
 Achraf

**Comment by mattlewis92** [comment]
It's all in the [readme](https://github.com/mattlewis92/angular-bootstrap-calendar#internationalization-and-localization). :smile:

**Comment by achraftalbi** [comment]
Thanks.

**Comment by gmerabishvili** [comment]
Hello, really great work! I am using angular-4 version and how can I change language here?

**Comment by burtek** [comment]
@gmerabishvili - This is the wrong place to ask this - you should be asking it [here](https://github.com/mattlewis92/angular-calendar/issues).  What's more, there is a [demo](https://mattlewis92.github.io/angular-calendar/#/i18n) showing how to achieve this.

**Comment by gmerabishvili** [comment]
I couldn't find any example of how to change language in demos...
