### ISSUE TITLE
Not display the list of event when click in a cell

### ISSUE THREAD

**Issue by achraftalbi** [mattlewis92/angular-bootstrap-calendar#169]
Hi,

 It's me again. I want to display a popup instead of the list which is displayed under the cell when clicking on. So i want to don't display this list.

 Can you telle me how ?

 Thanks

**Comment by mattlewis92** [comment]
I've just released 0.15.1 which passes the event to the on-timespan-click option. So if you do:
`on-timespan-click="$event.preventDefault()"` it should disable the slidebox.

**Comment by achraftalbi** [comment]
Thanks for your response.

**Comment by ketsugi** [comment]
I'm using 0.18.4 and trying to accomplish the same thing.

`on-timespan-click="$event.preventDefault()"` doesn't seem to work.

I've also tried using a scoped function:
`on-timespan-click="timeSpanClicked(calendarDate, calendarCell, $event)`

`$scope.timeSpanClicked = function(calendarDate, calendarCell, event) {`
`        console.log(event);`
`       event.preventDefault();`
`     }`
 
The `console.log()` works but the slidebox still displays.

**Comment by mattlewis92** [comment]
It works fine for me, would you mind sharing a plunker that reproduces your problem please. Thanks!
