### ISSUE TITLE
Color a list of dates like current-day in view month

### ISSUE THREAD

**Issue by silviotroia** [mattlewis92/angular-bootstrap-calendar#171]
Hi guys, 
 i want to color in the same way of current-day a list of dates
for example that list ["2015/10/05","2015/10/19","2015/11/02","2015/11/16"]

i would like color them with different color of current-day. It is possible?

**Comment by mattlewis92** [comment]
Sorry I don't quite get what you mean, could you explain a little bit more please and I'll do my best to help :)

**Comment by silviotroia** [comment]
I try to explain better.
given a list of dates, can I get the corresponding calendar cells coloured by the same color? 
I looked at the 'cell-modifier' attribute and it seems I need to use it to achieve my goal.

**Comment by mattlewis92** [comment]
You don't need to actually modify the template, if you do this then the class will automatically be applied:
```
$scope.modifyCell = function(calendarCell) {
      for (var i = 0; i < $scope.dates.length; i++) {
        if (moment(calendarCell.date).isSame(moment($scope.dates[i]), 'day')) {
          calendarCell.cssClass = 'my-custom-class';
        }
      };
    }
```

Hope that helps! :smile:

**Comment by silviotroia** [comment]
Works fine :+1:
