### ISSUE TITLE
Adding new events dynamically?

### ISSUE THREAD

**Issue by ThinklabsGbR** [mattlewis92/angular-bootstrap-calendar#172]
Hey,

first of all i want to thank you for your great calendar plugin! Im using an ajax call to fetch all events, preprocessing them on client side, to bring them i the needed format and saving them to a scope variable. In chrome it is working fine, but firefox and internet explorer arent showing any events in the calendar. Is there a problem with data binding in your directive? Because of setting the events variable after processing the directive?

Thanks in advance!

Cheers,
Antony

**Comment by mattlewis92** [comment]
That's weird, it shouldn't be happening, please could you provide a plunker, codepen etc which demonstrates your issue? Also are you using the latest version of the calendar?

**Comment by ThinklabsGbR** [comment]
No offence but i was missing a conversion bug of javascripts Date function...sorry. When using moment(date).toDate() everything works like a charm. Maybe IE and FF cant handle every format given to the Date function, i was using something like "2015-11-14 01:09:00". Momentjs handeled it correctly, so everythings fine now!

Can be closed.

**Comment by mattlewis92** [comment]
Oh yeah there are lots of weird discrepancies of date handling between browsers which is one of the reasons that moment.js exists, I'm glad you got it sorted :smile:
