### ISSUE TITLE
change tooltip-html-unsafe - leave only title on

### ISSUE THREAD

**Issue by silviotroia** [mattlewis92/angular-bootstrap-calendar#173]
could I change tooltip-html-unsafe="{{ (event.startsAt | calendarDate:'time':true) + ' - ' + event.title }}" without change template?

**Comment by mattlewis92** [comment]
You'd have to use a custom template, but this is easy enough to do with [this option](https://github.com/mattlewis92/angular-bootstrap-calendar#month-cell-events-template-url). There's also an option to display the event end times if that's all you need:
```
calendarConfigProvider.setDisplayEventEndTimes(true);
```

**Comment by silviotroia** [comment]
I've done this.

  ```
app.config(function($provide) {
  $provide.decorator('mwlCalendarMonthCellEventsDirective', function($delegate) {
    var directive = $delegate[0];
    delete directive.template; //the calendar uses template instead of template-url so you need to delete this
    directive.templateUrl = 'assets/views/template/calendarMonthCellEvents.html';
    return $delegate;
  });
});
```

But I get `Unknown provider: mwlCalendarMonthCellEventsDirectiveProvider`

**Comment by mattlewis92** [comment]
Are you using the latest version of the calendar?

**Comment by silviotroia** [comment]
sure

**Comment by mattlewis92** [comment]
Sorry I must have missed your last reply, this is because the month cell events template isn't a directive, you should override it by directly passing the template url using [this attribute](https://github.com/mattlewis92/angular-bootstrap-calendar#month-cell-events-template-url).

**Comment by silviotroia** [comment]
ok works fine. Tnx a lot!
