### ISSUE TITLE
Fully responsive calendar 

### ISSUE THREAD

**Issue by calvinKG** [mattlewis92/angular-bootstrap-calendar#176]
Hi Matt

I know this isn't a bug, more an enhancement. Is it possible to make this calendar to be fully responsive rather than flowing. 

Please take a look at this calendar for an example. 
http://tympanus.net/Development/Calendario/index.html

**Comment by mattlewis92** [comment]
This isn't something I have the time to add, the calendar isn't really intended to be fully responsive. If you want to add this kind of functionality yourself then your best bet is to [use a decorator](https://github.com/mattlewis92/angular-bootstrap-calendar#custom-directive-templates) to override the template and write your own responsive CSS using media queries.

**Comment by fcristel** [comment]
I would really love to see the calendar responsive. Maybe you should leave this opened, in case that someone provide a template for this that we can all use. Thanks!
