### ISSUE TITLE
Display Events labels 

### ISSUE THREAD

**Issue by calvinKG** [mattlewis92/angular-bootstrap-calendar#177]
Hi Matt

How to display the events labels on the cell events rather than clicking on the slide box to show them.

**Comment by mattlewis92** [comment]
You'll need to use a custom template: https://github.com/mattlewis92/angular-bootstrap-calendar#month-cell-events-template-url

**Comment by calvinKG** [comment]
So, need to write my own template or should I use
the calendarMonthCell.html. I am really confused.

Kind Regars,

KC MASHISHI

**Comment by mattlewis92** [comment]
So you would copy [this template](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthCellEvents.html) into your own working directory, modify it to display the event names etc, and then pass in the new template url to the `month-cell-events-template-url` attribute. It's on the [roadmap](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/162) to provide better demos.

**Comment by calvinKG** [comment]
Then i use the decorator to link the template. 

 $provide.decorator('mwlCalendarSlideBoxDirective', function($delegate) {
        var directive = $delegate[0];
        delete directive.template; //the calendar uses template instead of template-url so you need to delete this
        directive.templateUrl = '/';
        return $delegate;
    });

**Comment by mattlewis92** [comment]
You only need to override the decorator if you need to override the entire calendar template for the month view - if you do that then you don't need to use the attribute templates.

**Comment by silviotroia** [comment]
i've got the same problem. I can't change mwlCalendarMonthCellEventsDirective template.

https://github.com/mattlewis92/angular-bootstrap-calendar/issues/173
some advice?

**Comment by calvinKG** [comment]
This is what I did and I am not sure if its correct or not.

Home.html 

 <mwl-calendar
                    events="filteredEvents"
                    view="calendarView"
                    view-title="calendarTitle"
                    current-day="calendarDay"
                    on-event-click="eventClicked(calendarEvent)"
                    month-cell-events-template-url ="./templates/calendarMonthCellEvents.html">
            </mwl-calendar>


I get this error and my path is correct: 
Error: [$compile:tplrt] Template for directive 'mwlCalendarSlideBox' must have exactly one root element. ./

**Comment by mattlewis92** [comment]
Are you also using a decorator to change the slidebox template?

**Comment by calvinKG** [comment]
No, I have added the month-cell-events-template-url  attribute on the mwl-calendar tag in my home.html page.

**Comment by mattlewis92** [comment]
That shouldn't cause an error with the slidebox though. This would definitely cause that error though: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/177#issuecomment-144006930

**Comment by calvinKG** [comment]
I am still getting the same error. Please test it on your side. 

2angular.js:11707 Error: [$compile:tplrt] Template for directive 'mwlCalendarSlideBox' must have exactly one root element. ./
http://errors.angularjs.org/1.3.18/$compile/tplrt?p0=mwlCalendarSlideBox&p1=.%2F
    at REGEX_STRING_REGEXP (angular.js:63)
    at angular.js:7972
    at processQueue (angular.js:13300)
    at angular.js:13316
    at Scope.parent.$get.Scope.$eval (angular.js:14552)
    at Scope.parent.$get.Scope.$digest (angular.js:14368)
    at Scope.parent.$get.Scope.$apply (angular.js:14657)
    at done (angular.js:9734)
    at completeRequest (angular.js:9924)
    at XMLHttpRequest.requestLoaded (angular.js:9865)(anonymous function) @ angular.js:11707jqNodes.$get @ angular.js:8628processQueue @ angular.js:13308(anonymous function) @ angular.js:13316parent.$get.Scope.$eval @ angular.js:14552parent.$get.Scope.$digest @ angular.js:14368parent.$get.Scope.$apply @ angular.js:14657done @ angular.js:9734completeRequest @ angular.js:9924requestLoaded @ angular.js:9865

**Comment by mattlewis92** [comment]
Works fine for me:
<img width="884" alt="screen shot 2015-09-29 at 12 12 09" src="https://cloud.githubusercontent.com/assets/6425649/10162474/5af1a158-66a3-11e5-9aca-4dd47a42f446.png">

```
<script type="text/ng-template" id="test.html">
  Hello world
</script>

<mwl-calendar
  events="vm.events"
  view="vm.calendarView"
  view-title="vm.calendarTitle"
  current-day="vm.calendarDay"
  on-event-click="vm.eventClicked(calendarEvent)"
  on-event-times-changed="vm.eventTimesChanged(calendarEvent); calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
  edit-event-html="'<i class=\'glyphicon glyphicon-pencil\'></i>'"
  delete-event-html="'<i class=\'glyphicon glyphicon-remove\'></i>'"
  on-edit-event-click="vm.eventEdited(calendarEvent)"
  on-delete-event-click="vm.eventDeleted(calendarEvent)"
  auto-open="true"
  day-view-start="06:00"
  day-view-end="22:00"
  day-view-split="30"
  cell-modifier="vm.modifyCell(calendarCell)"
  month-cell-events-template-url="test.html">
</mwl-calendar>
```

**Comment by calvinKG** [comment]
I still get the same erro
![error](https://cloud.githubusercontent.com/assets/1926014/10162656/0c0dc382-66ad-11e5-9be7-172659779ab8.PNG)
r even after implementing you code.

**Comment by calvinKG** [comment]
Which attribute can I use to list the event in a list format in the cell events?

**Comment by mattlewis92** [comment]
You need to use the `month-cell-events-template-url` attribute to override the cell events template, then they are available in the template scope as `day.events`. Alternatively if you don't mind the jquery dependency, there's always the [fullcalendar](http://angular-ui.github.io/ui-calendar/)

**Comment by calvinKG** [comment]
I can't use the jquery calendar in a angularJS application. It give me issues when I want to run End2End testing.

**Comment by Saul3d** [comment]
I see this thread is a bit old but I've been looking for a way to change the slidebox template into a pop-up modal, and from what I've read here it seems as if all I need to do is change the $provide.decorator to link my modal/new template in order to display my appointments as a pop-up modal.  Is this right?
