### ISSUE TITLE
Add directive for overriding the default templates

### ISSUE THREAD

**Issue by yorkchanhk** [mattlewis92/angular-bootstrap-calendar#179]
Support overriding
- calendar.html
- calendarDayView.html
- calendarHourList.html
- calendarMonthView.html
- calendarSlideBox.html
- calendarWeekView.html
- calendarYearView.html

in addition to
- calendarMonthCell.html
- calendarMonthCellEvents.html

**Comment by mattlewis92** [comment]
These cannot be done in the same way as they're directive templates, you'll need to use a decorator for that instead as explained here: https://github.com/mattlewis92/angular-bootstrap-calendar#custom-directive-templates
