### ISSUE TITLE
View Events in Month View with just numbers

### ISSUE THREAD

**Issue by chadwtkns** [mattlewis92/angular-bootstrap-calendar#18]
Hi I was wondering if there is way to have the events in the month view as numbers just like they are in the year view. This would be a great option since I can have like 60-80 events on a day and it would be better if the calendar would just show a number instead. Thanks. 

PS Not sure if this where feature requests should go but I wasn't sure if there was anywhere else to put the request.

**Comment by mattlewis92** [comment]
Hi there, that seems like something that is doable. I'm super busy with a project at work right now that is taking up 100% of my time, it won't be until the weekend after next that I can get this in.

**Comment by mattlewis92** [comment]
Done
