### ISSUE TITLE
Day view type columns

### ISSUE THREAD

**Issue by JonnyBGod** [mattlewis92/angular-bootstrap-calendar#180]
Hi all,

I would like to propose a feature for daily view where you could display different columns for each type.
This would make possible to use this view as a multiple user scheduler. Each user would be a "type" and had its own column for its tasks.

I have been trying to find a library with this functionality to in in a project where I need a dashboard where and "admin" would be able to have a full view of the tasks for each user for the day. Only found a couple of libraries but all of them were proprietary and worst of all presented the daily timeline horizontally and I prefer it to be vertical, giving more space for description and closer to how users are used to see a daily timeline.

**Comment by mattlewis92** [comment]
This is too specific to be added into the core of the calendar - for additional business logic like this you can implement it using a custom template as described [here](https://github.com/mattlewis92/angular-bootstrap-calendar#custom-directive-templates).

**Comment by mitomm** [comment]
+ 1 for @JonnyBGod . I actually think that having multiple "columns/resources" in a day view would be quite generalizable and useful to many people. A nice example of how it could look like, can be found [here](http://fullcalendar.io/js/fullcalendar-scheduler-1.2.1/demos/vertical-resource-view.html). But as you suggest @mattlewis92 , it might very well be doable with a custom template without modifying the core. Adding such a template to the repo would then probably be enough.
