### ISSUE TITLE
calendarDay is not using the correct time, even with moment-timezone

### ISSUE THREAD

**Issue by Frondor** [mattlewis92/angular-bootstrap-calendar#181]
Maybe this has something to do with my time zone offset?.. I don't know, please check yourself, I'm null at date/times: http://www.timeanddate.com/time/zone/uruguay/montevideo

![](https://i.gyazo.com/bcd19db719c1e8588a5cbe456de138d5.png)

As you can see in the above picture, the date showing is 2 hours later than the real time in my PC.
I'm "printing" that date just like `{{calendarDay | json}}` while in the controller, `$scope.calendarDay = new Date();`
Even if I try to use angular `$filter` or `moment().subtract(2, 'hours').toDate()` on `$scope.calendarDay`, it'll get back to the wrong time after I press *prev*/*next* buttons ("Anterior" / "Siguiente" respectively)

Any guess on this?

**Comment by Frondor** [comment]
Even demo site is displaying wrong for me:
![](https://i.gyazo.com/76a7925af8b5e41a6e77dc05dd770150.png)

**Comment by mattlewis92** [comment]
This looks like a nasty bug to fix, thanks for reporting it!. Luckily I'm travelling today so will be in a different timezone in a few hours so will hopefully be able to work it out then. I'll let you know when I've pushed out a fix :smile:

**Comment by Frondor** [comment]
Shit! I was hoping this not to be a bug :( I hate to deal with dates in javascript, it's so annoying!
Maybe you can try something like `calendarConfigProvider.setTzOffset('-0300');` for example... or let moment handle it somehow using its API... Don't know... I'm just throwing (dumb) ideas :)

**Comment by Frondor** [comment]
I managed to "normalize" the date, but it's a bit dirty in my opinion... Sadly it's the only way I found.
I think the whole calendar should make use of `moment-timezone.js` and modify the global `moment().format()` (which already includes locales) instead of `new Date()` (which is slower by the way) if provided.

I've changed the `new Date()` method here https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlDateModifier.js#L13 and also in my application controller so `$scope.calendarDay` and `vm.date` are both matched using
`moment().format("YYYY-MM-DDTHH:mm:ss.SSSS") + 'Z';`

Check my calendar controls here using `vm.date = new Date()` and `$scope.calendarDay = new Date();` **at 13:18:51 real time**:
![](https://i.gyazo.com/5605fa9643b26ffe3fcae034a24f0f2d.gif)

Now check my calendar controls here using `vm.date = moment().format("YYYY-MM-DDTHH:mm:ss.SSSS") + 'Z';` and `$scope.calendarDay = moment().format("YYYY-MM-DDTHH:mm:ss.SSSS") + 'Z';` **at 13:20:44 real time**:
![](https://i.gyazo.com/3f57236bc07472b96283506bf6f341c9.gif)

**Note the hours are getting updated in October and April for summer/winter time change**, that's the only way I found to "workaround" the problem. Because there's another alternative, this one doesn't update at summer/winter time changes, check this gist please: **https://gist.github.com/Frondor/38cc71b5fa063ed5f639/revisions**
With those changes you are actually making use of `moment().format()` to handle correctly local times, but summer/winter time change aren't getting updated that way, I'm afraid :trollface: 

Sorry for the extension, but I wanted to share everything I've experimented :D Didn't make a pull request because I don't feel competent for such action.
For more information I've created a [SO question](http://stackoverflow.com/questions/32950369/javascript-datetime-strings-ignoring-timezone-offset-experiment), reaaaaaally silly one, but worth the attempt:

**Comment by mattlewis92** [comment]
Sorry I am a bit lost now, can you just explain in a sentence what exactly the current behaviour is and what you expect the behaviour to be? Thanks! :smile:

**Comment by Frondor** [comment]
:flushed: 
:tired_face::gun: 
:dizzy_face:
Ok, but please, try to read again.

1. As I can see, the calendar uses `$scope.calendarDay` to display "today" date.
2. `mwlDateModifier` directive **try to use** the same `$scope` variable to change the content in views.
3. Said directive [re-declare](https://gist.github.com/Frondor/38cc71b5fa063ed5f639/revisions#diff-c448086b3b78c1ded168cbc6fdff8b73R12) a date object for "today" if `set-to-today` attribute is present, instead of using `$scope.calendarDay` (from my own app controller, the same I use for calendar directive).
4. `new Date()` and `toDate()` aren't taking care of timezone offsets, so the datetime my calendar is using is wrong (offset not being applied to the date object/string). [:warning:](https://gist.github.com/Frondor/38cc71b5fa063ed5f639/revisions#diff-c448086b3b78c1ded168cbc6fdff8b73)

When I click one of `<mwl-date-modifier>` directives, the date object contained in my `$scope.calendarDay` gets changed to the methods I've mentioned in above Nº 3 and Nº 4 points, so if my local time is 13:00, `$scope.calendarDay` will return 15:00 (ignoring my -0200 timezone offset). I've provided two methods I found to "fix" it with a "workaround" but I don't feel like they are good practices, that's up to you.
I still believe that there should be a way to set the timezone so the whole calendar and its directives uses the same date object, which the local timezone, but I think that requires a major change in your code and the way that `<mwl-date-modifier>` behaves.

**Comment by Frondor** [comment]
It was a misunderstanding of mine about UTC timezones, a moment.js developer has explained me about what I though it was a problem. This calendar itself is using UTC dates... So this shouldn't be a problem, but anyway you have to be careful with your directives because using UTC datetimes and not formating them to a *local time* turns into misbehavior like this one:
![](https://i.gyazo.com/e8f7b9c201d9135ffc3e2b7f53b9eaae.png)

**Note its 04:35 here, but the `day view` displays 06:00 + events (because its taking the UTC time, I mean, ignore my `-02:00` timezone offset)**

Is this behavior intended? Because in my own project I can see the "Time" rows from 00:00 to 23:00 without problem, but in the demo: ![](https://i.gyazo.com/6d0e096927ef252de2841608ba64ecd3.gif)

Adding an event for today at the same time its created will result in a wrong placement inside the grid in day view.

**Comment by mattlewis92** [comment]
As far as I'm aware `new Date()` automatically creates a date with the local timezone embedded in it rather than created a UTC date:

```
var d = new Date();
console.log(d.getTimezoneOffset() / -60); //should be your timezone
```

As for the date view, this is expected as it's an option configured by the calendar:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/index.html#L97
