### ISSUE TITLE
Possible global pollution

### ISSUE THREAD

**Issue by jmsherry** [mattlewis92/angular-bootstrap-calendar#182]
Hi Matt,
I just noticed this and wondered if you knew about it?

<img width="448" alt="screen shot 2015-10-05 at 19 15 10" src="https://cloud.githubusercontent.com/assets/697341/10289320/a779ad1c-6b95-11e5-8026-f0a258189a93.png">

Thanks

James

**Comment by mattlewis92** [comment]
That's just how webpacks UMD works, it exports the module name so if you're using commonjs you can do angular.module('myApp', [require('angular-bootstrap-calendar')]);

As you're using globals it exports the module name on the window (I think). AFAIK this is OK, I based this method on what I saw several other popular angular modules doing to support UMD loading.

**Comment by jmsherry** [comment]
OK, cool. :) Just thought I'd mention...
