### ISSUE TITLE
Is there a possibility to use week view not for the week?

### ISSUE THREAD

**Issue by purple-sunrise** [mattlewis92/angular-bootstrap-calendar#183]
Hi! This will be very helpful for me if there is some way to show week view for a full year for example. Because this view is beautiful for gantt diagram, it's simple, it's pretty. But in the scale of the week it will not work for this purpose.

**Comment by mattlewis92** [comment]
Unfortunately this isn't a common enough use case to add to this module, maybe something like [this](https://www.angular-gantt.com/demo/) might be more suited to your needs?

**Comment by purple-sunrise** [comment]
Thank you for quick feedback. Yes, I saw it, but for me your plugin is more pretty and simple.

**Comment by mattlewis92** [comment]
Maybe fork it for your needs then to add the functionality you need :smile:
