### ISSUE TITLE
recursOn 'month' 

### ISSUE THREAD

**Issue by grunvaldo** [mattlewis92/angular-bootstrap-calendar#185]
Hi,

The attribute "recursOn" seams to work only when it is set to 'year', I am not able to create an event with a month recursivity, did I miss something ?
Thanks in advance for your help.

Grunvald

**Comment by mattlewis92** [comment]
Just double checked and it's working for me, can you share some code with me?

**Comment by grunvaldo** [comment]
Tank your for your support.
The difference between your code and mine is that I use a var "$scope.vm" instead of using directly the controller.

I copy / paste your code and it doesn't work.
I just changed the attribute recursOn to 'year' and it works...
But I create my own recursive event creation to bypass this problem...

// init 
$scope.initCalendar = function () {
        
        $scope.vm = {
            calendarView: 'month',
            calendarDay: new Date(),
            events: [],
            eventClicked: function (event) {
                $scope.showUpdateTaskModal(event);
            },
            eventEdited: function (event) {
                $scope.showUpdateTaskModal(event);
            },
            eventDeleted: function (event) {
                $scope.showDeleteTaskModal(event);
            },
            eventTimesChanged: function (event) {
                //showModal('Dropped or resized', event);
            },
            toggle: function ($event, field, event) {
                $event.preventDefault();
                $event.stopPropagation();
                event[field] = !event[field];
            }
        }
}

// on add event validation
$scope.validateAddModal = function () {
            $scope.vm.events.push({
                title: 'This is a really long event title that occurs on every year',
                type: 'important',
                startsAt: moment().startOf('day').add(7, 'hours').toDate(),
                endsAt: moment().startOf('day').add(19, 'hours').toDate(),
                recursOn: 'month'
            });
}

**Comment by mattlewis92** [comment]
hmm that's really odd, as that should just work. If you can share a plunker or something similar demonstrating the bug I can dig deeper for you, but otherwise if you're happy with just duplicating the event then I'm going to close this as it's working ok for me on my local.
