### ISSUE TITLE
as I can implement my own template

### ISSUE THREAD

**Issue by dchi1** [mattlewis92/angular-bootstrap-calendar#186]
Hello, first thank for the great contribution you make.
I see the documentation that you can add your own template, but I can not understand how inplementarla, I add the lines of code to my config. but now that I devo do?

![screenshot_42](https://cloud.githubusercontent.com/assets/15113623/10467182/bbde8734-71ce-11e5-96bd-5d23a027d86d.png)

**Comment by mattlewis92** [comment]
Hi sorry I don't really get what you mean, can you explain a bit more in detail please? Maybe share some code in a plunkr demonstrating your problem?

**Comment by dchi1** [comment]
now achieved implement the decor but my query is:
You can add an additional view of the existing as year, month and day ?, further as pictured, to throw me to get my custom template.
what I did is now using the decorator with ```mwlCalendarDayDirective directive replaces the day ``` template, and it works perfect but: as you step values depending on the day?

**Comment by mattlewis92** [comment]
Sorry I don't quite understand what you mean, can you explain a bit more please. Thanks!

**Comment by mattlewis92** [comment]
Closing to keep issues clean, if this is still an issue let me know.
