### ISSUE TITLE
events do not agree on the timeline

### ISSUE THREAD

**Issue by dchi1** [mattlewis92/angular-bootstrap-calendar#187]
in the day view, change ````day-view-start = "vm.dayViewStart" ````  to```` day-view-start = "'08:00'"```` to begin at 08:00 AM, but not change this coiciden events in the time line.

![screenshot_43](https://cloud.githubusercontent.com/assets/15113623/10489570/06310fc8-7274-11e5-9bd8-73dbf305d22e.png)

**Comment by mattlewis92** [comment]
Can you share a plunker which reproduces your problem. Thanks.

**Comment by mattlewis92** [comment]
Closing to keep issues clean, if this is still an issue let me know.
