### ISSUE TITLE
asynchronous data and more.

### ISSUE THREAD

**Issue by physio** [mattlewis92/angular-bootstrap-calendar#188]
good morning, sorry for my orrible english. I want to apologize if I write here but I did not know what the right channel.
I think this is a very interesting project and I wanted to use it.
I ask myself what is the best way to load the list of events if I list is long (perhaps by clicking the buttons next and prev)

I wanted to also ask how come I can not edit or drag event object if I set the following parameters:
     event.editable = true;
     event.deletable = true;
     event.draggable = true;
     event.resizable = true;

reguards

**Comment by mattlewis92** [comment]
For drag and drop to work you need to include [this library](http://interactjs.io/).
