### ISSUE TITLE
Sliding panel does not close properly

### ISSUE THREAD

**Issue by Tropicalista** [mattlewis92/angular-bootstrap-calendar#19]
If I try to insert a new event, sliding panel is opened, I click on edit icon and appears a modal. After closing modal if I try to click on other date, without closing sliding panel, the sliding panel does not close properly. I would expect that the panel would be closed automatically.

I'm on chrome.

**Comment by mattlewis92** [comment]
Nice spot, will get that fixed up soon.

**Comment by mattlewis92** [comment]
Fixed

**Comment by Tropicalista** [comment]
Well done!
