### ISSUE TITLE
I am having problem with events

### ISSUE THREAD

**Issue by heavenchains** [mattlewis92/angular-bootstrap-calendar#190]
Events are added like this:

$scope.events = [
{
    title: 'My event title', // The title of the event
    type: 'important', 
    startsAt: new Date(2015,10,26),
    endsAt: new Date(2015,10,26), 
    editable: false,
    deletable: false,
    incrementsBadgeTotal: true
   }
];

however its supposed to be on October right? well it's not it displays on November and every date I assign in the events are always 1 month difference like if it's 2015,9,26 it gets on October and etc, 

one more thing, how can I change the color of the weekends because here in my country we are having weekends on Fridays and Saturdays

can you please solve this issues .. thank you in advance.

**Comment by mattlewis92** [comment]
Javascript date objects have [0 based months](http://www.w3schools.com/jsref/jsref_getmonth.asp) so what you're doing is the correct behaviour.

As for changing the weekend on the calendar, see the i18n guide [here](https://github.com/mattlewis92/angular-bootstrap-calendar#internationalization-and-localization).
