### ISSUE TITLE
calendarTitle

### ISSUE THREAD

**Issue by tjcflys** [mattlewis92/angular-bootstrap-calendar#191]
Really awesome what you have done! Thank-you so much for this!!

Having trouble getting the calendarTitle to show. Plunker: http://embed.plnkr.co/LOQSOvcwZxij0OdrcZeh/preview

Thanks for your help!

**Comment by mattlewis92** [comment]
Sorry I couldn't get your plunker to run. Looking at the code though you're missing the `view-title="calendarTitle"` attribute on the calendar which bind the title to your variable
