### ISSUE TITLE
Underlying settings/configuration

### ISSUE THREAD

**Issue by stodolos** [mattlewis92/angular-bootstrap-calendar#192]
Awesome project!  Thank you so much for this.

I was curious as to how to reach/control the underlying settings of the bootstrap calendar.  For instance, how do I change the option to hide the weekbox?  I was able to hide it in CSS, but I know there is an 'weekbox' option on the bootstrap calendar.  Another option would be to hide the weekends.

Would I just use the calendarConfigProvider or calendarHelper accordingly, and change what I needed depending on the situation?  I know I can start tweaking the code, but I just wanted to make sure I wasn't missing something obvious.

Thanks again,

Chris

**Comment by mattlewis92** [comment]
To hide the weekbox just use CSS - in an effort to keep the API clean I wouldn't add an option to hide it when you can just do it with CSS.

For hiding weekends it is far more complicated, for that you would be best off using a [custom template](https://github.com/mattlewis92/angular-bootstrap-calendar#custom-directive-templates).
