### ISSUE TITLE
dayClicked override?

### ISSUE THREAD

**Issue by jbabuscio** [mattlewis92/angular-bootstrap-calendar#194]
I'm digging through and don't see anything available at this point.  Do you have plans to expose this?  For example, I'm looking to drill into the day, rather than expand with the events.

**Comment by mattlewis92** [comment]
Use a [decorator](https://github.com/mattlewis92/angular-bootstrap-calendar#custom-directive-templates) to override the [month template](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthView.html), then remove the  `mwl-calendar-slide-box` and replace the [ng-click handler](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthView.html#L17) with `ng-click="vm.calendarCtrl.drillDown(day.date)"`

**Comment by jbabuscio** [comment]
One more additional change.  In the month template, I had to remove this line:
<ng-include src="vm.cellTemplateUrl || 'calendarMonthCell.html'"></ng-include>

All good after that.  Thanks!

**Comment by mattlewis92** [comment]
Great to hear!
