### ISSUE TITLE
how to implement my own driver when using Decorator

### ISSUE THREAD

**Issue by dchi1** [mattlewis92/angular-bootstrap-calendar#195]
I am using the decorator option to have my own template personalizablede week view,

but as I can use my own functions within the new template.
example my template I have a week ng-click = "diaSelecionado(day.date)" this is not working. the function is defined day in my controlling father "MiControlador"

**Comment by mattlewis92** [comment]
As the directives use an isolate scope none of your controller functions will be exposed in your custom template. However you can expose them using the directives api, so if you pass: `on-event-click="myControllerFunction(day)"` to the calendar, you can call it in the calendar template like so:
`ng-click="vm.onEventClick(day.date)"`

**Comment by dchi1** [comment]
@mattlewis92  thank you very much, but if I want to work more proper functions?

**Comment by mattlewis92** [comment]
Maybe create a child directive then with your additional functionality in it. So in your custom template do something like
```
<my-custom-directive events="vm.events"></my-custom-directive>
```

then create that directive which displays most of the content for your custom template and has all the additional functionality you need.

**Comment by dchi1** [comment]
add a decorator in this way, so you can add a new attribute to the directive
             ````   $provide.decorator('mwlCalendarWeekDirective', function ($delegate) {
                    console.log($delegate)

                    var directive = $delegate[0];
                    delete directive.template;
                    directive.templateUrl = 'views/myweek.html';                    
                           directive.$$isolateBindings['evento'] = {
                             attrName: 'evento',
                              mode: '=',
                              optional: true                              
                              
                              };
                 return $delegate;
                });````

in my controlling father I want to send to the newly created template.
but it does not work

**Comment by dchi1** [comment]
Hi, I have an example here, where I pass parameters between my father and the new controller template week.

http://embed.plnkr.co/XihZabCHjLHtPiCQnbUi/preview
