### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by vova1987** [mattlewis92/angular-bootstrap-calendar#196]
RTL (Right to Left languages) support is very partial.
using a bootstrap-UI RTL theme (which mainly sets all possible direction directives to RTL), the calendar is very inconsistent. Some fields and columns are flipped as expected, but most the views - day columns, day title positions, etc. remain LTR.

IS there a way to at least override the column settings to be RTL?

**Comment by mattlewis92** [comment]
Sorry RTL isn't something I know much about, your best bet is probably to use a [custom template](https://github.com/mattlewis92/angular-bootstrap-calendar#custom-directive-templates) or I'd happily accept a PR that adds RTL support! :smile:
