### ISSUE TITLE
Event startsAt should be a javascript date object

### ISSUE THREAD

**Issue by celsomtrindade** [mattlewis92/angular-bootstrap-calendar#198]
I'm using this calendar and the time for `startsAt` and `endsAt` is being generated in my database, with `PHP` so i have a time like this: 

    2015-11-03T16:30:00.000Z

When I show the calendar, everything is working fine, but i keep getting this warning message:

    `Bootstrap calendar:  Event startsAt should be a javascript date object`

How to solve this?

**Comment by mattlewis92** [comment]
Use the date constructor to convert the strings to date objects:
```
new Date('2015-11-03T16:30:00.000Z');
```

**Comment by celsomtrindade** [comment]
That was fast! And it fixed the problem. Thanks!!!

**Comment by mattlewis92** [comment]
NP, happy to help :smile:

**Comment by joaquinrivero** [comment]
So, when all events return, need to run a loop for change each one?

**Comment by mattlewis92** [comment]
@joaquinrivero yup, it's as simple as:
```
events.forEach(event => {
  event.startsAt = new Date(event.startsAt);
});
```
