### ISSUE TITLE
Programmatically toggle the event list (the one that slides out in the month view)

### ISSUE THREAD

**Issue by worldspawn** [mattlewis92/angular-bootstrap-calendar#199]
Hi,

I made some event seeking button (first, previous, next, last) that seek through the sorted event list and set the current day to the event it finds. This moves the view to the correct month (sweet!) if needed. But I would also like to close any open sliders and have it expand the slider on the day I have just set.

How might I do that? Note this is not happening as part of any calendar triggered event.

Also would like to change the slidebox template. I dont want the time appearing, is that template overridable?

**Comment by mattlewis92** [comment]
In `0.16.x` I've added a new `cell-is-open` attribute, which you can use to control if the slidebox is open or not (If you set it to true it will now by default have the behaviour you expect of opening the same day of the next month when going between them)

**Comment by mattlewis92** [comment]
To change the slidebox template, use a decorator: https://github.com/mattlewis92/angular-bootstrap-calendar#custom-directive-templates
