### ISSUE TITLE
add Spanish language

### ISSUE THREAD

**Issue by newmesiss** [mattlewis92/angular-bootstrap-calendar#20]
I watched that bootstrap-calendar You can change the language, as it did this with this module?

**Comment by mattlewis92** [comment]
The library uses the angular date filter to generate the days of the week and the months. Thus you just need to include the appropriate angular language file and the calendar should automatically update to your language.

https://docs.angularjs.org/guide/i18n
https://github.com/lgalfaso/angular-dynamic-locale

**Comment by mattlewis92** [comment]
I've just made some small changes to allow full i18n and updated the docs to reflect this, see https://github.com/mattlewis92/angular-bootstrap-calendar/commit/dffe35ed74e9dad263a2e3654880561e172c73eb
