### ISSUE TITLE
recursOn = week?

### ISSUE THREAD

**Issue by kalletoxic** [mattlewis92/angular-bootstrap-calendar#200]
Hello,

I was wondering why recursOn only have year and month as an option.

Why not have week?

//Kalle

**Comment by mattlewis92** [comment]
I tried to implement this but was [unsuccessful](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/127), as it requires duplicating the event to get it to appear several times. Your best bet is to implement the logic yourself with the snippet I posted in that issue.
