### ISSUE TITLE
 calendarConfigProvider.setDateFormatter();

### ISSUE THREAD

**Issue by SachinKalsi** [mattlewis92/angular-bootstrap-calendar#202]
I have to use the same calendar in two different pages. For one calendar the day view title  has to be shorter , and for the other one the day view title has to be longer. 

In one page I used the following code.

calendarConfigProvider.setTitleFormats({
      day: 'dddd D MMM' 
   });

In other page I used the following code.

calendarConfigProvider.setTitleFormats({
      day: 'ddd D MMM' 
   });

But when I tried to load any of the page , setTitleFormats function is getting called twice. Help me out

**Comment by mattlewis92** [comment]
The angular config phase only runs once, so you can only configure the provider once. To modify settings at runtime, in 1 controller do:
```calendarConfig.titleFormats.day = 'dddd D MMM';```
and in the other controller do:
```calendarConfig.titleFormats.day = 'ddd D MMM';```

**Comment by bsssp** [comment]
it doesn't work for templates at runtime
