### ISSUE TITLE
Push startsAt and endsAt data into $firebaseArray

### ISSUE THREAD

**Issue by heavenchains** [mattlewis92/angular-bootstrap-calendar#204]
Hello, I am working on a project that included your calendar which of course awesome and everything but I am bound to make this having a backend and data base so I have tried many times to work with your demo until I made it work however when you push a new tr it only contains title, type, draggable and resizable I want when I create or add a new event and when I update the date and click on a send button it delivers the startsAt and endsAt time to the data base into firebaseArray here is the function 

 $scope.pushEvents = function(event){
       console.log('adding..')
       var ref = new Firebase('myURL/vacations');
       
      $scope.events = $firebaseArray(ref);
      $scope.events.$add({
        title : event.title,
        type : event.type,
        startsAt : event,
        endsAt :   event

      })
      }

however, when I click on this send button it comes back to me without the startsAt or the endsAt however I have added them into the event.push in the html like this : 

<code>
 <button
              class="btn btn-primary pull-right"
              ng-click="events.push({title: 'New event', type: 'important', draggable: true, resizable: true, startsAt : calendarDay , endsAt : calendarDay })">
              Add new
 </button>
</code>

it just doesn't update or even create into the array in the database so can you please help me , Thank you in advance for your cool calendar :)

**Comment by mattlewis92** [comment]
`startsAt : event,` and `endsAt :   event` looks wrong as you're setting those fields to the event object. Is `calendarDay` initialised? Have you tried `console.log`ing the objects you're working with to debug what's going on?
