### ISSUE TITLE
Event binding

### ISSUE THREAD

**Issue by ackdev** [mattlewis92/angular-bootstrap-calendar#207]
Hi,  love the calendar, but having a problem with the calendar not noticing the bound scope variables.

trying $scope.calendarEvents.splice(0, $scope.calendarEvents.length); and populating via  data
                .forEach(function(
                    entry) {
                    if (entry.appointmentStartTime) {
                        tmp
                            .push({
                                title: entry.title,
                                type: 'info',
                                startsAt: new Date(entry.appointmentStartTime),
                                endsAt: new Date(entry.appointmentEndTime),
                                editable: false,
                                deletable: false,
                                draggable: true,
                                resizable: true,
                                incrementsBadgeTotal: true,
                                cssClass: 'a-css-class-name'
                            });
                    }
                });
$scope.calendarEvents = tmp;
but the calendar doesn't notice unless I remove the calendar from the DOM and readd - any ideas how to fix?

Thanks!!

**Comment by MacheteDSMS** [comment]
I think, than `$scope.$apply()` must help.

**Comment by mattlewis92** [comment]
Please can you share a plunker / reproducible code that demonstrates your problem. Thanks!

**Comment by mattlewis92** [comment]
Closing, if still an issue LMK.

**Comment by ackdev** [comment]
getting plunker going may take awhile.  I temporarily worked around the
issue by using ng-if to remove and re add to dom and force a redraw of
events.

**Comment by ackdev** [comment]
refactored calendar into it's own directive, issue no longer occurs and
watches the collection as expected, no apply needed etc

false alert :)
