### ISSUE TITLE
configure project in one driver

### ISSUE THREAD

**Issue by newmesiss** [mattlewis92/angular-bootstrap-calendar#21]
I have the following questions, I am working on the basis of the code sample project, I am modifying main.js and I want to leave all the drivers view this file so set as follows

```javascript
var app = angular.module('mwl.calendar', ['ui.bootstrap','firebase']).constant('moment', window.moment);

  app.controller('MainCtrl', ['$firebase' ,'$scope',
        function ($firebase,$scope, $modal, moment) {

    var currentYear = moment().year();
    var currentMonth = moment().month();

```

but I do not get to run the project now

![image](https://cloud.githubusercontent.com/assets/5264883/6170399/3a2ec7c4-b2b3-11e4-8513-6eb098d8ed82.png)

**Comment by mattlewis92** [comment]
You don't appear to have moment.js installed: http://momentjs.com/

**Comment by newmesiss** [comment]
estoy utilizando el mismo proyecto angular-bootstrap-calendar, y lo unico que ise fue cambiar 
 en el main,js
```javascript
app.controller('MainCtrl',['$scope','$firebase', function ($scope, $modal, moment) {

    var currentYear = moment().year();
    var currentMonth = moment().month();

```

y en app.js

var app = angular.module('mwl.calendar', [
    'ui.bootstrap','firebase'
  ]);
