### ISSUE TITLE
Add new options

### ISSUE THREAD

**Issue by ramilS** [mattlewis92/angular-bootstrap-calendar#210]
Please, add new options to directive:
```scope: {
display-week-numbers: true/false,
weekbox: true/false,
}```

**Comment by mattlewis92** [comment]
You can easily implement this yourself with CSS:
```
#cal-week-box {
  display: none;
}
```

**Comment by ramilS** [comment]
it's not so cool to do like that

**Comment by mattlewis92** [comment]
Anything that can be implemented yourself that easily I wouldn't add to the calendars API to keep it as clean and minimalistic as possible.
