### ISSUE TITLE
Week view

### ISSUE THREAD

**Issue by cojack** [mattlewis92/angular-bootstrap-calendar#211]
Could you make the week view, to looks like day view? I mean with time on the left.

**Comment by mattlewis92** [comment]
There is already experimental support for this, however there are some bugs with it and the event end time is ignored:
```
angular.module('myModule')
  .config(function(calendarConfigProvider) {
    calendarConfigProvider.showTimesOnWeekView(true);
  });
```

**Comment by cojack** [comment]
Thanks!
