### ISSUE TITLE
Using $scope.$watch in demo.js to manipulate vm.event.endsAt in a modal

### ISSUE THREAD

**Issue by laurentvoyer** [mattlewis92/angular-bootstrap-calendar#217]
Is it possible to manipulate vm.event.endsAt on $watch in demo.js? 

I'm asking because the function doesn't react to the changes i'm doing while i'm in a Modal  (trying to change the end-date when updating the start-date of a ui bootstrap datepicker)

    function showModal(action, event,events) {
	
        modalInstance = $modal.open({
        templateUrl: 'modalEventContent.html',
        controller: function() {
          var vm = this;
          vm.action = action;
          vm.event = event;
		  vm.events = events;
		  

          // ------  Update END DATE based on the START DATE 
          $scope.$watch('vm.event.startsAt', function (newVal, oldVal) {
            if(!newVal) return;

            // if the new start date is greater than the current end date .. update the end date
            if(vm.event.endsAt){
              if( +vm.event.endsAt < +vm.event.startsAt ){
                vm.event.endsAt = newVal;
              }
            } else {
              // just set the end date
              vm.event.endsAt = newVal;
            }
          });			  
		  
		  
		  
        },
        controllerAs: 'vm'
      });
    }

Thanks

**Comment by mattlewis92** [comment]
It works fine for me, please can you share a plunker that reproduces your problem.

**Comment by laurentvoyer** [comment]
Hi Matt,

you can see my code in demo.js in here http://plnkr.co/edit/nXJ0SKzDemrhvgWyfue5

In the function below:
```
    /* 
    ******************************************
    ****  Show Event Modal
    ******************************************
    */
        function showEventModal(action, event, events) {
```

I want to make sure the end-date is equal to start-date when start-date is set to greater than end-date, but once the modal is opened, the watch doesn't seem to react. Any idea?

I'm a bit confused about the vm.event.startsAt, does vm represent $scope
