### ISSUE TITLE
onDayClick event

### ISSUE THREAD

**Issue by ecabrera1** [mattlewis92/angular-bootstrap-calendar#222]
Is there a way to run my own function on the click of a day instead of the current handleEventDrop? Or even to run handleEventDrop and then execute my function? Any assistance would be great. 

Thank you

**Comment by mattlewis92** [comment]
I think you want one of these options:
https://github.com/mattlewis92/angular-bootstrap-calendar#on-timespan-click
https://github.com/mattlewis92/angular-bootstrap-calendar#on-drill-down-click

**Comment by ecabrera1** [comment]
Thank you so much for the quick response. I also need to pull a list of all the events that show up on a specific day clicked. I'm just not seeing exactly how it's done.  Thank you
