### ISSUE TITLE
View dont update

### ISSUE THREAD

**Issue by IgorDePaula** [mattlewis92/angular-bootstrap-calendar#223]
After the calendar is loaded, the array variable used for fill the calendar don't update view, I call the push method and view don't is updated. Is only this part that view isn't updated.

**Comment by IgorDePaula** [comment]
I finished one test now, I retired the calendar directive and the view is updated. The calendar component is lock the view.

**Comment by mattlewis92** [comment]
This is working fine in the demo: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/index.html#L122

Please can you share a plunker that reproduces the issue you're experiencing. Thanks.

**Comment by IgorDePaula** [comment]
You closed the issue without giving me a chance to explain. This is arrogance. The example have libs  out updated.
