### ISSUE TITLE
onDayClick event

### ISSUE THREAD

**Issue by ecabrera1** [mattlewis92/angular-bootstrap-calendar#224]
I need to pull a list of all the events that show up for day clicked. I'm just not seeing exactly how it's done. Thank you my script is on-timespan-click="dayClicked(calendarDate, calendarEvent)" and nothing is being returned for the day clicked. So I need to click on a day show the date clicked and a list of all events that show up on that day. Thanks

**Comment by mattlewis92** [comment]
There is no API to do this, it's easy enough to implement yourself though:
```
$scope.dayClicked = function(calendarDate) {
  var eventsOnDay = $scope.events.filter(event => moment(event.startsAt).startOf('day').isSame(moment(calendarDate)));
};
```

**Comment by ecabrera1** [comment]
Ok, thank you I figured I would ask before I started down that path. Great plugin. TY
