### ISSUE TITLE
Wrong day select

### ISSUE THREAD

**Issue by ntnhan0512** [mattlewis92/angular-bootstrap-calendar#226]
In your demo page. When i click on 2/12/2015 (same for 3/12 4/12 5/12), your calendar show event of day 1/12. Can you let me know how to fix this? thank you!

**Comment by mattlewis92** [comment]
Is this when clicking on a cell on the month view to then drill down into the day view for that months day? It might be a timezone issue as it works fine for me.

**Comment by ntnhan0512** [comment]
In your source file angular-bootstrap-calendar-tpls.js, in "MwlCalendarMonthCtrl" ctrl at line 531, i think condition should be 
if (vm.cellIsOpen && vm.openRowIndex === null)
because when you select day in row 0, vm.openRowIndex equal to 0. And in calendar.refreshView it will call dayClicked function with current day.

**Comment by mattlewis92** [comment]
Ah nice spot, fixed in 0.17.6, thanks for reporting! :smile:
