### ISSUE TITLE
Changing the current-day via a date selecter

### ISSUE THREAD

**Issue by belo32** [mattlewis92/angular-bootstrap-calendar#227]
When I bind calendarDay to currentDay and I modify/change calendarDay the calendar updates properly to the correct day.  When I click on next or previous then the binding breaks and currentDay no longer updates when I modify calendarDay

**Comment by mattlewis92** [comment]
I can't reproduce my end, can you make a plunker or something that demonstrates the issue. Thanks.

**Comment by belo32** [comment]
I ended up resolving the problem. Thanks :+1:

**Comment by mattlewis92** [comment]
Great to hear :smile:
