### ISSUE TITLE
setting up!!

### ISSUE THREAD

**Issue by t3k0o** [mattlewis92/angular-bootstrap-calendar#229]
I really dont know how to set up the calendar :/

**Comment by mattlewis92** [comment]
See the demo for an example:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/index.html#L85
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/demo/demo.js

If you get stuck you can always ask for help on stackoverflow :smile:
