### ISSUE TITLE
Show month name in navigation

### ISSUE THREAD

**Issue by kalihos** [mattlewis92/angular-bootstrap-calendar#230]
Hi Matt.

I'm sure it's a stupid mistake of my side, but I'm not able to show the month name over the calendar. Everything works fine, and I can navigate through different months with the previous and next buttons. But I can't see no month name at all. What am I missing?

Thank you very much. Your calendar is helping me much.

**Comment by mattlewis92** [comment]
You need to bind the title to a variable like in the demo:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/index.html#L88 and then you can just display it in your template like so:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/index.html#L39

:smile:

**Comment by kalihos** [comment]
That was! Thanks again Matt.
