### ISSUE TITLE
Remove red box with number of events per day

### ISSUE THREAD

**Issue by kalihos** [mattlewis92/angular-bootstrap-calendar#232]
Hi again Matt,

I would like to hide the red box, which shows the number of events for each day in the month view. The reason is that I'm using the calendar to show when a user has an agenda opened, so in my case that number is always "1". Even, I would like to strecht vertically the calendar to gain that space. Is it possible?

Thank you in advance.

**Comment by mattlewis92** [comment]
You can just use CSS to do this:
```
.cal-events-num {
  display: none;
}
```

**Comment by kalihos** [comment]
Thanks a lot!

It worked fine.
