### ISSUE TITLE
Calendar Component :   When user click on the text, only that time works the hyperlink. better to expand it to whole cell (Year, Month, Week)

### ISSUE THREAD

**Issue by sajithasela** [mattlewis92/angular-bootstrap-calendar#233]
Calendar Component :  
When user click on the text, only that time works the hyperlink. better to expand it to whole cell
(Year, Month, Week)
![hyperlink](https://cloud.githubusercontent.com/assets/16249527/11803027/7d45f6c6-a331-11e5-99e2-cb12c8727b77.JPG)

**Comment by mattlewis92** [comment]
Sorry I don't quite get what you mean, would you mind expanding a bit more, maybe with a screenshot of the part you mean?

**Comment by mattlewis92** [comment]
Ah right, thanks for explaining it a bit more. This is a hard problem to solve, as you need to be able to click on the outer edge of the cell to open the slide box of events. I can't think of a clean way currently to implement this that would allow the current behaviour. I think your best option is to override the template and move the click handler up to the parent.

**Comment by mattlewis92** [comment]
After more thought I realised you can use the existing `on-timespan-click` hook to implement this yourself:
`on-timespan-click="vm.changeView(calendarDate)"`

```
vm.changeView = function(date) {
  if (vm.calendarView === 'month') {
    vm.calendarDay = date;
    vm.calendarView = 'day';
  } else if (vm.calendarView === 'year') {
    vm.calendarDay = date;
    vm.calendarView = 'month';
  }
}
```
