### ISSUE TITLE
Event sizes don't reflect "endsAt" property

### ISSUE THREAD

**Issue by rddolan** [mattlewis92/angular-bootstrap-calendar#234]
Hi,  Love the widget! performance is much much much better than full calendar - no jQuery!

Issue is that the end time isn't used to size events in the week view. Would also be nice to have the 
day details (click on day) have an agenda view that shows event times overlap, etc..

**Comment by mattlewis92** [comment]
Sorry I don't quite get what you mean, would you mind explaining a bit more please? Thanks! :smile:

**Comment by rddolan** [comment]
Sure, I was wondering whether it would be possible to render the events on the monthly and weekly calendars as an "agenda" - where they overlap and are ordered top-to-bottom based on their start and end dates. Also, would be nice to use an agenda view in the details section when you expand the day instead of just a list of event details. 

Is this possible?

**Comment by mattlewis92** [comment]
Sorry this is way beyond the scope of this plugin and not something that I would ever have the time to implement (and it's also really difficult to implement well)
