### ISSUE TITLE
How to change Days of the Week to Abbreviations 

### ISSUE THREAD

**Issue by calvinKG** [mattlewis92/angular-bootstrap-calendar#237]
from 

![image](https://cloud.githubusercontent.com/assets/1926014/11976739/19250caa-a984-11e5-8946-0cd8e49bf498.png)

to

![image](https://cloud.githubusercontent.com/assets/1926014/11976727/044827e0-a984-11e5-91ea-9b74aa4685ba.png)

**Comment by mattlewis92** [comment]
This should do the trick:

```
calendarConfigProvider.setDateFormats({
  weekDay: 'EEE'
});
```

See [the docs](https://github.com/mattlewis92/angular-bootstrap-calendar#configuring-date-formats) for more info.

**Comment by calvinKG** [comment]
Thanks Matt
