### ISSUE TITLE
Make it possible to use a promise for the events

### ISSUE THREAD

**Issue by GrimaceOfDespair** [mattlewis92/angular-bootstrap-calendar#239]
Right now, it's assumed it's an array (e.g. filter). Imo, it would be consistent with Angular if it could also be a promise.

**Comment by mattlewis92** [comment]
Thanks for the feedback! This isn't something I would implement as it adds extra complexity for little gain. It's easy enough in your controller to do something like
```
getEvents().then((events) => this.events = events);
```

or just use [a resolve](https://github.com/angular-ui/ui-router/wiki#resolve)

**Comment by GrimaceOfDespair** [comment]
Yeah, I solved it that way. Just wanted to make the suggestion, but I understand it would complicate things.

Anyway: thanks for the great calendar ;)
