### ISSUE TITLE
Internationalization and localization does not work title

### ISSUE THREAD

**Issue by newmesiss** [mattlewis92/angular-bootstrap-calendar#24]
I only translates the names of the days but months of title

```javascript
 <h2 class="text-center">{{ calendarControl.getTitle() }}</h2>
```
![image](https://cloud.githubusercontent.com/assets/5264883/6229645/ad2bc9a6-b697-11e4-90e8-6531732104ec.png)

**Comment by mattlewis92** [comment]
That's already fixed in the latest version (https://github.com/mattlewis92/angular-bootstrap-calendar/commit/dffe35ed74e9dad263a2e3654880561e172c73eb), upgrade to 0.7.0

**Comment by newmesiss** [comment]
week even as usual , Greetings friend.
![image](https://cloud.githubusercontent.com/assets/5264883/6241834/1734baae-b703-11e4-9f09-cfb3919dc040.png)

**Comment by mattlewis92** [comment]
Upgrade to 0.7.1 then add the attribute with your translation like so:
```
calendar-week-title-label="Week {week} of {year}"
```
