### ISSUE TITLE
Enable static views

### ISSUE THREAD

**Issue by GrimaceOfDespair** [mattlewis92/angular-bootstrap-calendar#240]
Trying to set a static view seems to be an issue, as the code assumes it's a variable:
```
<mwl-calendar
  view="'month'">

**Comment by mattlewis92** [comment]
It works for me, a guess would be that you're missing the `current-day` or `events` attributes which are always required for the calendar to work.

**Comment by GrimaceOfDespair** [comment]
I'm sorry, I wasn't complete. You're correct: it's possible. You'll just get an exception on the drill down, which makes sense, though expected behaviour might be not to try to update the view variable at all.
