### ISSUE TITLE
Improving "recursOn"

### ISSUE THREAD

**Issue by adamatnetrist** [mattlewis92/angular-bootstrap-calendar#241]
This directive is great for simple, one-off events, but what if I need to display weekly events that start on a certain date and end on a certain date?  For example, I want to show an event that starts on January 25, then goes every Monday at the same time for two months.  Is that possible, or is support for such a use-case planned?

**Comment by mattlewis92** [comment]
`recursOn` is a bit of a hack as it is. This is something is [best implemented yourself](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/127#issuecomment-136022090).
