### ISSUE TITLE
Time slots in calendar

### ISSUE THREAD

**Issue by swapy** [mattlewis92/angular-bootstrap-calendar#242]
In this calendar ui, it supports slot division by 30 mins. What I mean is 
eg : division between 6AM and 7AM, only one line is present that indicates 6:30AM.
![image](https://cloud.githubusercontent.com/assets/1929023/12014033/12046050-ad4a-11e5-945b-f2494b81a61f.png)

Can I do something like this
06:00AM
06:15AM
06:30AM
7:00AM 

ie i want to divide by 15 mins slots.

I resized it but title or text inside the div is not visible.

![image](https://cloud.githubusercontent.com/assets/1929023/12014026/cb4b3d5a-ad49-11e5-875b-2d851c9d0c38.png)

**Comment by mattlewis92** [comment]
[This option](https://github.com/mattlewis92/angular-bootstrap-calendar#day-view-split) should do the trick :smile:

**Comment by swapy** [comment]
Great ! Works perfect ! Thanks a lot .

**Comment by tripciergedev** [comment]
Hello,
I love the way calendar works. But I  need a way to separate time slot for individual. I want to have just like http://www.smartschedule.co.za/Portals/0/Calendar%20Screen%20shadow.png  where users can see each practitioner's appointment time. Please help.
