### ISSUE TITLE
Adding weekdays labels inside the day view in responsive mode 

### ISSUE THREAD

**Issue by calvinKG** [mattlewis92/angular-bootstrap-calendar#243]
Hi, 

I managed to get the calendar to be responsive using media query. But my challenge is getting the removing weekdays labels from the top  and adding them inside the day view block. 

like this 

![image](https://cloud.githubusercontent.com/assets/1926014/12015343/b263597c-ad43-11e5-8d91-0a390b0b3123.png)

**Comment by mattlewis92** [comment]
Sorry I don't quite get what you mean, can you show me a screenshot of your actual app?

**Comment by calvinKG** [comment]
Hi Matt, 

Normally the calendar in full view has the days label at the top. 
![image](https://cloud.githubusercontent.com/assets/1926014/12048298/ffde171a-aee1-11e5-86e7-e82e65472e43.png)

I managed to add some styling and make this calendar to be responsive. So my challenge is to  add weekdays labels (Mon, Tue, etc ) inside the day cell in responsive view like, please check the below screen dump 

![image](https://cloud.githubusercontent.com/assets/1926014/12048321/68646050-aee2-11e5-99f1-879dba64122e.png)

**Comment by mattlewis92** [comment]
Your best bet is probably to use a custom template for the week view.

**Comment by calvinKG** [comment]
I have already use a decorator to create my own template. The challenge is adding   weekdays label as illustrated by the second screen dump. 

Hi Matt, 

This is for the Month view in responsive 

This is how you display your week days using ng-repeat. 

ng-repeat="day in vm.weekDays track by $index" ng-bind="day"

Then you have another ng-repeat where you map the weekday with the month view grid 
ng-repeat="day in vm.view | calendarLimitTo:7:rowOffset track by $index"

So the way am thinking is to find a way in which I can map the weeks days individually. without using the month view grid. 

Responsive view 

![image](https://cloud.githubusercontent.com/assets/1926014/12064754/d1166d90-afd3-11e5-8e94-ab94511eadf5.png)


Desktop view 
![image](https://cloud.githubusercontent.com/assets/1926014/12064729/4781dfc4-afd3-11e5-9520-6f2bf94f588d.png)

**Comment by mattlewis92** [comment]
Oh I get what you mean now, something like this in your template would work:
```
  <span
    class="pull-right hidden-xs hidden-sm"
    data-cal-date
    ng-click="vm.calendarCtrl.dateClicked(day.date)"
    ng-bind="day.label">
  </span>
  <span
    class="pull-right visible-xs visible-sm"
    data-cal-date
    ng-click="vm.calendarCtrl.dateClicked(day.date)">
  {{ day.date.format('D MMM') }}
  </span>
```
