### ISSUE TITLE
add drag and drop from external box

### ISSUE THREAD

**Issue by badreal** [mattlewis92/angular-bootstrap-calendar#246]
Is there any way to drag events from a external box into the calendar ?

**Comment by mattlewis92** [comment]
I think you should be able to use the internal directives to do this like so:
```
<div class="my-event" mwl-draggable="true" drop-data="{event: event}"></div>
```

Where `event` exists somewhere in your `$scope` and is a valid calendar event. Then when you drop it on the calendar the `on-event-times-changed` callback should fire with the event :smile:

**Comment by badreal** [comment]
thanks man you rock !!!!
