### ISSUE TITLE
Error while updating ui bootstrap

### ISSUE THREAD

**Issue by samundrak** [mattlewis92/angular-bootstrap-calendar#248]
![image](https://cloud.githubusercontent.com/assets/3079452/12061766/d763cb74-afb6-11e5-8799-560b81edd7a5.png)
I am getting error shown above whn i updated my ui bootstrap from Version: 0.13.3 - 2015-08-09 to Version: 0.14.3 - 2015-10-23... any solution for this

**Comment by mattlewis92** [comment]
I think you're using an old version of the calendar, the latest (0.17.x) has support for the latest ui-boostrap. See the [changelog](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/CHANGELOG.md) for more details on upgrading.
