### ISSUE TITLE
how to save the events created ?

### ISSUE THREAD

**Issue by renatocsilveira** [mattlewis92/angular-bootstrap-calendar#25]
how can I and where can I save the created events. They are the standard by main.js. file How do I burn them in an xml file for example?

**Comment by renatocsilveira** [comment]
I want to delete those events and add other

**Comment by mattlewis92** [comment]
I would suggest reading up on angular a bit more: https://angularjs.org/

You would need to create an API server that can serve the events as JSON, then use angulars $http service to download them and pass them to the calendar via the controller.

**Comment by renatocsilveira** [comment]
Sorry but I did not understand, can you give me an example of programming?
