### ISSUE TITLE
Get the day from where the event drag started

### ISSUE THREAD

**Issue by badreal** [mattlewis92/angular-bootstrap-calendar#250]
Is it possible to get the day from where the event drag started in month controller. I noticed that it has no drag events , and HandleDropEvent triggers onEventTimesChanged event to which the event and new date are passed but not the day from where the drag started.

**Comment by mattlewis92** [comment]
`on-event-times-changed` doesn't actually do anything to the original event, so just use `calendarEvent.startsAt` to get the original start date.

**Comment by badreal** [comment]
I was actually talking about the date from where the drag started in case the event is taking more than one day. I figured out that MwlDraggable controller has access to global scope so i was able to add a startdragdate property to the "vm" from interact function.

    interact($element[0]).draggable({
	      snap: snap,
	      onstart: function (event) {
	        if (canDrag()) {
	          angular.element(event.target).addClass('dragging-active');
	          event.target.dropData = $parse($attrs.dropData)($scope);
	          event.target.style.pointerEvents = 'none';
	            //used to get the date from where the drag started
	          if (event.isInCalendar == true)
                            $scope.vm.startDragDate = $scope.day.date;
                 .....

**Comment by mattlewis92** [comment]
Ah right, that makes sense, it's implemented now in master and I'll cut a new release once the new docs are finished in the next few days.
