### ISSUE TITLE
The calendar adding one month to the events 

### ISSUE THREAD

**Issue by badreal** [mattlewis92/angular-bootstrap-calendar#251]
I'm setting two events in January and the calendar is showing them in February, always adding one month to the events I don't know why ??

    $scope.events = [{
            title: 'My event title 0', // The title of the event
            type: getTypeFromColor('ggd'), // The type of the event (determines its color). Can be important, warning, info, inverse, success or special
            startsAt: new Date(2016, 1, 5), // A javascript date object for when the event starts
            endsAt: new Date(2016, 1 ,15), // Optional - a javascript date object for when the event ends
            editable: true, // If edit-event-html is set and this field is explicitly set to false then dont make it editable.
            deletable: true, // If delete-event-html is set and this field is explicitly set to false then dont make it deleteable
            draggable: true, //Allow an event to be dragged and dropped
            resizable: true, //Allow an event to be resizable
            incrementsBadgeTotal: true, //If set to false then will not count towards the badge total amount on the month and year view
            //recursOn: 'year', // If set the event will recur on the given period. Valid values are year or month
            cssClass: 'a-css-class-name', //A CSS class (or more, just separate with spaces) that will be added to the event when it is displayed on each view. Useful for marking an event as selected / active etc
            id: '5',
            isTask : true
        },
        {
            title: '<strong>My event title 1</strong>', // The title of the event
            type: getTypeFromColor('blue'), // The type of the event (determines its color). Can be important, warning, info, inverse, success or special
            startsAt: new Date(2016, 1, 1), // A javascript date object for when the event starts
            endsAt: new Date(2016, 1, 10), // Optional - a javascript date object for when the event ends
            editable: true, // If edit-event-html is set and this field is explicitly set to false then dont make it editable.
            deletable: true, // If delete-event-html is set and this field is explicitly set to false then dont make it deleteable
            draggable: true, //Allow an event to be dragged and dropped
            resizable: true, //Allow an event to be resizable
            incrementsBadgeTotal: true, //If set to false then will not count towards the badge total amount on the month and year view
            //recursOn: 'year', // If set the event will recur on the given period. Valid values are year or month
            cssClass: 'a-css-class-name', //A CSS class (or more, just separate with spaces) that will be added to the event when it is displayed on each view. Useful for marking an event as selected / active etc
            id: '6',
            isTask : true
        }];

<b>Html :</b>

    <mwl-calendar view="calendarView"
                  current-day="calendarDay"
                  events="events"
                  view-title="calendarTitle"
                  on-event-click="eventClicked(calendarEvent)"
                  on-event-times-changed="addEvent(calendarEvent, calendarDate, calendarDragDate, calendarNewEventStart, calendarNewEventEnd)"
                  edit-event-html="'<i class=\'glyphicon glyphicon-pencil\'></i>'"
                  delete-event-html="'<i class=\'glyphicon glyphicon-remove\'></i>'"
                  on-edit-event-click="eventEdited(calendarEvent)"
                  on-delete-event-click="eventDeleted(calendarEvent)"
                  cell-is-open="true">
    </mwl-calendar>

**Comment by mattlewis92** [comment]
`new Date(2016, 1, 5)` is your problem. JS dates month values are [0 based](http://www.w3schools.com/jsref/jsref_getmonth.asp) so you should instead do `new Date(2016, 0, 5)` for january
