### ISSUE TITLE
Time is show from 6:00 to 22:00 in day view

### ISSUE THREAD

**Issue by samundrak** [mattlewis92/angular-bootstrap-calendar#253]
I got some problem as it shows only from 6 to 22 but not from 0 to 24 
![image](https://cloud.githubusercontent.com/assets/3079452/12089401/8492aaba-b30c-11e5-895a-becf9439d10e.png)

**Comment by mattlewis92** [comment]
Remove the day view start and end options:
https://github.com/mattlewis92/angular-bootstrap-calendar#day-view-start
