### ISSUE TITLE
prev and next buttons

### ISSUE THREAD

**Issue by RobEDarling** [mattlewis92/angular-bootstrap-calendar#255]
Hi Matt,

It looks like your 0.8.0 release broke the next and previous buttons.  This can be replicated by going to your demo site and clicking the next and previous buttons.  Thought you would want to know.

Cheers

**Comment by InsidersByte** [comment]
+1

**Comment by RobEDarling** [comment]
Correction 0.18.0 :-)

**Comment by mattlewis92** [comment]
Thanks for reporting, it's fixed now!

**Comment by RobEDarling** [comment]
Glad to help.  Thanks for making this!
