### ISSUE TITLE
How day event based on date not time

### ISSUE THREAD

**Issue by calvinKG** [mattlewis92/angular-bootstrap-calendar#256]
Hi Matt, 

My event don't have time but only date, how to enable  the day view to depend only on the date but not on the time. My day view is not showing anything at the moment. 

Month view 

![image](https://cloud.githubusercontent.com/assets/1926014/12174793/6c23e43c-b567-11e5-8a21-ee4c12834e28.png)

Week View 

![image](https://cloud.githubusercontent.com/assets/1926014/12174799/788eeac8-b567-11e5-9b70-6836610dec80.png)

Day View 

![image](https://cloud.githubusercontent.com/assets/1926014/12174814/8be50396-b567-11e5-9b0a-50c26fade6f9.png)

**Comment by mattlewis92** [comment]
Can you give me an example of one of these events? Specifically the values you have set for the start and end?

**Comment by calvinKG** [comment]
"events": [
        {
          "startDate": "2015-06-01",
          "endDate": "2015-06-01",
          "guid": "00163E103BE21ED49AA397536C91C238",
          "externalId": "11111111111111",
          "objectType": "Me",
          "priority": "002",
          "responsibleBp": "0600006251",
          "smartform": "Z_NOTUSED",
           "Event Title": "Golf Day"

        }
]

**Comment by mattlewis92** [comment]
Just omit the end date, with that config you are saying the event starts and ends at the exact same time so the day view will render the event with 0px height. See here for an example: http://mattlewis.me/angular-bootstrap-calendar/#?example=optional-event-end-dates

**Comment by calvinKG** [comment]
Thanks man, now I understand.

Thanks for the effort.
