### ISSUE TITLE
Documentation: Exception thrown when "cell-is-open" expression not specified

### ISSUE THREAD

**Issue by aschwartz-satcom** [mattlewis92/angular-bootstrap-calendar#259]
The cell-is-open attribute is bound to the mwl-calendar directive's isolate scope using the "=" option.

The documentation does not specify that this attribute is required, but if omitted you will receive this exception every time a cell is clicked:

https://docs.angularjs.org/error/$compile/nonassign?p0=undefined&p1=mwlCalendar

EDIT: alternately, if it really is optional, use the "=?" binding option instead

**Comment by mattlewis92** [comment]
Ah thanks for reporting, I'll get that fixed up asap. Are you running angular 1.3.x by any chance?

**Comment by aschwartz-satcom** [comment]
Yes, 1.3.8, sorry for not specifying.

Thanks!

**Comment by mattlewis92** [comment]
Thought that might be the case, as it doesn't happen with 1.4.x. Anyway it's fixed now in `0.18.2`, thanks for reporting! :smile:
