### ISSUE TITLE
Render events in JSON format from an ajax request

### ISSUE THREAD

**Issue by imyque** [mattlewis92/angular-bootstrap-calendar#26]
Hi,

Thanks for this project. 

Please I would like to use this calendar only to render events in JSON from an Ajax request, without displaying the events editor. Could you please guide me (if possible, without Angular, I am not using it in my project)?

Thanks
Michael

**Comment by mattlewis92** [comment]
Use the angular $http service to load your events from the server, for example
```
$http.get('/events').success(function(events) {
    //TODO - format your array of events to match the format described in the docs
    $scope.events = events; //Once formatted correctly add them to the scope variable and the calendar will update
});
```

For more info read the angular docs: https://angularjs.org/

**Comment by imyque** [comment]
Thank Matt.

I don't mean to bother, but I need more.

Please how do I get query parameters from the url into the controller. 

For example, how do I get the query parameter "userid" from the url "index.html?userid=1"

into the controller like this:
$http.get('/events' + '?userid=' + userid).success(function(events) {...

**Comment by mattlewis92** [comment]
Use $location.search(): https://docs.angularjs.org/api/ng/service/$location
