### ISSUE TITLE
10 $digest() iterations reached

### ISSUE THREAD

**Issue by vogloblinsky** [mattlewis92/angular-bootstrap-calendar#260]
Using the kitchen sink demo, i have implemented your directive in one project.

I get on mouseoverring event bullet this error :

"Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!"

AngularJS v 1.4.8

**Comment by mattlewis92** [comment]
What version of ui-bootstrap are you using? Can you provide a plunker which reproduces your problem, you can use this as a starting point: http://plnkr.co/edit/JVRJmCDSAls87nJ80BEd?p=preview

**Comment by vogloblinsky** [comment]
Ok, the source of the problem is AngularJS Batarang chome extension. Disabling it and the problem disappear.

But i don't know which cause this, something your your directive code or in their extension code.

Your plunker running locally produce the same error.

Regards

angular.js:12520 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = watchExpression.apply(this, arguments);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":{},"oldVal":{}}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = watchExpression.apply(this, arguments);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":{},"oldVal":"..."}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = watchExpression.apply(this, arguments);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":{},"oldVal":"..."}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = watchExpression.apply(this, arguments);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":{},"oldVal":"..."}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = watchExpression.apply(this, arguments);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":{},"oldVal":"..."}]]
http://errors.angularjs.org/1.4.8/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…20%20%20%7D%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%22...%22%7D%5D%5D
    at angular.js:68
    at Scope.$digest (angular.js:15934)
    at Scope.scopePrototype.$digest (hint.js:1972)
    at Scope.$apply (angular.js:16160)
    at Scope.scopePrototype.$apply (hint.js:2035)
    at HTMLAnchorElement.<anonymous> (angular.js:23618)
    at specialMouseHandlerWrapper (angular.js:3357)
    at HTMLAnchorElement.eventHandler (angular.js:3334)

**Comment by mattlewis92** [comment]
Yup, that's batarang code, there's nothing I can do about it really. It's well know that batarang has [tonnes of bugs](https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk/reviews?hl=en) and doesn't work properly.
```
var start = perf.now();\n        var ret = watchExpression.apply(this, arguments);\n        var end = perf.now();
```
