### ISSUE TITLE
Hiding week info during mouseover and click events

### ISSUE THREAD

**Issue by anand1st** [mattlewis92/angular-bootstrap-calendar#261]
![mwl-calendar](https://cloud.githubusercontent.com/assets/8436010/12381203/509f3caa-bdc0-11e5-8660-54416c7f30f9.png)

Firstly, my thanks for the calendar. It's impressive.

I have a query. If I would like to hide the Week Info (please see attached image) for both mouseover and click event, how would i go about doing that?

**Comment by mattlewis92** [comment]
You can just hide it with CSS :smile: 
```
#cal-week-box {
  display: none;
}
```

**Comment by anand1st** [comment]
Thanks a bunch Matt... for some reason, thought it'd be harder than that...

**Comment by mattlewis92** [comment]
No problem, happy to help :)

**Comment by prashanth-n** [comment]
for the people who want to delete it from the template, if the css trick didn't work:
<div class=cal-week-box-cell ng-if="$first && rowHovered"> 
<span ng-bind=vm.getWeekNumberLabel(day)></span> 
</div>
Just delete this part..
