### ISSUE TITLE
Minor error in documentation

### ISSUE THREAD

**Issue by bp74** [mattlewis92/angular-bootstrap-calendar#262]
The readme says ...

    calendarConfig.allDateFormats.moment.title = 'ddd D MMM';

... but i think it should be like this:

    calendarConfig.titleFormats.day = 'ddd D MMM';
    calendarConfig.titleFormats.week = 'Week {week} of {year}';

**Comment by mattlewis92** [comment]
That's intentional - `titleFormats` is a getter only that retrieves the config from the `allDateFormats` object. See the source [here](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarConfig.js#L45) to see what I mean.

**Comment by bp74** [comment]
okay i see, but than the .day is missing - right?

    calendarConfig.allDateFormats.moment.title.day = 'ddd D MMM';

**Comment by mattlewis92** [comment]
Oh yeah you're correct, fixed now, thanks!
