### ISSUE TITLE
One event per range

### ISSUE THREAD

**Issue by wesley3523** [mattlewis92/angular-bootstrap-calendar#263]
Is it possible to add only one event per daterange?

Thanks

**Comment by mattlewis92** [comment]
Sorry I don't quite follow what you mean, could you explain a bit more please?

**Comment by wesley3523** [comment]
I want to limit my events to 1. for example if i plan an event today i should not be able to add another event on today.

i appreciate it

**Comment by mattlewis92** [comment]
The calendar simply displays the events you give it, wherever you add events to the calendar in your UI simply check the date of the new event isn't the same as any of the events already passed to the calendar.
