### ISSUE TITLE
Badge is clickable when $mdDialog (Angular material) is used for event click

### ISSUE THREAD

**Issue by KalpanaAr** [mattlewis92/angular-bootstrap-calendar#264]
Please see the attached picture. You can notice that the badge is active in the background. I would appreciate if someone can help me disable badge when a dialog is open. Thanks!
![mddialog_angularcalendar_overlayissue](https://cloud.githubusercontent.com/assets/8092075/12495157/d4fb1c40-c053-11e5-96e4-3fa61184db3d.PNG)

**Comment by mattlewis92** [comment]
Should be fixed in 0.18.3 :smile:

**Comment by KalpanaAr** [comment]
I see the fix. Thanks!  :dancer:
