### ISSUE TITLE
month-cell-events-template-url property not working

### ISSUE THREAD

**Issue by claytonhottinger** [mattlewis92/angular-bootstrap-calendar#265]
Hi there,
I am a new developer so forgive me for the ugly code and potential obviousness of the question. I am trying to emulate your demo of event labels appearing in the month view (https://github.com/mattlewis92/angular-bootstrap-calendar/issues/177), but it's not grabbing the custom template for some reason. Here's what I have:

HTML:
```
<div>
  <script type="text/ng-template" id="test.html">
    Hello World
  </script>
  <mwl-calendar
    events="eventData"
    view="view"
    view-date="viewDate"
    view-title="viewTitle"
    month-cell-events-template-url="test.html">
  </mwl-calendar>
</div>
```
Controller:
```
app.controller('userCal', ['$scope','moment',function($scope, moment){

  var monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];

  $scope.eventData = [
    {
      title: 'Test',
      type: 'info',
      startsAt: new Date(2016, 1, 12, 15),
      endsAt: new Date(2016, 1, 12, 16)
    }
  ];

  $scope.view = 'month';

  $scope.viewDate = new Date(2016, 1, 1, 0);

  $scope.viewTitle = monthNames[$scope.viewDate.getMonth()];

}]);
```

The calendar is displaying, but only with the default view. I am not using some of the default features (as my app does not need them) and think that may be part of the problem, but would like to hear your thoughts.

**Comment by mattlewis92** [comment]
That option was [removed in 0.18.0](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/CHANGELOG.md#0180-2016-01-02) in favour of a more generic way of using custom templates. [See here](http://mattlewis.me/angular-bootstrap-calendar/#?example=custom-templates) for an example of what to do in 0.18.0+
