### ISSUE TITLE
why is 'recursOn' limited to 'month' and 'year'

### ISSUE THREAD

**Issue by grimace** [mattlewis92/angular-bootstrap-calendar#267]
I would be interested in 'week' and 'day' as well.  Is this possible?

**Comment by mattlewis92** [comment]
recursOn is a hack and won't work easily for week and day. I think the best way to implement it is in userland rather than through the directive. See here for some [sample code](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/127#issuecomment-136022090) on how you might do it.
