### ISSUE TITLE
Check if there is events on particular date

### ISSUE THREAD

**Issue by samundrak** [mattlewis92/angular-bootstrap-calendar#268]
Is there any way to check if there is any event selected date

**Comment by mattlewis92** [comment]
Just loop through your events array:
```
vm.events.forEach(event => {
  const isOnDay = moment(event.startsAt).startOf('day').isSame(moment(someDate).startOf('day'));
});
```

**Comment by samundrak** [comment]
It doesnt work .. also if date is between 20jan to 30jan then this is not solution

**Comment by mattlewis92** [comment]
OK then, you could try using the `calendarHelper.eventIsInPeriod` function, read the source for how to use it:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarHelper.js#L59
