### ISSUE TITLE
why don't you add 'interact'  as a direct dependency ?

### ISSUE THREAD

**Issue by DrHelmut** [mattlewis92/angular-bootstrap-calendar#269]
I just installed your nice component, but I don't understand why you don't specify 'interact' as a direct dependency, in the bower conf file (as I had to install it in order to make your diective works)

Thanks for your work ;)

**Comment by mattlewis92** [comment]
Because it's an optional dependency, if you don't need drag + drop then you don't need to include it. If it's marked as a dependency then it will get auto included into your project with tools like wiredep etc and AFAIK bower doesn't support optional depdendencies.

**Comment by DrHelmut** [comment]
But it's not optionnal since it was impossible for me to add your directive in my project without specifying "interact" as dependency in my requireJS configuration... xD

If I don't specify it, angular throw a configuration exception

**Comment by mattlewis92** [comment]
It's definitely optional for commonjs + using it as a global, but I've never used require.js before so I'm not too sure how to make it optional for requirejs.

**Comment by DrHelmut** [comment]
I just check the tpls file https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/dist/js/angular-bootstrap-calendar-tpls.js, in my configuration. The following test is verified (l 10) 

`else if(typeof define === 'function' && define.amd)`

so this is executed  at line 11 :

`define(["angular", "interact", "moment"], factory);`

In the other tests, the code calls "webpackLoadOptionalExternalModule" in order to add interact or not, I think it's pretty easy to fix, please reopen this issue if you agree.

Best regards

**Comment by mattlewis92** [comment]
I can't use that fix as it'll get overwritten every time the dist files are generated as that is all inserted automatically by webpack. There also doesn't seem to be an option in webpack to generate that either. I think your best bet is just using require.js to define `interact` yourself and just set it to null and everything should just work.

**Comment by DrHelmut** [comment]
I'll try this workaround, thanx ;)
