### ISSUE TITLE
integrate the add button caendario

### ISSUE THREAD

**Issue by newmesiss** [mattlewis92/angular-bootstrap-calendar#27]
may ud can integrate a button to add an activity directly from the calendar?
or could tell me how to perform this integration , Greetings

![image](https://cloud.githubusercontent.com/assets/5264883/6307905/6e2f6c42-b91e-11e4-99db-507f2525f59d.png)

**Comment by mattlewis92** [comment]
There isn't really a way of doing this currently, I suppose you could add a day clicked callback on the calendar.

**Comment by newmesiss** [comment]
I 'm trying to understand your code and by tracking features to know how to integrate this option- .

**Comment by newmesiss** [comment]
and later ud will add this option ?

**Comment by mattlewis92** [comment]
Added in 0.7.2
