### ISSUE TITLE
Month view : cell click event

### ISSUE THREAD

**Issue by vogloblinsky** [mattlewis92/angular-bootstrap-calendar#270]
Hi,

I need for one project to display the current selected day in month view.
I can get it with "Timespan click", but it will be nice to display a feedback for the user with a border on the cell or anything else.

Regards

**Comment by mattlewis92** [comment]
I've just pushed 0.18.4 which should let you do this. 
`on-timespan-click="cellClicked(calendarCell)"`

```
var previousCell;
$scope.cellClicked = function(cell) {
  if (previousCell) {
    delete previousCell.cssClass;
  }
  cell.cssClass = 'selected'; // then style it with CSS.
  previousCell = cell;
};
```

Hope this helps! :smile:

**Comment by vogloblinsky** [comment]
Nice, thanks, test that ASAP.
