### ISSUE TITLE
Disable certain days in a month

### ISSUE THREAD

**Issue by KalpanaAr** [mattlewis92/angular-bootstrap-calendar#272]
Hi, 

Is it possible to disable all days in a month except wednesdays like the feature available in angular material md-datepicker? If yes, can someone provide me a code sample of how to do that? 

Thanks!

**Comment by mattlewis92** [comment]
You can use the `cell-modifier` option to add a custom class to days and then style accordingly like so:
http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=cell-modifier

For CRUD of events that is left up to you, so you can prevent your users from creating events on certain days etc.

Hope this helps :smile:

**Comment by KalpanaAr** [comment]
Thanks @mattlewis92 ! I am able to change the style of cells using cell-modifier but those days are still clickable. Can you tell me how to disable selection too?

**Comment by KalpanaAr** [comment]
Also hovering over those disabled days shouldn't display week selection on the left. Appreciate your help! Thanks.

**Comment by mattlewis92** [comment]
Use the `on-view-change-click` callback, see the [docs](https://github.com/mattlewis92/angular-bootstrap-calendar#on-view-change-click) and [example](http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=view-change-click).

Hiding the [week number](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/261#issuecomment-172476307).

**Comment by KalpanaAr** [comment]
Okay. But looks like we handle viewChange once day/cell is selected. Is there a way to you know prevent users from selecting certain days? Like if certain days in a month are disabled, no hover or mouse click should be enabled on them? 
![img_1973](https://cloud.githubusercontent.com/assets/8092075/12901232/1635fcd6-ce80-11e5-98b4-6321af9b7943.JPG)

In the above image, you can see that hovering mouse over disabled days shows clickable/selectable finger icon. Is there a way to configure calendar so that certain days are truly disabled? If not already present, can this feature be added? thanks!

**Comment by mattlewis92** [comment]
You can easily implement that yourself with CSS:
```
.disabled-day { // or whatever your custom disabled class is
  cursor: not-allowed;
}
.disabled-day:hover {
  background-color: white; //whatever the normal color is
}
```

**Comment by KalpanaAr** [comment]
Is there a class for disabled-day/disabled-cell for your calendar?

**Comment by mattlewis92** [comment]
Just use your `wed-cell` class to add the disabled state, like so: http://plnkr.co/edit/hd28C8gvcza0m3TBcBEW?p=preview

**Comment by KalpanaAr** [comment]
Thanks @mattlewis92 ! I am not a front-end person, just learning stuff. Thanks for your patience.
Saw your plunker, but even when I hover over disabled days, the week is getting highlighted. Any way to prevent that?

**Comment by KalpanaAr** [comment]
Also,  I would like display a link/button on each calendar day. If someone wants to schedule an event on a particular day, they have to click on the schedule link which would take them to a separate view with the date populated.  I am looking for one of the options below

view 1
![view1](https://cloud.githubusercontent.com/assets/8092075/13022293/eacd807c-d1a5-11e5-8bcf-69a8a1d99c48.PNG)


view 2
![view2](https://cloud.githubusercontent.com/assets/8092075/13022256/b2174510-d1a5-11e5-886a-53f0b611bf1a.PNG)

Is it possible to achieve any of this result using your calendar? Thanks for all the help!
