### ISSUE TITLE
This is not working when clone to local pls advise

### ISSUE THREAD

**Issue by raviji** [mattlewis92/angular-bootstrap-calendar#273]
This is not working when clone to local pls advise

**Comment by mattlewis92** [comment]
Please can you define what you mean by "not working" - any errors in the terminal, console etc?

Are you following the dev guide:
https://github.com/mattlewis92/angular-bootstrap-calendar#development

**Comment by mattlewis92** [comment]
Closing, LMK if you're still having issues.
