### ISSUE TITLE
when using an ngDialog popup, calendar elements pop through

### ISSUE THREAD

**Issue by grimace** [mattlewis92/angular-bootstrap-calendar#274]
I'm triggering eventEdit and loading a popup dialog with ngDialog. Is there a way to set the z-index lower so the calendar elements are not seen?  I could be totally lost here but am just spinning trying to find a solution.

**Comment by mattlewis92** [comment]
What version of the module are you using? I put in [a fix](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/CHANGELOG.md#0183-2016-01-22) for this the other day. If this doesn't fix it please can you create a plunker which demonstrates the issue (you can fork one off the demo page)

**Comment by mattlewis92** [comment]
Closing, LMK if you're still having issues.
