### ISSUE TITLE
Custom day view

### ISSUE THREAD

**Issue by gklontza** [mattlewis92/angular-bootstrap-calendar#275]
I have created a custom day view, replacing the original. I can view it and navigate properly from both the day/month/year menu and clicking on a specific day on the calendar from week/ month views.

The issue is that I cannot get the correct date the user selected. It always shows today's events.

How can I get the correct current date according to user selection and corresponding events?

**Comment by mattlewis92** [comment]
Sorry I don't quite follow you, do you mean when the user clicks the day number on the month view?

**Comment by gklontza** [comment]
Yes, when the user clicks on the day number on week or month view, it goes to day view but the events have not been updated. It will always shows todays' events.

**Comment by mattlewis92** [comment]
That's odd, as it works fine in the demo: http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink

Can you reproduce it in a plunker please?

**Comment by gklontza** [comment]
Sorry I cannot reproduce it. Events are loaded from back-end and on the day view a separate AJAX call is made to filter the data. It seems there is a scope issue.

**Comment by mattlewis92** [comment]
Maybe try this then? 

https://github.com/mattlewis92/angular-bootstrap-calendar/issues/271#issuecomment-176841792

**Comment by mattlewis92** [comment]
Closing, LMK if you're still having issues.

**Comment by gklontza** [comment]
I resolved it. It was a scope issue after all. Thank you very much for the
help and quick responses.

Regards
Georgia

2016-02-07 14:27 GMT+00:00 Matt Lewis <notifications@github.com>:

**Comment by mattlewis92** [comment]
Great to hear! :smile:
