### ISSUE TITLE
Events are not being update

### ISSUE THREAD

**Issue by kptLucek** [mattlewis92/angular-bootstrap-calendar#276]
Hi there

Well, basicly im loading all events at once, for single day (day view is only view).
````javascript
		$scope.events = [];
		$scope.calendarView = 'day';
		// some code here

		$scope.$watch(function(){
			//filters watch
		}, function(){
			$scope.events = $filter('filter')(events, function(event){
				//some terms here
			});
		}, true);
````

After using any kind of filter, (yes conditions are matched) events are not filtered, when i do reload state with filters being active it works like it should.

Thanks for assistance

**Comment by mattlewis92** [comment]
Please can you give me a plunker which reproduces this (you can fork a started template from the demo)

**Comment by kptLucek** [comment]
Might be kinda dificult, toons of logic are hidden before events reach controller's scope :)

**Comment by mattlewis92** [comment]
Without a re-produceable plunker I can't help you much as I'm just guessing. This guy had a similar problem the other day:
https://github.com/mattlewis92/angular-bootstrap-calendar/issues/271

I noticed you're using $scope instead of controllerAs, I'd imagine it's the same problem.

**Comment by kptLucek** [comment]
`controllerAs` haven't fixed issue yet

**Comment by mattlewis92** [comment]
Just to be clear you're now doing something like:
```
function myCtrl() {
  this.events = [];
}
```
```
<mwl-calendar events="vm.events"></mwl-calendar>
```

**Comment by kptLucek** [comment]
````javascript
var vm = this;
vm.events = [];
vm.freeSlots = [];
````

So, basicly yes :)

**Comment by mattlewis92** [comment]
Can you send me the way you're using `<mwl-calendar>` html?

**Comment by kptLucek** [comment]
````html
		<mwl-calendar
			view="calendarView"
			current-day="calendarDay"
			events="vm.events"
			view-title="vm.calendarTitle"
			on-event-times-changed="calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
			edit-event-html="'<i class=\'glyphicon glyphicon-pencil\'></i>'"
			delete-event-html="'<i class=\'glyphicon glyphicon-remove\'></i>'"
			on-edit-event-click="eventEdited(calendarEvent)"
			on-delete-event-click="eventDeleted(calendarEvent)"
			auto-open="true"
			day-view-split="15"
			on-timespan-click="alert(calendarDate)"
			day-view-start="{{calendarDayViewStart}}"
			>
		</mwl-calendar>
````

**Comment by mattlewis92** [comment]
What version of the directive are you using?

**Comment by kptLucek** [comment]
0.17.6

1.4.6 angular

**Comment by mattlewis92** [comment]
Putting your code into a plunker works fine:
http://plnkr.co/edit/zoHhOnGfHxvpQE5YotPw?p=preview

I'm 99% sure this is an issue with your code.

**Comment by kptLucek** [comment]
Oh damn, after debugging whole night, i've got the point...

I had broken reference for some events, i mean some of them were **copied** using ``angular.copy()`` which broken whole thing.

Many thanks for helping in there, sorry for wasting your time

**Comment by mattlewis92** [comment]
No problem, glad you got it resolved :smile:
