### ISSUE TITLE
the output format is not valid calendar

### ISSUE THREAD

**Issue by newmesiss** [mattlewis92/angular-bootstrap-calendar#28]
I am testing the output timing input and chrome warns me that it is invalid, it can be happening?

![image](https://cloud.githubusercontent.com/assets/5264883/6315587/111679ac-b9e5-11e4-8a3a-15cec5b5f630.png)
![image](https://cloud.githubusercontent.com/assets/5264883/6315588/1bb9eac4-b9e5-11e4-8ff5-f6cd58a486d8.png)

**Comment by mattlewis92** [comment]
Please can you provide me with the steps to reproduce the error you are experiencing.

**Comment by newmesiss** [comment]
I'm trying to save the selected date, but receives a very long time which does not allow and does not keep such data

![problema](https://cloud.githubusercontent.com/assets/5264883/6349851/feaf11c6-bc04-11e4-9716-8720a2a37cd8.gif)

**Comment by mattlewis92** [comment]
I can't reproduce the error, maybe it's a bug with your code?

**Comment by newmesiss** [comment]
as shown in this other gif , function receives at first date, but then discarded


![problema2](https://cloud.githubusercontent.com/assets/5264883/6350091/111e960e-bc07-11e4-85af-03027f22789d.gif)



this is my html . these receiving from the imput ng-model="event.fecha"



```javascript
          <table class="table table-bordered">
                     <thead>
                        <tr>
                           <th>Titulo</th>
                           <th>tipo</th>
                           <th>Fecha y hora</th>

                        </tr>
                     </thead>
                     <tbody >
                        <tr>
                           <td>
                              <input type="text" class="form-control" ng-model="event.title">
                           </td>
                           <td>
                              <select ng-model="event.type" class="form-control">
                                 <option value="Limpieza">Limpieza</option>
                                 <option value="Muelas">Muelas</option>

                              </select>
                           </td>
                           <td>
                               <span>{{event.fecha}}</span>
                              <p class="input-group" style="max-width: 250px">
                                 <input
                                        type="text" class="form-control"
                                        readonly
                                        datepicker-popup="medium"
                                        date-disabled="disabled(date, mode)"
                                        datepicker-options="dateOptions"
                                        ng-model="event.fecha"
                                        is-open="event.startOpen"
                                        close-text="Close" />
                                 <span class="input-group-btn">
                                 <button type="button" class="btn btn-default" ng-click="toggle($event, 'startOpen', event)"><i class="glyphicon glyphicon-calendar"></i></button>
                                 </span>
                              </p>
                              <timepicker ng-model="event.fechah" hour-step="1" minute-step="15" show-meridian="true"></timepicker>
                           </td>

                        </tr>
                     </tbody>
                  </table>

```

**Comment by mattlewis92** [comment]
Try setting the starts_at and ends_at properties of the event as well as the title and type.

**Comment by newmesiss** [comment]
el valor fecha entra a la funcion de esta manera ```javascript Sun Feb 08 2015 00:00:00 GMT-0300 (Hora verano Sudamérica Pacífico) ```

**Comment by mattlewis92** [comment]
Sorry. I don't speak spanish.

**Comment by newmesiss** [comment]
forgiveness , update it now

**Comment by mattlewis92** [comment]
Looks like a problem with the ui-bootstrap datepicker not with the calendar, raise it with them: https://github.com/angular-ui/bootstrap

or try a different datepicker such as:
https://github.com/dalelotts/angular-bootstrap-datetimepicker

**Comment by newmesiss** [comment]
load this other module, but I feel the same
