### ISSUE TITLE
events rendering in week view

### ISSUE THREAD

**Issue by badreal** [mattlewis92/angular-bootstrap-calendar#280]
Is there any way to render events in week view the same as google does.
In the plugin, each event is taking an entire row. If Monday has big list of events, Tuesday events start at the bottom and the view isn't easy to understand.
It would be great if "one day" events could start from the top of each day, and place the long events on the very top row stacked one after the other.
Can you please guide me to the easiest solution to achieve that ?
Thank you.

**Comment by mattlewis92** [comment]
There isn't currently a way to do this (it's a limitation with the CSS from the original jquery plugin this is based on). I'll try and find the time on the weekend to see if it's feasible as a couple of people have requested it. If you don't care about event end times there is the `calendarConfig.showTimesOnWeekView` option which will display the week view more like the day view.

**Comment by mattlewis92** [comment]
I tried to implement this tonight, but it turned out it's actually a really difficult problem to solve, and isn't something I really have the time or motivation to implement. The `calendarConfig.showTimesOnWeekView` option is the best solution I can offer, or you could try it yourself with a custom template but it would be a difficult task to complete. Sorry I couldn't be of more help.

**Comment by mikejohanson** [comment]
I took a stab at this...very rough stab...

In summary, I added a parent div for each collection of events on each day, I utilized [angular.filter ](https://github.com/a8m/angular-filter) to group by startsAt  and also order them by startsAt. I gave the parent div some style with a set width(vm.dayColumnDimensions.width) and setting the position to absolute to utilize the 'cal-offset' classes appropriately when there happens to be no events on a certain day. I also added 'float:none' to the cal-cell div. 

I'm absolutely positive I broke the showTimesOnWeekView feature, but I didn't need that as my events don't need time level granularity. In any case, hope it helps someone!

I replaced/inserted this after the <mwl-calender-hour-list> element in the calendarWeekView.html template. 
```
<div ng-repeat="(key, value) in vm.view.events | groupBy: 'startsAt' | orderBy:'startsAt'"  ng-style="{width:vm.dayColumnDimensions.width+ 'px'}" style="position: absolute;" ng-class="(vm.showTimes ? 1 : value[0].daySpan) + (vm.showTimes ? '' : ' cal-offset' + value[0].dayOffset)">
            <div ng-repeat="event in value track by event.$id">
                <div  ng-class="'cal-cell' + ' day-highlight dh-event-' + event.type + ' ' + event.cssClass"
                     ng-style="{
              top: vm.showTimes ? ((event.top + 2) + 'px') : 'auto',
              position: vm.showTimes ? 'absolute' : 'inherit',
              width: vm.showTimes ? (vm.dayColumnDimensions.width + 'px') : '',
              left: vm.showTimes ? (vm.dayColumnDimensions.width * event.dayOffset) + 15 + 'px' : '',
                     float:'none' }"
                     data-event-class
                     mwl-draggable="event.draggable === true"
                     axis="vm.showTimes ? 'xy' : 'x'"
                     snap-grid="vm.showTimes ? {x: vm.dayColumnDimensions.width, y: 30} : {x: vm.dayColumnDimensions.width}"
                     on-drag="vm.tempTimeChanged(event, y)"
                     on-drag-end="vm.weekDragged(event, x, y)"
                     mwl-resizable="event.resizable === true && event.endsAt && !vm.showTimes"
                     resize-edges="{left: true, right: true}"
                     on-resize-end="vm.weekResized(event, edge, x)">
                    <strong ng-bind="(event.tempStartsAt || event.startsAt) | calendarDate:'time':true" ng-show="vm.showTimes"></strong>
                    <a href="javascript:;"
                       ng-click="vm.onEventClick({calendarEvent: event})"
                       class="event-item"
                       ng-bind-html="vm.$sce.trustAsHtml(event.title)"
                       uib-tooltip-html="event.title | calendarTrustAsHtml"
                       tooltip-placement="left"
                       tooltip-append-to-body="true">
                    </a>
                </div>
            </div>
        </div>
```

**Comment by kvitozev** [comment]
@mattlewis92, is this fixed in any newer version? :)

**Comment by mattlewis92** [comment]
Yup 😄 
<img width="1015" alt="screen shot 2016-07-13 at 14 49 51" src="https://cloud.githubusercontent.com/assets/6425649/16805647/17190fae-4909-11e6-9b83-29878e3982e3.png">

**Comment by neghani** [comment]
I did something to resolve this issue to an extent:

I had grouped the event even before giving data to the plug-in, this method can be userful.

Look at his plunker link below:

https://plnkr.co/edit/5ejGRGNFaIW8AxWl8kSE?p=preview

**Comment by Neha-saini** [comment]
I am not able to see different events by using groupEvents.
It's showing all the events as a single data.

===================HTML==================
<mwl-calendar
            events="events"
            view="calendarView"
            view-title="calendarTitle"
            view-date="viewDate"

            cell-modifier="groupEvents(calendarCell)"
            cell-auto-open-disabled="true"

    >
    </mwl-calendar>

=======================JS================
![screenshot from 2017-08-17 18-06-14](https://user-images.githubusercontent.com/31100420/29412522-d032439a-8376-11e7-93b9-6415723cf7b0.png)



 $scope.events = [
            {
                title: 'Event 1',
                type: 'warning',
                color: calendarConfig.colorTypes.warning,
                startsAt: moment().startOf('month').toDate()
            }, {
                title: 'Event 2',
                type: 'info',
                color: calendarConfig.colorTypes.info,
                startsAt: moment().startOf('month').toDate()
            }, {
                title: 'Event 3',
                type: 'info',
                color: calendarConfig.colorTypes.info,
                startsAt: moment().startOf('month').toDate()
            }, {
                title: 'Event 4',
                type: 'danger',
                color: calendarConfig.colorTypes.important,
                startsAt: moment().startOf('month').toDate()
            }, {
                title: 'Event 5',
                type: 'success',
                color: calendarConfig.colorTypes.success,
                startsAt: moment().startOf('month').toDate()
            }
];

$scope.groupEvents = function(cell) {
            cell.groups = {};
            cell.events.forEach(function(event) {
                cell.groups[event.type] = cell.groups[event.type] || [];
                cell.groups[event.type].push(event);
            });

            console.log(cell.groups);
        };
=========================IN THE ATTACHED SCREENSHOT============
1 aug show 5 but it should show 1 2 1 1

**Comment by burtek** [comment]
@Neha-saini it's enough to ask your problem once. I already answered your question [here](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/624#issuecomment-323507317).

**Comment by Neha-saini** [comment]
@burtek Thanks a lot for your help. It works like charm :-)
