### ISSUE TITLE
how to get all the events of the day in angular-bootstrap-calendar

### ISSUE THREAD

**Issue by athimannil** [mattlewis92/angular-bootstrap-calendar#281]
Is there any option in ``angular-bootstrap-calendar`` to grab the day's with ```on-timespan-click = "dateClicked(eventsOfTheDay)"```

Demo: http://codepen.io/anon/pen/bEOeKw

http://stackoverflow.com/questions/35318159/how-to-get-all-the-events-of-the-day-in-angular-bootstrap-calendar

**Comment by mattlewis92** [comment]
This should do the trick :smile: 
```
on-timespan-click="dateClicked(calendarCell.events)"
```

**Comment by athimannil** [comment]
@mattlewis92  Appreceiate your quick response 👍 You saved my time  😊

**Comment by mattlewis92** [comment]
No worries, happy to help! :)

**Comment by franklindner** [comment]
Unfortunately this only works for the month view because calendarCell is undefined when clicking in rows of the the day view.
