### ISSUE TITLE
How to disable Navigating between views in $scope.viewChangeEnabled ?

### ISSUE THREAD

**Issue by athimannil** [mattlewis92/angular-bootstrap-calendar#282]
Can we use ``$scope.viewChangeEnabled = false;`` instead of ``vm.viewChangeEnabled = true;``

Demo http://codepen.io/anon/pen/KVbavW

**Comment by mattlewis92** [comment]
Sorry I don't quite follow what you mean, you just have a variable in your controller called `viewChangeEnabled` that isn't tied to anything else

**Comment by athimannil** [comment]
@mattlewis92  Actually I wanted to prevent **Navigating between views** by default without add any function.

Here is the solution I found http://codepen.io/anon/pen/YwdLQw hope these are ideal.

**Comment by mattlewis92** [comment]
Any angular expression is valid here so you can just do `on-view-change-click="false"`

**Comment by athimannil** [comment]
cheers buddy :+1:
