### ISSUE TITLE
Draggable external events with  Week and Day Droppable

### ISSUE THREAD

**Issue by Kottidev** [mattlewis92/angular-bootstrap-calendar#284]
I suggest you to add Draggable external events with Day and Week.

http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=draggable-external-events

i can't drag event to  Day View

![drag_event](https://cloud.githubusercontent.com/assets/12915009/13003496/29a96de0-d176-11e5-99b0-34d5ecc0218b.png)

**Comment by mattlewis92** [comment]
Ah good spot, the week + day views don't have the droppable directive on them so it won't work. I'll see if  I can get this added in :smile:
