### ISSUE TITLE
Changing week number format

### ISSUE THREAD

**Issue by Hypocrite** [mattlewis92/angular-bootstrap-calendar#286]
I am using version v0.18.8.

I am trying to change the displayed week number format without luck.

I have tried the following settings:
```
calendarConfig.i18nStrings = {
            eventsLabel: 'Tapahtumat',
            timeLabel: 'Aika',
            weekNumber: 'Viikko {week}'
        };
```

```
calendarConfig.i18nStrings.weekNumber = 'Viikko {week}';
```

But it always displays "WEEK 7 OF 2016".

**Comment by mattlewis92** [comment]
That's the week number on hover on the month view. For the week view title you want:
`calendarConfig.allDateFormats.angular.title.week`
