### ISSUE TITLE
Set minimum limit for resize.

### ISSUE THREAD

**Issue by swapy** [mattlewis92/angular-bootstrap-calendar#287]
I have been using angular bootstrap calendar recently. I am facing a problem on resizing the appointment in day view.

- If we resize to a very small box, then the box disappears completely. 
- I have day-view-split to 15 . I want such that user cannot resize the event <15.

**Comment by mattlewis92** [comment]
Thanks for reporting this, it should be fixed now in 0.18.9!

**Comment by swapy** [comment]
@mattlewis92 by any chance can I restrict it to be resized below 15 height?

**Comment by swapy** [comment]
I tried the new 0.18.9 version. It say view date is not set and html page is broken.

**Comment by mattlewis92** [comment]
The day view events should be restricted to a minimum height of one row now which should fit your usecase. 

What version were you previously on? Sounds like you've been hit by a breaking change: 
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/CHANGELOG.md#0180-2016-01-02

**Comment by swapy** [comment]
@mattlewis92 It is working fine. Thanks a lot ! I appreciate your efforts . This library is really good.

**Comment by mattlewis92** [comment]
Great to hear! :smile:
