### ISSUE TITLE
connect two or more views

### ISSUE THREAD

**Issue by mattletw** [mattlewis92/angular-bootstrap-calendar#288]
Hi! Is it possible to connect two or more calendars with each other with drag and drop capabilities? I need it for some timetable software for a local festival with multiple stages.

**Comment by mattlewis92** [comment]
This should just work out the box with no extra configuration, the only thing you'll need to do is when dropping on one calendar with the `on-event-times-changed` hook, check if the event is in the other calendar and remove it from that calendars events array. Here's an example that's kind of similar to what you need:
http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=draggable-external-events

**Comment by mattletw** [comment]
Thanks a lot!

Just another question, if I'm right you can only change the events label on the day view globally in the CalendarConfig, could you add an eventsLabel tag to the directive itself? 

Thanks!
