### ISSUE TITLE
The value passed to calendar-view is not set

### ISSUE THREAD

**Issue by jessica521** [mattlewis92/angular-bootstrap-calendar#29]
Hey Matt,

I'm getting the error message "The value passed to calendar-view is not set" where the calendar should be located.  Calendar-view="calendarView" in the index.html file, so I'm not sure why it is showing that error. I have tried changing it to "month" or "year" but it doesn't change anything. 

If you have a fix for this I would greatly appreciate it! I can also supply more information if that is needed. Thanks!

**Comment by mattlewis92** [comment]
Are you setting $scope.calendarView = 'year' in the controller? Have a look at the source of the demo for a working implementation:
http://mattlewis92.github.io/angular-bootstrap-calendar/docs/scripts/controllers/main.js

**Comment by jessica521** [comment]
After fiddling around with it for a little bit I got it to work! I misunderstood the direction to add this line angular.module('myModule', ['mwl.calendar']); to the app, so that was causing some issues. Thanks for your help!

**Comment by mattlewis92** [comment]
Glad you got it working :)
