### ISSUE TITLE
Disallow overlapping of two time slots.

### ISSUE THREAD

**Issue by swapy** [mattlewis92/angular-bootstrap-calendar#290]
I have written this code in controller to disallow overlapping of any two time slots. I dont know if this library has any option to disallow overlapping.

The code does not work with all test cases.
The method **eventTimesChanged** is called when an event is dragged and dropped or resized into a different date / time on the calendar. What if I resize an existing event? It shifts any event coming in its way to right side 

![image](https://cloud.githubusercontent.com/assets/1929023/13225551/5bca0ace-d9b3-11e5-8715-e3343b8c4f5f.png)

Any ideas?
Please have a look at my code too. I have passed calendarNewEventStart and calendarNewEventEnd 
 from html page itself.

```
		vm.calendar.eventTimesChanged = function(calendarEvent,calendarNewEventStart,calendarNewEventEnd) {
//			console.log(vm.calendar.events.length);
			
			for (var i = 0; i < vm.calendar.events.length; i++) {
				var oneEvent = vm.calendar.events[i];
				if(oneEvent === calendarEvent)
				{
					console.log("i found that event");
				}
				else
				{
					//console.log("this is not at all equal" + oneEvent);
					if(calendarNewEventStart >= oneEvent.startsAt && calendarNewEventStart < oneEvent.endsAt)
					{
						//start is between the time range  of another event
//						console.log("start is overlapping");
						alert('start is overlapping', calendarEvent);
					}
					else if(calendarNewEventEnd > oneEvent.startsAt && calendarNewEventEnd <= oneEvent.endsAt)
					{
						//end is between the time range  of another event
//						console.log("end is overlapping")
//						alert('end is overlapping', calendarEvent);
					}
					else
					{
						alert('perfect', calendarEvent);
						calendarEvent.startsAt = calendarNewEventStart;
						calendarEvent.endsAt = calendarNewEventEnd;
					}
					
					console.log("not eq " + oneEvent);
					break;
				}
				
```

**Comment by mattlewis92** [comment]
There isn't any option to disallow overlapping events, the calendar purposefully gives you all the hooks so you can implement this yourself. You might want to try using the `calendarHelper.eventIsInPeriod` helper function for what you're trying to accomplish:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarHelper.js#L61

If you still need more help you can put the code that's failing into a plunker and I can try and fix it for you :smile:

**Comment by swapy** [comment]
Hello @mattlewis92 , 
Please have a look at [http://plnkr.co/edit/WYJdXcax0m8ISUJKsB20?p=preview](plunker)

It does not work for overlapping as desired.
Also, events are disappearing .

**Comment by mattlewis92** [comment]
You didn't check the event against any of the other events which was why it wasn't working, here's your plunker fixed: http://plnkr.co/edit/JW6JpLQrRBOQwys1Kw79?p=preview

**Comment by swapy** [comment]
I checked the plunker , but now resize does not work and gives alert of event overlapping.Also, I cannot push one 15min event between two events with space of 15 mins. You may try it in plunker.

**Comment by mattlewis92** [comment]
You were passing the event end date as the start date which was why it was broken. I've fixed that and added a check if the event is not the dragged / resized event which should fix your problem.
