### ISSUE TITLE
WeekView on-timespan-click does not pass clicked day

### ISSUE THREAD

**Issue by vova1987** [mattlewis92/angular-bootstrap-calendar#291]
When using the on-timespan-click callback of the week view, only the clicked hour is passed as parameter.
It would be extremely helpful to also pass the date on which the user clicked - for example if I would like to create a new event on the clicked day and time.

**Comment by mattlewis92** [comment]
A date object should already passed to the callback:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarHourList.html#L8

If I'm on about a different thing let me know :smile:

**Comment by vova1987** [comment]
You are right - it is passed... But, it contains only the time portion
(e.g. 09:00) - the DATE part (e.g. 22/02/2016) is always the same - no
matter what day I click on. The issue to make it pass the correct day as
well.

**Comment by mattlewis92** [comment]
Sorry I can't replicate this, can you show me a screenshot of the part you're clicking?

**Comment by vova1987** [comment]
Sure:[image: Capture.PNG]
Note: to support RTL, I ran the CSS through an RTL css tool (the same one
used by bootsrap-RTL)

**Comment by mattlewis92** [comment]
Sorry I can't see that image, it just displays as `[image: Capture.PNG]`, can you send it again?

**Comment by vova1987** [comment]
[image: Capture.PNG]

On Wed, Feb 24, 2016 at 9:09 PM Matt Lewis <notifications@github.com> wrote:

> Sorry I can't see that image, it just displays as [image: Capture.PNG],
> can you send it again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattlewis92/angular-bootstrap-calendar/issues/291#issuecomment-188409639>
> .
>
Thats the only way I can send it... can you give a regular gmail address to
send it to?

**Comment by mattlewis92** [comment]
It's still coming through as `[image: Capture.PNG]`, maybe try natively through github?

**Comment by vova1987** [comment]
An example screenshot:
![capture](https://cloud.githubusercontent.com/assets/235639/13298252/afee0c40-db3e-11e5-90dc-ac895614e5a0.PNG)

**Comment by mattlewis92** [comment]
Oh I get what you mean now, I'm not sure if that's even possible as there isn't a grid of cells where I could put click handlers. I'll have a think about it and get back to you, but it's pretty unlikely as I can't see a simple way of implementing it.

**Comment by vova1987** [comment]
I would really appreciate it! Thank you for the quick response.
Maybe you have an Idea for a workaround to this issue? perhaps a way to get
the day when adding a custom ng-click listener on the entire view (on my
side)?

**Comment by mattlewis92** [comment]
The 2 ideas I currently have, neither of which are easy to implement are:
* Create a hidden set of divs the same sizes as the column headers that overlay the current time rows and put the click handlers there
* Use the x-y co-ordinates of the click event to calculate on which day the event was clicked

**Comment by vova1987** [comment]
I like the second Idea... I think it might even be not that difficult...
I am relatively new to angular, but I found the following piece of code
that looks promising:

app.controller('MainCtrl', function($scope, $element) {
  var elInput = $element.find('input');
  alert(elInput[0].offsetWidth);
  $scope.name = 'World';});


Knowing the layout of the Weekly View, I guess we could use the $element to
calculate the offset on click.

I will try it myself and let you know...

**Comment by vova1987** [comment]
I tried looking at it in the source... sorry.. my javascript just isn't
good enough...
Do you think you can also take a look and see if it's possible?
Thanks,
Vladimir

**Comment by mattlewis92** [comment]
I found a way to implement it, it'll be in the next release :smile:

**Comment by vova1987** [comment]
Thank you very much!!!!  :)
