### ISSUE TITLE
Week view does not show appropriate time slot size

### ISSUE THREAD

**Issue by swapy** [mattlewis92/angular-bootstrap-calendar#294]
I have week view with 

`calendarConfig.showTimesOnWeekView=true;`

Two cases don't work  here :
1. I have slot of 10 to 11 , which should show as 10 to 11 in week view but it shows only from 10 to 10:30 slot.

**Day view :**

![image](https://cloud.githubusercontent.com/assets/1929023/13310290/b8e90dce-dbaa-11e5-86d8-41d486c89c87.png)

**Week view:**

![image](https://cloud.githubusercontent.com/assets/1929023/13310299/d2ab3066-dbaa-11e5-87ad-92504a029866.png)

2. Now, I resize a slot which is from **10 to 11 ** to **10 to 12** , week view does not get updated with that  

**Day view on resize :**

![image](https://cloud.githubusercontent.com/assets/1929023/13310311/e847bfd4-dbaa-11e5-842c-28e3b0bb6f59.png)

**Week view on resize:**
![image](https://cloud.githubusercontent.com/assets/1929023/13310315/f2bdbc70-dbaa-11e5-9616-6069c8e638ee.png)

Have a look here 
http://plnkr.co/edit/RPfnR6igPlPuME11x7C6?p=preview

**Comment by mattlewis92** [comment]
The event end time isn't supported on that week view, as stated in the docs:
```
Make the week view more like the day view, with the caveat that event end times are ignored.
```

**Comment by swapy** [comment]
But if that is the case , calendarConfig.showTimesOnWeekView=true; sounds misleading

**Comment by mattlewis92** [comment]
It does clearly state in the docs that end times are ignored right next to the option. I don't get how much clearer I can make it.

**Comment by swapy** [comment]
ohh thats sad. Okay.

**Comment by artemgrygor** [comment]
Is there any reason why end date is ignored? Some issues to implement this?

**Comment by swapy** [comment]
:+1:  i would also like to have this implemented.

**Comment by MaksimPauliuchuk** [comment]
If to each event add a field with name _height_:
`event.height = (event.endsAt - event.startsAt)/60000 * (30 / self.eventDuration);`
Where `self.eventDuration` is duration of event and which use in component:
`<mwl-calendar ... day-view-split="{{vm.eventDuration}}" custom-template-urls="{calendarWeekView: 'calendarWeekView.html'}" ... />`
[calendarWeekView.html](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarWeekView.html) is template, which need modify (line 62):
` <div class="day-highlight" ... ng-style="{height: eventRow.event.height + 'px', lineHeight: eventRow.event.height + 'px', backgroundColor: eventRow.event.color.secondary}" ... />`

![bttool_ reservation](https://cloud.githubusercontent.com/assets/15263250/18587774/3c809aea-7c2c-11e6-99f5-3ef9a22e9b16.png)

Sorry for my bad English :)

**Comment by swapy** [comment]
@MaksimPauliuchuk  can you post the complete code in gist? It will be very helpful. Also, @mattlewis92 now I think this might work with calendar api. Finally . :smiley:

**Comment by MaksimPauliuchuk** [comment]
@swapy, @mattlewis92 http://plnkr.co/edit/4feXeKO9TOrP2jn8iw6i?p=preview

**Comment by burtek** [comment]
+1, would love to have it implemented in the component
