### ISSUE TITLE
I can't see the calendar

### ISSUE THREAD

**Issue by BrUn3y** [mattlewis92/angular-bootstrap-calendar#295]
Before the calendar working good but when again download the project
![captura de pantalla 2016-02-25 a las 12 59 20 p m](https://cloud.githubusercontent.com/assets/6274023/13330974/e12e207e-dbc0-11e5-82f9-46e42fc8a133.png)

**Comment by mattlewis92** [comment]
It sounds like you've been hit by a [breaking change](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/CHANGELOG.md#breaking-changes). To fix it you need to set the `view-date` attribute as it states in the error message.
