### ISSUE TITLE
Week view inconsistency

### ISSUE THREAD

**Issue by mikejohanson** [mattlewis92/angular-bootstrap-calendar#298]
On the demo provided here: 
http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink

When you hover over today's date (Sun, Feb 28th, 2016) on month view, the week on the left shows Week 10. However, when you switch modes into Week Mode. The title shows Week 8 for me. Cross verifying with google....Sun Feb 28th is the last day of Week 8, so week view seems correct, and correctly shows Week 9 when having Monday the 29th as the selected day.  However month view I would think should show week 9 when hovering... Going back and looking at January 1st of 2016, the calendar shows Week 1, but I'm pretty sure it should be Week 53, and Week 1 would start with Monday, Jan 4th.

http://week-number.net/calendar-with-week-numbers-2016.html

**Comment by mattlewis92** [comment]
Thanks for the bug report, fixed in 0.19.1 :smile:
