### ISSUE TITLE
about slide-box-disabled 

### ISSUE THREAD

**Issue by jmarreroc** [mattlewis92/angular-bootstrap-calendar#299]
Hi @mattlewis92, and congrats for this amazing work! I'm trying to set **the slide box** on my calendar but i can't make it working. Also i tried your demo example 'Slidebox is open' and modified the directive of your demo in plunker but finally i cannot make it working... 

This is my pretty easy directive:

```
<mwl-calendar ng-swipe-left="hola"
    events="vm.events"
    view="vm.calendarView"
    view-title="vm.calendarTitle"
    view-date="vm.viewDate"
    on-event-click="vm.eventClicked(calendarEvent)"
    on-event-times-changed="vm.eventTimesChanged(calendarEvent); calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
    cell-is-open="vm.isCellOpen"
    day-view-start="06:00"
    day-view-end="22:00"
    day-view-split="6"
    slide-box-disabled=false
    cell-modifier="vm.modifyCell(calendarCell)">
  </mwl-calendar>

```

Am i missing something?

Thank you for your time. Cheers

**Comment by mattlewis92** [comment]
You're missing the quotes around the attribute value `slide-box-disabled=false` should be `slide-box-disabled="false"`

**Comment by jmarreroc** [comment]
Oh my! ... thats true. And also i thought that the slide box was a slider to change month and years during touch events. Sorry for that.
