### ISSUE TITLE
Recurrence "recursOn"  none/month/year

### ISSUE THREAD

**Issue by is9875** [mattlewis92/angular-bootstrap-calendar#300]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by mattlewis92** [comment]
This seems like a reasonable request, I'll get that implemented later today :smile:

**Comment by is9875** [comment]
@mattlewis92  awesome !! appreciate it :)

**Comment by mattlewis92** [comment]
Done in 0.19.2 :smile:

**Comment by is9875** [comment]
@mattlewis92 thank you
