### ISSUE TITLE
how to bind click on year/Month/Week/Day

### ISSUE THREAD

**Issue by ermarkar** [mattlewis92/angular-bootstrap-calendar#301]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Bug description / Feature request:

how to bind click on year/Month/Week/Day?

### Versions

Angular: angular-1.4.8

Calendar directive: version v0.19.1

Browser name and version: Google Chrome 48.0.2564.116 m

**Comment by mattlewis92** [comment]
With the `on-timespan-click` callback: http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=timespan-click

**Comment by ermarkar** [comment]
Thanks, Mattlewis,

but this works on the click of the day from the calendar. But I want to bind click on buttons (Year / Month / Week/ Day)

![image](https://cloud.githubusercontent.com/assets/10824292/13659457/cdf1b24a-e6a7-11e5-9234-aced047488b8.png)

**Comment by mattlewis92** [comment]
Just use ng-click? https://docs.angularjs.org/api/ng/directive/ngClick

**Comment by ermarkar** [comment]
but where to put ng-click. the template is rendered dynamically. and I didn't found the relative code for that particular labels(Year/Week/Month) in angular-bootstrap-calendar-tpls.min.js.

**Comment by mattlewis92** [comment]
Those controls aren't actually part of the directive, they're just included in the demo. It's left up to you to implement them yourself: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/index.html#L97

**Comment by ermarkar** [comment]
thanks :)

**Comment by Clembl-git** [comment]
I'm sorry to reopen the issue, but after 3 hours struggeling i still can't manage to switch between the year / month / week / day with the header buttons :(.. 

It seems to me that the calendar need some call to be update or refresh, all the involved value are properly set but nothing changed on screen .. Please help me what am i missing ? 
I started angular.js just a week ago and i'm not very confident with the differents scopes level, i think my problem might come from that. 
Here are 3 screen showing my controller code and especially the timespanClicked function, my html markup and the console.log of the vm state and property after clicked on the year/month/week buttons.

I would be very grateful if you could enlighten me on the subject. Have a good  day !
![console screen](https://cloud.githubusercontent.com/assets/16428319/14041631/3997e9b6-f273-11e5-8025-a10a57556a3d.PNG)
![markup](https://cloud.githubusercontent.com/assets/16428319/14041632/39a0b456-f273-11e5-9933-0fea8c35cddd.PNG)
![timespanfunciton](https://cloud.githubusercontent.com/assets/16428319/14041633/39a2a928-f273-11e5-8b66-d3f3d85ce301.PNG)
