### ISSUE TITLE
Issue while adding event at end of the day

### ISSUE THREAD

**Issue by swapy** [mattlewis92/angular-bootstrap-calendar#302]
I was trying out adding event to the kitchensink example
Please look at the two screeshots
![1](https://cloud.githubusercontent.com/assets/1929023/13637670/8dd2dbd6-e62e-11e5-9507-008fd301b40b.png)
![2](https://cloud.githubusercontent.com/assets/1929023/13637671/8ea719a0-e62e-11e5-8626-dcbae33a0e0c.png)

The day view split is at 30 (in example)

Adding event works fine for any time except the end hour ie here **day view end hour** 10PM in screenshot. I think this is a bug . It adds a 1 hour slot even if I select 30 min one.

**Comment by mattlewis92** [comment]
hmm that does look like a bug, although I'm confused why it would work for 9-9:30 and not for 10-10:30. Please can you put a [plunker](http://plnkr.co/edit/tursHHxWA8SdALaj0Bx6?p=preview) together that minimally reproduces this please? Thanks!

**Comment by swapy** [comment]
Created a plunkr here : [plunkr]( http://plnkr.co/edit/xy1wR2fE4TgNI8OERNaL?p=preview)

**Comment by swapy** [comment]
One more thing, on resize for 10 to 10:30 , the appointment dissapears.

**Comment by swapy** [comment]
Thats great!
