### ISSUE TITLE
Allow event dragging only in boundaries

### ISSUE THREAD

**Issue by swapy** [mattlewis92/angular-bootstrap-calendar#303]
Tried to drag and drop event outside boundaries defined.

For eg: In my case, I have set day view start to 10AM and day view end to 12PM. Event should not be draggable outside these boundaries.

I fixed in this way , by adding following code to `eventTimesChanged` method

```
var validStartTime = moment().hours(10).minutes(0);
			var validEndTime = moment().hours(23).minutes(59);
			if(moment(calendarNewEventStart).isBefore(validStartTime) || moment(calendarNewEventStart).isAfter(validEndTime)){
				//do nothing
				console.log("You cannot schedule appointment before today");
			}else{
				//set to new time
				calendarEvent.startsAt = calendarNewEventStart;
				calendarEvent.endsAt = calendarNewEventEnd;
				console.log("Appointments has been rescheduled to "+ calendarEvent.startsAt);
			}
```

Ideally it should not allow dragging outside boundaries and set to default time 
eg: if I try to drag my time slot above 10AM which is my day start , **the event start time should be changed to 10AM** vice versa in end time case.

**Comment by mattlewis92** [comment]
I looked into implementing this before and there isn't a way of reliably restricting the area that you can resize an event to in the interact.js library, the best solution available is to use the one you have now unfortunately.
