### ISSUE TITLE
too many events make the calendar dirty 

### ISSUE THREAD

**Issue by fqaiser** [mattlewis92/angular-bootstrap-calendar#304]
Hi Matt, 

Thanks for developing this very useful calendar. I am using it currently but there is a slight problem aesthetically.  If I have more than 20 events on a day the events end up overlapping the cell below and the calendar starts to look really messy. If i have a huge number of events on everyday, then the calendar will be full of overlapping events. This will eventually defeat the whole purpose of using a calendar by making it unreadable.

![calendar](https://cloud.githubusercontent.com/assets/16575022/13781064/f42dba92-eab9-11e5-9b4c-efeb4f211763.png)

Regards,

The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by mattlewis92** [comment]
This is a limitation with the original CSS / HTML of the calendar and can't be fixed easily. I'd recommend using a custom template for the month cell and grouping events together by type (it makes for a better UX anyway). For example this is what I do at my work when using this calendar:
<img width="829" alt="screen shot 2016-03-15 at 16 53 19" src="https://cloud.githubusercontent.com/assets/6425649/13786208/85c9cf90-eace-11e5-9d8d-126233cc2d73.png">

**Comment by fqaiser** [comment]
thanks for coming back on this. can you kindly elaborate a bit more on how to achieve this grouping of events together.

**Comment by mattlewis92** [comment]
Sure thing, I've added an example here: http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=grouping-events

**Comment by fqaiser** [comment]
Thanks alot for providing a very clear example Matt. I have tried it and it does group the events. But my problem is that I am using the calendar in a small space and the square grouped events are too big to fit in the day cell. Is there anyway to just display one colour dot / event only once on each cell?

**Comment by mattlewis92** [comment]
`day.events` in the custom template contains the events for the day so you could just do something like:
```
<span class="label label-primary">{{ day.events.length }}</span>
```

**Comment by fqaiser** [comment]
Sorry I should have been clearer. What I meant to say was that each color dot/event to appear only once in each cell. e.g. we have six colors for each kind of event. info, warning etc. i just want one dot to represent all the info and another one to represent all the warnings, instead of them repeating inside each cell.

**Comment by mattlewis92** [comment]
Oh right, use the example from the demo and then the `events-list` and `event` classes from the [original template](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthCellEvents.html)

```
<div class="events-list">
  <a ng-repeat="(type, events) in day.groups track by type" class="pull-left event" ng-class="'event-' + event.type + ' ' + event.cssClass">
  </a>
</div>
```
