### ISSUE TITLE
Rendering events from cordova sql issue

### ISSUE THREAD

**Issue by benben10** [mattlewis92/angular-bootstrap-calendar#305]
I'm using your calendar with cordova and I am attempting to fetch events from a cordova sqlite database. The events array is populated with a slight delay and therefore the events do not render to the calendar. I would have thought even with the delay the watch would have picked this up. Any idea what the problem may be? 

Cheers

**Comment by mattlewis92** [comment]
I'd imagine it's because the events are fetched outside of angular, so you need to call `$scope.$apply()` to trigger a digest cycle after populating the events array.
