### ISSUE TITLE
 s.onEventTimesChanged 

### ISSUE THREAD

**Issue by ws6** [mattlewis92/angular-bootstrap-calendar#306]
I am having troulbe with  s.onEventTimesChanged when enable weekly hour view.
if I do  calendarConfig.showTimesOnWeekView = true;
can you give me a help?

**Comment by swapy** [comment]
Are you facing #294 ?

**Comment by mattlewis92** [comment]
Please follow the issue template, it exists for a reason. Without the info required in that I can't help you, sorry.
