### ISSUE TITLE
Can I create an event by selecting a timespan and dragging the mouse to vary the length of the event?

### ISSUE THREAD

**Issue by TeddyDreyfus** [mattlewis92/angular-bootstrap-calendar#308]
Hi there,

First, thanks for this amazing calendar widget. It's very useful and super easy to setup. I'm sure this is available but cannot find a way to do it:

I'd like to be able to create an event by selecting a timespan and drag the mouse to create an event of 30 or 45 min for example. How can I do that?

Thanks for your time and help.
Ted

**Comment by swapy** [comment]
You can create a new event with your desired timespan. eg: 10 to 10:30 AM
Then you can resize the event by dragging it. You can resize in the day view of the calendar.

Try out in the [demo](http://mattlewis92.github.io/angular-bootstrap-calendar/)

For documentation you can have a look at 
https://github.com/mattlewis92/angular-bootstrap-calendar#documentation

**Comment by mattlewis92** [comment]
To elaborate on what @swapy said, I've put together a basic example for you: http://plnkr.co/edit/tursHHxWA8SdALaj0Bx6?p=preview

**Comment by TeddyDreyfus** [comment]
Thank you both for your answers, it helps me to get closer to the solution I want. What I want exactly is the possibility to drag and drop my mouse to create event in that way:

http://alloyui.com/examples/scheduler/real-world/

but I want to stick with your solution because more complete and way more extensible ;)
If you have something is mind, let me know, thanks again, much appreciated.

**Comment by mattlewis92** [comment]
Oh right I get what you mean now, sorry but there isn't a way to do this with this calendar.

**Comment by TeddyDreyfus** [comment]
Ok, thanks I understand. If you have a recommendation on where I should start to look to tackle this task to support it, let me know. Would be nice to have it so I'm gonna try it.

Ted

**Comment by mattlewis92** [comment]
It's not a particularly trivial thing to add. I would start with putting an [`ng-mousedown`](https://docs.angularjs.org/api/ng/directive/ngMousedown) on [this template](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarHourList.html#L5) so you can detect the starting time slot. Then use [ `ng-mousemove`](https://docs.angularjs.org/api/ng/directive/ngMousemove) on the parent container to track the drag action. From that you can calculate the height of the new event by comparing the diff of the `$event.clientY` given by the mouse move / down directives and draw a temporary event on the screen. Then on mouseup you would need to bubble the new event up by creating a new callback that works similar to `on-event-delete`, `on-event-edit` etc. But this way you can't let the user choose the event title or the type of event etc and would still need a second bit of the UI to manually input that anyway.
