### ISSUE TITLE
Issues with no default interpolateProvider symbols

### ISSUE THREAD

**Issue by upmauro** [mattlewis92/angular-bootstrap-calendar#309]
I'm using Django in my app, so, the "template engine" symbols of Django is {{ }} and {% %}, this is a ploblem, because is the same of angular.

But, the solution is simple, change the default angular template sybmbols to another.

 `    app.config(function($interpolateProvider, $httpProvider) {
        $interpolateProvider.startSymbol('[[');
        $interpolateProvider.endSymbol(']]');
    });
`

This is a problem when i use angular-bootstrap-calendar, because the symbol is fixed "{{}}" on replace string and in another functions.

For example, see the image.

![image](https://cloud.githubusercontent.com/assets/106457/14145704/27ef11c0-f66b-11e5-9f39-6ec4054de78a.png)

Thanks for your great job and your awesome project.

**Comment by mattlewis92** [comment]
Should be fixed now in 0.19.6 :smile:
