### ISSUE TITLE
Week view broken?

### ISSUE THREAD

**Issue by reysharks** [mattlewis92/angular-bootstrap-calendar#31]
Hi,

first of all thank you for the precious work.

Then, check dates of "event 1" and it's representation. What's wrong?
As you can see an Event from 3pm to 6pm of the same day (3th or 5th March) is seen over multiple days.

![2015-03-04_1541](https://cloud.githubusercontent.com/assets/1992574/6485652/8d93123a-c285-11e4-82a8-42766a10ba5e.png)
![2015-03-04_1542](https://cloud.githubusercontent.com/assets/1992574/6485651/8d9329e6-c285-11e4-9beb-a85a13a3c810.png)
![2015-03-04_1542_001](https://cloud.githubusercontent.com/assets/1992574/6485650/8d90cbba-c285-11e4-80c5-c2aea12d562f.png)

**Comment by mattlewis92** [comment]
Fixed in 0.7.4
