### ISSUE TITLE
Modal on Date Clicked

### ISSUE THREAD

**Issue by ClovertechAU** [mattlewis92/angular-bootstrap-calendar#310]
### Bug description / Feature request:
 **vm.dateClicked Override.**

Is there a way to place a button on each day that when clicked will alert the date regardless of if there are events in that day or not.
My want is to use this calendar allowing uses to click a day and be presented with a modal depending on the day selected. 

Upon clicking the Add Event button, I would be able to ascertain the date that the button was click on and from that date display an add modal with that date set. While also returning a set of data to populate on that screen.

### Link to minimally-working plunker that reproduces the issue

http://plnkr.co/edit/hdqsfwjrJTsvqA2xNXLh?p=preview

### Versions

Angular: 1.5.0

Calendar directive: angular.module('UserCal', ['mwl.calendar', 'ui.bootstrap', 'ngAnimate'])

Browser name and version: Chrome

**Comment by mattlewis92** [comment]
You can use a [custom template](http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=custom-templates) to do this, then on your button place this `ng-click="vm.dayClicked(day, false, $event)"` and it will call the [`on-timespan-click`](https://github.com/mattlewis92/angular-bootstrap-calendar#on-timespan-click) callback with the date that was clicked and then you can add whatever logic you'd like to display a modal etc.
