### ISSUE TITLE
 Bootstrap calendar warning in console

### ISSUE THREAD

**Issue by Shreeshag** [mattlewis92/angular-bootstrap-calendar#311]
Can any one please help me to remove warning from console?

Warning will be displayed in console as bellow : 

> Bootstrap calendar:  Event startsAt should be a javascript date object Object {nodeID: "58878", TaskStatus1: "0", SiteStatus: "Under Construction", name: "Task KR 7", spliceID: "alltasks"…}

**Comment by mattlewis92** [comment]
You need to wrap the events startsAt field in a date object like `event.startsAt = new Date(event.startsAt)`

**Comment by Shreeshag** [comment]
Thank you @mattlewis92

**Comment by mattlewis92** [comment]
np :)
