### ISSUE TITLE
See hours in week view

### ISSUE THREAD

**Issue by succeeddoctor** [mattlewis92/angular-bootstrap-calendar#313]
Hi, 
 
I m using your calendar in my application. Currently we can see in a day in week view only events for this day, not all the free hours for this day.

 Can you implements this to permit to see hours of all day in week view for to have an agenda like "google agenda"?

 Thanks

**Comment by mattlewis92** [comment]
You can do this already by setting this option like so, with the caveat that event end times are ignored.
```
calendarConfig.showTimesOnWeekView = true;
```

**Comment by succeeddoctor** [comment]
Thanks this help me.
