### ISSUE TITLE
Abbreviate weekday name

### ISSUE THREAD

**Issue by akj627** [mattlewis92/angular-bootstrap-calendar#314]
How do I abbreviate the weekday name on the calendar title such as Sunday to Sun ?
 I tried `calendarConfig.allDateFormats.moment.date.weekDay = 'ddd'; `

**Comment by mattlewis92** [comment]
You want the `calendarConfig.allDateFormats.angular.title.day = 'EEE d MMMM, yyyy';` option

**Comment by MargaretKrutikova** [comment]
I only got it working with this option on the config:
```calendarConfig.allDateFormats.angular.date.weekDay = 'EEE';```
