### ISSUE TITLE
Incrementing day on week view

### ISSUE THREAD

**Issue by Clembl-git** [mattlewis92/angular-bootstrap-calendar#315]
Hello !  First of all thanks for your great plugin, i'm currently integrating it into an ionic/cordova application. I have managed to make a custom week view which only display 2 days (because of limited screen space), but i'm now struggling to increment day on this week view .. In short I'm displaying only monday and tuesday, and i would like to increment to tuesday / wednesday, then wednesday / thursday and so on insted of getting the monday / tuesday of the next week.. 
Can you guid me a little on the best way to do it ? I have tried to redefined your increment function (tpls.js:1049) but i don't see how to do it on the angular template side..
I'ld really appreciate, thanks in advance

**Comment by mattlewis92** [comment]
If you're using ionic I'd recommend avoiding this calendar all together and building it using pure ionic components. I've built this before using just the tabs, slide box and list components:
![image](https://cloud.githubusercontent.com/assets/6425649/14633052/add4258e-0613-11e6-8ed3-260dd3ee4e2d.png)
