### ISSUE TITLE
Issue regarding the events in day view.

### ISSUE THREAD

**Issue by abhiDivekar** [mattlewis92/angular-bootstrap-calendar#318]
My requirement is to provide events on 3 icons (view, edit, delete) in below image. But there doesn't seems  to be any option to customise the event title. I am struggling with this for two days. Help would be appriciated.

![screen shot 2016-04-12 at 6 07 49 pm](https://cloud.githubusercontent.com/assets/18420410/14461521/959acd8e-00e0-11e6-847f-41090887406d.png)

Plunker link http://plnkr.co/edit/3fRfJx2F56TZHZdYI0mI?p=preview

**Comment by swapy** [comment]
You need to check **calendarConfig**
https://github.com/mattlewis92/angular-bootstrap-calendar#configuring-the-calendar-default-config


if you try to print calendarConfig like this :
   ` console.log(calendarConfig); //view all available config`

You'll see all avaliable options , in that, 
You can change   

`    calendarConfig.templates.calendarDayView = 'path/to/custom/template.html'; `

for source have a look here , copy paste this code and modify it:  
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarDayView.html

**Comment by mattlewis92** [comment]
There are already hooks provided to manage editing  / deleting of events as shown in this [demo](http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=editable-deletable-events). For viewing an event just use the `on-event-click` callback as shown [here](http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=clickable-events)
