### ISSUE TITLE
Big amount of events make it slow

### ISSUE THREAD

**Issue by freefri** [mattlewis92/angular-bootstrap-calendar#32]
I have tried angular-bootstrap-calendar, it looked awesome in the demo, but when I have implemented it in my application I realize it got terrible slow when I have a big amount of events. For example, over 100 events I feel some seconds of delay when switching from year to month calendar, and over 300 events the browser says the script stops responding.
Maybe I have done something wrong in my implementation, but I've added 20 events into the live demo (http://mattlewis92.github.io/angular-bootstrap-calendar/) and I already fill some miliseconds of delay between switching.

The problem seems to occur during updateView() function.

**Comment by mattlewis92** [comment]
I've never tried it with that many events before, there's some easy performance improvements I can make though which should sort it out.

**Comment by PatrickRansom** [comment]
I'd be very interested in any improvements in speed as well.  I am in the process of implementing but imagine I'll have quite a few events.

**Comment by mattlewis92** [comment]
I've just put in a few performance improvements, however the majority of the lag isn't caused by the calendar itself though, it's actually the demo table of events, if you remove the event editor from the demo I successfully added 1000 events to the calendar with no noticeable lag.

**Comment by freefri** [comment]
Awesome, I have tested now my proyect with the new code and I really feel the difference. I am working with month view, with arround 250 events in that month, before it was hanging some times and now I just notice a small aceptable lag

**Comment by mattlewis92** [comment]
Great to hear! :)

**Comment by PatrickRansom** [comment]
Thanks for the updated code.  Implementing now.  Indeed it appears it's the editor that's slowing things down.  Much appreciated!


Patrick Ransom
