### ISSUE TITLE
Events cannot be dragged to desired time in day view.

### ISSUE THREAD

**Issue by swapy** [mattlewis92/angular-bootstrap-calendar#320]
Hello,
I am working on latest angular-bootstrap-calendar version. I have an event with start time eg: 6:02AM and ends at 6:20AM.
I want to drag it to 6:03AM ,so that it will end at 6:21AM, which is not possible. You can only drag in multiples of last number in minutes.
eg: 6:02 can be dragged to 6:32,6:42 ... and so on but not 6:03,6:04...

I have created a plunkr , please try on it.
http://plnkr.co/edit/FZhdeIzwT3P37FCwOE3F?p=preview

**Comment by mattlewis92** [comment]
This is easy enough to implement, it's currently hard set to 30px but can easily be overridden with a [variable here](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarWeekView.html#L59)

**Comment by mattlewis92** [comment]
Hi sorry about the late reply on this, I've been super busy with angular2 projects lately. I've just released 0.20.0 which will allow you to set `day-view-event-chunk-size` to limit the granularity of event drags and resizes e.g. `day-view-event-chunk-size="1"` will let you drag and resize events down to the individual minute level. Let me know if you have any issues with it! 😄

**Comment by swapy** [comment]
Thanks! Sure ill  try it out and let you know!
