### ISSUE TITLE
week view title text warp

### ISSUE THREAD

**Issue by haricet** [mattlewis92/angular-bootstrap-calendar#321]
Hi is it possible to show the description along with title and also need to change the text warp in week view .is that is possible?

**Comment by mattlewis92** [comment]
If you want to show a description you'll probably want a [custom template](http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=custom-templates). I don't get what you mean by text warp though, I'd imagine it's something you can just implement with some CSS styling though.
