### ISSUE TITLE
Duplicating day when using Firefox

### ISSUE THREAD

**Issue by Dudssource** [mattlewis92/angular-bootstrap-calendar#322]
Hello all!

I'm experiencing some issues when using the plugin (**v0.19.6**) with firefox **v45.0**.

Using the month view, in the 10th month (October) the day 15 is duplicated. I'm using moment.js as the formatter. I tried to set moment's local() to use the browser defaults but with no lucky.

Using Chrome the plugin works just fine.

Both the browsers are configured to use the Portuguese-Brazilian language.

I believe that the problem is related to the timezone, but I couldn't check this information yet.

This issue is critical for me (here in my company), so any help will be really great!

**Comment by Dudssource** [comment]
Folks, I figure out that the problem is with the Firefox Javascript Engine.
The day is getting duplicated because we have a daylight change and the moment.js library juts exposes an error that is caused by the javascript engine.

I'm sorry for not searching before.

Here is the link to the conversation:

http://stackoverflow.com/questions/21318357/moment-js-issue-adding-days-with-daylight-savings-time

**Comment by mattlewis92** [comment]
OK closing here as it's not an issue with the calendar.
