### ISSUE TITLE
In day view, unable to set day-view-start and day-view-end dyamically

### ISSUE THREAD

**Issue by statesman4** [mattlewis92/angular-bootstrap-calendar#323]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by statesman4** [comment]
Here is the plunkr

http://plnkr.co/edit/HRVIKi1g9ck8zwYagms8

**Comment by mattlewis92** [comment]
Those are interpolated values, here's your plunker fixed: http://plnkr.co/edit/Ek3hVGvoZF7FMONBlk4P?p=preview

**Comment by statesman4** [comment]
Thank you very much.
