### ISSUE TITLE
align the week data without messing up everything

### ISSUE THREAD

**Issue by haricet** [mattlewis92/angular-bootstrap-calendar#324]
Hi Matt,
      Really thanks for this great plugin.i am unable to load huge record(over 300000 records).take much time to load.any idea?.after loading the calendar if i change the year (using next and previous button)  data still binding.how can i clear it?

**Comment by mattlewis92** [comment]
This plugin isn't designed for that many events, trying to do anything with 300000 items in angular will cause performance issues (the recommended maximum amount of watchers is 2000). I'd suggest changing your UX to support filtering of events as you'd never need to display that many to the user anyway.
