### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by ncfx** [mattlewis92/angular-bootstrap-calendar#325]
### Versions: all

Angular: 2-beta15

Support Angular 2

**Comment by mattlewis92** [comment]
I've been having a think about this for a while now and I will start working on it soon, I've thrown up a placeholder repo where I've jotted down some ideas [here](https://github.com/mattlewis92/angular2-calendar). It will be a complete rewrite and fix all the flaws in the current implementation. In the meantime you can use [ngUpgrade](http://blog.thoughtram.io/angular/2015/10/24/upgrading-apps-to-angular-2-using-ngupgrade.html) to use this directive with angular2 today.
