### ISSUE TITLE
Drag and drop to last day of month problem

### ISSUE THREAD

**Issue by tonychim** [mattlewis92/angular-bootstrap-calendar#326]
Hello,

Dragging an external event to the last day of 31 day month sets startsAt to the first day of the month.
This happens in the Draggable External Events plunker:
http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=draggable-external-events

30 day months/February seem fine.

TC

**Comment by mattlewis92** [comment]
Thanks for reporting! I'll get that fixed up in the next version 😄
