### ISSUE TITLE
Events cannot be edited or deleted on mobile devices when drag is active

### ISSUE THREAD

**Issue by eldr3n** [mattlewis92/angular-bootstrap-calendar#327]
When I put a draggable event on the list, i cant delete or edit or even click the event, just drag work...

There is some option in the plugin to choose some kind of priority or something like that? 

Thanks!

**Comment by mattlewis92** [comment]
I can replicate this, although I'm not sure if a fix is possible. I'll do some research and see if I can come up with something.

**Comment by eldr3n** [comment]
I think it's something about the <li> or <ul> element, if you touch the last event of the example like that:
![image](https://cloud.githubusercontent.com/assets/15046215/14914803/d449d18a-0e0d-11e6-97c6-ed947e9bec9e.png)

You'll click the event, I dont know why, but I hope this information it's going to be usefull to you.

Also, I did some modifications on the code to play this and make draggable and clickable events.
My solution was to change the template and put 2 lists element, 1 draggable with the colour balls and 1 with clickable elements with the attr ng-draggable === false and then put the 2 lists (<ul>) on 2 colums at the same position with css.

It's just a temporaly fix, I hope you find a solution, but dude, really thanks you for your code, it's so usefull and complete. (PD: Sorry for my bad english  ^-^' )

**Comment by mattlewis92** [comment]
I think it might be [this line](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlDraggable.js#L51) that's causing the issue, I think I put it in there to prevent click events on desktop, but I'm not sure it applies to touch devices. I think the fix might just be to disable this when on a touch device 😄

**Comment by eldr3n** [comment]
Nope, I tried to disable and nothing, but thanks for the quick response

**Comment by mattlewis92** [comment]
I finally had the time to dig into this today, you can get around it by including ngTouch and enabling `$touchProvider.ngClickOverrideEnabled(true)` if using angular 1.5.0+ Hope this helps 😄
