### ISSUE TITLE
Bug for week view with time.

### ISSUE THREAD

**Issue by artemgrygor** [mattlewis92/angular-bootstrap-calendar#328]
If `calendarConfig.showTimesOnWeekView = true;` event position is incorrect according to day column. Especially after resize. Probably some offset is incorrect. 
Have a look here http://plnkr.co/edit/CYpnBrH4fxwptqXP2dhh?p=preview
When u resize a window event position would be incorrect and some of them could be even on other day column

**Comment by mattlewis92** [comment]
I can replicate this, thanks for reporting. I'll get it fixed in the next version 😄
