### ISSUE TITLE
Custom templates for Day View

### ISSUE THREAD

**Issue by ClovertechAU** [mattlewis92/angular-bootstrap-calendar#329]
### Bug description / Feature request:

Was using the Custom templates for Month quite well, but need to be able to change the template for Week View. Have looked through all the documentation and demos and am unable to find out if this is possible and if so how to do it. 
Failing that (This is a very secondary option as the week view template would be much better) I was wondering how to intercept the vm command vm.calendarCtrl.dateClicked(day.date) "The hyperlink on each day in the week view which currently move to the day view" 

### Versions

Angular: "1.5.0"

Calendar directive: "0.19.3"

Browser name and version: Chrome 49.0.2623.112

**Comment by mattlewis92** [comment]
All templates can be configured using the calendarConfigProvider like so:
```
console.log(calendarConfig.templates); // view all templates that follow this naming convention: https://github.com/mattlewis92/angular-bootstrap-calendar/tree/master/src/templates
calendarConfig.templates.calendarWeekView = 'path/to/custom/template.html';
```
