### ISSUE TITLE
support day-view-end to the next day?

### ISSUE THREAD

**Issue by wolleysesom** [mattlewis92/angular-bootstrap-calendar#331]
Hello,

I am interested in having the day-view to show pass midnight. Ex: show until the 2 am of the next day. Is that something you would consider supporting?

Thanks
Moses

**Comment by mattlewis92** [comment]
Sorry this isn't something I would want to support, there are too many edge cases to consider and it's a confusing UX for a calendars day view to display more than that days events. Sorry I couldn't be of more help 😞
