### ISSUE TITLE
Moment doesn't work properly

### ISSUE THREAD

**Issue by rshmiraf** [mattlewis92/angular-bootstrap-calendar#332]
Hi everybody,
How to translate this text "WEEK 18 OF 2016". Im using fragment of code: moment.locale("pl"); to change language to POLISH. But not everything are changed. Thanks for answer!

![zrzut ekranu 2016-05-07 o 19 22 36](https://cloud.githubusercontent.com/assets/14861637/15093464/6b611732-1489-11e6-823c-604cf6606327.png)

**Comment by rshmiraf** [comment]
![zrzut ekranu 2016-05-07 o 19 32 35](https://cloud.githubusercontent.com/assets/14861637/15093505/7b88917a-148a-11e6-9134-18eab121b685.png)

Resolved, but its cheating! 💃

**Comment by mattlewis92** [comment]
You need to do this:
```
calendarConfig.dateFormatter = 'moment'; // use moment rather than angular to format dates
calendarConfig.allDateFormats.moment.title.week = 'Week {week} of {year}'; // change this
```
