### ISSUE TITLE
vm.dayClicked Not Firing from WeekView

### ISSUE THREAD

**Issue by ClovertechAU** [mattlewis92/angular-bootstrap-calendar#333]
### Bug description / Feature request: 

`ng-click="vm.dayClicked(day, false, $event, 'button')" ` does not seem to fire from a Custom WeekView. This method works correctly from a custom MonthView but results in no event firing from day view.

The onclick is tied to the date value:

```
                        <span class="pull-right"
                              data-cal-date
                              ng-click="vm.dayClicked(day, false, $event, 'button')"
                              ng-bind="day.label">
                        </span>
```

### Link to minimally-working plunker that reproduces the issue:

[Link to Plunker- http://plnkr.co/edit/t29L3G3VhMbOWvKnoGdD](http://plnkr.co/edit/t29L3G3VhMbOWvKnoGdD?p=preview)

### Versions

Angular: 1.5.0

Calendar directive: 0.19.3

Browser name and version: Chrome - 50.0.2661.102 m

**Comment by mattlewis92** [comment]
This is because `dateClicked` is only defined in the month view directives controller and not in the week views controller (they have 2 separate isolated scopes so there is no communication between them). Based on the [original template](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarWeekView.html#L21) I think you want `vm.calendarCtrl.dateClicked(day.date)`

**Comment by ClovertechAU** [comment]
Hi Matt,

I have followed that guide, though still have the issue that the javascript will not fire onclick of those dates, on click it moves to day view 

I have both     
```
calendarConfig.dateClicked = function (event, date, clicktype, $event, type) {
        console.log('Never gonna get here')
     };
```

And

```

    vm.dateClicked = function (event) {
       console.log('Never gonna get here either')
    }
```

The `ng-click="vm.calendarCtrl.dateClicked(day.date)"` should hit one of those shouldn't it?

**Comment by mattlewis92** [comment]
Ah sorry to explain a bit more, it calls the dateClicked function of the parent `mwl-calendar` directive: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendar.js#L18

So when you define the directive you can hook into the click with `on-view-change-click`, if you return false it will cancel the view change click and you can implement your custom logic there.

**Comment by ClovertechAU** [comment]
Having no love with this at all, tried quite a few permutations.

In my mark up on the calandarWeekView.html

`                               <span data-cal-date
                                      ng-click="vm.dateClicked(day.date)"
                                      class="pointer btn"
                                      id="openDay"
                                      ng-bind="day.dayLabel">
                                </span>` 

In the calendar directive I have:

`                              on-timespan-click="vm.dateClicked(date)",
                              on-view-change-click="vm.dateClicked(date)"`

And in the javascript:

`calendarConfig.templates.calendarWeekView = 'calendarWeekView.html';
    vm.dateClicked = function (date) {

        alert("Do Something");

    };`

Nothing hits that dateClicked... Sorry to keep annoying you, just getting drove simple and don't know what else to try

**Comment by mattlewis92** [comment]
In `calendarWeekView.html` you need to put `vm.calendarCtrl.dateClicked(day.date)` NOT `vm.dateClicked(day.date)`, and then it will bubble up to the `on-view-change-click` callback

**Comment by ClovertechAU** [comment]
That did it thanks Matt!
The day.date isn't passing though in the `vm.dateClicked = function (date)` , once I get that fixed, hopefully it will be the last tinkering I have to do!
