### ISSUE TITLE
How to implement navigator?

### ISSUE THREAD

**Issue by Jeevanandanj** [mattlewis92/angular-bootstrap-calendar#334]
First of all, I need to thank for the great plugin.
Here I am posting that not an issue. I need to know for the following feature.

Is there any navigator for this plugin how to implement like following?

![image](https://cloud.githubusercontent.com/assets/11751821/15348597/c6dbb06e-1ce9-11e6-9818-51bac0866f72.png)

There is a plugin for calender with navigator. Can we implement like this using ui bootstrap datepicker?
http://javascript.daypilot.org/demo/calendar/navigator.html

![image](https://cloud.githubusercontent.com/assets/11751821/15348643/1665e064-1cea-11e6-87e4-00a2322df89e.png)

**Comment by mattlewis92** [comment]
You could easily implement this with a datepicker component such as [this one](http://angular-ui.github.io/bootstrap/#/datepicker). Just bind it to the date you pass to the `view-date` of the calendar.
