### ISSUE TITLE
The recurring events do not appear in day view. How can I fix that?

### ISSUE THREAD

**Issue by anushree-jain** [mattlewis92/angular-bootstrap-calendar#335]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by mattlewis92** [comment]
It works for me in the demo: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=recurring-events

Please post a plunker that reproduces your issue.
