### ISSUE TITLE
How to implement without dots

### ISSUE THREAD

**Issue by Jeevanandanj** [mattlewis92/angular-bootstrap-calendar#336]
When we add more events, then dots looks like improper. The dots go out of the box (Date).

Can we implement like following image? Here they are having more link, when we add more events and if we click on the link, pop over comes with the events.

Can we implement like the following image?
![image](https://cloud.githubusercontent.com/assets/11751821/15358139/70229828-1d20-11e6-8c55-c0e559997eb4.png)

**Comment by mattlewis92** [comment]
I'd recommend grouping events together like so:
http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=grouping-events
