### ISSUE TITLE
day-view-start set to 8:30, though calendar still display the 8:00-8:30 range

### ISSUE THREAD

**Issue by TeddyDreyfus** [mattlewis92/angular-bootstrap-calendar#337]
Hi,

I've set the day-view-start property to 8:30. though it still display the 8:00 time. Also when I select the 8:30 to 9:00am cell, I have the 9:00 to 9:30 cell selected. Looks like everything is shifted by 30 min.

Any clue?

Thanks,
Teddy

**Comment by mattlewis92** [comment]
It works fine for me on the demo: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=day-view-start-end

As clearly stated in the issue template, please provide a plunker that demonstrates your problem. Thanks!
