### ISSUE TITLE
Can we use without moment?

### ISSUE THREAD

**Issue by Jeevanandanj** [mattlewis92/angular-bootstrap-calendar#338]
In angular more features available like for date and time with localisation.

Why do we need to use moment js?
Can we use without this?

**Comment by mattlewis92** [comment]
Moment is used heavily under the hood for doing complex date operations for generating the calendar, however by default angulars date filter is used for all date formatting, if you load a different angular locale file all dates will be automatically change to the locale

**Comment by Jeevanandanj** [comment]
So is moment js is optional?

**Comment by mattlewis92** [comment]
Nope, it's still used [heavily by the calendar](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarHelper.js), you just don't use it directly.
