### ISSUE TITLE
In week view alone, how to drag elements to next week?

### ISSUE THREAD

**Issue by Jeevanandanj** [mattlewis92/angular-bootstrap-calendar#339]
Hi,

In month view, I am able to move events to different dates.

But I disabled the month and year view. Now I am having only week view.

Now I want to drag the events from one week to another week.

How to do that?

**Comment by mattlewis92** [comment]
Sorry there isn't a way to do this as the week view can only view one week at a time.

**Comment by Jeevanandanj** [comment]
Will it be implemented in future? or is there any option will be provided for that?

**Comment by mattlewis92** [comment]
I don't have any plans to implement it as I can't see a way for it to even work with the current design. How can you drag an event to a week that isn't visible?
