### ISSUE TITLE
Get current week start and end date

### ISSUE THREAD

**Issue by Jeevanandanj** [mattlewis92/angular-bootstrap-calendar#341]
How to get current week start and end date?

**Comment by mattlewis92** [comment]
As clearly stated in the [issue template](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/.github/ISSUE_TEMPLATE.md) and the [contributing guide](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/.github/CONTRIBUTING.md) please use stackoverflow for support queries.

You can just use moment for this `moment(vm.viewDate).startOf('week').toDate();` and `moment(vm.viewDate).endOf('week').toDate();`
