### ISSUE TITLE
Event startsAt should be a javascript date object

### ISSUE THREAD

**Issue by RonAlmog** [mattlewis92/angular-bootstrap-calendar#342]
i get this warning when loading the events into the calendar:

Event startsAt should be a javascript date object. 
Do `new Date(event.startsAt)` to fix it. 
Object {id: "574c63a7cb66e56c3982ee64", startsAt: "2016-06-28T22:00:00.000Z", endsAt: "2016-06-28T23:00:00.000Z", title: "event title", type: "important"…}

and the same for endsAt. Now i'm looking at those dates and they look pretty much Kosher javascript dates to me. aren't they? Can you please suggest a way to avoid this warning?
Thank you!

**Comment by mattlewis92** [comment]
Those are just strings, not JS date objects. As the warning states you need to wrap the strings in a date constructor like: `new Date('2016-06-28T22:00:00.000Z')`

**Comment by RonAlmog** [comment]
Yes, that worked. cool stuff, thanks!
