### ISSUE TITLE
hours bar in week view?

### ISSUE THREAD

**Issue by RonAlmog** [mattlewis92/angular-bootstrap-calendar#343]
2 quick questions:
1. How do i cause the hours bar on the left side to appear in week view?

2. i have millions of events in the server. the user is browsing the calendar, moving back and forth, changing views (month, week, day). with every move she makes, i need to go to the server and fetch the events. is there a method, or trigger for such event?
i need a range of 2 dates to query the server side: fromDate, toDate. so it depends on the view. What's the best way to manage this? 
Thanks!

**Comment by mattlewis92** [comment]
The github issue tracker is for bug reports and feature requests only, as the issue template states please use stackoverflow / gitter etc for support queries.

You can use 
```
calendarConfig.showTimesOnWeekView = true;
```
to display the times on the week view, although event end times are ignored.

You can watch the value you pass to `view` and `view-date` like so to change the list of events:
```
$scope.$watchGroup(['vm.calendarView', 'vm.calendarDate'], function(view, date) {
  var start = moment(date).startOf('view').toDate();
  var end = moment(date).endOf('view').toDate();
  // fetch events
});
```

**Comment by RonAlmog** [comment]
great, thanks.
