### ISSUE TITLE
Bug: Shifted time when using minute specific starting times

### ISSUE THREAD

**Issue by Fatih75** [mattlewis92/angular-bootstrap-calendar#344]
Hi matt,

**Thanks for fixing all bugs and issues within a blink of an eye!** 
There is a small bug with the selected time when adding or dragging an Event in the scheduler.

### Bug description
When the day-view-start/end is set to a half hour, like 9:30, the grid is rendered perfectly. 
But the time on each block is shifted 30 minutes.

![selection_105](https://cloud.githubusercontent.com/assets/10922502/15678231/d1623a3a-274d-11e6-99b8-b2332d77d098.png)

**However,** This does not occur when you click on a the timespan.
In addition to issue #340,  the on-timespan-click method now works perfectly by returning the correct time. 

![selection_106](https://cloud.githubusercontent.com/assets/10922502/15678239/d63a5d8a-274d-11e6-867e-6ec68a47907d.png)

### Plunker
http://plnkr.co/edit/T0xk4OMqpdWldgTrbozk?p=preview

### Related issues
Issue #340 - Bug: day-view-start time only works with exact hours 

Kind regards,

**Comment by Fatih75** [comment]
### Edit
It seems that the bug is not  only related to the minute specific starting times...
This bug also occurs when an exact hour is set, it also occurs when the day-view-start is NOT set.

**The problem might be the rendering of the day view grid.**
The grid on all days BEFORE the current day is different.
Plunker demonstrating the bug : http://plnkr.co/edit/wTVVSPRYSkYI3GyMihnH?p=preview

**When a minute specific time is set, the days _before_ AND _after_ are also different**
http://plnkr.co/edit/JBAZz0?p=preview

Figured this out because i was looking at the kitchen sink example : https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink
The events ( and hour grid ) on the days before the current date are shifted by 1 hour.

It might be related to version 0.20.1.

**Comment by mattlewis92** [comment]
Looks like the fix for 0.20.1 broke a lot of other things, I've reverted it in 0.20.2 for now until I have the time to fix it properly.

**Comment by mattlewis92** [comment]
Apologies for the late reply on this, I ended up rebuilding the entire day view logic from scratch in the end!
