### ISSUE TITLE
on-edit-event-click and on-timespan-click

### ISSUE THREAD

**Issue by SynRJ** [mattlewis92/angular-bootstrap-calendar#345]
Hi, thanks for the great plugin.

I noticed what might be an issue with the _in-edit-event-click_ and _on-timespan-click_ events. Both events are triggered when I click on any event, which doesn't fit my needs. Is there a way to prevent the _on-timespan-click_ event to fire when I click on an event ?

The behavior appears with any configuration, as long as the _on-edit-event-click_ and the _on-timespan-click_ attributes are set.

What I'd like to do is open a popup/whatever to create a new event with the _on-timespan-click_, and open another popup/whatever to edit an existing event with the _on-edit-event-click_.

Thanks for your help.

Edit: same issue with the _on-event-click_ (which is probably even more appropriate to my use case)

**Comment by mattlewis92** [comment]
It should be fixed in 0.20.2, thanks for reporting!
