### ISSUE TITLE
Changing multiple templates

### ISSUE THREAD

**Issue by mick1313** [mattlewis92/angular-bootstrap-calendar#346]
I am using a calendar in more than one spot within a work flow.  Each view needs a different template, to be when my first controller opens, it sets the template for the monthCell.  That controller, then opens a MODAL, with another calendar in it, that needs to be templated differently.

I have the config being set in the 2nd controller, but it seems to have no effect.  It reverts to the default view.  If I remove any configuration change in the second controller, it reverts to the first template I set.  Is there a way to change or reset the calendar when then modal opens with a different template?

**Comment by mattlewis92** [comment]
It might be possible to get this behaviour by using one time binding on the ng-include of the template. Can you try overriding the month view template and changing [this line](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthView.html#L19) to:
```
<ng-include src=":: vm.calendarConfig.templates.calendarMonthCell"></ng-include>
```
