### ISSUE TITLE
"Resource vs Timeline" views for use as scheduler

### ISSUE THREAD

**Issue by deksden** [mattlewis92/angular-bootstrap-calendar#347]
### Feature request:

Any plans for adding "resources" for use calendar as scheduler? I mean adding any "resource vs timeline"-styled views (horizontal/vertical). 

Good list of possible features for inspiration is "scheduler" premium add-on for FullCalendar.io (link: http://fullcalendar.io/scheduler/ ).

IMHO really cool features will be:

* horizontal / vertical layout (resources will be Y- or X-axis);
* groupByResource layout for X-axis (so, column should start with date, then it will have dedicated columns for each resource)

**Comment by mattlewis92** [comment]
Sorry I've got no plans to support anything like this, it's too much work to implement / maintain.
