### ISSUE TITLE
I am getting the warning from angular

### ISSUE THREAD

**Issue by Jeevanandanj** [mattlewis92/angular-bootstrap-calendar#348]
Hi I am using angular 1.3.17.

I am getting the following warning from angular.

![image 3](https://cloud.githubusercontent.com/assets/11751821/15798669/d875ce46-2a5d-11e6-807a-f60c90dc43da.png)

**Comment by mattlewis92** [comment]
Thanks for reporting, fixed in master and will cut a new release soon!
