### ISSUE TITLE
Events without time

### ISSUE THREAD

**Issue by Jeevanandanj** [mattlewis92/angular-bootstrap-calendar#349]
I don't know whether this is a issue or not.

1. Need to remove the time in event in month view.
2. For the week view (I don't have time in the week view), the dates are aligned in different position, even if there is a space in the above line.
![1](https://cloud.githubusercontent.com/assets/11751821/15799308/fd00ad2c-2a75-11e6-8a27-a378936c42e3.png)
![2](https://cloud.githubusercontent.com/assets/11751821/15799309/fd032ed0-2a75-11e6-9327-335b3ed6c987.png)

**Comment by mattlewis92** [comment]
1/ I can wrap the time in a span which you can hide with a CSS selector
2/ This is a limitation with the original calendars CSS and really, really hard to solve

**Comment by Jeevanandanj** [comment]
1. Thanks. It would help to design and hide. If you give any quick fix, that will help to apply in my application.
2. If you solve this it would be so helpful. Check the overlay-ed events (where one or more events, starts in the same time and same date), that will give some idea.

**Comment by mattlewis92** [comment]
1/ You could override the slidebox template for now to remove the time.
2/ The problem is more with how the CSS works as each event is effectively its own row. If you don't use event end times you could use the `calendarConfig.showTimesOnWeekView = true` option.

**Comment by Jeevanandanj** [comment]
2. That's great to have this. Can we trick to using this same concept without time span in left and the time in the cards.

**Comment by mattlewis92** [comment]
Sorry I don't follow what you mean, a screenshot would help

**Comment by Jeevanandanj** [comment]
Sorry I've mistakenly mentioned.

1. Another bug is i found that,
I've 3 cards in the same date with the same time.
But I can see only the 3 rd card. All other cards are overlapped.
(1-ImageSample)


1 - Image sample
![image](https://cloud.githubusercontent.com/assets/11751821/15850305/e94503be-2cb4-11e6-84d8-9288932d0b52.png)

**Comment by Jeevanandanj** [comment]
You are generating the same style for arranging events which is time frame based week view.

The css are not affected the events. Doing calculation to set top and left px for the events, deciding the position of the events.

So doing change in calculation to display events in the week view, We can get the events without space in the week view.

Please check the following image. 

![image](https://cloud.githubusercontent.com/assets/11751821/15850605/837f0d84-2cb6-11e6-91d7-ff67fc76a140.png)

**Comment by mattlewis92** [comment]
I get around this at work by grouping events on the week view together by the start date like this:

![screen shot 2016-06-07 at 09 17 58](https://cloud.githubusercontent.com/assets/6425649/15850610/d3494d3c-2c90-11e6-892a-3e2a66df9851.png)

Then I use the `on-event-clicked` callback of these grouped events to switch to the day view and scroll to the time that was clicked

**Comment by Jeevanandanj** [comment]
Thank you. Did you check my previous post?
I've notice that you are using the same css for the timespan events and the events without timespan.
I think,
Only the difference is the calculation for the event to find for absolute position.
I think if we concentrate on that part, we may fix this.
But we can have with enable and disable option.

I have in another work so concentrate now on this.

**Comment by deepmirchandani** [comment]
SOLVED---------------------------
Just change below line in angular-bootstrap-calendar-tpls.min.js.  OR angular-bootstrap-calendar-tpls.js

function monthView(event) {
	        //return event.title + ' (' + calendarDateFilter(event.startsAt, 'time', true) + ')';
	        return event.title; 
	    }
YOU CAN CHANGED CODE IN ALL VIEW INSTEAD OF function monthView
