### ISSUE TITLE
Time_split in day view.

### ISSUE THREAD

**Issue by ShivaliPatel** [mattlewis92/angular-bootstrap-calendar#35]
This is a good plugin of bootstrap-calender by `Serhioromano`.

In bootstrap-calendar, it having `time_split` option for day view.
Hence, if we want to display day with some minute interval, then how to configure it??

**Comment by mattlewis92** [comment]
This isn't currently possible, but I can add an option for it.

**Comment by mattlewis92** [comment]
Added in 0.8.0
