### ISSUE TITLE
Edit button is not found in Day view

### ISSUE THREAD

**Issue by Jeevanandanj** [mattlewis92/angular-bootstrap-calendar#351]
https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=editable-deletable-events

Hi If I implement edit functionality, I can't find edit button in day view.

Please see the attached image.
![2](https://cloud.githubusercontent.com/assets/11751821/15800980/483d7c96-2aa5-11e6-846f-2548967d7009.png)
![1](https://cloud.githubusercontent.com/assets/11751821/15800981/4849d69e-2aa5-11e6-855c-f25b5497ff6f.png)

**Comment by mattlewis92** [comment]
huh, it looks like I never implemented this, I'm surprised it's taken so long for someone to point it out. Will add it in the next release!
