### ISSUE TITLE
Show slide box for cells without events 

### ISSUE THREAD

**Issue by swrocket** [mattlewis92/angular-bootstrap-calendar#352]
Is there a way to show the slide box when clicking on a cell without events?

### Versions

Angular:1.5

Calendar directive:0.20

Browser name and version:Chrome

**Comment by mattlewis92** [comment]
Not currently as it wouldn't show anything. What's your use case?

**Comment by swrocket** [comment]
Thanks for the quick reply. 
I really like the slide box and want to use it to allow the user to add an event instead of using a modal or other "add" controls.
I customized the template for the SlideBox (very easy to do) so it's just a matter of showing it. I looked through the code but couldn't figure out how to set the isCollapsed variable from my controller.

Thanks,

Andrew

**Comment by mattlewis92** [comment]
Ah ok, if you override the month view template and change the expression on [this line](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthView.html#L24) to:
```
vm.openRowIndex === $index && !vm.slideBoxDisabled
```
it should give you the behaviour you need 😄

**Comment by swrocket** [comment]
Thank you sir.
