### ISSUE TITLE
Support updating day-view-split on the fly?

### ISSUE THREAD

**Issue by wolleysesom** [mattlewis92/angular-bootstrap-calendar#358]
Currently, if I assign 'day-view-split' to a scope variable and dynamically change it, The calendar updates it visually, but the calendar events do not resize accordingly. Is this something you would support?

**Comment by mattlewis92** [comment]
Yup this is something I can add, as a workaround for now once you change the split amount call `$scope.$broadcast('calendar.refreshView');` and it should update.

**Comment by wolleysesom** [comment]
That works, thank you!
