### ISSUE TITLE
Allow Events to occur Daily

### ISSUE THREAD

**Issue by nikitakindra** [mattlewis92/angular-bootstrap-calendar#360]
Bug description / Feature request:

### Versions
Browser name and version:All Browsers

**Comment by jeevasusej** [comment]
Can you post any sample image for your requirement description?

**Comment by mattlewis92** [comment]
The current recurring events is a bit of a hack really and not something that particularly plays well with the design of the calendar. I'd recommend just implementing it yourself in user land every time the view is changed using something [like this](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/127#issuecomment-136022090).
