### ISSUE TITLE
Show each day event  in each coulmn. Now it  shows like 2nd  day event start s only after the completion of 1 day event

### ISSUE THREAD

**Issue by immaraj** [mattlewis92/angular-bootstrap-calendar#363]
I am using bootstrap calendar and i need to know how to  Show each day event  in each coulmn. Now it  shows like 2nd  day event start s only after the completion of 1 day event

**Comment by mattlewis92** [comment]
This is done intentionally, if they didn't stack like this then you wouldn't be able to see all of the events as they would overlap one another.
