### ISSUE TITLE
Events missing end time on weekview with hours

### ISSUE THREAD

**Issue by frnk01** [mattlewis92/angular-bootstrap-calendar#364]
Is there any specific reason for why the week view with hour display enabled does not support end time on the events, and if not are there any plans to implement this anytime soon?

I would really appreciate a tip on how to solve this with a quick fix if possible.

**Comment by mattlewis92** [comment]
As the readme says: Make the week view more like the day view, with the **caveat that event end times are ignored** Basically supporting end times is really complex as you need to handle event overlapping each other etc, hence why it's not the default view.
