### ISSUE TITLE
[Feature Request] Support on-date-range-select on week view?

### ISSUE THREAD

**Issue by wolleysesom** [mattlewis92/angular-bootstrap-calendar#366]
Hello,

Using week view with showTimesOnWeekView to true, I would like to be able to do range select across days. Would that be feasible?

**Comment by mattlewis92** [comment]
What's your use case? As event end times are ignored on this view I don't see the value in it

**Comment by wolleysesom** [comment]
My use case is to create a new event by range select on the week view. I do understand the newly created event will be displayed in the week view without end time, but the actual event would have the endtime the user desired.

**Comment by mattlewis92** [comment]
OK fair enough, I already actually added support for this previously but removed it as it seemed redundant, if you have a use for it I'll re-add it: https://github.com/mattlewis92/angular-bootstrap-calendar/commit/991b7031d96702eefe74f6763cde7b6df89d954e

**Comment by wolleysesom** [comment]
please do. Thanks!

**Comment by STheFox** [comment]
I would also like to be able to select a range at week level. Please revert your commit :-)

**Comment by willnew** [comment]
is it possible to also enable range selector on month view?

**Comment by mattlewis92** [comment]
Tracking that here: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/391

**Comment by willnew** [comment]
Awesome, nice to hear about that

**Comment by STheFox** [comment]
Is it possible to enable range selector on week view?
Use case: select like 3 hours on a single day in week view to create an event.
