### ISSUE TITLE
Day view set the events in horizontally 

### ISSUE THREAD

**Issue by immaraj** [mattlewis92/angular-bootstrap-calendar#367]
How to load the day view events as horizontally  in bootstrap calendar
![image](https://cloud.githubusercontent.com/assets/16030181/16111256/4b035ed6-33cf-11e6-9755-a486e213f266.png)

**Comment by mattlewis92** [comment]
Sorry there isn't a way to do this with this module.

**Comment by immaraj** [comment]
is there any way to display events horizontally in bootstrap calendar week
view

**Comment by mattlewis92** [comment]
If there isn't a [demo of a feature](https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink) then it isn't supported

**Comment by immaraj** [comment]
sir i need load the events in week view like this image
can you help out sir
 to load [image: Inline image 1]

**Comment by immaraj** [comment]
sir i am using bootstrap calendar only not a angular bootstrap calendar
