### ISSUE TITLE
How to know the day clicked in the slide box ?

### ISSUE THREAD

**Issue by asicfr** [mattlewis92/angular-bootstrap-calendar#369]
### 0.20.2

I tried to use dayClicked to add more data but not found onTimespanClick function.
Is there any way to do that ? 

Thx for your help.

**Comment by mattlewis92** [comment]
Sorry I don't quite follow you, would you mind explaining a bit more, maybe with a screenshot or a plunker?

**Comment by asicfr** [comment]
Sorry, in the template of slide box (calendarSlideBox.html), 
i want to know the clicked day (dayClicked -> onTimespanClick) .

**Comment by asicfr** [comment]
When the user click on a day (1st of august), the slide box present all events of that day.
Is it possible in the slide box controller to get that day, the day selected by the user ?

**Comment by mattlewis92** [comment]
Sorry about the late reply, the next release will have `vm.cell` available in the slide box scope which will contain the current month or day cell with the info you need in it

**Comment by asicfr** [comment]
Ok, great, thx.
