### ISSUE TITLE
The value passed to the calendar-view is not set

### ISSUE THREAD

**Issue by NikhilNanjappa** [mattlewis92/angular-bootstrap-calendar#37]
Hey I have created a controller named DateCtrl(date.js) + date.html

In date.js >>

![screen shot 2015-03-20 at 12 03 52 pm](https://cloud.githubusercontent.com/assets/5576981/6747036/3c9ac8c0-cef9-11e4-8967-4e5f9f483b67.png)

In date.html >>

![screen shot 2015-03-20 at 12 05 02 pm](https://cloud.githubusercontent.com/assets/5576981/6747053/6798c7e8-cef9-11e4-9245-3ebc833b9b2a.png)

This is how the rendered page looks like >>

![screen shot 2015-03-20 at 12 02 31 pm](https://cloud.githubusercontent.com/assets/5576981/6747068/a67418b4-cef9-11e4-9bd0-faec65066fc3.png)

Please help.. This might be the wrong place to post but i cudn't find any.

**Comment by NikhilNanjappa** [comment]
Hey Matt... I went through Issue #29 and somehow fixed the rendering issue but now the view is going haywire.. Here is the screenshot + the scripts and stylesheets im using. Any help is appreciated. 
Thanks buddy #Awesome-Work

Page >>

![screen shot 2015-03-20 at 12 22 18 pm](https://cloud.githubusercontent.com/assets/5576981/6747212/0a9e9d12-cefc-11e4-83f7-b29b211612a5.png)

![screen shot 2015-03-20 at 12 22 39 pm](https://cloud.githubusercontent.com/assets/5576981/6747213/11378256-cefc-11e4-8726-42180c497be3.png)

scripts and stylesheets >>

![screen shot 2015-03-20 at 12 23 00 pm](https://cloud.githubusercontent.com/assets/5576981/6747219/1f7ef858-cefc-11e4-97f9-0b4ab8f98d34.png)

![screen shot 2015-03-20 at 12 23 16 pm](https://cloud.githubusercontent.com/assets/5576981/6747221/261c70b4-cefc-11e4-955f-834da81471a3.png)

**Comment by mattlewis92** [comment]
You need the CSS from bootstrap 3, not bootstrap 2, hence why all your styling is messed up.

**Comment by NikhilNanjappa** [comment]
Aww... Thanks for pointing it out matt . But when i use BS 3, my other pages are getting messed up since i build my app based on BS2. Is there any way to get around it ? May be use BS3 only for this ng-view page (date.html)

**Comment by mattlewis92** [comment]
You can't run bs 2 and 3 in parallel. Maybe you could use the original jquery version of the plugin which does support BS2, the links at the top of the read me.
