### ISSUE TITLE
Browserify with Gulp and the resolve plugin

### ISSUE THREAD

**Issue by okayawright** [mattlewis92/angular-bootstrap-calendar#371]
I use Browserify with Gulp and the resolve plugin to concatenate all NPMs into one single JS file.
I need to add the attribute:
    "main": "dist/js/angular-bootstrap-calendar-tpls.js"
in 'package.json' for resolve to pick up an entry point in that module.
Can you please add this to your setup?

Thank you.

**Comment by mattlewis92** [comment]
That's odd, browserify should already pick up the [browser field](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/package.json#L56) that's set, changing it to main shouldn't break anything though.

**Comment by okayawright** [comment]
It's this module : https://github.com/substack/node-resolve which is apparently not compliant with the 'browser' field.
Browserify works fine with 'browser' but my set up is a bit uncommon: in my gulp tasks, I first need to resolve which files are later needed by browserify, and then concatenate them into a single file. For this purpose I use this 'resolve' plugin. And this plugin was apparently not designed with browserify in mind.

**Comment by mattlewis92** [comment]
Ah I've come across issues with that module before, I'll fix this when I have some free time, in the meantime you should be able to `require('angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls')` to work around this for now.
