### ISSUE TITLE
Bootstrap CSS

### ISSUE THREAD

**Issue by okayawright** [mattlewis92/angular-bootstrap-calendar#372]
Instead of having to be dependent on the full Bootstrap package, just linking 'bootstrap-css-only' appears to be enough according to my initial tests.

**Comment by mattlewis92** [comment]
Yup only the CSS is required, however bootstrap-css-only is not an official package. It's only an extra few kb to download the jquery as well, plus you can just ignore the peer dependency warning and install `bootstrap-css-only` if you'd prefer

**Comment by bergera** [comment]
This issue breaks `npm-shrinkwrap`. In my case, I'm using `bootstrap-sass` instead of `bootstrap`.

```
$ npm shrinkwrap
...
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: bootstrap@^3.3.6, required by angular-bootstrap-calendar@0.20.2
...
```

This project is great, it's not a breaking thing but if it's billled as Angular-only and jQuery-free there's got to be a more elegant solution which doesn't require an unnecessary package in order to support best practices like `npm-shrinkwrap`.

**Comment by mattlewis92** [comment]
I would have assumed as peer dependencies were optional in npm3 it wouldn't break a shrinkwrap. I think the best solution here is just to completely remove the peer dependency on bootstrap completely

**Comment by bergera** [comment]
Thanks for the quick reply. I think you're right idea, as there isn't a direct need within the project itself. A simple step to bring in something with Bootstrap CSS, most would probably have that anyway.

**Comment by mattlewis92** [comment]
Yup as there's no `require('bootstrap')` anywhere in the code it's effectively a redundant dependency, I should have some time this weekend to get this done and cut a new release  😄

**Comment by bergera** [comment]
:tada:
