### ISSUE TITLE
Event slide not display when adding/removing events dynamically.

### ISSUE THREAD

**Issue by alakratt** [mattlewis92/angular-bootstrap-calendar#376]
I'm adding and removing events dynamically when clicking on the days in the month view. When a day is first clicked the slide that shows the event under the day displays just fine and it's added to the events array. Now, when the array has multiple events (I'm just allowing one per day) and you click on a day, that's not the last on the array, to remove it, which it does and then click again to re-add it the event slide doesn't show. 

I hope I explained my issue well since I'm no good at explaining in general. Anyway, can anyone help?

**Comment by mattlewis92** [comment]
Sorry I don't quite follow you, could you maybe put together [a plunker](http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview) that reproduces the problem you're experiencing?

**Comment by mattlewis92** [comment]
I had some time to dig into this a bit more today, I'm assuming you're adding events via the `on-timespan-click` event, if you pass in the `$event` object like so: `on-timespan-click="toggleEvent(calendarCell, calendarDate, $event)"` and then call `$event.preventDefault()` only when removing the event on the first click it should solve your problem.
