### ISSUE TITLE
The mwl-date-modifier directive listener

### ISSUE THREAD

**Issue by owenhope** [mattlewis92/angular-bootstrap-calendar#377]
Hi,

I was wondering if there is a listener for the mwl-date-modifier. We only want to grab events for display in the date range that is currently loaded in the view.

I have tried to set watches on the viewDate to no success.

Any suggestions would be helpful.

**Comment by owenhope** [comment]
I solved this by setting both calendarView and viewDate to be on the $scope.

The wrote this listener

`$scope.$watch(function(scope){
            return scope.viewDate + scope.calendarView;
        }, function(n,o)
        {
            getEventsByDateRange(moment($scope.viewDate).startOf($scope.calendarView).unix(), moment($scope.viewDate).endOf($scope.calendarView).unix());
        });`

**Comment by mattlewis92** [comment]
Glad you got it sorted 😄 FYI A simpler solution might be to just put an `ng-click` event on the buttons though
```
<button ng-click="dateChanged()" class="btn btn-primary" mwl-date-modifier date="vm.viewDate" decrement="vm.calendarView">
  Previous
</button>
```

**Comment by haithemhasni** [comment]
Hi, 

For some reason the ng-click event not firing, I have used ng-click="dateChanged()" and ng-click="vm.dateChanged()", still not firing. Am I missing something? Please help.

Thank you

**Comment by gintsgints** [comment]
ng-click works for me.
