### ISSUE TITLE
Localization and dates: time in day view

### ISSUE THREAD

**Issue by okayawright** [mattlewis92/angular-bootstrap-calendar#378]
Hello,

compared to others captions in other views (ex: month names in the year view, days of week in the week view, etc), the time labels (hour of day) in the day view don't appear to be properly 'double binded': they don't automatically update when the format is changed. The format changes if you switch view first though.

Here are my relevant settings:
                calendarConfig.dateFormatter = 'angular';
                calendarConfig.allDateFormats.angular.date.hour = 'shortTime';
                calendarConfig.allDateFormats.angular.date.day = 'd MMM';
                calendarConfig.allDateFormats.angular.date.time = 'shortTime',
                calendarConfig.allDateFormats.angular.date.datetime = 'medium',
                calendarConfig.allDateFormats.angular.title.day = 'fullDate',
                calendarConfig.allDateFormats.angular.title.week = 'Week {week} of {year}',
                calendarConfig.allDateFormats.angular.title.month = 'MMMM yyyy';

**Comment by mattlewis92** [comment]
I think if you set `moment.locale('new_locale')` (you don't need any of the moment locale files installed to do this) when changing the language it [should update](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarHourList.js#L45)

**Comment by okayawright** [comment]
Ok, but what if calendarConfig.dateFormatter is set to 'angular' and not 'moment' (what I do), manually switching the moment locale should be irrelevant (and apparently I really need the moment locale file installed to manually update the language, which is overkill in my situation.)

What about just removing your control on the "originalLocale" in the linked code, it works for both angular and moment-based date formatting. The 'refreshView' event for the day view is apparently working differently than the other views: it is only actually triggered if the moment locale has changed, for the other views the event is always processed.
