### ISSUE TITLE
 Localization and dates: 'week' 

### ISSUE THREAD

**Issue by okayawright** [mattlewis92/angular-bootstrap-calendar#379]
Hello,

I'm having difficulties to properly translate the 'week' text in the calendar, at runtime time, dynamically.
calendarConfig.allDateFormats.angular.title.week is an exception compared to the other time formats and not a proper filter but a fixed chain of characters. Same for calendarConfig.i18nStrings.weekNumber.

I mainly use angular-dynamic-locale, angular-i18n, and angular-translate for i18n and l10n purposes.

Any advice? Is it possible to change the way the week time format is handled?

**Comment by mattlewis92** [comment]
The title logic is abstracted into the `calendarTitle` service so you can do just that by overriding this method:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarTitle.js#L13

e.g.
```
calendarTitle.week = function(viewDate) {
  // custom logic here
}
```

Hope that helps 😄
