### ISSUE TITLE
locale bug when edit events

### ISSUE THREAD

**Issue by MarcelBuian** [mattlewis92/angular-bootstrap-calendar#38]
Hello. Great plugin. Just tested it.
I have integrated angular-i18n for my locale and moment.js too.
The calendar works great, in my language with my locale strings and the weekly days begins with "Monday".

But in "Edit events" tab, StartsAt and EndsAt show me something like "Wed Mar 25 2015 08:30:00 GMT+0200 (EET)". When I change date from calendar view and click on some date - this field will show me the right locale date (for my language), but when click on some buttons (when changing time, for example) the wrong date (english format) appears again.
Another bug is that when calendar-picker displays the first weekly day is "Sunday" (translated in my language, that is good), but must be "Monday" (as it in first big calendar). 

I don't know if these bugs comes from this plugin or maybe I do something wrong.

**Comment by mattlewis92** [comment]
Can you send me a screenshot of the parts that aren't being translated just so we're on the same page. Thanks.

**Comment by MarcelBuian** [comment]
![screenshot from 2015-03-23 12 52 51](https://cloud.githubusercontent.com/assets/3746903/6778501/c30a8e4a-d15b-11e4-970b-dcddf5500d39.png)
![screenshot from 2015-03-23 12 53 11](https://cloud.githubusercontent.com/assets/3746903/6778502/c30b5b18-d15b-11e4-94ae-00cbc486813a.png)
![screenshot from 2015-03-23 12 53 45](https://cloud.githubusercontent.com/assets/3746903/6778503/c30f99f8-d15b-11e4-97a5-fb0bbb783357.png)

Here some pics.
If you want, you can test online by visit this site: http://104.236.88.95/admin/calendar/events  (user and password: angajat )

**Comment by mattlewis92** [comment]
Ah OK, I thought that was the case. The datepicker there isn't actually a part of this library, it's part of the [ui-bootstrap library](https://angular-ui.github.io/bootstrap/#/datepicker).

Maybe use a different datepicker? I've used [this one](https://github.com/dalelotts/angular-bootstrap-datetimepicker) before and I think it has the i18n support you need.

**Comment by MarcelBuian** [comment]
ok, then I need to integrate other datepicker? 
Thx.

**Comment by mattlewis92** [comment]
Using another datepicker with proper i18n support should solve your problem.

**Comment by MarcelBuian** [comment]
Thank you again. Cool plugin.

**Comment by MarcelBuian** [comment]
hey, I just read that this plugin have i18n support. 
Here we can see some examples http://stackoverflow.com/questions/19671887/angularjs-angular-ui-bootstrap-changing-language-used-by-the-datepicker
Maybe in your project exists some conflicts between loading angular model?

It work's good only when I click on some date from calendar. After clicking on buttons that change the string comes back in english.
I will investigate what can be the reason, but if you can help, I will appreciate.

**Comment by MarcelBuian** [comment]
I can see this bug in your demo, too.
Notice that your "Starts at" Event is for the beginning something like "Wed Mar 25 2015 08:30:00 GMT+0200 (EET)"

After picking a date (for example 1 march) this field will be "Mar 1, 2015 8:30:00 AM"
This is good, how it must be, but after changing the hour (for example) the field will be again something like "Sun Mar 01 2015 09:30:00 GMT+0200 (EET)".

I tried to replicate this behavior without your plugin. And these strings works good. Please check this when you have some free time. Thanks.

**Comment by mattlewis92** [comment]
I can replicate the bug you are experiencing but it has nothing to do with the calendar. When I remove the calendar plugin from the demo it still occurs. It's an issue with ui-bootstrap and not with this library. Here's a codepen to demonstrate the problem with the calendar stripped out of it: http://codepen.io/anon/pen/VYgKzo

**Comment by MarcelBuian** [comment]
Just found the problem. The problem is that angular 1.3.15 is incompatible with ui-bootstrap-0.12.1

Tested with angular 1.2.16 and works fine. 
http://codepen.io/anon/pen/GgzNad

Should I use angular 1.2.16 instead of 1.3.15?

**Comment by mattlewis92** [comment]
I'm planning on dropping support for angular 1.2 in the calendar soon, you could try this fix: https://github.com/angular-ui/bootstrap/issues/2659#issuecomment-75801715

**Comment by MarcelBuian** [comment]
Good. Now looks better: http://codepen.io/anon/pen/azXBeB
Still persist a small problem: On loading page: fields doesn't have hours.

**Comment by mattlewis92** [comment]
Try this one instead, it seems to work: https://github.com/angular-ui/bootstrap/issues/2659#issuecomment-60750976

**Comment by MarcelBuian** [comment]
not really. The first fix works better. But I will try another fixes.
