### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by raghavsood33** [mattlewis92/angular-bootstrap-calendar#380]
### Bug description / Feature request:
Can I have the draggable/resizable events over a span of 4 days or a week. Currently I think it is only intra-day. Something like in the link shared below

### Link to minimally-working plunker that reproduces the issue 
http://dhtmlx.com/docs/products/dhtmlxScheduler/sample_basic.shtml

### Versions

Angular: 1.3/1.4/1.5

Calendar directive: draggable/resizable events

Browser name and version: Chrome v51 (ubuntu) / firefox 47 (ubuntu)

**Comment by mattlewis92** [comment]
There is the `calendarConfig.showTimesOnWeekView = true` option that you can use to make the week view more like the day view. The only caveat is that end times are ignored, so resizing events won't work, however dragging and dropping between times and days will.
