### ISSUE TITLE
Allow ability to pass custom data to custom cell template

### ISSUE THREAD

**Issue by wonder95** [mattlewis92/angular-bootstrap-calendar#384]
I'm posting this as a feature request, because I haven't been able to figure a way to do it with the current code, but it also could be that I just haven't figured out how to do it with the current code.

I'm using [custom cell templates](https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=custom-templates) with a [cell modifier](https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=cell-modifier), because I don't want standard calendar events; I just need the month view skeleton, and then I'll add my custom data and handle the display in a template. 

However, it appears that I can't do that in a controller, because the expression is called from the calendarHelper service, which doesn't allow for passing any data in addition to to the calendarCell object. The only way I can see around it is to use the required vm.events array, since that is available in the cellModifier. 

It could also be that I'm just not writing my code correctly. Here's what I'm trying with my controller:

```
(function() {
  angular.module('myApp')
    .controller('calendarController', function($scope, moment, calendarConfig, $http, Formio, shiftService) {

    var vm = this;

    calendarConfig.templates.calendarMonthCell = 'views/calendar/dayTemplate.html';
    calendarConfig.dateFormatter = 'moment';

    vm.events = $http.get('shifts.json').then(function(response){ return response.data});
    vm.calendarView = 'month';
    vm.viewDate = moment().startOf('month').toDate();
    var startDate = moment(this.viewDate).toISOString();
    var endDate = moment(this.viewDate).endOf('month').toISOString();

    var endpoint = 'https://nutmvrwoblsalot.form.io/shift/submission';
    var token = Formio.getToken();

    var onShifts = function(data) {
      vm.events = data;
    };

    var onError = function(error) {
      vm.error = 'There was an error.';
    };

    shiftService.getShiftsMonth(token, startDate, endDate)
      .then(onShifts, onError);

    vm.cellModifier = function(cell, shifts) {
      cell.text = 'Test Text';
      //console.log(cell);
    };

    $scope.$on('$destroy', function() {
      calendarConfig.templates.calendarMonthCell = 'mwl/calendarMonthCell.html';
    });
  });
})();
```

and here's my service:

```
(function() {
  angular
    .module('myApp')
    .service('shiftService', shiftService);

  shiftService.$inject = ['$http'];
  function shiftService($http) {
    var getShiftsMonth = function (token, startDate, endDate) {
      var config = {
        headers: {
          'x-jwt-token' : token
        },
        params: {
          /*  'date.date__gte': startDate,
           'date.date__lte': endDate */
          limit: 10
        }
      };
      // return $http.get('https://abcdefghijklmno.form.io/shift/submission', config)
      return $http.get('shifts.json')
        .then(function(response) {
           return response.data;
        },
        function(error) {
          return $q.reject(error.data);
        });
    };

    var addNameToShift = function(locationid) {
      return $http.get('/api/locations/' + locationid);
    };

    return {
      getShiftsMonth: getShiftsMonth,
      addNameToShift: addNameToShift
    };
  }
})();
```
So if it's just that my code is wrong and it is possible to pass custom data to the cellModifier, that's great, but if not, it would be nice to be able to pass custom data to the template.

Thanks.

**Comment by mattlewis92** [comment]
It should already be possible to attach additional data on the callback to the cell modifier, you can see an example of this here: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=grouping-events

Another option if you need more granular control is to create a child component and use it in your custom template e.g.

```
// custom cell component
.component('customCell', {
  controller() {
    this.$onInit = () => {
     // do something complicated like an ajax request etc with this.cell
    };
  },
  bindings: {cell: '<'},
  template: '{{ $ctrl.cell }}'
});

// inside your custom calendar cell template
<custom-cell cell="day"></custom-cell>

```

Hope that helps 😄

**Comment by wonder95** [comment]
Well, what I was referring to was being to pass additional information in to the cell modifier callback in addition to the cell object, something like .

    vm.cellModifier = function(cell, addtionalData) {
      cell.text = 'Test Text';
      //console.log(cell);
    };

but it looks like the required events[] array is the only way to get data into the cell. I moved my code around in my controller a bit and got it to work.

    var onShifts = function(data) {
      vm.events = data;
    };

    var onError = function(error) {
      vm.error = 'There was an error.';
    };

    shiftService.getShiftsMonth(token, startDate, endDate)
      .then(onShifts, onError);

    vm.cellModifier = function(cell) {
      cell.text = 'Test Text';
      cell.shifts = this.events;
    };

Thanks for the controller tip, though. I'll give that a look.
