### ISSUE TITLE
Hover title "Week" still in English when localized.

### ISSUE THREAD

**Issue by mickeychu** [mattlewis92/angular-bootstrap-calendar#385]
I use the moment localization for the calendar but this hover title "Week" is still in English, how can I manually override it  to "Vikko"? Thank you!
![screen shot 2016-07-04 at 16 28 24](https://cloud.githubusercontent.com/assets/7807777/16562108/f6a051ac-4204-11e6-96da-fc09b48c060e.png)

![screen shot 2016-07-04 at 16 37 33](https://cloud.githubusercontent.com/assets/7807777/16562420/a7c63a46-4205-11e6-9ef4-4714f77de7ab.png)

**Comment by mattlewis92** [comment]
```
calendarConfig.i18nStrings.weekNumber = 'Vikko {week}';
```

**Comment by azachar** [comment]
Would it be possible to make it work with angular-gettext, which is pretty much the standard for i18n? THX!
