### ISSUE TITLE
Calendar support only two action to manage events (edit & delete)

### ISSUE THREAD

**Issue by ysnjzl** [mattlewis92/angular-bootstrap-calendar#386]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Bug description / Feature request:
I want to add new action to manage my events. However the calendar has only two option for events (edit & delete).

I didn't find any other entry aside these two.

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by mattlewis92** [comment]
There currently isn't a way to do anything other than edit or deleting of events, I think a better API would probably be something like:
```
const events = [{
  startsAt: new Date(),
  title: 'Title',
  actions: [{
    label: '<i class="fa fa-edit"></i>',
    onClick(calendarEvent) {
      console.log('The edit icon was clicked', calendarEvent);
    }
  }];
}];
```

This would also cleanly get rid of the `edit-event-html`, `delete-event-html`, `on-edit-event-click`, `on-delete-event-click` options as well as `event.editable` and `event.deletable `

**Comment by xMrWhite** [comment]
angular2 sanitizes innterHTML so using that label property to store a template requires allot of checking and to [bypass security]( https://angular.io/docs/ts/latest/guide/security.html#!#bypass-security-apis)
