### ISSUE TITLE
Event Dots Exceed The Boundary of a Given Day

### ISSUE THREAD

**Issue by artforlife** [mattlewis92/angular-bootstrap-calendar#387]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Bug description / Feature request:

When there are many events added to a given day, they start exceeding the boundary of the Day in the calendar. It would be good to implement some kind of scroll or other way of treating this problem.

### Link to minimally-working plunker that reproduces the issue (starter template: http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview)

Just create a calendar with about 20 events added to a given day.

### Versions

Angular:

Calendar directive:

Browser name and version:

All

**Comment by mattlewis92** [comment]
This is a limitation with the original calendars markup and styling that's really hard to get around, I've spent several hours trying to implement a fix for it and got nowhere. The best thing I can recommend is setting 
```
.cal-month-day {
  height: 200px; 
}
```

Or group events by type like so: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=grouping-events
