### ISSUE TITLE
Business days

### ISSUE THREAD

**Issue by caguilarg** [mattlewis92/angular-bootstrap-calendar#388]
Sorry, 

this is not exactly one issue, I don't know how to find this information:

- can this calendar disable non-business days as weekends ??
- it is possible to set slot duration to 15min or less ??

sorry for my poor english and sorry for this non-issue comment.

Thanks,

Carlos.

**Comment by mattlewis92** [comment]
There is no way of disabling weekend days from displaying. You can set the day view to be 10 minute intervals like so: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=day-view-split
