### ISSUE TITLE
Day view doesn't support horizontal scrolling

### ISSUE THREAD

**Issue by saulojg** [mattlewis92/angular-bootstrap-calendar#389]
### Bug description / Feature request:

When creating a certain amount of events on the same day, they'll become non visible when using the day view, since this view doesn't support horizontal scrolling.

The use case would be when you need to see all activities assigned to a given group of people. On these cases it'd be usual to have several overlapping events.

### Link to minimally-working plunker that reproduces the issue 

http://plnkr.co/edit/2LMw9CECJSMdTf7ti7zR?p=preview

### Versions

Angular: Same as plunker template

Calendar directive: N/A

Browser name and version: N/A

**Comment by mattlewis92** [comment]
Ah yeah that's a limitation with the CSS of this module, I'm working on fixing it in the angular2 version of this module and when I do I'll backport it to this module as well.
