### ISSUE TITLE
Is it possible to get the displayed date range?

### ISSUE THREAD

**Issue by z3ntu** [mattlewis92/angular-bootstrap-calendar#390]
![Screenshot](https://cloud.githubusercontent.com/assets/3768500/16808109/696c7d2e-491b-11e6-9d9e-39bafbb6d94b.png)
For example in this view is it possible to get the dates 26.06. & 06.08. ?

**EDIT:** Apparently `vm.view` is used internally although I don't know if it is possible to access this.

**Comment by mattlewis92** [comment]
You can easily calculate this yourself with moment:
```
// where $scope.calendarDate is the variable you pass to the `view-date` option, and $scope.view is the variable you pass to the `view` option:
var start = moment($scope.calendarDate).startOf($scope.view).toDate();
var end = moment($scope.calendarDate).endOf($scope.view).toDate();
```

[Internally](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarHelper.js#L136) this is all the calendar does as well. Hope that helps! 😄

**Comment by z3ntu** [comment]
I don't think that's what I wanted.
Your solution returns `Fri Jul 01 2016 00:00:00 GMT+0200 (CEST)` as `start` and `Sun Jul 31 2016 23:59:59 GMT+0200 (CEST)` as `end`, which is the start and the end of the month, but not the "displayed ones" (which are those days in the previous and next month which are still shown).

**Comment by mattlewis92** [comment]
OK, try:
```
var start = moment($scope.calendarDate).startOf('month').startOf('week').toDate();
var end = moment($scope.calendarDate).endOf('month').endOf('week').toDate();
```

**Comment by z3ntu** [comment]
Works perfectly, thanks!
```
Mon Jun 27 2016 00:00:00 GMT+0200 (CEST) - Sun Jul 31 2016 23:59:59 GMT+0200 (CEST)
```
(I also changed the start of the week to monday)

**Comment by z3ntu** [comment]
I have one more question:
Is it possible to get a string from angular-translate (either possible via filter, service or directive) into the `calendarConfig.i18nStrings.weekNumber` variable? I already tried using a custom `calendarMonthCell.html` and getting a string from my controller into this view, although it seems that this is not possible (I tried `{{'WEEK' | translate}} {week}` what would be perfect, but I can't figure out a way to assign this resulting string to a variable (or directly use it with the `<span ng-bind="weekString.replace('{week}', day.date.clone().add(1, 'day').isoWeek())"></span>` line where I didn't made it because there is some problem with using all those single and double quotes, it would be something like this: `ng-bind="'{{'WEEK' | translate}} {week}'.replace(`). I hope you understand what this wall of words mean and I hope you can help me :)

**Comment by mattlewis92** [comment]
On more thought, not very easily, I've made a new ticket to track it here: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/393

**Comment by z3ntu** [comment]
Thanks!
