### ISSUE TITLE
Feature request: ability to click multiple dates and create an event that spans clicked dates

### ISSUE THREAD

**Issue by water42** [mattlewis92/angular-bootstrap-calendar#391]
I'm not sure where to start to implement this myself, basically I need the functionality to create a several week long event that does not include weekends. Do you have any suggestions on how to accomplish this, either through a pull request or otherwise?

**Comment by mattlewis92** [comment]
There's already support for doing this on the day view, it would be pretty simple to adapt it for the month view as well: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=select-range

For excluding weekends something like a `date-range-select-validate` input option could be added, whereby you pass a function which is passed a start and end date to indicate the current month cell that is moused over, and return true / false to indicate whether it can be selected.

**Comment by water42** [comment]
Thanks for the pointers. I hacked around the weekend problem by creating an array of single day events from the original event and associating them with a single event model in my backend. So I'm closing this for now but might revisit this in the future to implement the ability to click multiple dates.

**Comment by mattlewis92** [comment]
Glad you got it sorted, I'll re-open the issue as someone else requested it as well 😄
