### ISSUE TITLE
How to create a recurrent weekly event with start and end time

### ISSUE THREAD

**Issue by erickespinoza** [mattlewis92/angular-bootstrap-calendar#392]
Hi I was checking this link: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/127#issuecomment-136022090

but I don't see or how I can create an weekly recurrent event with start and end date, because I need this for university schedule manager.

 Can you help me to solve this thing?

I don't know if is something that I can fix with this:

var start = moment(vm.calendarDay).startOf(vm.calendarView);
var end = moment(vm.calendarDay).endOf(vm.calendarView);

but changed the dates with the event, dates, thanks in advice.

Erick

**Comment by mattlewis92** [comment]
Sure, I'll make an example for you and put it up on the docs site :)

**Comment by Jean-PhilippeD** [comment]
Hi, I've folloed the @mattlewis92  method in the original post, but how can I trigger the addWeeklyEvent  function ?

I've used the on-view-change-click class in the calendar directive but it seems to work only If you click on a specific date, while I would like to trigger it even if I change the view (by month or by year for example).

Moreover, it doesn't seems to be triggered at the initial loading of the calendar (or maybe just before I get the events list through http api).

What do you suggest ?

**Comment by mattlewis92** [comment]
You'd need to call it whenever you click the buttons for the day / week / year view to change the view as well as when you hydrate the initial events array. `on-view-change-click` is only called when the user clicks a date to change the view.

**Comment by Jean-PhilippeD** [comment]
and how you do that ? I didn't not found this in the doc.
I've tried to use $scope.$watchGroup(['vm.calendarView','viewDate']) but it's not triggered.

Sorry but I'm new to angular bootstrap calendar

**Comment by mattlewis92** [comment]
I will put up a full example on it on the docs site for you when I have some spare time

**Comment by Jean-PhilippeD** [comment]
Nice :) 
Thanks

**Comment by mattlewis92** [comment]
I've added an example now of how you can use the [rrule library](https://github.com/jkbrzt/rrule) to add weekly events, you can see it in action here: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/docs/examples/recurring-events/javascript.js

**Comment by Jean-PhilippeD** [comment]
how do you handle the endsAt ?

**Comment by mattlewis92** [comment]
It doesn't really make a lot of sense when doing recurring events, the best way is to instead just add a fixed duration to each generated event start e.g.
```
event.endsAt = moment(event.startsAt).add(1, 'day);
```
