### ISSUE TITLE
Better translations API

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-bootstrap-calendar#393]
Provide a better story for translating strings with angular translate etc

**Comment by z3ntu** [comment]
Quick question without looking at it very much:
How can you integrate that with angular-translate?

**Comment by mattlewis92** [comment]
Sorry I didn't have time to write any docs. There is an example test that shows how to use it here: https://github.com/mattlewis92/angular-bootstrap-calendar/commit/247f2c14ec39385993f527b1861e09413b85307a#diff-26039e1b6e6997694f04d9b660430955R188

tl;dr
```
// in a .run() block
calendarConfig.i18nStrings.weekNumber = function(translationParams) {
  return $translate.instant('KEY', {weekNumberParam: translationParams.weekNumber});
};
```

**Comment by z3ntu** [comment]
Thanks. I will try it tomorrow!

**Comment by mattlewis92** [comment]
I haven't yet cut a new release so you won't be able to try it just yet, you can fork the module and rebuild the dist files your self though if you need it right away
