### ISSUE TITLE
showTimesOnWeekView = true and displaying events that include but do not start on a date

### ISSUE THREAD

**Issue by stvnmntjy** [mattlewis92/angular-bootstrap-calendar#394]
### Bug description / Feature request:

The calendar does not show events that *do not start but include* some date in the week view. 

The plunk below clarifies this. 

It has one event that starts the previous week and continues through this week.

If you comment-out the `calendarConfig` `showTimesOnWeekView` on L6 of the `script.js` in the plunk, you will see the calendar shows the event correctly spanning the week. But with `showTimesOnWeekView = true`, the event does not show at all.

Might have something to do with https://git.io/vKVHH filtering out events whose `startsAt` does not fall in the week.

I don't have time to fully investigate. Hope that's clear enough.

How to get the event to display in "show hours" view?

For now I'll revert to the default view but would be nice if this could be possible in "show hours" view.

Thanks.

### Link to minimally-working plunker that reproduces the issue 

https://plnkr.co/edit/8hLHnxY2nFQ6IM3IOmP0?p=preview

### Versions

Angular: 1.5.6

Calendar directive: `mwl-calendar`

Browser name and version: Google Chrome 51.0.2704.103 (64-bit)

**Comment by mattlewis92** [comment]
This is by design, the week view with times is a hack that ignores the event end time, thus if it starts outside of the current week then it won't be displayed.

**Comment by pratikp91** [comment]
Hi mathewis92, can we implement it somehow without ignoring the end time?
