### ISSUE TITLE
how to set language for date??

### ISSUE THREAD

**Issue by callmesoul** [mattlewis92/angular-bootstrap-calendar#395]
how to set language for date??

**Comment by mattlewis92** [comment]
You need to add the [locale files](https://www.npmjs.com/package/angular-i18n) for your language and then everything should just work.

**Comment by callmesoul** [comment]
I  add the locale files  but not:
`<script src="bower_components/moment/locale/zh-cn.js"></script>
 <script>moment.locale('zh-cn'); </script>`

**Comment by mattlewis92** [comment]
Ah right, if you're using moment then you need to use moments date formatter:
```
calendarConfig.dateFormatter = 'moment';
```

**Comment by callmesoul** [comment]
It still doesn't work ( ▼-▼ )

**Comment by mattlewis92** [comment]
Works for me: http://plnkr.co/edit/nDXuFEpIVeU7CGG7uRKN?p=preview (I included the locale file, and called `calendarConfig.dateFormatter = 'moment';`)

**Comment by callmesoul** [comment]
I tell you exactly, but I do not know why not. There may be some mistake, I'll look for mistakes. Thank you in advance. My English is to use software translation, HA HA

**Comment by callmesoul** [comment]
I tell you exactly, but I do not know why not. There may be some mistake, I'll look for mistakes. Thank you in advance. My English is to use software translation, HA HA

**Comment by callmesoul** [comment]
ti's ok. thank you so much! i add moment.min.js again.only add moment.js is ok

**Comment by mattlewis92** [comment]
Glad you got it sorted 😄
