### ISSUE TITLE
Event saved at 23:00 onwards appears on the next day Cell

### ISSUE THREAD

**Issue by fqaiser** [mattlewis92/angular-bootstrap-calendar#396]
Hi there, 

Not sure if its actually an issue or something to do with my lack of JS Date format understanding. I have encountered this problem, when I save an event on the calendar anytime on or after 23:00, it appears on the next day cell. 
For Example, startsAt stores the following value 2016-07-28T23:00:00.000Z, but the event dot appears on 29th. 

Thanks

**Comment by mattlewis92** [comment]
I'm guessing you're in GMT+1 timezone as well? `2016-07-28T23:00:00.000Z` in GMT+1 is actually midnight at 29th July so it's displaying on the correct date as the calendar automatically respects local timezones. Try something like `new Date('2016-07-28T23:00:00+01:00')` which includes the timezone in the  string.

**Comment by fqaiser** [comment]
Yes that's correct. It was not an issue with the calendar,  in fact it was caused by our Sql wrapper not managing the dates properly, so this issue has been sorted now.

**Comment by fqaiser** [comment]
Yes that's correct. It was not an issue with the calendar,  in fact it was caused by our Sql wrapper not managing the dates properly, so this issue has been sorted now.

**Comment by mattlewis92** [comment]
Glad you got it sorted 😄
