### ISSUE TITLE
Adding Total Time to Events Array Object

### ISSUE THREAD

**Issue by artforlife** [mattlewis92/angular-bootstrap-calendar#397]
Having been playing with this calendar for a couple of months, it seems to me that it may be useful to allow for storing the total time of an event and displaying it when needed.

Granted, we do have startDate and endDate, but there is currently no way to display the total time an event took on the calendar. Instead of introducing a Total Time field, one could probably do a boolean flag that would let Total Time (not) be displayed.

**Comment by mattlewis92** [comment]
You can implement this yourself with this service: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarEventTitle.js
```
.run(function(moment, calendarEventTitle) {
  calendarEventTitle.monthView = function(event) {
    return event.title + ' (' + moment(event.end).diff(event.start, 'minutes') + ' minutes)';
  }
});
```
Hope that helps! 😄
