### ISSUE TITLE
Cannot read property 'starts_at' of null

### ISSUE THREAD

**Issue by kamaribedwarddev** [mattlewis92/angular-bootstrap-calendar#40]
I keep getting the error 'Cannot read property 'starts_at' of null' when i try to consume the event data from an asp.net web api 2 web service. The strange thing is that i have a 'starts_at' property in a array of json objects that are being returned.

**Comment by mattlewis92** [comment]
What is the value that you are passing to calendar-events?

**Comment by kamaribedwarddev** [comment]
Thanks for your reply

This is a sample of my code.

vm.loadSessions = function ()
 {
            dataservice.getSessions().then(function (data) {
                console.log('Calendar Data: ' + data[0].starts_at);//Calendar Data: 2014-01-20T09:00:00
                vm.events = data;
                console.log('Calendar Data after: ' + vm.events[0].starts_at); //Calendar Data: 2014-01-20T09:00:00
            });
        }
        vm.loadSessions();

**Comment by mattlewis92** [comment]
That only checks if the first event has a starts_at field, every item in the array of events needs to have that field set.

**Comment by kamaribedwarddev** [comment]
I know. Based on the result that i got from the server, all of the fields are set.
I'll do further checks on the other records in the array.

Thanks.

**Comment by mattlewis92** [comment]
Just console.log the entire data variable and you can inspect each one in the console. From the error you were getting one of the items in the array is null.

**Comment by kamaribedwarddev** [comment]
Thats so right, after checking i realized that some of the objects are actually null. Therefore, i'll have to filter out all null objects. 

Thanks man.

**Comment by mattlewis92** [comment]
NP
