### ISSUE TITLE
How to customize day cell to show some info about the tasks

### ISSUE THREAD

**Issue by sternh** [mattlewis92/angular-bootstrap-calendar#400]
hi, Matt and other folks. Nice work, thanks for sharing.

I 'm trying to customize day cell of month view to show total times required by all tasks of the day.  but has some problems:

Firstly I use "custom-template-urls="{calendarMonthCell: 'customMonthCell.html'}"" to customize cell display,but cannot access day object to insert some data. then I try to use "  cell-modifier="vm.cellModifier(calendarCell)"“ to insert data into cell object, looks like cell object has same properties as day object. but statements in customMonthCell.html still cannot display the desired data.
which means the cell object maybe not the day object.

Please give me some suggestions, a example would even be better.
Many Thanks.

Best regards.
Stern

**Comment by mattlewis92** [comment]
Everything you're doing seems correct, you can see a full e2e example of what you're trying to accomplish here: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=grouping-events

**Comment by sternh** [comment]
Hi, Matt, thanks for the advice, it's worked! 

Have a nice day!
