### ISSUE TITLE
How to set the month view to a specific month of choice?

### ISSUE THREAD

**Issue by anushree-jain** [mattlewis92/angular-bootstrap-calendar#401]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by mattlewis92** [comment]
Set the value you pass to the `view-date` to a date in that month.
