### ISSUE TITLE
Allow the event colors to be specified on the event object

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-bootstrap-calendar#402]

**Comment by saulojg** [comment]
Just a (pretty obvious) comment, this enhancement might be related to the `incrementsBadgeTotal` attribute.

**Comment by Gamester2097** [comment]
I understand that you want to add the possibility to define the event's color customly instead of just having to choose one of the provided types? Is that correct, because that would be super awesome! :+1:

**Comment by mattlewis92** [comment]
Yup that's right, I've already implemented it in the angular2 version so it makes sense to backport it.

**Comment by Gamester2097** [comment]
Oh man, that's super awesome! Just this morning I was thinking about writing you a feature request about exactly that function woohoo! :+1: :+1:

**Comment by artforlife** [comment]
Big props for making this happen! If I update through bower or npm will this change be available?

**Comment by mattlewis92** [comment]
Yup it's in 0.22: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/CHANGELOG.md#0220-2016-07-27

**Comment by artforlife** [comment]
Excellent! Also, I am just curious about the "src" directory within the project. What does it contain and for what purpose? I seem to only be including the files from "dist" and have things working as expected.
Lastly, is it realistic to have dynamic change of colors for calendar events? That is, can I somehow set the colors dynamically AFTER populating the calendar with events? Should I be rewriting the entire JSON to the calendar or just cherry-picking a certain entry from it? Would it update without refresh?

**Comment by mattlewis92** [comment]
src contains the source code, dist contains the built bundled files i.e. I use webpack to bundle all the files together, otherwise you wouldn't be able to use the files in the browser as require doesn't exist.

Changing the colors after creating the events should work, in fact you can see it in the demo (scroll to the event editor at the end and change the primary color of an event to see it update: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink)

**Comment by artforlife** [comment]
I have another related question. If you were to try changing events in the calendar dynamically, would you just address the `vm.events` array and change the appropriate entry? I am wondering about the most efficient way of doing it.

**Comment by mattlewis92** [comment]
Yup, the events array is deep watched by angular so any changes you make to it will be automatically reflected in the calendar.

**Comment by luigipereira** [comment]
When I make a change in an event, the calendar makes the change, but when when I go back to edit the same event, the data is old. How can I update data from a certain event and see them updated on the form?

**Comment by mattlewis92** [comment]
I can't reproduce this, can you make a plunker? (You can generate one from any of the demos)

**Comment by luigipereira** [comment]
Hello Matt. I already solve the problem. It's already working. Thanks.
