### ISSUE TITLE
Localization and dates: time in day view (2)

### ISSUE THREAD

**Issue by okayawright** [mattlewis92/angular-bootstrap-calendar#403]
It's a follow-up to issue #378

I think it is safe and useful to drop the check on the moment locale in [mwlCalendarHourList.js](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarHourList.js#L35) and always call updateDays() for the reasons stated in the last comment of the linked issue.

**Comment by mattlewis92** [comment]
This is no longer an issue in master now the date formatting is done via a filter in the template
