### ISSUE TITLE
Unable to perform several customization

### ISSUE THREAD

**Issue by soyiatgit** [mattlewis92/angular-bootstrap-calendar#406]
Trying to customize the view of calendar. Unable to change as simple as height and width of calendar. It takes whole of my page. Tried applying css width to few divs on DOM, it works but height still do not work. Can't a general object be added to directive which would define its layout like:

{
height:
width:
color:
}
It was easier in original code to change tmpls directly. Seems a bit harder here. Also will it be possible to show events in month view similar to how they are shown in week view with strips. Kindly guide the way to customize... I have a question for the same here. would appreciate  an answer..
http://stackoverflow.com/questions/38636447/how-to-customize-angular-based-bootstrap-event-calender

**Comment by mattlewis92** [comment]
Wrapping the `mwl-calendar` component in a simple `<div style="max-height: 200px; overflow: scroll">` allowed me to easily change the height of it: http://plnkr.co/edit/E5vArN9FKysU9bXGd1YB?p=preview

For custom templates there is an example on how to change them here: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=custom-templates

The source templates are available here: https://github.com/mattlewis92/angular-bootstrap-calendar/tree/master/src/templates

**Comment by soyiatgit** [comment]
Thanks Matt,
 I  Tried the suggested approach and was able to customize my year view. However, now on click the month in year view the slide window do not appear. I wanted all the months in a straight row, instead of default view. So I removed the ng-repeat ="rowOffset......", and got the desired view. I assume it has nothing to do with slider. The ng-click of div is still intact. Below is my code, can u have a look and suggest what might have caused slider to disappear.

<script id="customYearCell.html" type="text/ng-template">
	<div class="cal-year-box cal-year-box-modified">
	<div class="row">
		<div ng-repeat="rowOffset in [0] track by rowOffset" class="row cal-before-eventlist">
		  <div class="mymonthInYear cal-cell {{ day.cssClass }}"
			ng-repeat="month in vm.view track by $index"
			ng-init="monthIndex = vm.view.indexOf(month)"
			ng-click="vm.monthClicked(month, false, $event)"
			ng-class="{pointer: month.events.length > 0, 'cal-day-today': month.isToday}"
			mwl-droppable
			on-drop="vm.handleEventDrop(dropData.event, month.date)">

			<span data-cal-date
			  ng-click="vm.calendarCtrl.dateClicked(month.date)"
			  ng-bind="month.label">
			</span>

			<small
			  class="cal-events-num badge badge-important pull-left"
			  ng-show="month.badgeTotal > 0"
			  ng-bind="month.badgeTotal">
			</small>

			<div
			  class="cal-day-tick"
			  ng-show="monthIndex === vm.openMonthIndex && vm.view[vm.openMonthIndex].events.length > 0 && !vm.slideBoxDisabled">
			  <i class="glyphicon glyphicon-chevron-up"></i>
			  <i class="fa fa-chevron-up"></i>
			</div>

		  </div>
		</div>
			<div class=" row calendar-year-slide-box-modified">
			<mwl-calendar-slide-box
			  is-open="vm.openRowIndex === $index && vm.view[vm.openMonthIndex].events.length > 0 && !vm.slideBoxDisabled"
			  events="vm.view[vm.openMonthIndex].events"
			  on-event-click="vm.onEventClick"
			  edit-event-html="vm.editEventHtml"
			  on-edit-event-click="vm.onEditEventClick"
			  delete-event-html="vm.deleteEventHtml"
			  on-delete-event-click="vm.onDeleteEventClick"
			  cell="vm.view[vm.openMonthIndex]">
			</mwl-calendar-slide-box>
			</div>
		</div>
	</div>
	</script>

**Comment by mattlewis92** [comment]
I think it's because `openRowIndex` isn't set, try removing `vm.openRowIndex === $index` from the `is-open` logic on the slidebox

**Comment by soyiatgit** [comment]
Great..that works, but how did it get affect?

**Comment by soyiatgit** [comment]
Is its logic based on number of rows created or something

**Comment by mattlewis92** [comment]
Yup, as you've removed the rows it's no longer relevant: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarYear.js#L47

**Comment by soyiatgit** [comment]
Okay..will it be safe to assume that if I customise my views for single row (month views too), removing this condition will suffice ?

**Comment by mattlewis92** [comment]
Yeah probably

**Comment by soyiatgit** [comment]
Great...thanx for the guidance..and BTW great job !!
