### ISSUE TITLE
Allow getting date range of current display

### ISSUE THREAD

**Issue by yitzchokneuhaus1** [mattlewis92/angular-bootstrap-calendar#407]
It would be nice if we can have an even triggered upon changing the views date-range, and getting the start and End date of the current view (for loading async events from the server between date ranges)

**Comment by mattlewis92** [comment]
As you have full control over when the date and view is changed you can easily implement this yourself:
```
var start = moment(vm.viewDate).startOf(vm.view).toDate();
var end = moment(vm.viewDate).endOf(vm.view).toDate();
```

**Comment by yitzchokneuhaus1** [comment]
This will not return the full preview range. only the dates from the beginning of the month till the end. not from the first date of the preview till the last day of the preview.
![2016-08-01_1510](https://cloud.githubusercontent.com/assets/3825762/17305773/2abad6e6-57fa-11e6-8891-15b9a84a638a.png)

**Comment by mattlewis92** [comment]
```
var start = moment(vm.viewDate).startOf(vm.view).startOf('week').toDate();
var end = moment(vm.viewDate).endOf(vm.view).endOf('week').toDate();
```
