### ISSUE TITLE
Resize across weeks or days in month view

### ISSUE THREAD

**Issue by arunrajn** [mattlewis92/angular-bootstrap-calendar#408]
Thanks for this great calendar.  Is there a possibility to resize an event to extend beyond a week in the week view or resize the event in month view. I was looking through the documents and previous issues, but haven't been able to find a solution.

Link to minimally-working plunker that reproduces the issue http://plnkr.co/edit/Lwf9JN7IQ8Zl4y3Ui7HU?p=preview

### Versions

Angular: 1.5.8

Calendar directive: 0.22

Browser name and version: Chrome 51

**Comment by mattlewis92** [comment]
This isn't something supported by this module, mainly because I have no idea how the UX would even work to implement this.
