### ISSUE TITLE
Can we customize Silde box?

### ISSUE THREAD

**Issue by SudheerDotNetDev** [mattlewis92/angular-bootstrap-calendar#409]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by mattlewis92** [comment]
Yup you can override the [slidebox template](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarSlideBox.html), here's an example of how to: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=custom-templates
