### ISSUE TITLE
Time column visiblity in day-view

### ISSUE THREAD

**Issue by Gamester2097** [mattlewis92/angular-bootstrap-calendar#410]
Hi Matt,

Is it somehow possible to make the time column of the day-view invisible? I know that doesn't make much sense in a calendar's day-view but I would need it anyway...

View and column I mean:
[http://i.imgur.com/2Wzl8Zx.png]

By the way, you're doing a great job on this component! I really appreciate your work.

Best regards
Markus

**Comment by mattlewis92** [comment]
You can do this with pure CSS:
```
.cal-day-box .cal-day-hour-part .cal-day-hour-part-time {
  display: none;
}
.cal-day-box .day-highlight {
  margin-left: -60px;
}
```

Hope that helps! 😄

**Comment by Gamester2097** [comment]
Awesome! Thanks :+1:
