### ISSUE TITLE
How to adjust the height of the cell in month view?

### ISSUE THREAD

**Issue by hualongsheng** [mattlewis92/angular-bootstrap-calendar#411]
I am using angular-bootstrap-calendar now, I want to know how to adjust the height of the cell.

**Comment by mattlewis92** [comment]
As the issue template says, this tracker isn't for support requests. 

You can change the height of the cell with css:
```
.cal-month-day {
  height: 200px;
}
```

**Comment by hualongsheng** [comment]
It works, thanks.

**Comment by hualongsheng** [comment]
Hi, @mattlewis92 .
Sorry, I didn't make my question clear.
Here is the problem. Check this [http://plnkr.co/edit/K7VdXPTXA64rpzjTu4KD?p=preview](url)
You can see the above method only makes the cell height to be about of the row.
I want to adjust overall height of every row, not just the cell.

**Comment by mattlewis92** [comment]
If you inspect element on the month cell you will see the CSS class that is causing this which you can then override in your styles
<img width="1045" alt="screen shot 2016-08-03 at 12 56 38" src="https://cloud.githubusercontent.com/assets/6425649/17364717/c023a660-5979-11e6-827d-26c4234b45db.png">

**Comment by hualongsheng** [comment]
Thanks, it works.
