### ISSUE TITLE
On month view how can I  get day clicked?

### ISSUE THREAD

**Issue by SudheerDotNetDev** [mattlewis92/angular-bootstrap-calendar#412]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by SudheerDotNetDev** [comment]
vm.viewdate is not change when we change from one to anthore day in month view.

**Comment by mattlewis92** [comment]
As the issue template says the issue tracker is only for bug reports / feature requests, please use other channels for getting support. 

There is an example of getting the clicked day on the month view here: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=timespan-click
