### ISSUE TITLE
$apply already in progress when calling functions from within on-event-click handler

### ISSUE THREAD

**Issue by mcshaz** [mattlewis92/angular-bootstrap-calendar#413]
### Bug description:
$apply already in progress errors are generated when some functions are called from within the method bound to the on-event-click event handler. This error can be reproduced by calling the window.alert method, which is easily worked around, but is intermittently causing the same issue when I call $location.path within the same method (harder to repro in a plunker).

I am a beginner in angular, but would using $applyAsync on every instance $apply is currently being used help the problem?

### Version - 0.22.0

Angular: 1.5.7

Calendar directive: on-event-click

Browser name and version: Firefox 48.0

_A fantastic piece of software BTW_ - thank you

**Comment by mattlewis92** [comment]
Thanks for the detailed bug report! I was only able to reproduce it on FF and no other browsers, doing some digging I found a [similar issue](https://github.com/angular/angular.js/issues/10083) reported on the angular framework itself, and the resolution was that it was actually a bug with firefox.
