### ISSUE TITLE
All day events are appear on every day in the day view

### ISSUE THREAD

**Issue by quang-nguyen** [mattlewis92/angular-bootstrap-calendar#414]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Bug description / Feature request:
All day events are display incorrectly. In the day view, it list all "all days events" even the all day events are not in the same day of the current day

### Versions

Angular: 1.5.6

Calendar directive: v0.22.0

Browser name and version: all browser

**Comment by mattlewis92** [comment]
Sorry I have no idea what your issue is, please provide a plunker which demonstrates your issue. Thanks!

**Comment by quang-nguyen** [comment]
Please take a look at this plunker: http://plnkr.co/edit/BL1q4QybPOrS6K40oLmd
There are 2 events on the calendar. One is allday event (August 9) , and the other is not.
In the day view, when I navigate to different day like August 10, the "allday event (August 9)" is still appear on August 10. Am I doing something wrong?

**Comment by mattlewis92** [comment]
Ah yeah that does look like a bug, thanks for the plunker, I'll get that fixed up in the next version!

**Comment by quang-nguyen** [comment]
Thank you! 
Btw, this plugin works really well. I really appreciate your work.
