### ISSUE TITLE
Support for unavailable hours in Week and Day view.

### ISSUE THREAD

**Issue by Sh1d0w** [mattlewis92/angular-bootstrap-calendar#418]
### Feature request:

@mattlewis92 is it possible to create callback function for rendering Week and Day view cells, just like the month and year cells?

The case is the following: Lets say you are using the calendar directive to allow customers to book given time ranges for visitations. But some time intervals are not available for visitors and you need a way to tell the calendar to mark them as unavailable by applying a css class for example.

For this to work I assume you should pass the configured time interval (e.g. 15, 30, 60 min etc) to a callback just before rendering the cell.

This feature will be useful for many users. I wonder if you tried to implement this before? Do you see any problems with the possible implementation and the idea?

Kind regards.

**Comment by mattlewis92** [comment]
I can see the value in this and it's pretty trivial to add 😄
