### ISSUE TITLE
Week View Events sized to time span

### ISSUE THREAD

**Issue by matthewtrefz** [mattlewis92/angular-bootstrap-calendar#419]
Events expand to time span in the Week view using showTimesOnWeekView.

Angular: v1.5.5
Calendar directive: v0.22.0
Browser name and version: Chrome v52.0.2743.116

When I set the showTimesOnWeekView to true, the end time for event does not seem to change the height of the event. Is there a setting that I have over looked?

**Comment by mattlewis92** [comment]
This is a known limitation (hence why its not the default), as per the docs:
```
calendarConfig.showTimesOnWeekView = true; //Make the week view more like the day view, with the caveat that event end times are ignored.
```
