### ISSUE TITLE
unable to disable drilldown

### ISSUE THREAD

**Issue by simpixelated** [mattlewis92/angular-bootstrap-calendar#42]
This may be way out of scope for your project, but is there any way to disable the drillDown function for a specific date? For example, I want to show a month view where certain days are disabled. I can write my own calendar-timespan-click function to do this, but it gets preceded by the drillDown function when the user clicks on the day number.

I can work on a pull request for this; would you be more likely to accept one where the drillDown can be disabled as an attribute on the directive or by having the drillDown function run the timespan click first? (which could return false/stop propagation right?)

**Comment by mattlewis92** [comment]
Having the drilldown run the timespan click function first would be better I think.

**Comment by ptrckc** [comment]
+1

**Comment by mattlewis92** [comment]
I've merged your PR so I guess this can be closed now?
