### ISSUE TITLE
How to overrite calendar directive?

### ISSUE THREAD

**Issue by SudheerDotNetDev** [mattlewis92/angular-bootstrap-calendar#420]
When I am impliment my own directive its give following error:

angular.js:13920 Error: [$compile:multidir] Multiple directives [mwlCalendarWeek (module: mwl.calendar), mwlCalendarWeek (module: mwl.calendar.docs)] asking for new/isolated scope on: <mwl-calendar-week events="vm.events" view-date="vm.viewDate" on-event-click="vm.onEventClick" on-event-times-changed="vm.onEventTimesChanged" day-view-start="vm.dayViewStart" day-view-end="vm.dayViewEnd" day-view-split="vm.dayViewSplit" day-view-event-chunk-size="vm.dayViewEventChunkSize" on-timespan-click="vm.onTimespanClick" on-date-range-select="vm.onDateRangeSelect" custom-template-urls="vm.customTemplateUrls" ng-switch-when="week">

Link to error:
https://docs.angularjs.org/error/$compile/multidir?p0=mwlCalendarWeek&p1=%20(module:%20mwl.calendar)&p2=mwlCalendarWeek&p3=%20(module:%20mwl.calendar.docs)&p4=new%2Fisolated%20scope&p5=%3Cmwl-calendar-week%20events%3D%22vm.events%22%20view-date%3D%22vm.viewDate%22%20on-event-click%3D%22vm.onEventClick%22%20on-event-times-changed%3D%22vm.onEventTimesChanged%22%20day-view-start%3D%22vm.dayViewStart%22%20day-view-end%3D%22vm.dayViewEnd%22%20day-view-split%3D%22vm.dayViewSplit%22%20day-view-event-chunk-size%3D%22vm.dayViewEventChunkSize%22%20on-timespan-click%3D%22vm.onTimespanClick%22%20on-date-range-select%3D%22vm.onDateRangeSelect%22%20custom-template-urls%3D%22vm.customTemplateUrls%22%20ng-switch-when%3D%22week%22%3E

The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by mattlewis92** [comment]
Sounds like you have 2 directives with the same name (`mwlCalendarWeek`) maybe? Please use stackoverflow for support questions
