### ISSUE TITLE
How can I add start hour next to the title in WEEK VIEW?

### ISSUE THREAD

**Issue by mickeychu** [mattlewis92/angular-bootstrap-calendar#421]
How can I add start hour next to the title in WEEK VIEW?

Many thanks!

**Comment by mattlewis92** [comment]
You need to override this function:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarEventTitle.js#L22

Something like:
```
.run((calendarEventTitle, moment) => {
  calendarEventTitle.weekView = event => `${moment(event.startsAt).format('hh:mm')} event.title`;
});
```
