### ISSUE TITLE
'Years' CSS problem with Ionic framework

### ISSUE THREAD

**Issue by hofman-p** [mattlewis92/angular-bootstrap-calendar#423]
### Bug description:
Hi !

I use your lib and Ionic Framework.
I've got a problem with Years design:

![Image of bug with calendar and Ionic](http://puu.sh/qBhzX/673bd4a4d7.png)

I saw in your documentation that there is a cell CSS customization, but I only see "cell.inMonth", there is no "inYear" in cells.

Do you have an idea on how to resolve this ? Or maybe if I can customize this part of the calendar by myself ?

Here is my directive, if needed:

```
<mwl-calendar view="calendar.typeView"
                      view-date="calendar.date"
                      events="calendar.events"
                      view-title="calendar.title"
                      cell-modifier="calendar.cellEdit(calendarCell)"
                      on-event-click="eventClicked(calendarEvent)"
                      on-event-times-changed="calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
                      cell-is-open="calendar.cellOpen"
                      day-view-start="00:00"
                      day-view-end="23:59"
                      day-view-split="30">
        </mwl-calendar>
```

### Link to minimally-working plunker that reproduces the issue:

Unfortunately I don't know how to use plnkr with Ionic...

### Versions

Angular: 1.4.3

Calendar directive: 0.23.0

Browser name and version: Google Chrome, v52.0.2743.116 m

Thank you !

**Comment by mattlewis92** [comment]
I think this is because this module relies on bootstraps CSS which isn't part of ionic. I would inspect element on the calendar on the demo and copy across any year view styles that are applied to the year view by bootstrap. 

Alternatively use a [custom template](https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=custom-templates) for the year view.
