### ISSUE TITLE
Bug with cell modifier function for week view

### ISSUE THREAD

**Issue by Sh1d0w** [mattlewis92/angular-bootstrap-calendar#424]
### Bug description

This ticket is regarding a feature implemented a few days ago #418 .

The problem is that in the week view, the slots passed to the function are only for the first day of the week and the rest are not. This way the calendar week view could not be properly painted as not all days/slots are passed to the callback and so the callback function can not apply correct CSS classes to the not available cells.

I guess this is because of the implementation of the current row/col system that is used in the week view? I guess each time slot requires its own cell in order that to work properly.

### Versions
Angular: 1.4.9
Calendar directive: 0.23.0

Browser name and version:
Every browser

**Comment by mattlewis92** [comment]
Ah I hadn't considered the week view, it should be relatively easy to fix this with a bit of refactoring.
