### ISSUE TITLE
Call event in custom template

### ISSUE THREAD

**Issue by rodrigopereeira** [mattlewis92/angular-bootstrap-calendar#425]
how to call an custom event in a custom template?

`<div mwl-droppable on-event-click="eventClicked()" class="cal-month-day {{ day.cssClass }}" ng-class="{
    'cal-day-outmonth': !day.inMonth,
    'cal-day-inmonth': day.inMonth,
    'cal-day-weekend': day.isWeekend,
    'cal-day-past': day.isPast,
    'cal-day-today': day.isToday,
    'cal-day-future': day.isFuture,
    'cal-day-selected': dateRangeSelect && dateRangeSelect.startDate <= day.date && day.date <= dateRangeSelect.endDate
    }">
    <span class="pull-right " data-cal-date ng-click="dateClicked(day.date)" ng-bind="day.label">
    </span>
    <small ng-click="customEvent()" style="position: absolute; top: 10px; left: 5px">
    <i   class="fa fa-calendar-plus-o fa-2x " aria-hidden="true"></i>
    </small>
    <small style="position: absolute; bottom: 5px; left: 5px "
        class="badge badge-important pull-left "
        ng-show="day.badgeTotal> 0" ng-bind="day.badgeTotal">
    </small>
</div>`

**Comment by mattlewis92** [comment]
You can use the `template-scope` attribute to expose your parents controller scope to the template: https://github.com/mattlewis92/angular-bootstrap-calendar/commit/c84e9ab
