### ISSUE TITLE
Open Month SlideBox Indexes Not Updated on Month Change

### ISSUE THREAD

**Issue by ptrckc** [mattlewis92/angular-bootstrap-calendar#426]
To reproduce, follow these steps:

See: http://plnkr.co/edit/p7NprlUw3AdUTe0C0Blm?p=preview

- Aug. 19, 2016 will be selected by default and the slide box open to the date.
- Click "Previous" to go back 1 month to July.
- Jul. 19, 2016 should now be selected. However, the slide box remains positioned at the row/day index of Aug. 19 (now Jul. 15) instead of refreshing to select the new view date of Jul. 19.

On line 23 of MwlCalendarMonthCtrl, removing " && vm.openRowIndex === null" on the if check should take care of fixing this issue.

**Comment by mattlewis92** [comment]
Thanks for the detailed repro, I think the best solution here is to change the behaviour of the slidebox to match the angular2 implementation of this module, whereby the slidebox will only open when the cell date === the `view-date` and `cell-is-open` is true
