### ISSUE TITLE
Length of events doesn't correspond the end time on week view with time grid

### ISSUE THREAD

**Issue by mjromper** [mattlewis92/angular-bootstrap-calendar#427]
The issue is on the week view and calendarConfig.showTimesOnWeekView set to TRUE. The length (height) of the events doesn't extend to the end time. It seems that all events are 30 minutes long.   

Plnkr here:
http://plnkr.co/edit/NTqtn2CvXhp8cyyQVNo8?p=preview

### Versions

Angular: 1.5.8

Calendar directive: latest

Browser name and version: all browsers

**Comment by mattlewis92** [comment]
This is a known caveat (hence why it's not the default behaviour).

**Comment by mjromper** [comment]
Sorry, didn't read it. Thanks!

It's a pity though

**Comment by Jean-PhilippeD** [comment]
Do you plan to add the feature ?

**Comment by mattlewis92** [comment]
Nope, as it's quite hard to implement and doesn't scale well if you have loads of events at the same time e.g 100 events that overlap, would be really hard to display in a user friendly way.

**Comment by EvilBMP** [comment]
@mattlewis92 I don't understand your argument, why scaling is still an issue here. First scaling an event horizontally correctly has nothing to do with multiple events starting at the same time. If there are no overlapping events, the event should scale horizontal correctly. And if there are multiple events, then stack them - if it looks "ugly" that's not your problem. If I have 20 events stacked in Google Calendar it's looking ugly too.

**Comment by mjromper** [comment]
@EvilBMP why don't you try a PR? :-) I'd love to have this feature too.
