### ISSUE TITLE
angular-bootstrap-calendar doesn't show GUI on hibrid app

### ISSUE THREAD

**Issue by datpt154** [mattlewis92/angular-bootstrap-calendar#428]
I'm building a project with Ionic framework for web browser, android and Ios.

Before i add angular-bootstrap-calendar to system. I called
**angular.module('mwl.calendar.docs', ['ionic'])** => it worked for web browser, android and Ios 

But when I add angular-bootstrap-calendar to system as below
**angular.module('mwl.calendar.docs', ['ionic', 'mwl.calendar', 'ngAnimate', 'ui.bootstrap', 'colorpicker.module'])**

then: it work on web brower (GUI is showed), but doesn't work on Hybird app (android, Ios). 
How can I make it work or any solution to workaround?

Framework: Ionic 2.0.0

**Comment by mattlewis92** [comment]
I have no idea sorry, debug the device and check the console output for any errors. If you're using ionic 2 then this module won't work for it as it's for angular 1 and ionic 2 users angular2 which is a completely different framework.

**Comment by datpt154** [comment]
Actually Ionic 2 uses angular1. And I found out the different between error and no error is "mwl.calendar" mudule.
I don't know why if I add, I could not work on android and Ios

**Comment by mattlewis92** [comment]
Ionic 2 defo uses angular2: https://github.com/driftyco/ionic/blob/master/package.json#L30

**Comment by datpt154** [comment]
http://ionicframework.com/docs/overview/

Default, Ionic2 uses angularJs. But you can change it by update angular version

**Comment by mattlewis92** [comment]
Those are the ionic 1 docs, ionic 2 docs are here: http://ionicframework.com/docs/v2/getting-started/migration/
```
Ionic 2 is built on top of Angular 2, which is a complete rewrite of the original framework.
```

**Comment by datpt154** [comment]
Sorry for that inconvenience. Actually i'm working on Ionic 1.3.3, and I have found a solution to work it, just ordered libraries again. It seems Android is stricter than Web browser

E:\dev\demo>ionic info
Your system information:
You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.5.0

**Comment by mattlewis92** [comment]
Glad you got it sorted 😄
