### ISSUE TITLE
angular-bootstrap-calendar doens't auto scale on mobile

### ISSUE THREAD

**Issue by datpt154** [mattlewis92/angular-bootstrap-calendar#431]
angular-bootstrap-calendar fit well on web browser, but on Mobile it doesn't scale or fit well. 

Here is picture that i capture on my phone:
https://i.gyazo.com/a4e5e29142d4f372d90057c972c6d807.png

as you see:
- the side of each cell on calendar is not good-looking
- last row for 28,29,30.. was overlap

Any solution to make it fit better? Thank you.

**Comment by mattlewis92** [comment]
This module isn't really designed to work on mobile, I'd recommend using a dedicated module for this such as: https://github.com/twinssbc/Ionic-Calendar
