### ISSUE TITLE
Choose the events from a calendar by checkboxes

### ISSUE THREAD

**Issue by soyiatgit** [mattlewis92/angular-bootstrap-calendar#432]
To provide a monthly-view having check-boxes on each date. User should select multiple check-boxes and the events on those dates should be available in an array (so that could be used in another calendar).

I tried to achieve the above functionality: 

I started with editing `calendarMonthCell.html ` and placed a check-box span next to the `<small>` tag for event number badge. This displayed the checkbox in the month view. Next I wanted checkbox to be displayed only when required. I added an ng-if condition to template as:
`<span ng-if=\"vm.enableEventSelection\"><input type = \"checkbox\" style=\"margin:2px\"/></span>`

Now the issue is binding this ng-if condition. I have added one attribute to the calendar directive as follows:

<mwl-calendar
				events="gcc.events"
				view="gcc.calendarView"
				view-title="gcc.calendarTitle"
				view-date="gcc.viewDate"
				on-event-click="gcc.eventClicked(calendarEvent)"
				on-event-times-changed="gcc.eventTimesChanged(calendarEvent); calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
				cell-is-open="gcc.isCellOpen"
				day-view-start="06:00"
				day-view-end="22:59"
				day-view-split="30"
				enable-event-selection = "gcc.enableEventSelection"> 
		</mwl-calendar>

After this I binded it to the isolated directive scope with  "=" prefix as:

			enableEventSelection: '='

When this didn't work I tried binding this scope property to `mwlCalendarMonth` directive too. I have also modified ./calendar.tpl (14) and added this additional attribute there too as:

`enable-event-selection=\"vm.enableEventSelection\"\n`

But nothing of this worked. Can you please suggest what is the problem above and what should be the correct way of binding a new attribute from main directive i.e. <mwl-calendar> so that it can be used (in a similar way as for example `cell-is-open` is used)

**Comment by soyiatgit** [comment]
related question here `http://stackoverflow.com/questions/39107384/how-to-fetch-the-events-out-of-angular-bootstrap-calendar-on-user-interaction`

**Comment by mattlewis92** [comment]
The mwl-calendar directive wraps the month view directive, so you need to add it to both directives and pass it through in the template here: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendar.html

Or instead of forking the calendar just use the `template-scope` option to pass in your parent controller to the template: https://github.com/mattlewis92/angular-bootstrap-calendar#template-scope

**Comment by soyiatgit** [comment]
Using the approach suggested by you, I am now using template-scope attribute. I have made a modified template for calendarMonthCell ans using it as:

`<mwl-calendar
    events="events"
    view="calendarView"
    view-title="calendarTitle"
    view-date="viewDate"
    on-event-click="eventClicked(calendarEvent)"
    on-event-times-changed="eventTimesChanged(calendarEvent); calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
    cell-is-open="isCellOpen"
    day-view-start="06:00"
    day-view-end="22:59"
    day-view-split="30"
	custom-template-urls="{calendarYearView: 'customYearCell.html', calendarMonthCell: 'customMonthCell.html'}"
	template-scope="templateObject">
  </mwl-calendar>`


I have added this template-scope attribute and assigned it an scope from object, which basically looks like this  (in my ctrl) :


	`$scope.templateObject = {};
	$scope.templateObject.enableEventSelection = true;`

As you mentioned, this object should be available to custom template as vm.templateScope. I am having the following in my monthCell template

`<span ng-if="vm.templateScope.enableEventSelection">
			  <input type = "checkbox" style="margin:2px"/>
			  </span>`


But with the above changes, the check-boxes do not show up now; (they were showing when I forked the original tpls in library)

**Comment by mattlewis92** [comment]
Are you running the latest version of this module? It only got added in `0.23.0`

**Comment by soyiatgit** [comment]
My bad, I was using 0.22.0. It works fine with 0.23.0. However, Can I use templateScope to bind a function as well. Like:

<span ng-if="vm.templateScope.enableEventSelection"> <input type = "checkbox" ng-click = "vm.templateScope.onCheckBoxClicked()/> </span>

I tried above and it works, however if any better approach exists I would like to implement it.

Additionally, will it be possible to get the event on a date once it is clicked. Any direct binding between date and its event.?

**Comment by mattlewis92** [comment]
```
vm.templateScope = {
  enableEventSelection: true,
  onCheckBoxClicked: function() {
    // pass in the event etc to this function
  }
};
```
?

**Comment by soyiatgit** [comment]
The only way that I can see right now is to pass `vm` from the `onCheckBoxClicked` function. Along with I also need to pass the `$index` of the corresponding date cell. Then in the controller I need to look the `view` array's `$index` element and see its `event` object. Like below:

onCheckBoxClicked = onCheckBoxClicked(vm, $index)

in Ctrl:

function onCheckBoxClicked(vm, index){
   var eventsonCheckDate = [];
   eventsOnCheckedDate = vm.views[index].event;
}

Is this the only way to view events on a particular date??
