### ISSUE TITLE
[BUG] Calendar Displays wrong days on October 2016 for firefox (month view)

### ISSUE THREAD

**Issue by GSoster** [mattlewis92/angular-bootstrap-calendar#434]
### Bug description / Feature request:
Hello, when in october (month view) of 2016 the calendar (running on firefox 48.0.1 and later) shows the day 15 twice. It appears in saturday and sunday, It also affects all the other days from there (not duplicating them, but making they be day+1).
![october](https://cloud.githubusercontent.com/assets/6067175/17969680/a7fedde8-6aa9-11e6-81ac-6250569b3594.PNG)

### Link to minimally-working plunker that reproduces the issue (starter template: 
TO check this just access the link (http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview) and use the month view, then go to October and you will see that there are saturday 15 and sunday 15..
### Versions
Angular: 1.5.5 
Calendar directive: mwl-calendar
Browser name and version: Firefox 48.0.1 and later (not tested on earlier versions)

PS.: Sorry for bad English, not native here.

**Comment by mattlewis92** [comment]
Works fine for me, try using private browsing and see if it's still affects it, it's probably an extension causing it.
<img width="1318" alt="screen shot 2016-08-25 at 16 19 47" src="https://cloud.githubusercontent.com/assets/6425649/17974903/cb41e7f6-6adf-11e6-8438-15528571ac93.png">
