### ISSUE TITLE
Custom calendarSlideBox not being applied to year view.

### ISSUE THREAD

**Issue by soyiatgit** [mattlewis92/angular-bootstrap-calendar#436]
I have my three overrides in my calendar:

`custom-template-urls="{calendarYearView: 'customYearCell.html', calendarMonthCell: 'customMonthCell.html', calendarSlideBox:'customSlideBox.html'}"`

The calendarSlideBox template is:

		`<div class="cal-slide-box" uib-collapse="vm.isCollapsed" mwl-collapse-fallback="vm.isCollapsed">
		
			
		<div style="height:30px;width:100%" ng-repeat="row in vm.templateScope.eventList">
			<div style="height:30px;width:8.33%;display:inline-block;border:1px solid black;" ng-repeat="m in [1,2,3,4,5,6,7,8,9,10,11,12]"> Slide Event</div>
		</div>
		</div>
	</script>`

While this renders perfectly for month view, it does not work on year view. For year view, I am still getting the original slider.

 I see in your source there is just one template to be overridden for slide box. Also if I see the `calendarYearView.html` and `calendarMonthView.html` there is similar implementation for calling <mwl-calendar-slide-box> directive.

Where lies the difference then. How do I override the template for slide box of calendar year view.

**Comment by mattlewis92** [comment]
In your custom year view template make sure you're passing all options through to the slidebox: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarYearView.html#L41
