### ISSUE TITLE
Angular bootstrap calendar templates not loading

### ISSUE THREAD

**Issue by snehagokarn** [mattlewis92/angular-bootstrap-calendar#438]
Hi,

I have posted a question on stackoverflow, please can you help me on this one?
 
http://stackoverflow.com/questions/39252107/angular-bootstrap-calendar-default-templates-not-loading

**Comment by mattlewis92** [comment]
You need to include `angular-bootstrap-calendar-tpls.js` and *not* `angular-bootstrap-calendar.js` which doesn't have the templates bundled.
