### ISSUE TITLE
Incorrect cal-day-weekend logic

### ISSUE THREAD

**Issue by ptrckc** [mattlewis92/angular-bootstrap-calendar#44]
If moment locale's week.dow is not set to 1 (Monday as first day of week), then the logic that applies the 'cal-day-weekend' class in the week and month views incorrectly marks non Saturday/Sunday days as the weekend. See your demo for an example, where Friday and Saturday are colored red.

**Comment by mattlewis92** [comment]
Good spot, I'll fix it in the next version.
