### ISSUE TITLE
Two sources for events.

### ISSUE THREAD

**Issue by danielraban** [mattlewis92/angular-bootstrap-calendar#440]
I would like to be able to use two different sources for events, with separate $http.get calls.  I have tried doing         $scope.events = [$scope.approvedEvents, $scope.unapprovedEvents]; but this does not work.

**Comment by mattlewis92** [comment]
I assume `approvedEvents` and `unapprovedEvents` are both arrays? In which case you should be doing
```
$scope.events = $scope.approvedEvents.concat($scope.unapprovedEvents);
```
