### ISSUE TITLE
angular-bootstrap-calendar not work in ipad or iphone

### ISSUE THREAD

**Issue by succeeddoctor** [mattlewis92/angular-bootstrap-calendar#442]
Hi,

 I m working from many months with this calendar  and it works correctly in android. But when i tested it in ipad or iphone the calendar is not populated with events and we can't see different events in years, months or weeks.

 I debug safari in ipad from a mac book pro but i don't found the solution.

 Thanks

**Comment by mattlewis92** [comment]
The [demo](https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink) loads fine for me in safari on my mac and iphone, I'd imagine there's probably an issue within your app causing it to fail. Try checking the console to see if there's any errors.
