### ISSUE TITLE
Calendar not rendering new events

### ISSUE THREAD

**Issue by ahardworker** [mattlewis92/angular-bootstrap-calendar#444]
The calendar seems to have problems loading my events coming from a data source.

The thing is, if i load the events and THEN load the calendar, they will be rendered perfectly. However, if I load the calendar and asynchronously load the events, they won't be rendered in the calendar... 

this is the html markup
`<mwl-calendar events="events" 
                              view="calendarView" 
                              view-title="calendarTitle" 
                              view-date="viewDate" 
                              on-event-click="eventClicked(calendarEvent)" 
                              on-view-change-click="viewChangeClicked(calendarNextView, calendarDate)" 
                              on-event-times-changed="eventTimesChanged(calendarEvent); 
                                                      calendarEvent.startsAt = calendarNewEventStart; 
                                                      calendarEvent.endsAt = calendarNewEventEnd" 
                              edit-event-html="'<i class=\'icon ion-android-checkbox-outline positive\'></i>'" 
                              delete-event-html="'<i class=\'icon ion-close assertive\'></i>'" 
                              on-edit-event-click="eventEdited(calendarEvent)" 
                              on-delete-event-click="eventDeleted(calendarEvent)" 
                              slide-box-disabled="false">
                </mwl-calendar>`

In Js, I have the variable : $scope.events = [];

which I populate by doing an ajax call and pushing the received events in it.

**Comment by mattlewis92** [comment]
You may be missing a `$scope.$apply` after populating the events array? Alternatively you might be running into a limitation with angular and may need to hoist the events array into a parent variable like `$scope.vm = {events: []};`. Without a runnable repro in a plunker etc I can't do much more to help as I'm just guessing. Sorry!

**Comment by ahardworker** [comment]
Thanks, puting the data source in a parent variable worked....
