### ISSUE TITLE
interact.js

### ISSUE THREAD

**Issue by xiesj** [mattlewis92/angular-bootstrap-calendar#445]
it's maybe not an issue, just i always get Warning about not find modules of interact.js
and it's gone when replace
`require('interact.js')`
to
`require('interact')`

**Comment by mattlewis92** [comment]
The npm module name is `interact.js`: https://www.npmjs.com/package/interact.js, but the global is `window.interact`, I assume there's something in your build setup that's mapping it.

**Comment by xiesj** [comment]
awesome, thinks for such a fast reply, i will check it

**Comment by xiesj** [comment]
fixed after add this config in webpack.config.js
```
alias: {
        , 'interact.js': 'interact'
}
```
thanks for the reply
