### ISSUE TITLE
resize event come back one day

### ISSUE THREAD

**Issue by majidln** [mattlewis92/angular-bootstrap-calendar#446]
hi
in the week view, at resize event in end date side when i drag event it's come back one day
for example the event in 7-8th and i resize 8th and drop mouse in the 10th the end date of event come back to 9th
whats the problem?how i can solve this problem
please help me
<a href="http://uploads.im/T6BJp.png"><img src="http://sm.uploads.im/t/T6BJp.png" border="0" /></a>

**Comment by mattlewis92** [comment]
Sorry I don't follow you, can you give me a plunker that reproduces your issue + a clear set of instructions on what to do to replicate. Thanks!

**Comment by mattlewis92** [comment]
Closing, as can't help without something that reproduces the issue
