### ISSUE TITLE
Feature Request: Show holiday as a calendar block

### ISSUE THREAD

**Issue by snehagokarn** [mattlewis92/angular-bootstrap-calendar#447]
Hi,
Can we add a feature to show the whole calendar block to be grayed out or maybe different from the other blocks which have events to signify a holiday?

This is not same as weekends but a maybe to show a public holiday?

Thanks,
Sneha

**Comment by mattlewis92** [comment]
You can use the cell-modifier hook to implement something like this: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=cell-modifier
