### ISSUE TITLE
Translate to other languages.

### ISSUE THREAD

**Issue by GrofGraf** [mattlewis92/angular-bootstrap-calendar#448]
Hello, this is really nice directive, I use it a lot.
But I have a request for you and would need some help.
Can you suggest the easiest way to translate calendar to other languages?
Thank you for your work, again.

**Comment by GrofGraf** [comment]
Never mind, I found an answer. I saw your directive uses moment, that already has all the local files. Sorry for any inconvenience, my question made, i really wasnt't familiar with moment library yet.

Best regards, GrofGraf

**Comment by mattlewis92** [comment]
Glad you found the answer :)
