### ISSUE TITLE
may fix documentation-error

### ISSUE THREAD

**Issue by LingLong** [mattlewis92/angular-bootstrap-calendar#449]
The helper-directive won't work in the way it is described:
If you use it like so: ...
<button
class="btn btn-primary"
mwl-date-modifier
date="calendarDay"
decrement="calendarView"&gt;
Previous
button&gt;

... you can click buttons like hell, wondering why the scope isn't applied.

Everything is working fine if you declare it like so:

The error seems to be the value of the date-attribute.
The correct working version is:
date="calendarDate"

**Comment by mattlewis92** [comment]
Thanks, fixed!
