### ISSUE TITLE
ng-click $event shadowing?

### ISSUE THREAD

**Issue by sheela-na-geek** [mattlewis92/angular-bootstrap-calendar#45]
In month view, I would like to be able to click event without triggering `calendar-timespan-click` function. To achieve this, I need to pass `$event` to my `calendar-event-click` function and call `$event.stopPropagation()`.
However, ng-click `$event` seems to be shadowed by a calendar event from you code: `ng-click="eventClick({$event: event})">` so I have to declare `calendar-event-click="eventClicked($event)"` and cannot pass `ng-click` `$event`.
Please correct me if I'm wrong :) Any workarounds/fixes?

**Comment by mattlewis92** [comment]
Ah you're correct, I'll rename $event to event in the next version which should fix the problem.
