### ISSUE TITLE
event mouseover

### ISSUE THREAD

**Issue by majidln** [mattlewis92/angular-bootstrap-calendar#452]
I need trigger an event when mouser over a calendar event?
for example we have an on-event-click for click on event, but we don't have an event for on-event-hover (for example)
how can i add this feature to this amazing calendar?

**Comment by majidln** [comment]
please help

**Comment by mattlewis92** [comment]
You can implement this with a custom template: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=custom-templates and the [template-scope](https://github.com/mattlewis92/angular-bootstrap-calendar#template-scope) option.

**Comment by majidln** [comment]
ddd

**Comment by majidln** [comment]
i need to show a popover when mouse over an event and show some data 
please help
