### ISSUE TITLE
Group month view events does not allow drag and drop

### ISSUE THREAD

**Issue by gchadid** [mattlewis92/angular-bootstrap-calendar#453]
I configure the control to  group events like in the demo "Group month view events" and i  enabled the draggable property to  a event, when i try to drag and drop the event the  on-event-times-changed is not fired and the event is not drop.

**Comment by mattlewis92** [comment]
Ah that's because I omitted a few things from the custom template. You will need to adapt the full template from here: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthCell.html

**Comment by gchadid** [comment]
Thank you very  much
