### ISSUE TITLE
change the height of cell in day view

### ISSUE THREAD

**Issue by majidln** [mattlewis92/angular-bootstrap-calendar#455]
day cell height is 30px and i need to change that 10px
how i can this change?
![selection_003](https://cloud.githubusercontent.com/assets/8521168/18903147/54b850d0-8564-11e6-80c1-35917697dd50.png)

**Comment by mattlewis92** [comment]
I think this should be easy enough to implement by removing all the hardcoded references to 30px in height.

**Comment by mattlewis92** [comment]
I'm afraid there was no easy way of implementing this without breaking a lot of stuff.
