### ISSUE TITLE
How can I change the icon of the event?

### ISSUE THREAD

**Issue by mishra1947** [mattlewis92/angular-bootstrap-calendar#459]
![calendar](https://cloud.githubusercontent.com/assets/17452641/19154523/876caf36-8bf8-11e6-8476-ac2e223128f4.JPG)

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by mattlewis92** [comment]
As [shown in the demo](https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink) just add the icon html in the event title.

**Comment by mishra1947** [comment]
I sent you a snap shot of calendar. Please see that and give solution to
add event icon instead of circles and content of event cell.

**Comment by samueljacobsmith** [comment]
Hi mishra, did you ever find a solution for this? Working on the same thing myself
