### ISSUE TITLE
Drilldown causing problems

### ISSUE THREAD

**Issue by pbellesa** [mattlewis92/angular-bootstrap-calendar#46]
Hello, I have a web app with multiple modules. "mwl.calendar" is injected into the main module. 
```
var app = angular.module('main', ['mwl.calendar', 'ui.bootstrap', 'EventCtrl']);
angular.module('EventCtrl', []).controller('EventController', EventController);
```
I'm using your calendar in a EventCtrl module. I'm having trouble with the calendar when drillDown is triggered.

If I trigger drillDown, the calendarView doesn't get updated anymore with the toggle controls.

I suspect it is a scope issue but I'm not sure.

**Comment by mattlewis92** [comment]
Can you reproduce the problem you're experiencing on the [demo](http://mattlewis92.github.io/angular-bootstrap-calendar/) on a [plunker](http://plnkr.co/)

**Comment by pbellesa** [comment]
I could not replicate the error, so I just made some changes in the mwlCalendar directive code:

```
        $scope.control.day = function() {
          $scope.changeView('day', moment($scope.currentDay).toDate());
        };
        $scope.control.month = function() {
          $scope.changeView('month', moment($scope.currentDay).toDate());
        };
        $scope.control.year = function() {
          $scope.changeView('year', moment($scope.currentDay).toDate());
          console.log("TEST");
        };
        $scope.control.week = function() {
          $scope.changeView('week', moment($scope.currentDay).toDate());
        };

        $scope.changeView = function(view, newDay) {
          $scope.view = view;
          $scope.currentDay = newDay;
          $scope.calendarView = view;
        };
```
I call those from the html using the calendarControl variable and it fixed my problem.

**Comment by mattlewis92** [comment]
Glad you got it solved :)
