### ISSUE TITLE
Calendar controller and cell modifer function not called when changing months

### ISSUE THREAD

**Issue by wonder95** [mattlewis92/angular-bootstrap-calendar#460]
I'm using this with a custom cell modifier and custom cell template in a sort of unorthodox way (I'm displaying tables inside each day, as compared to standard calendar events), and I'm pulling data from a remote URL to fill the cell (my code is [here](https://github.com/wonder95/formio-volunteers/blob/master/src/app/resources/shift/calendarController.js)). 

The problem is that when changing months (in the month view), my controller and cell modifier function are not called, so I can't update my data. The calendar structure changes for the month (day labels, etc). but since my code isn't called, I can't get updated data. What's weird is that it seems to be intermittent. I had this issue written up last night, but then it started to work (i.e. my controller was getting called); but coming back today, it isn't working again.

What is the expected behavior? Is there something I need to do to force the controller and modifier function to be called? Or is there something wrong in my code?

Thanks.

### Versions

Angular: 1.5

Calendar library: 0.23.0

Browser name and version: Chrome 53.02785 Mac

**Comment by mattlewis92** [comment]
That's odd, the cell modifier function should always be called whenever the [view updates](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/0.23.0/src/services/calendarHelper.js#L153) - in fact I do the exact same thing in our app at work without issues there. I will check out that repo tomorrow and see if I can see what's going on.

**Comment by wonder95** [comment]
OK, I discovered that I partially lied; the cell modifier function is getting called (it always helps to put breakpoints in all the appropriate places :-)). My problem is that I'm getting the data outside of the cell modifier and putting into vm.events, which makes it available inside the cell modifier function, It looks like I just need to query my data from inside the cell modifier.

**Comment by mattlewis92** [comment]
Ah great to hear you got it sorted :)

**Comment by wonder95** [comment]
OK now that I think more about it, I still have a problem in that the cell function gets called for each day, but I only need to query the data for the month as a whole, not each individual day (I get dinged by the back end for each query). Is there way to do that? Do I just need to store everything locally somehow and only query it the first time through?

**Comment by mattlewis92** [comment]
All the controls to change the current view are outside of the calendar component, you just need to get the start and end of the month whenever a user changes the view date or type. Or if you're really lazy just use a watcher for the vm.viewDate value.

**Comment by wonder95** [comment]
> All the controls to change the current view are outside of the calendar component, you just need to get the start and end of the month whenever a user changes the view date or type.

OK, thanks. One last question; I would do that in the cell modifier? Or is there a better way/place?

**Comment by mattlewis92** [comment]
The cell modifier is only really meant for minor things like adding extra classes to cells / attaching extra metadata for people using custom templates. A watcher on the current date would work:
```
$scope.$watch('vm.viewDate', () => {
  const start = moment(vm.viewDate).startOf('month');
  const end = moment(vm.viewDate).endOf('month');
  // fetch events from the server
});
```

**Comment by wonder95** [comment]
Beautiful. Thanks much for your time.
