### ISSUE TITLE
Disable day click

### ISSUE THREAD

**Issue by niqt** [mattlewis92/angular-bootstrap-calendar#461]
Feature request:
I'd like disable the click on the day number (in the month view) but change in day view when clikc on in everywhere in the box of the day (in month view). I tried setting in timespanClicked calendarView to 'day', the view change but the day is always today and not the clicked day. I need it also to have in the day view the events of the day (if i switch to the day view clicking on the day number the calendarCell is undefined).
         Thanks

**Comment by mattlewis92** [comment]
I've put together an example for you that shows how to implement this with the existing API, hope that helps :) http://plnkr.co/edit/ZNnLvvE60rUTkXGRVHll?p=preview

**Comment by qbunia** [comment]
How I can fully disable day click? So events wont show off?

**Comment by mattlewis92** [comment]
@qbunia https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=slide-box-disabled
