### ISSUE TITLE
Click event on week view - Drop area extension

### ISSUE THREAD

**Issue by zigkasg** [mattlewis92/angular-bootstrap-calendar#462]
Hi,

1. Could you please help me to add a create new event button in week view? or is there any way to add a click event trigger in the week view?

2. Can I extend the drop area in week view to the whole column of a day?(not only where the day and date exist)

Thanks
George

**Comment by mattlewis92** [comment]
1/ I'm not really sure where you'd put a new event button in the week view?
<img width="529" alt="screen shot 2016-10-09 at 12 14 47" src="https://cloud.githubusercontent.com/assets/6425649/19219973/19328bfc-8e1a-11e6-9dec-df6202583a98.png">

You can use the `on-event-click` option to handle when week view events are clicked (see the demo for an example: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink

2/ Sorry I'm not really sure what you mean by this, would you mind explaining a bit more. Thanks!

**Comment by zigkasg** [comment]
1. Lets say, in the white space next to the blue event - Saturday 15Oct I want to have a new event button that it will take as date the current date (15 oct). Do you have any suggestions how to do it?

2.If I have external events, the drop zone for those events are the areas of DAYS (eg. Thursday 14Oct).
Can I extend the drop zone to the whole column instead of that cell only?

I hope you understand what I mean.

Thanks.

**Comment by mattlewis92** [comment]
I'm afraid both of those use cases can't be trivially implemented with this calendar, I'd suggest building your own week view that can handle this (perhaps using the `calendar-utils` module to handle some of the business logic for you)
