### ISSUE TITLE
Change color of selected month/day.

### ISSUE THREAD

**Issue by captainmorgan0** [mattlewis92/angular-bootstrap-calendar#463]
It would be great if (in month, year view) you could add a css class to the the currently selected day/month. So not only is the list of events exapanded, you can change the color or the cell.

**Comment by mattlewis92** [comment]
Good idea! Added in master :)

**Comment by captainmorgan0** [comment]
I just tested this out. cal-day-selected doesn't seem to be applied to the day when you click on it.

**Comment by simandi** [comment]
@mattlewis92 ,

Can you let me know the css class for the selected day. I want to change the background color for the clicked day.

Thank you.
