### ISSUE TITLE
showTimesOnWeekView = true not displaying data like day view

### ISSUE THREAD

**Issue by captainmorgan0** [mattlewis92/angular-bootstrap-calendar#464]
### Bug description / Feature request:
When setting showTimesOnWeekView  to true, and setting two events to span the whole day, only the second event is displayed, spanning 12:00-12:30am in week view. I would expect the week view to appear similar to day view

**Comment by mattlewis92** [comment]
There are 2 major caveats with that option hence why it's not the default:
* overlapping events are displayed on top of each other
* event end dates are ignored

It works for some people, but if it doesn't fit your use case then I'd recommend the normal week view.

**Comment by captainmorgan0** [comment]
Is there any way to use the end date, so at least one of the events is shown?
