### ISSUE TITLE
Unable to call controller method from ng-click in custom cell template

### ISSUE THREAD

**Issue by wonder95** [mattlewis92/angular-bootstrap-calendar#465]
As I've mentioned in other issues, I'm using a custom cell template with a cell modifier function, and I'm unable to call a function in my controller using ng-click from an element in the template (controller code is [here](https://github.com/wonder95/formio-volunteers/blob/master/src/app/resources/shift/calendarController.js#L51), the template is [here](https://github.com/wonder95/formio-volunteers/blob/master/src/views/calendar/dayTemplate.html#L27)). When I click on the link, nothing happens, but in the console, it looks like it just calls the controller all over again. From what I can see, I have everything set up correctly, and I've asked on StackOverflow, but nobody there (at least the one person who answered :-)) can see anything wrong.

Is there anything in the calendar code that would keep this from working? Or is there maybe something I'm missing? I've been banging my head against this for a while, but I was just wondering if there's something unique about this controller and the way it's called that would cause this problem. If not, I'll go back to banging my head.

Thanks.

**Comment by mattlewis92** [comment]
The calendar has it's own isolate scope, so you can't access your controllers code inside the custom template. The way to get around this is to use the `template-scope` option - `template-scope="vm"` and then in your custom template `vm.templateScope.addName`

**Comment by wonder95** [comment]
Whew, glad it is something easy to fix.

Thanks again.
