### ISSUE TITLE
m.events.filter is not a function

### ISSUE THREAD

**Issue by Msaddyw23** [mattlewis92/angular-bootstrap-calendar#466]
Can anyone suggest me where i'm going wrong as i'm new to angularjs

 activeMenu = "Calendar";
        angular.module('mwl.calendar.docs', ['mwl.calendar', 'ngAnimate', 'ui.bootstrap', 'colorpicker.module']);
        angular
          .module('mwl.calendar.docs') //you will need to declare your module with the dependencies ['mwl.calendar', 'ui.bootstrap', 'ngAnimate']
          .controller('KitchenSinkCtrl', function (moment, alert, calendarConfig, $http, $scope, $rootScope, $window) {
              var vm = this;

              //These variables MUST be set as a minimum for the calendar to work
              vm.calendarView = 'month';
              vm.viewDate = new Date();

vm.events = [];
              $http.get('/Calendar/GetCalendarDetails1').success(function (events) {
                  console.log(events);
                  var Tagvalue = JSON.stringify(events)
                  var eve = JSON.parse(Tagvalue);
                  console.log(eve);
                  vm.events = events;
              });
 });

This is my code which i used from your example...

**Comment by mattlewis92** [comment]
I can't see what's going wrong from that code, please provide a reproducible plunker that demonstrates your issue. Starter template: http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview
