### ISSUE TITLE
Unexpected character '@' when npm run build

### ISSUE THREAD

**Issue by mickeychu** [mattlewis92/angular-bootstrap-calendar#468]
Hello, 

I download the latest version 0.24.0 but when I ran **npm run build** after **npm install,** there's error : 
![screen shot 2016-10-12 at 16 02 36](https://cloud.githubusercontent.com/assets/7807777/19311008/54a8d894-9095-11e6-9394-d7e094903a6d.png)

How can I fix this error? Many thanks!!!

**Comment by mattlewis92** [comment]
You need to install the less loader so webpack can understand less files: https://github.com/webpack/less-loader
