### ISSUE TITLE
Allow ability to customize event title displayed in day, week, month, etc. views...

### ISSUE THREAD

**Issue by ndicenso** [mattlewis92/angular-bootstrap-calendar#469]
**Feature request:** @mattlewis92  I would like to request the ability to customize the html used for the event title display. Currently the info displayed in each day/week/month/year/tooltip text is a concatenation of the title property and the start time of the event. For my current usage, I have some events where that display is fine, but in other cases I would like to show something like "Event title (9:00AM - 12:00PM)". 

There seems to be no easy way to do this currently other than overriding several templates just for that one html portion.

I could see a couple of possible ways to address this:

1. Only show exactly what is in the title property of the event
2. Create an enableSmartTitle property to display the current smart title. Default the property to true to maintain current behavior. Setting the property false would allow whatever text/html the developer uses for event title.

**Comment by mattlewis92** [comment]
You can already do this by overriding methods in the `calendarEventTitle` service: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarEventTitle.js

e.g. 

```
calendarEventTitle.yearView = function(event) {
  return 'Custom year view title: ' + event.title;
}
```

**Comment by ndicenso** [comment]
Thanks Matt. In general, this works great. The problem I run into is in the
case of dayView, the html template still embeds a formatted version of the
date/time in front of the title. So even if I override the .dayView
function, I would still have to customize the template to modify this
behavior.

I may end up doing this anyway since there is no tooltip html for the day
view and many of my event titles are cutoff since they default height is
only a single line display.

Regards,
Noah

**Comment by mattlewis92** [comment]
You could hide the embedded date for the event with some CSS which would give you a bit more space.
```
.day-event .cal-hours {
  display: none;
}
```

**Comment by ndicenso** [comment]
Cool. Thanks Matt.

Noah
