### ISSUE TITLE
Request: Move month view's events-list div into separate template

### ISSUE THREAD

**Issue by ptrckc** [mattlewis92/angular-bootstrap-calendar#47]
Would it be possible for you to move the events-list div in the month.html template into a separate template to be easily overridden? It'd allow for easier modifications to how events are displayed in their current circle+tooltip form. For example, directly displaying the event titles on the calendar for all dates with < X events on any given day.

**Comment by mattlewis92** [comment]
Can do - what I'll probably do is refactor the template for both the year and month view drill down into it's own directive as the template is shared for both of them. I'll add a scope variable as well so you can tell if it's the year or month view and add different logic for each view if you want to.

**Comment by ptrckc** [comment]
Ah, yea I notice that now for the drill-down. That should solve my request for #48. For this request, I'm talking about the block on line 22 (<div class="events-list" ng-show="day.events.length > 0">).

**Comment by mattlewis92** [comment]
Oh I get what part you're on about now. I don't think the existing CSS will allow this to work very easily, this is what happens if you display the events by title:
![screen shot 2015-03-28 at 18 18 11](https://cloud.githubusercontent.com/assets/6425649/6882279/e2ce1002-d576-11e4-9770-855f328fa085.png)

**Comment by ptrckc** [comment]
Yea, I figure I'll have to write additional css to support my overriding the html. Probably something that shows a few of the events along with a 'more' link to open the drilldown. I just didn't want to have to override the entire template to do that.

The dots definitely keep the interface clean, and I know they come from the original jquery implementation, but seeing a few events by default, without the extra hover or drilldown interaction, greatly improves the usability imho.

**Comment by simpixelated** [comment]
You should consider moving the entire day in the month to a separate template, which makes it easier to override everything in the cell.

**Comment by mattlewis92** [comment]
That's true, but once you do that as well as refactor the slide box drilldown into its own sub directive you're only left with a few lines of html which almost defeats the purpose of moving it into its own template.

**Comment by mattlewis92** [comment]
This is how much is left after the refactor if you put the cell template into its own directive 
![screen shot 2015-03-30 at 19 11 03](https://cloud.githubusercontent.com/assets/6425649/6903195/8f61dfc0-d710-11e4-92e9-a01a602b7717.png)

**Comment by simpixelated** [comment]
As I see it, the benefit is being able to override it with a different template, but I see your point.

**Comment by simpixelated** [comment]
Would the mwl-calendar-month-cell template/templateUrl be configurable? Similar to calendar-edit-event-html. I was about to open another issue for making the ng-class on the day configurable, but if I can swap the entire template that wouldn't be needed.
