### ISSUE TITLE
Custom day template doesnt render events in prev/next month

### ISSUE THREAD

**Issue by qbunia** [mattlewis92/angular-bootstrap-calendar#470]
### Bug description:
Custom day template doesnt render events in prev/next month. 

http://plnkr.co/edit/LZCZ7IfeZypATb2b1eeU?p=preview

At the start we are in October. October 1st contains 1 event, but September 30th also contains 1 event that is not showed. If we go to September we can see the event on 30th is there.

Angular: 
1.5.8
Calendar library: 
0.24.0
Browser name and version: 
Firefox 49.0.1

**Comment by mattlewis92** [comment]
This is by design, you can disable it by setting `calendarConfig.displayAllMonthEvents = true`
