### ISSUE TITLE
 Timezone for default

### ISSUE THREAD

**Issue by anniel** [mattlewis92/angular-bootstrap-calendar#471]
### Problem Description
Hi, I want to know how to set the schedule timezone using a setting variable

I want to use the timezone settled by the user instead OS's timezone.

Angular: 
1.5.8
Calendar library: 
0.24.0

**Comment by mattlewis92** [comment]
As moment.js powers everything, providing you use moment() to construct all your dates you should be able to override it with `moment.tz.setDefault()`.

Source: http://stackoverflow.com/questions/9369972/can-i-set-the-local-timezone-in-my-browser-via-javascript
