### ISSUE TITLE
Not possible change day-view split at start

### ISSUE THREAD

**Issue by niqt** [mattlewis92/angular-bootstrap-calendar#474]
In my example http://plnkr.co/edit/rXIwoT6MmEMu63ZSHxId?p=preview i wants set the day-view-split at the startup, but seems that the calendar uses always the default value (30 minutes)

Angular: 1.5.8

Calendar library: 0.24

Browser name and version: All

**Comment by mattlewis92** [comment]
I've fixed your example for you 😄  http://plnkr.co/edit/DHVbP3NJWY8NNlpQLndf?p=preview

It needs to be `day-view-split="{{ vm.opTime }}"` as the binding is just `@` for the day view parameters (although with hindsight maybe it shouldn't be)

**Comment by niqt** [comment]
Thanks!

2016-10-24 9:41 GMT+02:00 Matt Lewis <notifications@github.com>:
