### ISSUE TITLE
 I need add the doubleclick event

### ISSUE THREAD

**Issue by anniel** [mattlewis92/angular-bootstrap-calendar#477]
**Problem Description**
Hi, in this moment I need add the doubleclick event to activate a modal
You have any configuration created similary to on-timesoan-click

Thanks for you answer.

### Versions

Angular: ^1.5.8
Calendar library: ^0.24.0

**Comment by mattlewis92** [comment]
As it's quite a rare use case I'd recommend using a custom template: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=custom-templates
