### ISSUE TITLE
Call controller function from  the factory

### ISSUE THREAD

**Issue by freddyPower** [mattlewis92/angular-bootstrap-calendar#478]
Angular:  latest

Calendar library: angular-bootstrap-calendar v0.24.0

Browser name and version:  Chrome

**Comment by mattlewis92** [comment]
Sorry I don't understand what you mean, please would you mind explaining a bit more. Thanks! 😄

**Comment by freddyPower** [comment]
Thanks for your help.

How can I call a function thats is it in my main controller from the factory modal.
I have  been followed this example: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=editable-deletable-events

:)

**Comment by mattlewis92** [comment]
This is more of a ui bootstrap issue than with this calendar. Personally I'd recommend using the resolve feature to pass data into the modal, and the promise returned by the modal to get data back out of it once the modal is closed. 

However if you really need to call a function from the host controller from the modal while it's open you could define the modals controller within the hosts like so:
```
.controller('foo', function($uibModal) {  

  function controllerMethod() {}

  $uibModal.open({
    controller: function() {
      controllerMethod();
    }
    ...other properties
  });

});
```
