### ISSUE TITLE
Calendar integration issue with jHipster web application

### ISSUE THREAD

**Issue by sarjerav** [mattlewis92/angular-bootstrap-calendar#479]
Hello mattlewis

I have created web application using jHipster & I want to integrate this calender into my web application.

I don't know what was problem so can you tell me what are the steps that I should follow while integration the calendar.

Versions

Angular: 1.5.8

Calendar library: 0.24.0

Browser name and version: Chrome 53.0.2785.143 m (64-bit)

**Comment by mattlewis92** [comment]
Sorry I have no experience with jHipster, try asking stackoverflow (with a more detailed explanation of why it doesn't work / a reproduction of the issue).

**Comment by basiljude** [comment]
i want to know about  calendar in jhipster
