### ISSUE TITLE
Request: Add day of month to events in year view

### ISSUE THREAD

**Issue by ptrckc** [mattlewis92/angular-bootstrap-calendar#48]
When a month is selected on the year view, it shows all the events for it. However, there's no way to know what days of the month they're on unless you switch views. I think preceding the event's title with the day of the month would improve usability.

**Comment by mattlewis92** [comment]
That makes sense, I'll add that in the next version.

**Comment by mattlewis92** [comment]
Closed in https://github.com/mattlewis92/angular-bootstrap-calendar/commit/e72df58531d5c3b34c48233d4e20d0ea19739d62
