### ISSUE TITLE
Week view display issue when showTimesOnWeekView is true and events have same start time

### ISSUE THREAD

**Issue by Mirithal** [mattlewis92/angular-bootstrap-calendar#480]
### Bug description / Feature request:
If calendarConfig.showTimesOnWeekView = true and a day has more than one event with the same startTime, the WeekView will hide all but one event for that start time.

### Plunker
http://plnkr.co/edit/KXX6qsDEuEpDF3Rm71G6?p=preview

### Versions

Angular: ^1.5.8

Calendar library: ^0.24.0

Browser name and version: Chrome 53.0.2785.143

**Comment by mattlewis92** [comment]
This is a known limitation of this view (hence why it's behind a flag). To work around it I'd recommend grouping events together and then drilling down into the day view to see what the events are when you click on the grouped event. Example here: http://plnkr.co/edit/6OXds4DQiWpLLceaA6te?p=preview
