### ISSUE TITLE
unable to bring th events on side of calendar

### ISSUE THREAD

**Issue by gigglegirl** [mattlewis92/angular-bootstrap-calendar#481]
### Bug description / Feature request:
 Hi i am trying to get the events of the calendar on different div not on the calendar , i am trying from many days but i am unable to .I am working on year view , and i want the events to to be displayed in different div and they should change when i click on any month in year view.This is my project requirement .Please help me with that.

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Please use stackoverflow for support requests, this issue tracker is only for bug reports and feature requests. Thanks!

**Comment by gigglegirl** [comment]
Hi mattlewis, 

Thanks .
and you make an awesome calendar 

Laxmi
