### ISSUE TITLE
Bug in October Event

### ISSUE THREAD

**Issue by Jpmmdf** [mattlewis92/angular-bootstrap-calendar#482]
![captura de tela 2016-10-28 as 15 30 44](https://cloud.githubusercontent.com/assets/8302424/19815957/04dfe460-9d24-11e6-9e1a-c8c08800fcd3.png)

When you create an event in October and exchange year in the calendar the event is still there

See to your own example

https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink

Thanks for everything

**Comment by mattlewis92** [comment]
This is because the event has `recursOn: 'year'` set which makes it recur on every year. Thanks for reporting though! :)
