### ISSUE TITLE
Disable hover events when on mobile

### ISSUE THREAD

**Issue by SergioArrighi** [mattlewis92/angular-bootstrap-calendar#483]
### Bug description / Feature request:

Hi, I'm using your calendar for a pet project and I'm really liking it. Thanks a lot!
I would like to disable all hover events when on mobile and if not possible disable them completely
### Link to minimally-working plunker that reproduces the issue

Sorry I don't have :(
### Versions

Angular: 1.5.8

Calendar library: 0.23.0

Browser name and version: Chrome 54.0.2840.71 (64-bit)

Thanks if you will reply, have a nice day!

Best regards

**Comment by mattlewis92** [comment]
Sorry I'm a bit confused by what you mean, hover events on mobile shouldn't be possible as there isn't a mouse pointer to hover over anything? You can easily override any CSS styles yourself to reset any styling applied by `:hover` rules.
