### ISSUE TITLE
events can be shown in week view with time just like day view .

### ISSUE THREAD

**Issue by sonamgupta-kiwi** [mattlewis92/angular-bootstrap-calendar#485]
### Bug description / Feature request:
I need to show events in week view with time just like day view . How can i do that ?

### Versions

Angular: v1.5.8

Calendar library: v0.24.0

Browser name and version: 
Chrome

**Comment by mattlewis92** [comment]
You need to override this method to include the event time: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarEventTitle.js#L22

**Comment by sonamgupta-kiwi** [comment]
Hi,
i customised that but didn't get view like day view and resize is also not working in weekview with time.
