### ISSUE TITLE
Is there any way to disable the label/(dateNumber) click event?

### ISSUE THREAD

**Issue by Rickardkamel** [mattlewis92/angular-bootstrap-calendar#486]
Hello! First off I would like to thank you for this great calendar!

Can I in any way disable the click event that brings up a hour-list, from the month view, when clicking on the date (the number)?

example:
<img src="https://puu.sh/s6h0C/486302c779.png">

when clicking on "10" I don't want this view:

<img src="https://puu.sh/s6h5h/cf5c097fee.png">

Thanks in advance,
Rickard.

**Comment by mattlewis92** [comment]
Yup this is possible by returning false from this option: https://github.com/mattlewis92/angular-bootstrap-calendar#on-view-change-click

Demo here: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=view-change-click

Hope that helps! 😃
