### ISSUE TITLE
Hiding the Time in the calendar events

### ISSUE THREAD

**Issue by Msaddyw23** [mattlewis92/angular-bootstrap-calendar#487]
Hi Everyone,

I'm customizing the angular-bootstrap-calendar. i don't want the default time next to the events while displaying it in the calendar. for Eg:  myeventName (00:00) instead  i need like this myeventName . can anyone tell how i can achieve it

**Comment by mattlewis92** [comment]
You need to override the `calendarEventTitle.monthView` method like so:
```
calendarEventTitle.monthView = function(event) {
  return event.title;
}
```

Original source: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarEventTitle.js
