### ISSUE TITLE
Avoid globally namespaced css classes

### ISSUE THREAD

**Issue by amyhua** [mattlewis92/angular-bootstrap-calendar#488]
### Bug description / Feature request:

angular-bootstrap-calendar.css uses global css classes like

```
.event {
  width: 12px;
  height: 12px;
  margin-right: 2px;
  margin-bottom: 2px;
  box-shadow: inset 0 0 5px 0 rgba(0, 0, 0, 0.4);
  border-radius: 8px;
  border: 1px solid #ffffff;
}
.event,
.event-block {
  display: block;
  background-color: #c3c3c3;
}
```

instead of namespacing them, e.g. `.angular-bootstrap-calendar .event, .angular-bootstrap-calendar .event-block`

### Link to minimally-working plunker that reproduces the issue:

See [existing angular-bootstrap-calendar demo](http://plnkr.co/edit/?p=preview)

### Versions

Calendar library: v0.25.0

**Comment by mattlewis92** [comment]
Good catch, I'm surprised no one's ever reported this before! Wrapping all CSS selectors in `mwl-calendar` should do the trick, will push a fix soon.
