### ISSUE TITLE
in Week view with hours visible, more than one event at same hour, only show one event.

### ISSUE THREAD

**Issue by russojrv** [mattlewis92/angular-bootstrap-calendar#490]
### Bug description / Feature request: in Week view with hours visible, more than one event at same hour, only show one event. 

This is in week view, in "jueves" at 8:00 I have two events but I only can see one. 
![weekview](https://cloud.githubusercontent.com/assets/23401178/20215866/9999ce9c-a817-11e6-9e46-e92911dad033.jpg)

This image is in day view, it s only to check that I have both events correct. 
![dayview](https://cloud.githubusercontent.com/assets/23401178/20215908/eecebf76-a817-11e6-84b2-ce326a285ea0.jpg)

In month view also appear.
How can I display more than one event in same day and same hour? Can you fix this problem?
Thank you

### Versions

Angular: 1.5.8

Calendar library:  "0.26.0"  https://github.com/mattlewis92/angular-bootstrap-calendar"

Browser name and version:  Google Chrome

**Comment by mattlewis92** [comment]
This is a known limitation of this view (hence why it's behind a flag). To work around it I'd recommend grouping events together and then drilling down into the day view to see what the events are when you click on the grouped event. Example here: http://plnkr.co/edit/6OXds4DQiWpLLceaA6te?p=preview
