### ISSUE TITLE
vm.events issue with firebase array

### ISSUE THREAD

**Issue by Snookid** [mattlewis92/angular-bootstrap-calendar#491]
### Versions

Angular: 1.5+ 

Calendar library: Latest?

Browser name and version: Chrome 53

I have a basic setup with the calendar but I'm hooking the events from Firebase with the use of AngularFire.

When I pass the events from Firebase with AngularFire, the directive manipulates the entire Array and deletes functions of [AngularFire](https://github.com/firebase/angularfire/blob/master/docs/reference.md) like $add after which all the functionalities of Firebase is lost.

Anyway, that I could manipulate the directive where it's rewriting the events passed to it?

Let's say the original Firebase Array comes in

vm.events = [
0: {startsAt: 234562343423, endsAt: 123456789, title: 'New event'},
$add: func[],
$$added: funct(),
$watch: funct(),
$save: funct(),
];

I need to pass the same array to the mwl directive as I need it to be updated live, however when I pass it to the directive, it comes out like this: 

vm.events = [
0: {startsAt: 234562343423, endsAt: 123456789, title: 'New event'}
];

Any help here would be appreciated. Thanks!

**Comment by mattlewis92** [comment]
I'm not too familiar with how angularfire works but I think this should be fixed now in 0.26.1

**Comment by Snookid** [comment]
Great Thanks!
