### ISSUE TITLE
Setting events on start and end date

### ISSUE THREAD

**Issue by Msaddyw23** [mattlewis92/angular-bootstrap-calendar#492]
Hi,

I am using this calendar in my application and want to customize it. Can anyone know how to set the Events only on the start and end date instead of showing in all the in between dates.

**Comment by mattlewis92** [comment]
You could use the [`cell-modifier`](https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=cell-modifier) option to remove any events from days that don't start or end on that day.

**Comment by Msaddyw23** [comment]
Hi matt,

Can you please tell me how can i use the Cell-modifier to get the desired result. this is the plunker i'm working on 

http://plnkr.co/edit/Z48pHHhJBrvaJYRroXJg?p=preview

**Comment by mattlewis92** [comment]
No worries, here's your plunker that implements what you need: http://plnkr.co/edit/WDqVjRrDFgzGzNSaG0SK?p=preview Hope that helps! :)
