### ISSUE TITLE
incrementsBadgeTotal on a monthly basis

### ISSUE THREAD

**Issue by Snookid** [mattlewis92/angular-bootstrap-calendar#493]
### Versions

Angular: 1.5+

Calendar library: 0.26.1 

Browser name and version: Chrome 53

This is more of an FR rather than issue.

It'd be nice to have a count of badges for the whole month instead of just per day. Right now, if we switch to Year view then the badge total doesn't take into consideration of the fact that some events will be repeating on following days as well. It's just simply counting the number of events logged or array length.

On a month view, an event repeating for the whole week will show count of 1 every day for that week however, when switched to year view, it will still count as one.

It would be great to let users know how many events in total are up on the line.

Also, let's say i would like to show some other info from the array like title - reason. How do we do that? Right now, it shows 'title (time)" by default.

**Comment by mattlewis92** [comment]
You can implement this using the cell-modifier feature: https://github.com/mattlewis92/angular-bootstrap-calendar#cell-modifier

On the cell just change the `badgeTotal` to whatever you'd like it to be.
