### ISSUE TITLE
Week Order

### ISSUE THREAD

**Issue by marizuyat** [mattlewis92/angular-bootstrap-calendar#495]
hi i have a trouble, 

I need in week view, change the order because, when activities of the day finish, start from another day activity, so i need all init at same level. 

![image](https://cloud.githubusercontent.com/assets/3289976/20407860/bf741a80-acd8-11e6-86b9-16f85375a894.png)

**Comment by mattlewis92** [comment]
I think you're on an old version of this module, as `0.21.0`+ stacks the events next to each other. See the upgrade guide: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/CHANGELOG.md
