### ISSUE TITLE
[Weekview] Select range for the last day of week view doesn't work

### ISSUE THREAD

**Issue by wolleysesom** [mattlewis92/angular-bootstrap-calendar#496]
with on-date-range-select set, attempting to select timespan on the last day of the week view doesn't work.
Seems like the last cal-day-hour-part-spacer is pushed to the next row.

![untitled](https://cloud.githubusercontent.com/assets/9116521/20410841/d6dce832-acd3-11e6-9f12-5092012edd02.png)

[plunker](http://plnkr.co/edit/gbcy4YavXyrPGM3nvK2L?p=preview)

**Comment by mattlewis92** [comment]
Thanks for the repro, I'll get that fixed up in the next release!
