### ISSUE TITLE
How to customize new view?

### ISSUE THREAD

**Issue by qmy777** [mattlewis92/angular-bootstrap-calendar#498]
Just like year-view, day-view, month-view, week-view, can i customize a new view such as table-view? And i will use my own templates to show this view~

**Comment by mattlewis92** [comment]
I'd recommend building an alternate view outside of this component like so:

```
<my-custom-view ng-if="vm.view === 'table'"></my-custom-view>
<mwl-calendar ng-if="vm.view !== 'table'"></mwl.calendar>
```
