### ISSUE TITLE
double click timespan?

### ISSUE THREAD

**Issue by qmy777** [mattlewis92/angular-bootstrap-calendar#499]
Can i double click the timespan? 
Because one click may be easy to make wrong operations. :)
Thank you very much!

**Comment by mattlewis92** [comment]
The only way to do this is via a custom template. You'd need to change [this line](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthView.html#L18) from `ng-click` to `ng-dblclick`
