### ISSUE TITLE
Multiple columns per day (vertically) and week overlap

### ISSUE THREAD

**Issue by tassiocaique** [mattlewis92/angular-bootstrap-calendar#501]
Hey, I would like to know if I can do something like this in day view:
![](https://storage.googleapis.com/google-code-attachments/fullcalendar/issue-490/comment-7/multiresource.png)

And also this events overlap in week view: 
![](https://storage.googleapis.com/google-code-attachments/fullcalendar/issue-490/comment-7/multiresource_week.png) 

Thanks!

**Comment by bwobbones** [comment]
Yes, i have done this.  I made several calendars like this (excuse the jade...)

```
.resource-calendar(ng-repeat='resource in resources', )
            h3 {{resource.name}} 
            mwl-calendar(view='calendarView'....
```

**Comment by mattlewis92** [comment]
You make be able to implement something yourself like this using a custom template, however there is no out of the box support for this. If you need this functionality I'd recommend just using the full calendar module and simply lazy loading it plus jquery to mitigate most of the overhead of having to include the extra code.

**Comment by fabriciokerber** [comment]
Hey, samebody have this code?
