### ISSUE TITLE
In month and year views, remove start time for 'all day' events in slider

### ISSUE THREAD

**Issue by msawczyn** [mattlewis92/angular-bootstrap-calendar#502]
### Bug description / Feature request:
In the default slider template, the start time is displayed in the month and year sliders even when the event is an all-day event, which doesn't make a lot of sense. Alternatively, surround wiith span so that those who want to can css it out.

Thanks for the excellent work, btw. 

### Versions

Angular: 1.x

Calendar library: angular-bootstrap-calendar v0.27.1

Browser name and version: any

**Comment by mattlewis92** [comment]
The event title logic is handled by the `calendarEventTitle` service. You can override the logic here to give the use case you want:
```
calendarEventTitle.monthView = function(event) {
  if (event.allDay) {
    return event.title;
  }
  return event.title + ' (' + calendarDateFilter(event.startsAt, 'time', true) + ')';
}
```

You can see the source [here](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarEventTitle.js) for other views. Hope that helps! 😄

**Comment by msawczyn** [comment]
Helps a lot. Thanks for this.



-------- Original message --------
