### ISSUE TITLE
Yearly reccuring events not showing in month view of angular bootstrap calendar

### ISSUE THREAD

**Issue by cintucsabu** [mattlewis92/angular-bootstrap-calendar#504]
### Bug description / Feature request:
Hi,
I want to show an event which recurs yearly in month view of calendar. for example i want to show  my birthday(7 Dec 2016) on every year in month view of calendar. but as if now i am able to display the event only in year view and week view.  Actually, the event will display in 7 Dec 2016 in month view of calendar. but not displaying in the next years month view. That means, 7 Dec 2017, 7 Dec 2018 ...  and so on. 
[7 Dec 2017 BUG.docx](https://github.com/mattlewis92/angular-bootstrap-calendar/files/635803/7.Dec.2017.BUG.docx)

### Plunker
 
http://plnkr.co/edit/yeJmGLuZ9oSbrP3Uzhiu

### Versions

Angular:  1.5.8

Calendar library:  0.27.1

Browser name and version: google chrome 54.0.2840.99

**Comment by mattlewis92** [comment]
Ah it does look like recurring events got broken somewhere along the line. I'll fix it in the next release although I'd highly recommend using the rrule lib instead for generating recurring events - it's a far more stable and reliable way of creating them and gives you much more control.

**Comment by reshadf** [comment]
Do you have an example of how to use the rrule lib? And is it also suitable for weekly reccuring events? @mattlewis92

**Comment by mattlewis92** [comment]
@reshadf sure thing: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=recurring-events

The example includes how to do recurring weekly events, I'd also highly recommend doing the same for monthly and yearly recurring events.

**Comment by reshadf** [comment]
@mattlewis92  ah thanks! didn't see that one yet. I can't make it work with dynamically adding an event via the event editor as shown in the kitchen sink example. Do you have an example of that in the docs somewhere where I might have overlooked? Or perhaps you could point me in the right direction :) 
Something like this would be amazing if it worked.

     <td>
       <select ng-model="event.rrule" class="form-control">
         <option value="RRule.DAILY">dagelijks</option>
         <option value="RRule.WEEKLY">week</option>
         <option value="RRule.MONTHLY">maand</option>
         <option value="RRule.YEARLY">jaar</option>
       </select
     </td>

**Comment by cintucsabu** [comment]
Thank you @mattlewis92 .  I am waiting for the next release. In the mean while I can use RRule library.

**Comment by mattlewis92** [comment]
Should be fixed in 0.27.2, thanks for reporting! 😃

**Comment by cintucsabu** [comment]
Thanks @mattlewis92  for the fast response...
