### ISSUE TITLE
adding an event manually with recurrance

### ISSUE THREAD

**Issue by reshadf** [mattlewis92/angular-bootstrap-calendar#505]
Is there a way to use the recurring with rrule in combination with the kitchen sink event editor? I can't seem to get it to work. Could you extend the demo with an event editor please? :)

**Comment by mattlewis92** [comment]
Yup I can do this. 

Cont. from: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/504#issuecomment-265797095

**Comment by reshadf** [comment]
Thanks @mattlewis92

**Comment by reshadf** [comment]
@mattlewis92 Hey, I was curious about how the progress is going with the extended demo for recurrence? :) Is there a chance that there will be an update this week somewhere on that maybe?

**Comment by mattlewis92** [comment]
I will do what I can, most of my open source time is currently spent on porting this lib to angular2 at the moment. I will try and find some time over the next few days 😄

**Comment by reshadf** [comment]
Ok thanks a lot! That is actually the only functionality really necessary for my project since I want to create some sort of "schedule" that I don't have to make manually for every day in the future. :) Good luck! and thanks again.

**Comment by mattlewis92** [comment]
@reshadf Using event editor didn't make a lot of sense as each recurring event type (yearly, monthly, weekly) has different parameters. I suppose you could add a lot of dropdowns for each one, but hopefully you should get the idea.

**Comment by reshadf** [comment]
@mattlewis92 It's a bit clear now but I am still not sure how to save an event in the database (what parameters). I have created an api backend where my angular app talks to. But what should I be saving? The only things I save right now are 

> id, title, startsAt, entriesAllowed(this is a custom parameter), recursOn

Then I load the events from the api like in the following example but im not sure how to inject the rules separately in there. Do I have to save everything inside a rrule object? 

     vm.load = function() {

      $http({
        method: 'GET',
        url: baseurl + "/event",
        headers: {'Content-type': 'application/json'}
      })
      .then(function successCallback(response) {
        console.log(response);
        for(var i=0; i < response.data.data.length; i++) {

          vm.events.push({
            title: response.data.data[i]['title'],
            color: {
              primary: '#e3bc08',
              secondary: '#fdf1ba',
            },
            recursOn: response.data.data[i]['recursOn'],
            startsAt: moment(response.data.data[i]['startsAt']).toDate(),
            endsAt: moment(response.data.data[i]['startsAt']).clone().add(1, 'hours').toDate(),
            actions: actions,
            entries: response.data.data[i]['entries'].data,
            entriesAllowed: response.data.data[i]['entriesAllowed'],
            id: response.data.data[i]['id']
          });
        }
      }, function errorCallback(response) {
        console.log(response);
      });

    }

**Comment by mattlewis92** [comment]
This is the serialisable data you should be saving on your server (inc the rrule lib data): https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/docs/examples/recurring-events/javascript.js#L12-L34

Then you use the rrule lib to generate the events in a format that the calendar understands.
