### ISSUE TITLE
Takes three clicks for date change

### ISSUE THREAD

**Issue by bsherrill480** [mattlewis92/angular-bootstrap-calendar#507]
### Bug description / Feature request:

When attempting to change a date on the calendar, it's taking exactly three clicks to get the date to change. It could have to do with the build processes as I was not able to replicate it with plunker, and I am using browserify to import it.

### Link to minimally-working plunker that reproduces the issue

I can't seem to replicate it in plunker, here is my attempt, but it seems to work.
http://plnkr.co/edit/SMvD0glxoSlRl4NUczsH?p=preview

Here is a github pages where you can view the error:
https://bsherrill480.github.io/angular-bootstrap-calendar-bug/build/.
The code used to generate that page can be found here https://github.com/bsherrill480/angular-bootstrap-calendar-bug. The Relevant files would be in app/js/components/home/calendar.js and app/views/components/home/calendar.html

### Versions

Angular: ^1.6.0

Calendar library: ^0.27.1

Browser name and version: Chrome 54.0.2840.71

**Comment by mattlewis92** [comment]
Hi there, I tried your demo but it worked fine for me. Maybe it's a chrome extension interfering somewhere? Have you tried in private browsing / a different browser?

**Comment by bsherrill480** [comment]
@mattlewis92 

It's possible it's just local to me, but I've tried numerous browsers. 

Did you click on the plunker link, because that one **is** working. https://bsherrill480.github.io/angular-bootstrap-calendar-bug/build/ has the bug, but a similar setup to the plunker. I thought to include the plunker to help rule out possible variables based on the setup.

**Comment by mattlewis92** [comment]
Yes I only tried on the GitHub pages build - it was working fine for me there. I tried several times to reproduce but every time it worked on the first click.
