### ISSUE TITLE
Showing events in the editor based on the month

### ISSUE THREAD

**Issue by reshadf** [mattlewis92/angular-bootstrap-calendar#509]
Is there an 'out of the box' way to show the events in the event editor only when they are in the month you are currently viewing to avoid a big list?

**Comment by mattlewis92** [comment]
The event editor isn't part of this library, it exists solely for the demo, so WYSIWYG. You could easily just use the built in [angular filter](https://docs.angularjs.org/api/ng/filter/filter) with a function as the expression value to just include the events in the current month.
