### ISSUE TITLE
How Can I custom tooltips to show only title (without startsAt)?

### ISSUE THREAD

**Issue by WooCash9311** [mattlewis92/angular-bootstrap-calendar#510]
### Question / Feature request:

Hello, 

How Can I custom tooltips to show only title (without startsAt or with startsAt and endsAt) and if there is a possibility to add endsAt to bracket in events list after click on any day?

Regards.

### Versions

Angular: 1.5.8

Calendar library: 0.27.3

Browser name and version: All.

**Comment by mattlewis92** [comment]
To do this you just need to override the appropriate method from [this class](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarEventTitle.js).

```
.run(calendarEventTitle => {
  calendarEventTitle.monthViewTooltip = event => event.title;
});
```

Hope that helps!

**Comment by WooCash9311** [comment]
Yes, thank you very much!
