### ISSUE TITLE
Grunt ' wiredep ' task removing boostrap css after adding  angular-bootstrap-calendar

### ISSUE THREAD

**Issue by rameshind** [mattlewis92/angular-bootstrap-calendar#511]
### Bug description / Feature request:

Added dependencies of angular-bootstrap-calendar. But grunt  'wiredep' task removing bootstrap css entry from index.html

### Versions

Angular: 1.4.6

Calendar library: 0.27.4

Bootstrap version: 3.3.7

**Comment by mattlewis92** [comment]
Bootstrap is listed in `bower.json` so there's nothing actionable for me to fix there. Maybe you can force it via the overrides feature of wiredep: https://github.com/taptapship/wiredep#bower-overrides

**Comment by rameshind** [comment]
@mattlewis92  Thanks. It's working.
