### ISSUE TITLE
calendarSlideBox click event in angular-bootstrap-calendar

### ISSUE THREAD

**Issue by Anjaney26** [mattlewis92/angular-bootstrap-calendar#513]
I want click event of calendarSlideBox in angular-bootstrap-calendar.
![screen shot 2016-12-29 at 5 49 50 pm](https://cloud.githubusercontent.com/assets/8287273/21544051/e85fa65a-cdf1-11e6-9a2a-6ddf8cec81e5.png)

I also want to control event dots. Is it possible?

**Comment by mattlewis92** [comment]
You can use the [`on-timespan-click`](https://github.com/mattlewis92/angular-bootstrap-calendar#on-timespan-click) event to hook into when the slidebox is opened or closed.

To control the event dots you probably want to use a custom template, see [this example](https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=grouping-events)

Hope that helps!
