### ISSUE TITLE
at calendar week view get endAt  value

### ISSUE THREAD

**Issue by pahariyahimanshu11** [mattlewis92/angular-bootstrap-calendar#514]
Hi,

Thanks for this wonderful api it works easily and very fine.

Will you please help me out with how will i get endAt event variable value in week view, as of now it shows all 7 days of  week with start and end time and segmented in to minutes.

As per your day view template i want show same in week view, where user can see the Event Start and Event End time plotted area in their colour which i provided in event array.

"calendarConfig.showTimesOnWeekView = true; //Make the week view more like the day view, with the caveat that event end times are ignored."

With reference to this code i did it keeping my value TRUE but on the contrary i want event end time not to be ignore. So please help me resolve this issue, Thanks in advance.

**Comment by mattlewis92** [comment]
Event end times are ignored because handling overlapping events in the week view columns becomes very difficult, it works for some people that don't use event end dates, but I have no plans to support it.
