### ISSUE TITLE
Uncaught Error: Mismatched anonymous define() module: function

### ISSUE THREAD

**Issue by fpfcarvalho** [mattlewis92/angular-bootstrap-calendar#515]
Hi,

after version 0.23.0, this error occurred when compiled with requirejs:

_`Uncaught Error: Mismatched anonymous define() module: function (__WEBPACK_EXTERNAL_MODULE_12__, __WEBPACK_EXTERNAL_MODULE_76__, __WEBPACK_EXTERNAL_MODULE_78__) {`_

Any help why this happen?

**Comment by mattlewis92** [comment]
Sorry but I've never used requirejs before, would you be able to put together a simple repo that demonstrates your issue and I'll try and work out what's going wrong. Thanks! 😃

**Comment by tonogueira2** [comment]
Right here, says I

interact.js:13 Uncaught TypeError: Cannot read property 'module' of undefined
    at interact.js:13

module.exports = angular
	  .module('mwl.calendar', [])


Any .module is not recognized

**Comment by mattlewis92** [comment]
That error is thrown because angular is undefined, there's probably something misconfigured in your requirejs configuration. If you can create a repo that demonstrates it I can help more, otherwise I'm just guessing.

**Comment by mattlewis92** [comment]
This might help: http://requirejs.org/docs/errors.html#mismatch

Make sure `angular`, `moment` and `interact` are defined as dependencies of this lib in your require config. If you're still stuck I'd highly recommend posting a repo that reproduces your problem to stackoverflow where someone with better requirejs knowledge than me will be able to help. Happy new year! 😃

**Comment by fpfcarvalho** [comment]
Hi,
so, how can you explain that version 0.23.0 works and 0.24.0 not? In the version 0.23.0 you have:
})(this, function(__WEBPACK_EXTERNAL_MODULE_12__, __WEBPACK_EXTERNAL_MODULE_28__, __WEBPACK_EXTERNAL_MODULE_52__) {

and in the version 0.24.0 you have:
)(this, function(__WEBPACK_EXTERNAL_MODULE_12__, __WEBPACK_EXTERNAL_MODULE_76__, __WEBPACK_EXTERNAL_MODULE_78__) {

there is something you have changed that makes the plugin stop working :/
it's an enterprise project, so i can't give you code but i'll give you a print from the error:
http://prnt.sc/dq1lhf

**Comment by mattlewis92** [comment]
They’re just module ids generated by webpack, they’ll change if any new files are added or changed. I think that’s a red herring. You don’t need to share the entire project with me, just a minimal repo that demonstrates the issue in isolation.

Kind regards,
Matt Lewis
