### ISSUE TITLE
Cant add in my project

### ISSUE THREAD

**Issue by tonogueira2** [mattlewis92/angular-bootstrap-calendar#516]
### Bug description / Feature request:

I'm using requirejs and I tried to add the plugin and a module error occurs.

interact.js:13 Uncaught TypeError: Cannot read property 'module' of undefined
    at interact.js:13
(anonymous) @ interact.js:13
angular-bootstrap-calendar-tpls.js:92 Uncaught TypeError: Cannot read property 'module' of undefined
    at Object.module.exports (angular-bootstrap-calendar-tpls.js:92)
    at __webpack_require__ (angular-bootstrap-calendar-tpls.js:36)
    at angular-bootstrap-calendar-tpls.js:56
    at angular-bootstrap-calendar-tpls.js:59
    at Object.execCb (require.js:1693)
    at Module.check (require.js:881)
    at Module.<anonymous> (require.js:1136)
    at require.js:134
    at require.js:1186
    at each (require.js:59)

Follow my code to add.

"use strict";
(function () {
    require.config({
        baseUrl: "/app",
        paths: {
            'angular': "../scripts/angular",
            'angular-route': "../scripts/angular-route",
            'angular-sanitize': "../scripts/angular-sanitize",
            'angularAMD': "../scripts/angularAMD",
            'angular-local-storage': "../scripts/angular-local-storage",
            'angular-animate': "../scripts/angular-animate",
            'angular-aria': "../scripts/angular-aria",
            'angular-messages': "../scripts/angular-messages",
            'angular-material':"../scripts/angular-material/angular-material",
            'custom': "../scripts/custom",
            'jquery': "../scripts/jquery-3.1.1",
            'bootstrap': "../scripts/bootstrap",
            "toastr": "../scripts/toastr",
            "ngload": "../scripts/ngload",
            "mask": "../scripts/mask.min",
            "angular-ui-bootstrap": "../scripts/ui-bootstrap-tpls-2.3.2",
            "angular-i18n-pt-br": "../scripts/i18n/angular-locale_pt-br",
            "moment": "../scripts/moment",
            "lodash": "../scripts/lodash",
            "SVGMorpheus": "../scripts/svg-morpheus",
            "angular-material-icon": "../scripts/angular-material-icons",
            **"angular-bootstrap-calendar": "../scripts/angular-bootstrap-calendar-tpls",
            "interact": "../scripts/interact"**
        },
        shim: {
            "angular": ["jquery"],
            "angular-animate": ["angular"],
            "angular-aria": ["angular"],
            "angular-messages": ["angular"],
            "angular-material": ["angular"],
            'angularAMD': ["angular"],
            'ngload': ["angularAMD"],
            'angular-route': ["angular"],
            'angular-sanitize': ["angular"],
            'angular-local-storage': ["angular"],
            'bootstrap': ["jquery"],
            'custom': ["jquery", "bootstrap"],
            'toastr': ["jquery"],
            'mask': ["angular"],
            "angular-ui-bootstrap": ["angular", "bootstrap"],
            "angular-i18n-pt-br": ["angular"],
            "lodash": ["jquery"],
            "moment": [],
            "SVGMorpheus": [],
            "angular-material-icon": ["angular"],
            **"angular-bootstrap-calendar": ["angular", "bootstrap"],
            "interact": [],**
        },
        deps: [
            "custom",
            "app",
            "route-config",
            "app-configs",
            "angular-i18n-pt-br",
            "SVGMorpheus",
            "angular-material-icon"
        ]
    });
})();

and app inject:

"use strict";
define([
    "angularAMD",
    "custom",
    "angular-sanitize",
    "angular-route",
    "angular-local-storage",
    "mask",
    "angular-ui-bootstrap", "angular-animate", "angular-aria", "angular-messages", "angular-material", "angular-material-icon", **"angular-bootstrap-calendar"**],
    function (angularAMD) {
        var app = angular.module("app",
            ["ngSanitize",
                "ngRoute",
                "LocalStorageModule",
                "ui.mask", "ngMaterial", "ngMessages", "ngMdIcons", **"mwl.calendar", "ui.bootstrap"**]);

        return angularAMD.bootstrap(app);
    });

**It gave error in the whole project, it does not run anything gets white screen and the error in the console.

I had another calendar but I liked the mwl more**

### Versions

Angular: last

Calendar library: last

Browser name and version: chorme

**Comment by tonogueira2** [comment]
in add

angular: {
                exports: "angular"
            }

in shim... and Ok...

but now have 

Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: [object Object]

**Comment by mattlewis92** [comment]
I'm guessing that warning is due to how you're passing dates to the calendar - it only expects date objects - so make sure the `view-date` and `event.startsAt` and `event.endsAt` properties are actual date objects instead of strings e.g. `vm.viewDate = new Date(2017, 0, 1)`
