### ISSUE TITLE
SUGGESTION: adding (Resource) to the Calendar

### ISSUE THREAD

**Issue by IbrahimHd** [mattlewis92/angular-bootstrap-calendar#517]
Hi Matt,

Firt of all I would like to thank you for the great work you are doing!

I would suggest implementing **resource** feature to the calendar.
The _resource_ might be: person in-charge, location/room, ...
It will be great if the **resource** can be **FILTERABLE** through the UI.

Do you think that is feasible and can be done in the soon future?

Many thanks in advance!

**Comment by mattlewis92** [comment]
Sorry but this sounds like too specific a feature to add into this lib, you can probably implement it yourself but building features on top of this library based on the existing hooks the calendar exposes as well as maybe using a custom template.

**Comment by IbrahimHd** [comment]
Dear Matt,

Thank you for your feedback.
I'm not sure if I explained my suggestion in a good way and it's understood well.
In fact the "resource" feature is taken into account by most popular calendars/schedulers, and it's very common.
I believe this feature **extends** the usability of the calendar and makes it works like a **scheduler** for resources (people, equipment, vehicles, venues, ..etc)
Besides, it also can be used to help indicating the owner/creator of an event. Actually it's really useful and can be used for plenty of purposes.

I hope this feature will be taken into consideration for the next releases.
In case you still have some doubts, I suggest if we listen to some other opinions that may help us rating the importance of that feature.

Thank you once again.

**Comment by mattlewis92** [comment]
Sorry but I don't have any intention of supporting this - if you need this functionality then I'd recommend just using another calendar such as the full calendar: https://fullcalendar.io/docs/vertical_resource_view/groupByResource/

There is an angular directive for it as well: http://angular-ui.github.io/ui-calendar/

**Comment by IbrahimHd** [comment]
Ok it's fine, thank you.
