### ISSUE TITLE
Issue customizing templatte

### ISSUE THREAD

**Issue by Space69** [mattlewis92/angular-bootstrap-calendar#520]
### Bug description / Feature request:
Issue with building the whole project in order to custom the  calendarSlideBox

First of all, thank you very much for you great work.

I would like to customize it in order to add a ng-if on the <li ...> in order to only display special event. Thus I have customized the relevant template (calendarSlideBox.html) by adding the correct attrivute.

Then I want to rebuild your package with the following instruction: npm run build

But I have those errors:

`npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:min:exclude-templates"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular-bootstrap-calendar@0.27.4 build:min:exclude-templates: `webpack -p --config webpack.config.build.js --exclude-templates`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular-bootstrap-calendar@0.27.4 build:min:exclude-templates script 'webpack -p --config webpack.config.build.js --exclude-templates'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-bootstrap-calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p --config webpack.config.build.js --exclude-templates
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-bootstrap-calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-bootstrap-calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/Desktop/WebDev/bower_components/angular-bootstrap-calendar/npm-debug.log
`

So I want to install the package webpack from npm but I have this new error:

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
`

Could you help me. Which system are you using to build?

version: Latest with ubuntu

**Comment by mattlewis92** [comment]
I think your issue is caused because you're trying to run the npm scripts from the bower installed directory - they're only designed to be run when you clone the actual repo from github, as bower is set to remove unneeded files which will probably break the build.

However there's a simpler solution that doesn't involve forking this repo - instead you can just use the built in mechanism of overriding templates: https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=custom-templates

Hope that helps! 😄
