### ISSUE TITLE
Route issue

### ISSUE THREAD

**Issue by Space69** [mattlewis92/angular-bootstrap-calendar#521]
Thank you very much for your support and your help.

It looks like your tool override the route, could you help me by explaining where are defined those route, then I could modify it.

MfG

**Comment by mattlewis92** [comment]
This component shouldn't be doing anything to interfere with routing - please can you provide a plunker or a way of reproducing your problem. Thanks!

**Comment by Space69** [comment]
My main issue is that my routing is not use expect if I comment my scripts like this

`    
    
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="bower_components/angular-animate/angular-animate.js"></script>
    <script src="bower_components/angular-aria/angular-aria.js"></script>
    <script src="bower_components/angular-cookies/angular-cookies.js"></script>
    <script src="bower_components/angular-messages/angular-messages.js"></script>
    <script src="bower_components/angular-resource/angular-resource.js"></script>
    <script src="bower_components/angular-route/angular-route.js"></script>
    <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
    <script src="bower_components/angular-touch/angular-touch.js"></script>
    <script src="bower_components/moment/moment.js"></script>
    <script src="bower_components/angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls.js"></script>
    <script src="bower_components/interactjs/interact.js"></script>
    <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
    
    

        
        <script src="scripts/app.js"></script>
        <script src="scripts/controllers/main.js"></script>
        <script src="scripts/controllers/about.js"></script>
        <script src="scripts/controllers/register.controller.js"></script>
        <script src="scripts/controllers/login.controller.js"></script>
        
       
        


    
    <script src="scripts/js/agency.min.js"></script>`



and my calendar controller:`'use strict';
angular.module('webDevApp', ['mwl.calendar', 'ui.bootstrap', 'ngAnimate']).controller('CalendarController', function(moment, $scope, factoryCalendar) {

            $scope.calendar = factoryCalendar;

            console.log($scope.calendar);





            $scope.newEvent= {
                    title: "",
                    color: "",
                    startsAt:"" ,
                    startsHour:"",
                    endsAt: "",
                    endsHour:"",
                    draggable: true,
                    resizable: true,
                    status: "in progress",
                    actions: {}
                };

            });
`

**Comment by mattlewis92** [comment]
Sorry but I don't have any idea what's wrong from that, I'm not even really sure what your problem is. Please provide a *runnable* example that reproduces your problem. Thanks!

**Comment by Space69** [comment]
Are you using a ngview attribute within your tool?

**Comment by mattlewis92** [comment]
Personally I use ui-router, but I know of plenty of people using this lib successfully with ng-route.
