### ISSUE TITLE
Question: Custom template to create a multiweek plan

### ISSUE THREAD

**Issue by honkskillet** [mattlewis92/angular-bootstrap-calendar#524]
Awesome repo.  Thank you very much for all your efforts.

Can a-b-c be used to create a multiple week plan does not rely on a specific date.  For example, a university prof might have a 12 week plan semester (labeled weeks 1 thru 12) spelling out homework due.  Or this marathon training plan...
http://www.dailygarnish.com/wp-content/uploads/2011/01/Marathon-Training-Plan.jpg

Thank you

**Comment by mattlewis92** [comment]
For a use case like this I'd recommend just building your own week view component rather than trying to hack something in with a custom template as the UX deviates too much.
