### ISSUE TITLE
Module dependency failing after grunt build.  

### ISSUE THREAD

**Issue by rameshind** [mattlewis92/angular-bootstrap-calendar#525]
Fallowing is the bower.json configuration.

`{
  "name": "fosiness-ui",
  "version": "0.0.0",
  "dependencies": {
    "jquery": ">=2.1.0",
    "angular": "1.4.6",
    "angular-animate": "1.4.6",
    "angular-bootstrap": ">=2.4.0",
    "angular-cookies": "1.4.6",
    "angular-moment": "~0.10.1",
    "angular-resource": "1.4.6",
    "angular-route": "1.4.6",
    "angular-sanitize": "1.4.6",
    "angular-socialshare": "angularjs-socialshare#~2.3.0",
    "angular-touch": "1.4.6",
    "angular-ui-router": "~0.2.15",
    "animate.css": "~3.3.0",
    "bootstrap": "^3.3.7",
    "bootstrap-contextmenu": "~0.3.3",
    "checklist-model": "~0.2.4",
    "es5-shim": "~3.1.0",
    "fontawesome": "~4.3.0",
    "fullcalendar": "~2.4.0",
    "jquery.nicescroll": "3.6.7",
    "json3": "~3.3.1",
    "less": "~2.5.1",
    "ng-flow": "~2",
    "ng-intl-tel-input": "^1.4.0",
    "betsol-ng-intl-tel-input": "^1.3.2",
    "angular-ui-bootstrap-datetimepicker": "^2.0.3",
    "angular-bootstrap-calendar": "^0.27.5"
  },
  "devDependencies": {
    "jquery": ">=2.1.0",
    "angular-mocks": "1.4.6",
    "angular-scenario": "1.4.6",
    "bootstrap": "^3.3.7"
  },
  "appPath": "app",
  "resolutions": {
    "angular": "1.4.6",
    "intl-tel-input": "~6.0.4",
    "animate.css": "~3.3.0",
    "bootstrap": "^3.3.7"
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "less/bootstrap.less",
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js"
      ]
    }
  }
}
`

Locally app is working. But after doing grunt build `mwl.calendar` module is not loading. Please notice me where i did mistake.
Thanks.

**Comment by mattlewis92** [comment]
Sorry but I don't use grunt or bower, and there is not enough information provided to be able to reproduce your problem. Please use stackoverflow where you're more likely to get an answer.
