### ISSUE TITLE
Event that contain other events

### ISSUE THREAD

**Issue by azaharov** [mattlewis92/angular-bootstrap-calendar#526]
### Feature request:

Hi. Can I create a subevents in a master events? Something like this:
![image](https://cloud.githubusercontent.com/assets/21009739/22146347/642d7ad0-df15-11e6-8315-77368ddb1964.png)

And drag subevents to masters?

**Comment by mattlewis92** [comment]
Sorry there is no support for this, you might be able to implement it via a custom template or just build your own component for it.
