### ISSUE TITLE
Do not show days of the past on month view

### ISSUE THREAD

**Issue by llusem** [mattlewis92/angular-bootstrap-calendar#527]
Hello, 
As I can do to show in the monthly view, only days after the current. 

For example, if we are on January 23, show 4 weeks:
Week 4 [23/1/2017 - 29/1/2017]
Week 5 [30/1/2017 - 5/2/2017]
Week 6 [6/1/2017 - 12/2/2017]
Week 7 [13/1/2017 - 19/2/2017]

I've tried assigning a range of dates to the view-date variable, but I have not achieved it.

**Comment by mattlewis92** [comment]
Sorry there is no support for this, the UX of the month view is just to show a snapshot of the current month. There is a CSS class of `cal-day-past` added to days that have past, so you could apply some CSS rules to mark those days as disabled.
