### ISSUE TITLE
is it possible to get both the first and last date displayed on the calendar?

### ISSUE THREAD

**Issue by grimace** [mattlewis92/angular-bootstrap-calendar#528]
### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
You can use moment to do this:
```
const start = moment(vm.viewDate).startOf(vm.view).toDate();
const end = moment(vm.viewDate).endOf(vm.view).toDate();
```

**Comment by grimace** [comment]
Thank you for the response.  What I was interested in is, for the displayed calendar, the first date displayed on the page and the last date displayed on the page.  i.e. , in month view: Sunday Jan 1, to February 4, or if I hit next:  Sunday Jan 29, to Saturday Feb 4.  I'm looking for the begin displayed date and the end displayed date.

**Comment by mattlewis92** [comment]
For that just use the start and end of the week
```
const start = moment(vm.viewDate).startOf('month').startOf('week').toDate();
const end = moment(vm.viewDate).endOf('month').endOf('week').toDate();
```
