### ISSUE TITLE
A wish: event on click to empty days

### ISSUE THREAD

**Issue by DJHightower** [mattlewis92/angular-bootstrap-calendar#53]
This is not an issue but a feature-request.
Could you make day-cells without appointments clickable in month- and week-view? And then throw an event like "calendar-date-click(date)"? Maybe make empty months in year-view and hours in day-view clickable too.

A developer using your component could use this feature in two ways:
1) Use the calendar-date-click()-event to add a new appointment => no need for a "New Appointment"-button anymore.
2) Use the calendar-date-click()-event for actual date selection to replace components like DatePicker in some scenarios.

Greetings

**Comment by simpixelated** [comment]
Does [calendar-timespan-click](https://github.com/mattlewis92/angular-bootstrap-calendar#calendar-timespan-click) solve this for you?

**Comment by DJHightower** [comment]
Oh my fault. I really havent seen this. Thank you so much.
Gonna test that immediately.
