### ISSUE TITLE
Double click event

### ISSUE THREAD

**Issue by ghd9** [mattlewis92/angular-bootstrap-calendar#531]
Hello. I am using your Angular bootstrap calendar and I would like to know if it is possible to implement a double click event on a calendar day.

Thank you very much.

Greetings.

**Comment by mattlewis92** [comment]
You can implement this by modifying the templates and replacing `ng-click` with `ng-dblclick`. For example: http://plnkr.co/edit/86FfylsAaq8PRhBVcEOh?p=preview Hope that helps!
