### ISSUE TITLE
Using two templates at once

### ISSUE THREAD

**Issue by samueljacobsmith** [mattlewis92/angular-bootstrap-calendar#532]
### Bug description / Feature request:
Hi there, wondering if it is possible to use two templates at once. For example, the default calendarSlideBox.html and a customized version. So essentially if two events were in the slide box, one would be default and one would be custom. Is this possible in the current build? Thanks much!

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Sorry there is no support for this, you'd be better off just implementing the logic in your custom template like so:
```
<div>
  <div ng-if="condition === true">Template 1</div>
  <div ng-if="condition === false">Template 2</div>
</div>
```
