### ISSUE TITLE
Show past events on calendar (month view) possible?

### ISSUE THREAD

**Issue by intowhite** [mattlewis92/angular-bootstrap-calendar#533]
### Bug description / Feature request:

Is it possible to show past events on the calendar? Sorry if this is outlined anywhere.

**Comment by mattlewis92** [comment]
This is possible through the calendar config:

calendarConfig.displayAllMonthEvents = true;

Hope that helps! 😀

**Comment by intowhite** [comment]
Thanks, you da man!
