### ISSUE TITLE
Week view issue when calendarConfig.showTimesOnWeekView set to true

### ISSUE THREAD

**Issue by quang-nguyen** [mattlewis92/angular-bootstrap-calendar#534]
### Bug description / Feature request:
When calendarConfig.showTimesOnWeekView = true, the Week view displays only 1 event instead display all events of a day.

There are 3 events on Web, Feb 1, 2017, and the calendar display correctly in Month, Day view as expected. When switching to Week view, there is only 1 event displays.

### Versions
Angular: 1.6
Calendar library: 0.27
Browser name and version: Chrome 55

**Comment by mattlewis92** [comment]
It's a known issue, see this comment for a workaround: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/490#issuecomment-259976737
