### ISSUE TITLE
SQL server datetime is not recongnized

### ISSUE THREAD

**Issue by IbrahimHd** [mattlewis92/angular-bootstrap-calendar#535]
### Bug description / Feature request:
Hi Matt,

I'm storing the events in SQL Server and in particular `startsAt `and `endsAt `are stored in a _datetime_ data type field.
The calendar does not recognize the datatime format and it throws the following error:
_Event startsAt should be a javascript date object. Do `new Date(event.startsAt)` to fix it._
This means that I need to loop through all events in order to convert the datetime to a javascript date object.
My question is, why the datetime stored in SQL server is not recognized as a javascript date object?
Am I using the wrong SQL data type for a datetime data?

Thanks!
### Versions
Angular:  1.5.0
Calendar library: 0.24.0
Browser name and version: Chrome 55.0.2883.87 (64-bit)
SQL Server: 12 (2014)

**Comment by mattlewis92** [comment]
The reason for this is that your format is a string not a JavaScript Date object. There are many browser inconsistencies with how dates are constructed hence why I made it explicit that you as a user have to construct them yourself. A lot of people were relying on the calendar to construct invalid strings as dates and then wondering why they weren't displaying as the dates were invalid, hence why I went for this approach.

**Comment by IbrahimHd** [comment]
I appreciate if you can point me on how to get the datetime as a javascript date object rather than a string.
Actually I "google'd" this issue but all what I found are a sort of "hack" and say that datetime need to be converted in a query but I need a clean and standard approach that allows to retrieve datetime directly from the table as the field type is **datetime** not string!
Your support is highly appreciated!

**Comment by mattlewis92** [comment]
You can pass a second argument to JSON.parse to control the deserialisation of the json to parse dates as Date objects instead of strings: https://blog.mariusschulz.com/2016/04/28/deserializing-json-strings-as-javascript-date-objects

However as angular controls the deserialisation of events from the API it might be tricky to implement this, I'd recommend just looping over the events in your controller, it's only 4 lines of code:
```
vm.events = vm.events.map(function(event) {
  event.startsAt = new Date(event.startsAt);
  return event;
});
```

**Comment by IbrahimHd** [comment]
Thanks a lot Matt!
I'm already using the mentioned loop to fix that issue with my datetime data but I'm trying to find a better solution.
Thanks for your helpful info.
