### ISSUE TITLE
External draggable event in mobile

### ISSUE THREAD

**Issue by zigkasg** [mattlewis92/angular-bootstrap-calendar#537]
Hi,
Firstly, i would like to congratulate you for the great work of the calendar. Well done.

I do not know if it is something wrong with my configurations (ngtouch) but as long as the demo has the same issue, I decided to write a ticket here.

So, I am using your module and it works fine but on touch devices I cannot use draggable external events. They are stick and cannot be dragged.

Is there any fix for that?or any suggestion maybe?

Thanks

**Comment by mattlewis92** [comment]
It works for me on chrome on ios. What device / browser are you using?

**Comment by zigkasg** [comment]
chrome windows 10.
Do you have more instructions ?
I can only find this: ngtouch (optional, include if using the calendar on mobile devices. You will also need to enable $touchProvider.ngClickOverrideEnabled(true) on angular 1.5.0+)

**Comment by mattlewis92** [comment]
Sorry I'm a bit confused, I wouldn't normally associate windows 10 with being a touch device?

There isn't really anything else beyond calling `$touchProvider.ngClickOverrideEnabled(true)` that you need to do in order to enable touch events.

**Comment by mattlewis92** [comment]
Closing due to lack of information / it works fine for me
