### ISSUE TITLE
 Consume dates of an api

### ISSUE THREAD

**Issue by g4alejandro29** [mattlewis92/angular-bootstrap-calendar#538]
$scope.date={};
    $scope.date.date_st="2017-01-01";
    $scope.date.date_end="2017-02-02";
    proceedingService.getCalendar($scope.date).success(function(proceedings) {
            $scope.proceedings = proceedings;
    });

    vm.events = [
      {
        title: 'An event',
        color: calendarConfig.colorTypes.warning,
        startsAt: new Date(('proceeding.proceeding_date')),
        draggable: true,
        resizable: true,
        actions: actions
      }
    ];

**Comment by mattlewis92** [comment]
Please use stackoverflow for support, thanks.
