### ISSUE TITLE
Show/Hide Weekend option

### ISSUE THREAD

**Issue by senrav** [mattlewis92/angular-bootstrap-calendar#539]
### Feature request:
Is there an option available to show/hide weekend dates in the calendar? If no, any plans to introduce this feature?

**Comment by IdoiaArroyo** [comment]
I have the same problem. I need to hide weekend dates on week/day view, but I don't know to make it.

**Comment by mattlewis92** [comment]
Sorry there's no plans to support this, the calendar is built on the assumption that there are 7 days in a week. It wouldn't be possible without rewriting the whole thing from scratch. The closest thing I can offer is to use the `cal-day-weekend` helper class that is added to weekend days to show them in a disabled state:
<img width="1051" alt="screen shot 2017-02-19 at 18 25 56" src="https://cloud.githubusercontent.com/assets/6425649/23105055/ecab191c-f6d0-11e6-8c34-0a2f4a31d565.png">
