### ISSUE TITLE
Make logic in the calendarHelper less convoluted

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-bootstrap-calendar#54]
Return a flat array instead of a pre-generated grid of dates, and use limitTo and a custom offset filter to handle chunking up dates into rows for the month and year view. This would also be a good time to add unit tests.

**Comment by Balrog30** [comment]
Is there a specific part that you'd like to refactor?  Most of the pieces are so straight-forward that they don't even need comments.

The only pieces that are a big large are the `getMonthView()`, `getWeekView()` and similar functions.  They're just doing a bit much for one function, I would think.  Maybe some common elements could be broken out, or perhaps part of it could be moved to controller logic for these views?

What did you have in mind?

**Comment by mattlewis92** [comment]
This is now done and the code base has become a lot simpler because of it :)
