### ISSUE TITLE
Show Multi-day event in Month view like in week view

### ISSUE THREAD

**Issue by senrav** [mattlewis92/angular-bootstrap-calendar#540]
### Feature request:
Is there a way to show multi-day event in Month view like in week view ( a bar spanning across multiple days). Also the option to customize the styling.

**Comment by mattlewis92** [comment]
Sorry there's no support for this, I looked into it before as it's a nicer UX but it was too complicated to implement.

**Comment by marxmate** [comment]
Hi!

I was tricking a little with css and got this: 

![image](https://cloud.githubusercontent.com/assets/24889045/26360275/f8d7acf0-3fd7-11e7-825f-554e198e0fec.png)

If you want to do this: You need to use a js function in the constructor, where you add the cssClass for all events (e.g. "from00to01") and then you can get these classes and set the width and margin of the events in that class. Its a little hacky, but it works for me ...
