### ISSUE TITLE
calendarConfig is not defined

### ISSUE THREAD

**Issue by zaffydude** [mattlewis92/angular-bootstrap-calendar#542]
### Bug description / Feature request:
I am getting a "calendarConfig is not defined" error. Can you advise what's the obvious mistake I am making? Thanks in advance.

### Versions

Angular: 1.6

Calendar library: 0.28.0

Browser name and version: chrome 55.0.2883.x

**Comment by mattlewis92** [comment]
It's hard to say without seeng any code but I'm guessing you're not injecting it into your controller?
