### ISSUE TITLE
Programmatically refreshing display (i.e. triggering cellModifier to be called again) of the angular bootstrap calendar (mwl-calendar)

### ISSUE THREAD

**Issue by Kradothar** [mattlewis92/angular-bootstrap-calendar#543]
### Bug description / Feature request:

The only way to trigger the cells in the calendar to redraw to my knowledge is to switch views. See [here](http://stackoverflow.com/questions/40553223/programmatically-refreshing-display-i-e-triggering-cellmodifier-to-be-called-a)

Would it be possible to add this ability as a feature?

### Versions

Angular:  v1.5.8

Calendar library: v0.24.0

Browser name and version: Chrome

**Comment by mattlewis92** [comment]
You can do this already by doing `$scope.$broadcast('calendar.refreshView')` - [source](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarMonth.js#L28-L48). Hope that helps! 😄

**Comment by Kradothar** [comment]
Brilliant, thanks!
