### ISSUE TITLE
Event ball not displayed when dragging it to the last week of the month

### ISSUE THREAD

**Issue by rserentill** [mattlewis92/angular-bootstrap-calendar#545]
### Bug description / Feature request:
In the Month view, when dragging an event to the last week of the month (the last row of days) the counter is increased but the event ball doesn't appear, and if you click on the day, the cell with events info is not displayed.

It works fine for the other rows of the month.
This problem also happens on the demo page.

### Versions

Angular: 1.5.5

Calendar library: 0.28.0

Browser name and version: Google Chrome 56.0.2924.87 (64-bit)

**Comment by rserentill** [comment]
Ok, I just realized that this is the expected behavior for the event ball, as I was dragging the event to the next month.

The fact that the counter is being displayed but not the event ball confused me.

I'll leave the issue open in case you consider a bug the fact that the counter is being displayed (and not the event ball) when an event is dragged to any day of the next month.

If not, please close it and accept my apologies.

**Comment by mattlewis92** [comment]
Ah you're right, I think the total count should be hidden unless `calendarConfig.displayAllMonthEvents = true` is set. Will get that fixed up in the next version! 😄
