### ISSUE TITLE
Passing Parent Controller Data to uib-popover in Month date cell

### ISSUE THREAD

**Issue by suzondas** [mattlewis92/angular-bootstrap-calendar#546]
### Bug description / Feature request:
Hi, first of all I thank you very much for this nice library.
BTW, i added bootstrap ui popover in Calendar like :
` <div
      mwl-droppable
      on-drop="vm.handleEventDrop(dropData.event, day.date, dropData.draggedFromDate)"
      mwl-drag-select="!!vm.onDateRangeSelect"
      on-drag-select-start="vm.onDragSelectStart(day)"
      on-drag-select-move="vm.onDragSelectMove(day)"
      on-drag-select-end="vm.onDragSelectEnd(day)"
      class="cal-month-day {{ day.cssClass }}"
      ng-class="{
    'cal-day-outmonth': !day.inMonth,
    'cal-day-inmonth': day.inMonth,
    'cal-day-weekend': day.isWeekend,
    'cal-day-past': day.isPast,
    'cal-day-today': day.isToday,
    'cal-day-future': day.isFuture,
    'cal-day-selected': vm.dateRangeSelect && vm.dateRangeSelect.startDate <= day.date && day.date <= vm.dateRangeSelect.endDate,
    'cal-day-open': dayIndex === vm.openDayIndex
  }"
      popover-template="'signUpsPpopover.html'" popover-placement="right" popover-trigger="click outsideClick">
`
I want to pass some data to the popover template from my controller that contains the calendar directive.  
Thanks in Advance

### Versions

Angular: 
1.6.2
Calendar library: 
0.27.4
Browser name and version: 
Chrome 56.0.2924.87

**Comment by mattlewis92** [comment]
You can pass the parent controller through to your custom template via the `template-scope` [option](https://github.com/mattlewis92/angular-bootstrap-calendar#template-scope). Hope that helps! 😃
