### ISSUE TITLE
Add option to get events from external server

### ISSUE THREAD

**Issue by burtek** [mattlewis92/angular-bootstrap-calendar#547]
It would be great to be able to provide function instead of plain array as the source of events. The events are stored on external server and getting all events is not the best idea, so having a possibility to get events from server for current view (i.e. view start/end dates) or at least having a callback run when the view is changed, would be appreciated.

**Comment by IbrahimHd** [comment]
+1

**Comment by mattlewis92** [comment]
As the controls aren't part of this component you can implement this by loading the view events whenever the user changes the view with the controls. Example plunker: http://plnkr.co/edit/bIki3IcMgqdHUTRap2ai?p=preview

Hope that helps! 😄

**Comment by burtek** [comment]
Just to make sure I get it correctly: I have to externally save information what are the currently displayed dates, or is there a method to get the date range from the component?

**Comment by mattlewis92** [comment]
If you look at the end of the `example.js` file in the plunker you'll see how you can get the dates to load the view events for:
```
vm.loadEventsFromServer = function(date = vm.viewDate, view = vm.calendarView) {
      var start = moment(date).startOf(view).toDate();
      var end = moment(date).endOf(view).toDate();
      console.log(start, end);
      // Now load your events from your API from this date range and update the events array.
    };
```
