### ISSUE TITLE
Disable drop event for certain time slot

### ISSUE THREAD

**Issue by rajkotgire** [mattlewis92/angular-bootstrap-calendar#548]
How not to allow certain time slot to be drop able target, e.g During drag and drop of appointments i want to <b>DISABLE</b> lunch hrs as drop able target.

**Comment by burtek** [comment]
Why not use `on-event-times-changed` directive and then detect if the hours are not permitted - and if so, revert the change?

**Comment by mattlewis92** [comment]
What @burtek said is correct, here's an example for you: http://plnkr.co/edit/dfrFPCwz7YoPJKKBKSfO?p=preview Hope that helps! 😄
