### ISSUE TITLE
Is there a way to display the calendar with only one month?

### ISSUE THREAD

**Issue by optimacycorp** [mattlewis92/angular-bootstrap-calendar#549]
### Bug description / Feature request:

Can we get a calendarConfig that limits the display of the month view?  (from 0.6.0 which only displayed one month at a time.

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Sorry I'm not sure I follow you, do you mean disabling navigating between the previous and next months?

**Comment by optimacycorp** [comment]
Sorry if I wasn't clear.  The way the old calendar displayed was just one month with the extra days as blanks.  The new calendar displays (for March for example)  February 26,27,28 and April 1st.

**Comment by mattlewis92** [comment]
Ah ok, there are helper classes added to those days, just add a CSS rule to set the contents to display: none for any cells with the class cal-out-month.
