### ISSUE TITLE
Configurable Event Count Badge

### ISSUE THREAD

**Issue by Balrog30** [mattlewis92/angular-bootstrap-calendar#55]
I have mixed feelings about the new event count badges.  I generally like the idea, but in my use case it can be a big confusing.  My calendar presents a list of time slots, some empty and some filled.  Displaying the number in the way that this feature does is confusing for my users, and empty timeslots are included in this count.  See the attached screenshot:

![screenshot 2015-04-07 15 39 54](https://cloud.githubusercontent.com/assets/4421371/7031917/17263fc8-dd3d-11e4-857e-c1f721cbf399.png)

I would propose that you have at minimum an option to turn this feature off completely.  Even better would be to also have a property of events that would not count that particular event in this count.  Kind of an ignore flag or something.

**Comment by mattlewis92** [comment]
Every element in the calendar purposefully has classes set in the HTML. So you can hide it like so:
```css
.cal-events-num {
    display: none;
}
```

I can make the event types configurable easily enough as well.

**Comment by simpixelated** [comment]
:+1: for configurable even types

**Comment by Balrog30** [comment]
I'm working on a pull-request for this feature.  It will add a property to the event to determine whether it should be counted for the badge.  Would just like an opinion of what to call it.

I think of a badge like that as bringing attention to a new event, or calling it out as a reminder.  In that light it could be call `isNew`, `isReminder`, etc.

You could also think of it as a property to hide something that is there by default in which case the property name could be something like `hide`, `hideCount`, `hideNotification`, `noCount`, etc.  If I were just writing this for my own use case it would probably be something like `isEmpty`, as my calendar shows time slots that have yet to be filled.

**Comment by mattlewis92** [comment]
How about incrementsBadgeTotal?

**Comment by Balrog30** [comment]
I'll give that a try, and should have something to show by the weekend.

**Comment by Balrog30** [comment]
Yup.  That's pretty much exactly what I was going to write.  Thanks!

**Comment by Balrog30** [comment]
I had a chance to test this out and found one small problem.  The `ng-show` on the badge is tied to `events.day.length`, causing a badge with a zero to be displayed if none of the event increment the badge count.

I would usually do something like `ng-show="countEvents(day.events)>0"`, but this might not be so simple with a filter.  I think you'd need to expose the filter on `$scope`, but I've never tried this before.
