### ISSUE TITLE
Scheduler with angular bootstrap calendar

### ISSUE THREAD

**Issue by justinhomes** [mattlewis92/angular-bootstrap-calendar#550]
Is there any example for implementation for scheduler of resources using this plugin? 
i was looking for something that can scheduled calendar appt for a doctors office, where there can be multiple drs or multiple rooms etc.

**Comment by mattlewis92** [comment]
Sorry there's no support for anything like this in this component.

**Comment by burtek** [comment]
I don't think it is possible with this package. I'd rather try with sth like [this](https://www.npmjs.com/package/angular-weekly-scheduler)
