### ISSUE TITLE
Multiple "3AMs"

### ISSUE THREAD

**Issue by asciutto990** [mattlewis92/angular-bootstrap-calendar#552]
### Bug description / Feature request:
There are multiple 3AMs on the day view. I am seeing this, and it is also visible for one of your examples:
https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=side-time-position

### Versions

Angular: 1.6.2

Calendar library: Latest

Browser name and version: Google Chrome

**Comment by mattlewis92** [comment]
That's odd, I can't see it myself, can you send a screenshot of it?

**Comment by asciutto990** [comment]
![angular_bootstrap_calendar_3ams](https://cloud.githubusercontent.com/assets/6344052/23833118/a339dfb4-0717-11e7-9ff3-80ac32ab1e80.JPG)

**Comment by burtek** [comment]
@asciutto990 It may be due to the daylight saving time change. What country and timexone are you in?

**Comment by asciutto990** [comment]
Very good point. I believe that is it. My timezone Eastern Standard Time

On Mar 12, 2017 1:25 PM, "burtek" <notifications@github.com> wrote:

@asciutto990 <https://github.com/asciutto990> It may be due to the daylight
saving time change. What country and timexone are you in?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mattlewis92/angular-bootstrap-calendar/issues/552#issuecomment-285959632>,
or mute the thread

**Comment by mattlewis92** [comment]
Great shout @burtek, it does appear to be because of the DST change which is the the second sunday in march (today) in EST according to google 😄

**Comment by burtek** [comment]
Glad I could help. FYI I wasn't able to reproduce this bug for CET for last weekend of March, but will try to catch that on that date.

**Comment by mattlewis92** [comment]
I can reproduce it in my timezone (BST) 
<img width="781" alt="screen shot 2017-03-12 at 17 47 03" src="https://cloud.githubusercontent.com/assets/6425649/23834287/f1423128-074b-11e7-9ec1-9eb48c96eee7.png">

**Comment by burtek** [comment]
Yup, I got it now.

**Comment by mattlewis92** [comment]
On a side note @burtek as you've been doing a great job of answering issues lately, I've added you as a collaborator if you want it so you can close them as well. Thanks for your help! p.s. are you on twitter? If so you can DM me any time you have questions 😄

**Comment by burtek** [comment]
Thanks, I do appreciate the recognition :) I do have twitter, but I don't use it - but I'll DM you in case I have a question :)
