### ISSUE TITLE
Problem, icon of the events in view month

### ISSUE THREAD

**Issue by g4alejandro29** [mattlewis92/angular-bootstrap-calendar#553]
Angular: 

Calendar library: 

Browser name and version: 
![2017-03-13 17_34_49-photos](https://cloud.githubusercontent.com/assets/17556823/23879576/930399bc-0813-11e7-9d12-d737e375a277.png)

I'm stuck with this problem I do not know if I had noticed in advance the application works very well it's just this little problem when there are several events in a day in the month view leave that day and occupy space in another commented this error because let's say yes There would be several events one day, I attached an image

**Comment by burtek** [comment]
Wow, you must be really busy :D

I think it'd be nice to have up to 25 dots and then sth like "+ 22"...

**Comment by g4alejandro29** [comment]
![2017-03-14 00_22_55-](https://cloud.githubusercontent.com/assets/17556823/23888232/71006b54-084c-11e7-93ab-b0f197903999.png)
Problem solved
