### ISSUE TITLE
Event not displayed properly when resizing it in the week view with calendarConfig.showTimesOnWeekView = true

### ISSUE THREAD

**Issue by aymen00744** [mattlewis92/angular-bootstrap-calendar#554]
Hello, thank you for this great api
I have a problem with displaying the event after resizing it in the week view.

### Week View
`mwl-resizable="tue"`
` resize-edges="{top: true, bottom: true}"`
`on-resize-end="resizeWeekView(eventRow.event, edge, y / 30, vm.dayViewSplit)"`

### Angular controller 
```
$scope.resizeWeekView = function(event, edge, weekMinuteDiff, dayViewSplit) {
      var start = moment(event.startsAt);
      var end = moment(event.endsAt);
      var absWeekMinuteDiff = Math.abs(weekMinuteDiff) * dayViewSplit;
      if (edge === 'start') {
        if(weekMinuteDiff < 0){
          start.subtract(absWeekMinuteDiff, 'minutes');
        }else if(weekMinuteDiff > 0){
          start.add(absWeekMinuteDiff, 'minutes');
        }
      } else {
        if(weekMinuteDiff > 0){
          end.add(absWeekMinuteDiff, 'minutes');
        }else if(weekMinuteDiff < 0){
          end.subtract(absWeekMinuteDiff, 'minutes');
        }
      }
      event.startsAt = start.toDate();
      event.endsAt = end.toDate();
      //minuteDuration.get is to get the duration between startsAt and endsAt of the event
      event.duration = minuteDuration.get(event.startsAt, event.endsAt );
     //The new event is in the event variable
     //call the  vm.eventTimesChanged
    };
```

If i call the vm.eventTimesChanged function, the event will be updated. The problem is the new value of that event is not appearing in the week view directly. But if i change the view to Day, the changes appear perfectly even if i return in the week view the new event appear us i want. 
Any help? Thank you. 

### Versions

Angular: 1.6.1

Calendar library: 0.28.1

Browser name and version: google chrome 56

**Comment by burtek** [comment]
The week view DEOS ignore endtimes, so it won't show the correct size of an event. I'm working on a fix here.

**Comment by maxgerman1989** [comment]
i have the same problem.. did anyone got a solution for it? @burtek ?

**Comment by burtek** [comment]
PR #569 is in progress, but it's not mine and I'm unable to tell whether or not it's gonna be resolved and accepted.

**Comment by maxgerman1989** [comment]
Ok, thanks... it's strange that on the demo everything is working but some users have this problem that only the resizing of an event on the week page is doing problems.

**Comment by burtek** [comment]
As I said - until PR #569 is accepted, the week view will ignore event endTimes, so the function won't work properly.
