### ISSUE TITLE
month view and timezone

### ISSUE THREAD

**Issue by coolbombom** [mattlewis92/angular-bootstrap-calendar#555]
Hi

how do i get the utc date when clicking on a date instead of the timezone date.. im in timezone +1 and when clicking on 14/3 i get 13/3-23:00 as the event date ... my problem is when i sent this to my backend i have field in my DB with a date type, and when that is saved it saved as 13/3 and not the 14/3 which i want!

kind regards
c_bb

**Comment by burtek** [comment]
You can use moment (as [here](https://github.com/mattlewis92/angular-bootstrap-calendar#internationalization-and-localization)) nad configure it to use UTC time for displaying time.

**Comment by coolbombom** [comment]
Hi Burtek

can't seem to get it to work .. could i get you to make a plunker example? I would appreciate that very much

kind regards
c_bb

**Comment by burtek** [comment]
I will, but please provide me with exact info what do you want to achieve? You want to have both calendar and events displayed with correct date and time (what timezone?) and data saved on server in UTC?

**Comment by burtek** [comment]
I'm closing this issue, should you need help, provide details and I'll be more than happy to help you.

**Comment by wootwoot1234** [comment]
> You can use moment (as here) and configure it to use UTC time for displaying time.

Can you show me how to configure it to use UTC time?  I want to be able to set the calendar's timezone.  I see how to set it to use moment but I can't see how to set the display timezone.

Thanks!

**Comment by wootwoot1234** [comment]
> You can use moment (as here) and configure it to use UTC time for displaying time.

@burtek Can you show me how to configure it to use UTC time?  I want to be able to set the calendar's timezone.  I see how to set it to use moment but I can't see how to set the display timezone.

Thanks!
