### ISSUE TITLE
Hello, 

### ISSUE THREAD

**Issue by yasserht** [mattlewis92/angular-bootstrap-calendar#556]
Hello, Im trying to use the day view and week view at the same time, the problem is that the day view is vertical and the weekview is horizontal. is there any way i can make the weekview vertical as well >? Thanks

**Comment by burtek** [comment]
Could you describe the problem? At the moment you provided no info at all.

**Comment by yasserht** [comment]
sorry my mistake , i just updated it

**Comment by burtek** [comment]
You can use week view with `calendarConfig.showTimesOnWeekView = true;`, see [https://github.com/mattlewis92/angular-bootstrap-calendar#configuring-the-calendar-default-config](docs)

**Comment by burtek** [comment]
You can use week view with `calendarConfig.showTimesOnWeekView = true;`, see [https://github.com/mattlewis92/angular-bootstrap-calendar#configuring-the-calendar-default-config](docs). Example: [plunker](http://plnkr.co/edit/JX9cHBrrR9BnmGkwgyiB?p=preview). Is it what you wanted?

**Comment by yasserht** [comment]
I already tried it, that only adds the time to the week view, I want the week view to be horizontal

**Comment by burtek** [comment]
What do you mean by horizontal? In your fisrt post you said you want it vertical. Could you please specify what do you need exactly?

**Comment by yasserht** [comment]
yeah yeah vertical, instead of seeing hours, you see days of that week

**Comment by burtek** [comment]
So you want something like the dayView, but with days of month instead of hours? For my knowledge this is not possible with this library at the moment.

**Comment by yasserht** [comment]
exactly but is it possible to modify ?

**Comment by burtek** [comment]
You can modify this library for your own use with respect to [license conditions](https://github.com/mattlewis92/angular-bootstrap-calendar#license).

**Comment by yasserht** [comment]
will do, thank you for your help. I wonder where i can modify that, i mean which file?

**Comment by burtek** [comment]
As far as I'm concerned this is not a straight-forward modification. Best option would be to create new view with it's own controller. The controllers are in `src/directives/`, while the views itself in `src/templates/`.

**Comment by yasserht** [comment]
thank you so much, that was helping
