### ISSUE TITLE
Wrong year for calendarTitle.week when dow = 7

### ISSUE THREAD

**Issue by georgeos** [mattlewis92/angular-bootstrap-calendar#557]
Just to let you know. In the issue [#379](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/379) is mentioned the calendarTitle service, specifically for the week.

I guess the year is wrong when dow = 7, because if you try 1 January 2018, user will get week: 1 and year: 2017. As the week starts in 31 december 2017.

`return calendarConfig.titleFormats.week
        .replace('{week}', moment(viewDate).isoWeek())
        .replace('{year}', moment(viewDate).startOf('week').format('YYYY'));`

**Comment by mattlewis92** [comment]
Thanks for reporting, it should be fixed in 0.28.3 😄
