### ISSUE TITLE
how to add a new view

### ISSUE THREAD

**Issue by yasserht** [mattlewis92/angular-bootstrap-calendar#558]
Hello, 
How can I link a new view I modified to replace weekview ?

**Comment by mattlewis92** [comment]
You can reference the view outside of the calendar:
```
<my-custom-week-view ng-if="vm.view === 'myCustomWeekView'"></my-custom-week-view>
<mwl-calendar view="vm.view" ng-if="vm.view !== 'myCustomWeekView'"></mwl-calendar>
```
Hope that helps! 😄

**Comment by yasserht** [comment]
Thank you for your reply 😃
So inside the first one i put my modified view, and the second one is to show it right? 
There are already 4 views you can control with buttons

**Comment by burtek** [comment]
The first one is a directive, so You put just that code and it should work as is (provided that you included your JS file in the document).

**Comment by yasserht** [comment]
What about the html file of my view?

**Comment by burtek** [comment]
As I mentioned [here](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/556#issuecomment-287437063), the views should be in `src/templates/`.
