### ISSUE TITLE
Quick Links and Events

### ISSUE THREAD

**Issue by IDavidCP** [mattlewis92/angular-bootstrap-calendar#559]
First of all, awesome job with this calendar! Is really useful, complete and powerful.

There are three things I would like to ask:

1.- Is there a way to create a side calendar in month view so I can use as quick links? In other words, I want to use a second calendar to change the days in the main calendar. The main calendar would be in day view and the second in month view.

2.- How can I display the number of total events of the current day view?

3.- For this calendar I'm taking the events to display from a database. So, as soon as the page loads I request ALL the events in the DB, your directive takes care of sorting them pretty well, the thing is that I'm thinking that after a couple of months when I have hundreds of events in the DB the process will become really slow. Is there a way I can tell the controller in what day is the user so I request the events of only that day? Same for month view, can I tell what month to request the events of that month only?

**Comment by burtek** [comment]
1 - you mean something like in Coocle Calendar?
2 - would have to look at this
3 - have a look at [this post](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/547#issuecomment-284167894)

**Comment by burtek** [comment]
1 - I guess the best option would be to create a simple table with dates as links changing `vm.viewDate` (I'd use `moment` for simpler generating the table)

**Comment by burtek** [comment]
1 - you mean something like in Google Calendar? I guess the best option would be to create a simple table with dates as links changing `vm.viewDate` (I'd use `moment` for simpler generating the table)

2 - nothing comes to my mind at this time

3 - have a look at [this post](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/547#issuecomment-284167894) in issue #547

**Comment by IDavidCP** [comment]
Not sure if simple links would work. For example, the buttons to switch days are using the mwl-date-modifier directive, but they send the next or previous date with decrement or increment. Another option to tell the directive to switch to a custom date maybe?

**Comment by burtek** [comment]
Why not? Have a look at [this plunker](http://plnkr.co/edit/NxXuSdwFEPFN1ti9JmMI?p=preview). Of course it's dirty and not pretty, but shows how it would work.

**Comment by mattlewis92** [comment]
For 2 you can use [this helper method](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarHelper.js#L85-L89) to get the current view events:
```
const totalEvents = calendarHelper.getEventsInPeriod(vm.viewDate, 'day', vm.events).length;
```

**Comment by IDavidCP** [comment]
Thanks for the helper, and the suggestion dor number 3.
Any ideas guys how to solve number 1? @mattlewis92

**Comment by burtek** [comment]
One more idea from me - you can create small calendar with month view and use it's [on-timespan-click](https://github.com/mattlewis92/angular-bootstrap-calendar#on-timespan-click) property to detect the onclick event and then change bigger calendar's `vm.viewDate`. Look at [this example](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=timespan-click) how `on-timespan-click` works.

**Comment by mattlewis92** [comment]
You could just use a standard date picker to select the date maybe?

**Comment by IDavidCP** [comment]
Hey guys, bothering with silly questions again.
About the total events in current period, how can I use the helper? Do I need to download the js and include it just like the angular-bootstrap-calendar-tpls-min.js file?

**Comment by IDavidCP** [comment]
@burtek thanks for suggesting a new calendar with month view and passing the date with on-timespan-click, this works great. Your idea of just making links with moment works good too, however, with the new calendar I'm able to switch between months pretty easy and I can disable switching views in the small calendar.

**Comment by burtek** [comment]
Just add `calendarHelper` dependency to your controller, as you'd do with other angularJS dependiences.

Glad I could help :)

**Comment by IDavidCP** [comment]
Hey guys.
I get some errors trying to use the helper, could you please help me one more time?

> Uncaught ReferenceError: require is not defined at calendarHelper.js:3
> calendarHelper.getEventsInPeriod is not a function

also, @burtek going back to your code for the calendar that you made, what would be the best way to add other two calendars? Then you would have three months in a row

**Comment by burtek** [comment]
As for those errors, you'll need to wait for @mattlewis92's answer.

As for three calendars, I think I'd add three identical `<mwl-calendar>` tags with different `view-date` parameters and then add a `$scope.$watch`er in controller. Look at `index.html:64-116` and `example.js:11-20` in [this plunker](http://plnkr.co/edit/S4Dybwsdu1vL0cEDXULZ?p=preview). It kinda looks dirty, but it's the simplest example I could think of at 3 a.m. while pretending to be learning for mid-term ;) But I guess it's good enough for most projects.
The best solution would actually be to pass all three variables to @mattlewis92's `mwl-date-modifier` directive through the increment/decrement buttons, but I have no clue if that's possible at the moment.

**Comment by IDavidCP** [comment]
For the mini calendar I just added three in a row and increased 1 by 1 the values passed to `monthDate` as you did with the first calendar. But that is not optimized at all. Plus I had to add an extra row for the months like April, one week was missing.

**Comment by burtek** [comment]
Ah, you meant three months of the mini-calendar! I misunderstood you, sorry for that. I'm unable to think any more at this moment, but I'll try to think of something later today.

**Comment by IDavidCP** [comment]
Yeah I decided to give your mini calendar a chance 😄 Some css can make it look pretty and even similar to the `mwl-calendar`

**Comment by IDavidCP** [comment]
@burtek did you have a chance to try something?
@mattlewis92 do you know why am I getting those errors with the helper?
