### ISSUE TITLE
calendarWeekView add events 

### ISSUE THREAD

**Issue by korengal** [mattlewis92/angular-bootstrap-calendar#560]
###  First of all, thanks a lot  for your good work!!! 

My question is if there is a way in the calendar to add a new event by clicking on the calendar view?

The best example for it is to look how google calendar is working in weekly view.

Thanks.

**Comment by burtek** [comment]
You can use [on-timespan-click](https://github.com/mattlewis92/angular-bootstrap-calendar#on-timespan-click) property to detect the click and create an event with the date and time. Look at [this example](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=timespan-click) - clicking on date/time displays them in the div bove the calendar.
