### ISSUE TITLE
Change badgeTotal style

### ISSUE THREAD

**Issue by shaozi** [mattlewis92/angular-bootstrap-calendar#561]
Hi,

Is there a way to customize the color of badgeTotal? in the cellModifier function?

**Comment by mattlewis92** [comment]
Yup, the cell modifier is the way to go. Add a cssClass to the day cell and then style the badge accordingly, for example: http://plnkr.co/edit/UKmDh86GAYkEPdkXWzYb?p=preview

Hope that helps! 😄

**Comment by shaozi** [comment]
Cool! Works like a charm!
