### ISSUE TITLE
Can't drag events to other view

### ISSUE THREAD

**Issue by heavyrick** [mattlewis92/angular-bootstrap-calendar#562]
Sorry for ignoring the guidelines, but i'm not finding an answer to this problem anyhwhere.

[StackOverflow](http://stackoverflow.com/questions/42928979/event-hiding-on-dragging-to-parent-view-in-angular-bootstrap-calendar)

I have a main view and a sidebar. My events are rendered in the sidebar and i want to drag them to the main parent. But when i do this, the event hides itself behind the main parent.

I tried changing z-index, position or overflow, but it's no use.

**Comment by mattlewis92** [comment]
Can you make a plunker that reproduces the issue? What you're describing is basically [this demo](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=draggable-external-events) which works ok.

**Comment by mattlewis92** [comment]
You can hit the "Edit in plunker" from any of the demos to create a starting point.

**Comment by burtek** [comment]
Closing inactive thread.
