### ISSUE TITLE
onDragSelectEnd causes TypeError when dragging events between calendars

### ISSUE THREAD

**Issue by uplink42** [mattlewis92/angular-bootstrap-calendar#563]
### Bug description / Feature request:
When dragging events between different calendars, an error is thrown.

### Versions

Angular: 1.6.3

Calendar library: 0.28.3

Browser name and version: Chrome 56

This issue is very similar to https://github.com/mattlewis92/angular-bootstrap-calendar/issues/439, but the error is thrown in a different controller this time (MwlCalendarMonthCtrl). 
http://imgur.com/edit?deletehash=vebxADDVy8jNF6d&album_id=89REU

I have updated to the most recent version and it still persists. Perhaps I'm doing something wrong?

**Comment by burtek** [comment]
Please provide link to minimally-working plunker that reproduces the issue (starter template: http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview)

**Comment by burtek** [comment]
Closing inactive thread.
