### ISSUE TITLE
How to group event by Column

### ISSUE THREAD

**Issue by Blair2004** [mattlewis92/angular-bootstrap-calendar#564]
Hi, 
you did a nice, Work. I would like to know if it's possible to group similar event per column ?
![0f60e460-7233-42cb-8824-1bd730657ae9](https://cloud.githubusercontent.com/assets/5265663/24478031/9fb53652-14d9-11e7-8d8f-c967a2f89163.jpg)

**Comment by Blair2004** [comment]
Thank you in advance

**Comment by burtek** [comment]
I'm afraid you'll need to create a new view for that. How to do that has been briefly explained in threads #556 and #558.

Should you need any help with that feel free to ask.
