### ISSUE TITLE
Delete button and {{ calendarTitle }} are not working

### ISSUE THREAD

**Issue by yasserht** [mattlewis92/angular-bootstrap-calendar#565]
Hello Matt, I tried using {{ calendarTitle }} but it's not showing anything ( I'm using multiple calendars in the same page). Also Delete button is not deleting events even in the demo you provided. 
Thank you in advance

**Comment by burtek** [comment]
Please provide link to minimally-working plunker that reproduces the issue (starter template: http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview)

**Comment by burtek** [comment]
Are you sure you set up angular and it's modules correctly? Are you sure you have JS enabled in your browser?

**Comment by yasserht** [comment]
Thank you
I do have JS enabled and I guess Im using modules in the right way, but still no calendartitle 
here's a plunker http://plnkr.co/edit/UHjZ0ROqx7ijrsQLrsRA?p=preview when i click the remove icon instead of showing an alert i want it to delete that event

**Comment by burtek** [comment]
Lines 14-16 in `example.js` of your plunker show:

      onClick: function(args) {
        alert.show('Deleted', args.calendarEvent);
      }

There is no code, that would delete the event.

**Comment by yasserht** [comment]
Yes, I used vm.events.splice() but it's not working, what should I write ?

**Comment by burtek** [comment]
`vm.events.splice(args.calendarEvent.calendarEventId, 1)` seems to be working for me

**Comment by yasserht** [comment]
just tried it, working perfectly 
Thank youu

**Comment by yasserht** [comment]
what if we're using it in an html page is it the same ng-click="vm.events.splice()"

**Comment by burtek** [comment]
Depends how and where you want to use it.

**Comment by yasserht** [comment]
im using 8+ calendars in parallel , `<div ng-controller="DraggableExternalEventsCtrl as vm">
    <h2 class="text-center">{{ vm.calendarTitle }}</h2>` but this is not showing anything

**Comment by burtek** [comment]
I'm still not able to help you until you provide me with a plunker that reproduces the issue.

**Comment by yasserht** [comment]
I used    `    <h1 class="text-center">{{ vm.viewTitle }}</h1>` instead and it's working 
Thank you
