### ISSUE TITLE
Set when the first week should start

### ISSUE THREAD

**Issue by AlexandruTipter** [mattlewis92/angular-bootstrap-calendar#567]
Hi, it would be wonderful if we can have an option to set when the first week of the year should start. Maybe we can have the following options:
- On the 1th of January
- First week with 4 days
- First full week

Do you think this will be a hard feature to add?

**Comment by AlexandruTipter** [comment]
If the above request isn't something that can be done easily, maybe there is a way you don't display the week number in month view when hovering?

**Comment by burtek** [comment]
Ad.1. There is a standard (ISO) way of numbering weeks of year, which is the second option you mentioned. For your second question - setting CSS rule for `div#cal-week-box { display: none; }` should do the trick.

**Comment by AlexandruTipter** [comment]
Thanks! Works like a charm.
