### ISSUE TITLE
scroll while drag

### ISSUE THREAD

**Issue by Gozzi4** [mattlewis92/angular-bootstrap-calendar#568]
### Bug description / Feature request:
Cannot scroll while dragging the item,.

The item does not scroll down when being dragged

http://plnkr.co/edit/mTJa8fwVTTD5Wv4epcD3?p=preview

https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=draggable-external-events

### Versions

Angular: 
plunkr version
Calendar library: 

Browser name and version: 
chrome:  Version 56.0.2924.87

windows 10, 64 bit

**Comment by burtek** [comment]
Works for me with Chrome 57.0.2987.110 on 64-bit Windows 10. It may be due to your browser version and/or browser and system settings. Please provide more detailed info on your browser and OS

**Comment by Gozzi4** [comment]
tried it on other browsers aswell , i wont scroll beyond size of screen even if the calendar is beyond it

**Comment by burtek** [comment]
Once again - it does work for me. It also may be to the mouse' driver not allowing you to do that. Unfortunatelly that's not the issue with this project, and you did not proivide more details, so I'm closing the topic.

**Comment by Gozzi4** [comment]
its not the mouse driver, it doesn't scroll down while dragging.

**Comment by burtek** [comment]
1. Some drivers won't allow scrolling when holding mouse button.
2. That's not the issue with `angular-bootstrap-calendar`

**Comment by Gozzi4** [comment]
it scrolls when i drag images,  when not using angular-bootstrap-calendar

**Comment by burtek** [comment]
@mattlewis92 - maybe you'll have an idea?

**Comment by mattlewis92** [comment]
That was an easy fix! 😄
