### ISSUE TITLE
Cannot select time range under Saturday when using showTimesOnWeekView

### ISSUE THREAD

**Issue by graspsolutions** [mattlewis92/angular-bootstrap-calendar#571]
When in 'Week' view, it is not possible to select a time range under Saturday.

Steps to reproduce:
Here is a plunker from the official "Select range" demo with calendarConfig.showTimesOnWeekView = true added:
http://plnkr.co/edit/wH9Qe9QGMQEN5IoAs29l?p=preview

**Comment by mattlewis92** [comment]
I'm not able to reproduce this, it works fine for me?
![apr-05-2017 17-06-51](https://cloud.githubusercontent.com/assets/6425649/24715097/4d13c29e-1a22-11e7-9cb0-9cea85f60fc8.gif)

**Comment by graspsolutions** [comment]
Wow, interesting that it works for you.  I have tried in IE, Chrome & FF.  All seem to not let me select Saturday 

![apr 5 2017 12-38 pm](https://cloud.githubusercontent.com/assets/9884422/24716610/98936028-19fd-11e7-985c-0b7c9661f28a.gif)

**Comment by mattlewis92** [comment]
Ah maybe it's the scrollbar on windows getting in the way

**Comment by graspsolutions** [comment]
Yes, you are correct.  I hid overflow in CSS for body & .cal-week-box.cal-day-box .cal-day-panel, and it works now that the scrollbars are gone.

Is it possible to fix this while keeping the scrollbar?  Sometimes it is nice to be able to limit the height of the view, as in part of a dashboard view for example.

I must say as my final remark, great work on this project.  It is quite impressive.

**Comment by burtek** [comment]
@mattlewis92 - any progress on that? It started bothering me, too... :D

**Comment by mattlewis92** [comment]
TIL there's a mac setting to always show scrollbars like windows does so I can reproduce it now, I'm still not exactly sure how to fix it but I'll try and push something in the next couple of days.
