### ISSUE TITLE
version 0.28.3  on-timespan-click event not working

### ISSUE THREAD

**Issue by korengal** [mattlewis92/angular-bootstrap-calendar#572]
Hi,

This was worked for me in version  0.27.5. 
EDIT : It's working until version 0.28.0.

This is a code example : 

HTML : 
```
<mwl-calendar
    view="vm.calendarView"
    view-date="vm.viewDate"
    events="vm.events"
    view-title="vm.calendarTitle"
    on-event-click="vm.eventClicked(calendarEvent)"
    on-event-times-changed="vm.calendarEvent.startsAt = calendarNewEventStart; vm.calendarEvent.endsAt = calendarNewEventEnd"
    cell-is-open="true"
    on-timespan-click="vm.timespanClicked(calendarDate)"
    >
</mwl-calendar>
```

Controller :

```
                     vm.timespanClicked = function (time) {
                         // debugger;
                         console.log('onTimespanClick clicked');
                     };
```

After I have upgraded the version to 0.28.3 its stopped working.

Thanks.

**Comment by burtek** [comment]
Please provide link to minimally-working plunker that reproduces the issue (starter template: http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview). I will not be able to help without that.

**Comment by korengal** [comment]
I found the problem.

In my Code, I was overridden the weekly view template,
In the new version this code in green was added: 

![image](https://cloud.githubusercontent.com/assets/5110512/24681053/2f961ea0-199c-11e7-8a91-23203948f019.png)

I added it and solve the problem.

**Comment by burtek** [comment]
Great :) Should you need more help, feel free to ask again :)
