### ISSUE TITLE
build failed in Windows10

### ISSUE THREAD

**Issue by jujis008** [mattlewis92/angular-bootstrap-calendar#573]
### Bug description / Feature request:
Acutually I am not sure this is actually an issue in this project, I got the error as following and build failed in local in Windows:
32:1error      Expected linebreaks to be 'LF' but found 'CRLF'  errorlinebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
It's from eslint line break style, refer the https://github.com/este/este/issues/1132 to get more details, and need to add a rule to handle line breaks in .eslintrc to work well with windows.
{
  "extends": "mwl",
  "rules": {
    **"linebreak-style": 0,**
    "angular/controller-name": [2, "/[A-Z].*Ctrl/"],
    "angular/deferred": 2,
    "angular/directive-name": [2, "mwl"],
    "angular/empty-controller": 2,
    "angular/di-unused": 2
  },
  "env": {
    "node": true
  },
  "plugins": [
    "angular"
  ],
  "globals": {
    "EXCLUDE_TEMPLATES": true
  }
}
Anyway, please ignore and close it if you don't think is an issue like i said at the beginning, thanks.

**Comment by mattlewis92** [comment]
That's deliberate to enforce a universal code style, otherwise if someone sent a pull request that changed all the line endings to windows style along with a fix / feature it would mess up the git diffs. Most editors support changing the line endings in the project settings to linux style.
