### ISSUE TITLE
Adding events when clicking on day

### ISSUE THREAD

**Issue by jpmarques94** [mattlewis92/angular-bootstrap-calendar#574]
## Adding events when clicking on day (month view)

Hello! 

Is there someway to, on the month view, if the user click on a day we can add an event for that specific day ?
My idea was a feature that the user could add notes for a day on the month view, and for do this, i tought we should be able to add events (like notes) on a specific day. 

Thanks and keep the good work!

**Comment by mattlewis92** [comment]
You can use the on-timespan-click event for this, demo here: https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=timespan-click
