### ISSUE TITLE
Prevent !!vm.onDateRangeSelect from executing on right mouse click in calendarHourList.html

### ISSUE THREAD

**Issue by bwobbones** [mattlewis92/angular-bootstrap-calendar#575]
### Bug description / Feature request:
I have a custom calendarHourList.html that also contains a right click context menu (via [angular-boostrap-contextmenu](https://github.com/Templarian/ui.bootstrap.contextMenu)).  

When I right click in a `cal-day-hour-part` in chrome 57 on windows (note not on a mac!) it fires both oncontextmenu and onclick events which means that !!vm.onDateRangeSelect is executed unexpectedly and I get both the handler for the context menu and the handler for the left click.

Any ideas on how to prevent the !!vm.onDateRangeSelect function firing?

The context menu works when you right click on an event though, so I guess I need to use whatever mechanism that does to swallow the ng-click for right click events?

### Versions

Angular: 1.5.9

Calendar library: latest

Browser name and version: Chrome 57 on Windows

**Comment by mattlewis92** [comment]
I think if you do `oncontextmenu="$event.stopPropagation();"` it should prevent the handler from firing. Hope that helps!
