### ISSUE TITLE
Set Background Color at Calendar Cell

### ISSUE THREAD

**Issue by sky3913** [mattlewis92/angular-bootstrap-calendar#577]
Hi,
Is there a way how to set the calendar cell background color when I click the cell and how to set Saturday and Sunday background color in red at page load?

**Comment by mattlewis92** [comment]
Here you go: http://plnkr.co/edit/IgfQEgPFWIETgtzX1QuO?p=preview Hope that helps!

**Comment by sky3913** [comment]
Great...
Thanks for your help

**Comment by sky3913** [comment]
Hi matt,
How to set the weekend individually? I have added 2 checkboxes, one for Saturday and Sunday, if I tick Saturday then all Saturday in this year will be red and if I uncheck it then it will be white. So does the Sunday.

How to make multiple selected date and keep the background color in red until it's clicked again? Also can we get the selected dates using a button click?

Thanks in advance

**Comment by burtek** [comment]
Can you provide code sample? What checkboxes did you add?

**Comment by sky3913** [comment]
Here is the code: http://plnkr.co/edit/icdWZjkgk4IoHe7PQ63w?p=preview

There is also a year combobox to limit the calendar view, but I don't know how to make it.

**Comment by graspsolutions** [comment]
In a related extension to this question, can a day be selected from an external button? E.g. a button to return to the day of the current date and set its background color?

**Comment by burtek** [comment]
@sky3913 Please, have a look at issue #582, maybe you'll find your answer there.

@graspsolutions the button is standard button described [here](https://github.com/mattlewis92/angular-bootstrap-calendar#the-mwl-date-modifier-directive). As for setting it's background, have a look at issue #597.

**Comment by shahksh1011** [comment]
HI Matt.Can I add background color to cells with particular date. For example I want to add bgcolor to 1st dec 2017, 5 dec 2017, 5th jan 2018,11 dec 2018??
