### ISSUE TITLE
Allow the autoScroll container to be specified

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-bootstrap-calendar#578]
### Bug description / Feature request:
Hi,
My calendar day view time is divided for 15 min slots and because of that in 24 hours my day view looks very long so i tried giving custom height say 250px now up to this everything is fine, but now I want to move event from top to bottom so I have to scroll to go to bottom time and drop my event there, while scrolling pointer and event seems to lost somewhere. Please find attach plunker for more detail.

To reporduce this issue. 
http://plnkr.co/edit/aThLNdZjvV2rSRkITC53?p=preview
go to Day view and start dragging the event and try to drop @ 10.00 PM  you would get to know my problem.
Thank you.

Moved from https://github.com/mattlewis92/angular-calendar/issues/184 by @rajkotgire

**Comment by rajkotgire** [comment]
Hi, 
I just have checked against the plnkr given in issue description, but it still not working.

**Comment by mattlewis92** [comment]
You need to explicitly pass the scroll container to the new `draggable-auto-scroll` option [like so](http://plnkr.co/edit/MRQzhfsZoXwsDpDpUQRN?p=preview) although sadly it [doesn't seem to work very well](https://github.com/taye/interact.js/issues/185#issuecomment-100539003). Sadly I'm not sure what I can do when the issue is with the underlying interactjs library 😞
