### ISSUE TITLE
Choosing weekend days

### ISSUE THREAD

**Issue by marcoos13** [mattlewis92/angular-bootstrap-calendar#582]
### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by marcoos13** [comment]
Hey, there amazing job!

I would like to to know if there is a way to set the weekend days?
For example instead of Saturday and Sunday set it tp be Sunday and Monday.

Thank you 👍

**Comment by mattlewis92** [comment]
I wasn't aware of any countries where sunday and monday were the weekend? Out of curiosity which country is it? The only weekend logic regarding weekends is in the month view where you can use the cell modifier to change the logic like so: http://plnkr.co/edit/EQFu180W31SUD38QR0ZT?p=preview Hope that helps!

**Comment by marcoos13** [comment]
Actually, I was aiming for Friday and Saturday, but as a general concept I wonder If it is possible to change it... :)

**Comment by mattlewis92** [comment]
Ah ok, makes sense 😀

**Comment by marcoos13** [comment]
Thank you for your comment :)
I was referring to the week view though...
