### ISSUE TITLE
Disable the click event.

### ISSUE THREAD

**Issue by abhishekgupta0** [mattlewis92/angular-bootstrap-calendar#583]
I have two kind of events, one has a click event but other hasn't. How to disable or REMOVE the anchor tag for second event?

**Comment by mattlewis92** [comment]
You can set a cssClass on the events you want disabled that sets `pointer-events: none`. For example: http://plnkr.co/edit/vbVA5q8a1AyIa8bxC9p9?p=preview Hope that helps!

**Comment by abhishekgupta0** [comment]
Its working. Thanks a lot.
