### ISSUE TITLE
Set value badge total

### ISSUE THREAD

**Issue by augustocarniel** [mattlewis92/angular-bootstrap-calendar#584]
I need to set the amount that I want in the badge with the total of events of a certain day. I researched a lot and did not find a way to do that. Could you help me with this problem?

I thought of something like this:
$scope.events = [
     {
         title: 'Available'
         startsAt: new Date(),
         endsAt: new Date(),
         badgeTotal: 30
     }
]

**Comment by mattlewis92** [comment]
You can use the cell modifier to do this: http://plnkr.co/edit/W8LbMJo1TscV1sETbaP2?p=preview

**Comment by augustocarniel** [comment]
Thank you so much.
