### ISSUE TITLE
Hide Time in Event List

### ISSUE THREAD

**Issue by nguyennk** [mattlewis92/angular-bootstrap-calendar#586]
Is is possible to hide the time in event drop down?
Currently:
Event Name (00:00) {action}

Want:
Event Name {action}

I tried to look into the js file to see where this is written but can't seem to find it

Thanks,

**Comment by mattlewis92** [comment]
You can override the `calendarEventTitle.monthView` method to achieve this:
```
angular.module('myApp').run(function(calendarEventTitle) {
  calendarEventTitle.monthView = event => event.title;
});
```

Hope that helps! 😄
