### ISSUE TITLE
Drag between months

### ISSUE THREAD

**Issue by Angelko** [mattlewis92/angular-bootstrap-calendar#590]
###  Feature request:
Just a question, in month view, it seems that it isn't possible to drag an event between months ?

### Description
On month view, when an user drag an event, arrows could to be displayed on the sides.
The user could to drag the event on it to change month.

Thanks

**Comment by Angelko** [comment]
Maybe when dragEnter on Previous / Next buttons on month view to change it ?

**Comment by burtek** [comment]
It's not a bad idea, but I don't have time now to implement it. @mattlewis92...?

**Comment by mattlewis92** [comment]
You could implement it in userland by using interact to detect when an element is dragged over and then cycle through the months on an interval until the event is moved away. I'm quite strapped for time atm as all my efforts are going into migrating away from angularjs, so don't have time to chuck together a plunker

**Comment by mattlewis92** [comment]
Had a play to see if I could get this working tonight and this was the best I could come up with: http://plnkr.co/edit/kXNvxIf3JNB4vTX6LCCl?p=preview I realised as the event you're dragging gets destroyed when the view changes it's hard, if not impossible to implement this properly.

**Comment by Angelko** [comment]
:/
