### ISSUE TITLE
Dayview not displaying events

### ISSUE THREAD

**Issue by JonnyBGod** [mattlewis92/angular-bootstrap-calendar#591]
### Bug description / Feature request:
Events are not showing when using day view.
But they work properly with month and week views.

### Link to minimally-working plunker that reproduces the issue (starter template: )
```
<mwl-calendar
  view="calendarView"
  view-date="calendarDay"
  events="carEvents"
  day-view-split="10"
  on-event-click="eventClicked(calendarEvent)">
</mwl-calendar>
```

```
$scope.calendarView = 'day';
$scope.calendarDay = new Date();
$scope.carEvents = [{
  title: res[i].from.formatted_address + ' => ' + res[i].to.formatted_address,
  color: {
    primary: "red",
    secondary: "red"
  },
  startsAt: moment(new Date(res[i].date)).toDate(),
  endsAt: Date(res[i].date)).add(res[i].duration, 's').toDate()
  editable: false,
  deletable: false,
  draggable: false,
  resizable: false
}];
```

https://www.dropbox.com/s/vxy67sm2la175pc/Screenshot%202017-05-07%2019.56.33.png?dl=0

### Versions

Angular: 1.6.4

Calendar library: 0.29

Browser name and version: Chrome 60.0.3091.0 and 57.0.2987.133

**Comment by burtek** [comment]
Please use plunker for providing code sample, I cannot reproduce the problem using only the code you provided. Starting template: http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview. Edit the template or create new one and post plunker url here.

**Comment by mattlewis92** [comment]
Closing this due to the lack of response, happy to discuss it further though if you can provide a plunker that reproduces your issue.
