### ISSUE TITLE
index.html is not working on master head

### ISSUE THREAD

**Issue by jgpATs2w** [mattlewis92/angular-bootstrap-calendar#593]
It lacks some dependencies in the repo index.html (mainly angular), so the index.html is not loading.
After loading, with the script tags from the online demo, it does not load the calendar view...

Great calendar plugin, thanks!!

**Comment by mattlewis92** [comment]
The repo isn't designed to be run as a static server from master, as [per the dev instructions](https://github.com/mattlewis92/angular-bootstrap-calendar#development-server) you need to run `npm install && npm start` to start the local server that serves the assets.
