### ISSUE TITLE
Delete icon in weekview

### ISSUE THREAD

**Issue by zigkasg** [mattlewis92/angular-bootstrap-calendar#594]
Hi Matt,
Could you please inform me if it is possible to include delete action icon of an event in week view?
If yes, how is this done? Is there any example?

Thanks for your help and congrats for the job.
George

**Comment by burtek** [comment]
As I'm not using actions, hopefully @mattlewis92 would help here

**Comment by ariel-ibarra-jd** [comment]
I'm facing this requirement too. Would like to know if it possible.

**Comment by mattlewis92** [comment]
Sorry about the late reply on this, I've just cut `0.29.3` which should now included event actions on the week view. Hope that helps! 😄
