### ISSUE TITLE
Dropping events between two calendars

### ISSUE THREAD

**Issue by bwobbones** [mattlewis92/angular-bootstrap-calendar#595]
My app has two instances of the calendar and I'm trying to drag an event from one calendar and drop it on the other (in daily view only).  To do this, I need to have access to the dropzone._element from interact but I can't work out how to expose it so my controller can use it.

I can see in the code where I need to get it, something like:

`var dropElm = angular.element(event.dropzone._element);`

in `MwlDraggableCtrl.interact.onend` seems appropriate and definitely gets me the target element. 
 Have you got any hints on how I could go about exposing that back out to the controller that creates the calendar?

**Comment by bwobbones** [comment]
Nevermind, I got it.  Just use a global interact listener in the controller itself after injecting the interact library:

```
interact.on('dragend', function (event) {
  console.log(event);
});
```

Seems to work well, can you see any problems with that @mattlewis92?

**Comment by jmsunseri** [comment]
@bwobbones do you have a plunker for this?  did you have to modify the calendar lib or where you able to do it all in your own JS?  How were able to get around the physical representation of the event wanting to stay within the bounds of its original calendar?

**Comment by bwobbones** [comment]
No plunkr sorry.

I had to modify the calendar lib, see #620 for the change I made, I'm hoping to get time soon to break up the change as requested.

Keeping the bookingEvent on top was adding a class like this:

`.resource-overflow {
    overflow:visible !important;
}`

to the cal-day-box element in an overridden calenderDayView.html (see https://github.com/mattlewis92/angular-bootstrap-calendar#custom-template-urls) like this:

`<div class="cal-day-box resource-overflow">`

**Comment by jmsunseri** [comment]
Thanks so much for the help here.  I completed my implementation of a weekview of a calendar for a time keeping app.  My custom template probably won't be for a lot of people because of the specific nature of the calendar but they can see a completed implementation of me dragging the events from one day to another 

http://plnkr.co/edit/ZPYoKalCYJFxORhnhALE?p=preview

**Comment by bwobbones** [comment]
@jmsunseri, that's beautiful.  Well done.
