### ISSUE TITLE
show only month with event

### ISSUE THREAD

**Issue by Enitnelav** [mattlewis92/angular-bootstrap-calendar#596]
Hi, I am using your good calendar and I searched but I did not find how i can only show few months (where there are my events), by setting a start and end date.

thanks

**Comment by burtek** [comment]
Do you want to display few months simultaneously or what? Please, provide more details how it should look

**Comment by Enitnelav** [comment]
i'd like to show only fews month like for example if my first event is on the 5th june and my last on the 5th september, i'd like to show only from june to september (and do you know how to translate day  ?)

**Comment by burtek** [comment]
But you want to show the months simultaneously or block displaying of different months?

**Comment by Enitnelav** [comment]
Thanks, I use view by month and i don't want to change,
i'd like to limited the number of month that's the user can see

**Comment by burtek** [comment]
I won't help you, as I'm not familiar with that project. @mattlewis92

**Comment by mattlewis92** [comment]
As you have full control over when the view date is changed you can implement this logic yourself in your component like so: https://mattlewis92.github.io/angular-calendar/#/min-max-date

**Comment by Enitnelav** [comment]
You're great thank you :)
