### ISSUE TITLE
Set cell background using an external button

### ISSUE THREAD

**Issue by graspsolutions** [mattlewis92/angular-bootstrap-calendar#597]
I can use a button to navigate to a desired date in month view by simply using the following 2 lines in my controller:

vm.calendarView = 'month';
vm.viewDate = moment('2017-01-01');

How can I get the cell object so that I can set the background color using cell.cssClass?  Or, I there a better way to accomplish this?  Thanks!

**Comment by burtek** [comment]
Please, have a look at [this coment](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/582#issuecomment-294965648) to issue #582. In the given plunker you can see using cellModifier function by using `<mwl-calendar ... cell-modifier="vm.cellModifier(calendarCell)"></mwl-calendar>`. The function itself is in `example.js`.

**Comment by graspsolutions** [comment]
Thanks for the reply.

I use cell-modifier for css changes on calendar load, but how can it be used to set the css of a cell after the calendar is loaded?

I am trying to click a button, navigate to the specified date in month view, and change the background of the date's cell.

**Comment by burtek** [comment]
I guess you'd need to modify the template and add AngularJS `ng-style` attribute to each cell, or sth like this. Or maybe @mattlewis92 has another idea.

**Comment by graspsolutions** [comment]
Thanks, I figured it using the cellModifier from your suggestion.  I set vm.viewDate with a button, then check if the cell.date equals vm.viewDate in cellModifier();

function cellModifier(cell) {		
	if (vm.viewDate == cell.date) {
		cell.cssClass = 'cell-day-selected'
	} else {
		delete calCell.cssClass';
	}
};
