### ISSUE TITLE
get tasks from an api with different parameters 

### ISSUE THREAD

**Issue by yasserht** [mattlewis92/angular-bootstrap-calendar#598]
Hello, 
how can I get tasks from an api that looks like this : 
![capture](https://cloud.githubusercontent.com/assets/25863820/26169008/dc910bfa-3b44-11e7-98e2-95622e93011f.PNG)

what should I change exactly?

**Comment by burtek** [comment]
The api should return array of objects. Those objects must be formatted and created according to [this schema](https://github.com/mattlewis92/angular-bootstrap-calendar#events-required-attribute)

**Comment by yasserht** [comment]
Can't I change that schema, coz I don't have control over the api side

**Comment by burtek** [comment]
Well, you have to reformat the events then. I guess it'd be enough to:

1. Convert `date` and `duration` to `startsAt` and `endsAt` fields.
2. Convert `repeat` field to `recursOn` field.
3. `description` and `place` won't be showen untill you make changes to the project itself - at the moment those fields are not supported.
4. You can generate CSS classes that would relate to `priority` field and use `cssClass` for that.

**Comment by burtek** [comment]
Also, please keep in mind you have to provide `color` field here.

**Comment by yasserht** [comment]
Thank you for your response, if only you can provide a sample of code of how i can convert them

**Comment by burtek** [comment]
That's not that hard in fact for the time ranges:

`event.starsAt = new Date(apiEvent.date*1000);
event.endsAt = new Date(apiEvent.date*1000 + apiEvent.duration*60*1000);`

As for repeat field, the project does not allow daily and weekly reoccurence ( @mattlewis92 - feature suggestion? ).

As for no 3. I'm not able to provide this at this moment (no PC here).

As for no 4. you can create CSS:

` .priority {background-color: #f55; color: red}`

and then add:

`event.color = "red";
event.css = "priority";`

or sth like this.

**Comment by yasserht** [comment]
thank youu very much I appreciate it

**Comment by yasserht** [comment]
Can I ask, What does apiEvent do ? should I change it according to my case?

**Comment by burtek** [comment]
Yeah, I used `event` as the event from calendar's array and `apiEvent` for event from API's GET request.

**Comment by yasserht** [comment]
hey @burtek , do you have any idea how to get events for a specific range date, from a restapi 
I did this and now it's giving me today's events by default 
` vm.externalEvents = r.data.map(function(apiEvent) {
                           return {
                               title: apiEvent.title,
                               type: 'warning',
                               color: calendarConfig.colorTypes.warning,
                               startsAt: new Date(apiEvent.date),
                               draggable: true
                                  };
                        });
`

**Comment by burtek** [comment]
It depends on the API and the libraries you're using. I'm not able to help with this, ask the API provider.

**Comment by yasserht** [comment]
Thank you @burtek
