### ISSUE TITLE
Error: Expression 'undefined' used with directive 'mwlCalendar' is non-assignable!

### ISSUE THREAD

**Issue by argaen** [mattlewis92/angular-bootstrap-calendar#60]
Hi, after trying various combinations I can't make it work. I'm obtaining the error `Expression 'undefined' used with directive 'mwlCalendar' is non-assignable!`.

Here is my html:

```html
<mwl-calendar
   calendar-events="events"
   calendar-view="calendarView"
   calendar-current-day="calendarDay"
   calendar-on-event-click="eventClicked($calendarEvent)"
   calendar-edit-event-html="'<i class=\'glyphicon glyphicon-pencil\'></i>'"
   calendar-delete-event-html="'<i class=\'glyphicon glyphicon-remove\'></i>'"
   calendar-on-edit-event-click="eventEdited($calendarEvent)"
   calendar-on-delete-event-click="eventDeleted($calendarEvent)"
   calendar-auto-open="true">
</mwl-calendar>
```

And here is my controller:

```javascript
.controller('CalendarCtrl', function ($scope, $modal, moment) {

  var currentYear = moment().year();
  var currentMonth = moment().month();

  //These variables MUST be set as a minimum for the calendar to work
  $scope.calendarView = 'month';
  $scope.calendarDay = new Date();
  $scope.events = [
    {
      title: 'Event 1',
      type: 'warning',
      startsAt: new Date(currentYear,currentMonth,25,8,30),
      endsAt: new Date(currentYear,currentMonth,25,9,30)
    },
    {
      title: 'Event 2',
      type: 'info',
      startsAt: new Date(currentYear,currentMonth,19,7,30),
      endsAt: new Date(currentYear,currentMonth,25,9,30)
    },
    {
      title: 'This is a really long event title',
      type: 'important',
      startsAt: new Date(currentYear,currentMonth,25,6,30),
      endsAt: new Date(currentYear,currentMonth,25,6,60)
    }
  ];


  $scope.eventClicked = function(event) {
    console.log("wtf");
  };

  $scope.eventEdited = function(event) {
    console.log("hi");
  };

  $scope.eventDeleted = function(event) {
    console.log("lol");
  };

  $scope.setCalendarToToday = function() {
    $scope.calendarDay = new Date();
  };

  $scope.toggle = function($event, field, event) {
    $event.preventDefault();
    $event.stopPropagation();

    event[field] = !event[field];
  };
});
```

I don't know what I am missing. Maybe it is worth to mention that I'm using:

```javascript
.config(function($interpolateProvider) {
  $interpolateProvider.startSymbol('{$');
  $interpolateProvider.endSymbol('$}');
})
```

because I'm working with Django. It may be related to the error because once rendered, I obtain the following:

![screenshot from 2015-04-15 13 14 28](https://cloud.githubusercontent.com/assets/3578154/7157591/651bcbc8-e371-11e4-9f08-0161ae89d1f9.png)

but not sure... any guides?

Thanks! =).

**Comment by mattlewis92** [comment]
For now you will need to override the templates and replace all interpolated braces with your start and end symbols. I can't think of a nice solution that will also let you override the templates.

**Comment by argaen** [comment]
Hi, thanks for your help. I'm now able to render the calendar correctly with the assigned events but it still displays the same error and events are not triggered (clicked, edited, etc.). I have this now:

```html
        <mwl-calendar
            calendar-events="events"
            calendar-view="calendarView"
            calendar-current-day="calendarDay"
            calendar-event-click="eventClicked"
            calendar-edit-event-click="eventEdited"
            calendar-delete-event-click="eventDeleted"
            calendar-edit-event-html="'<i class=\'glyphicon glyphicon-pencil\'></i>'"
            calendar-delete-event-html="'<i class=\'glyphicon glyphicon-remove\'></i>'">
        </mwl-calendar>
```

Also, events are not triggered. One thing I've seen in the example, in the html you have `calendar-event-click="eventClick"` but in the demo.js the event is called `$scope.eventClicked` and it still calls it. What am I missing?

Thanks

**Comment by mattlewis92** [comment]
The click events are angular expressions not variables. As per the example you should do calendar-event-click="eventClicked($event)" where eventClicked is a function on the scope not a variable. It works exactly the same as you would use the ng-click directive.

**Comment by argaen** [comment]
Damn, I had it that way but modified it in order to try to fix the error because the angular page says the following:

![screenshot from 2015-04-16 10 53 54](https://cloud.githubusercontent.com/assets/3578154/7177431/f055fd3e-e426-11e4-8dc2-70222197f235.png)

Well, everything seems to be working now (although the error is still there).

Thanks for your help! =).

**Comment by mattlewis92** [comment]
NP :)
