### ISSUE TITLE
Month View load time

### ISSUE THREAD

**Issue by statesman4** [mattlewis92/angular-bootstrap-calendar#601]
Hello,

First, thank you for your hard work. The directive is working great except slow load when loading the month view. Day view loads pretty fast but when loading month view, it is noticeably slow even when there are no events. Appears to be more noticeable in IE than Chrome.

Thanks

**Comment by burtek** [comment]
Hi,

I do not have such problem myself. Have you tried that on a different computer and/or different internet connection? Does it also happen in [this demo](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=kitchen-sink)? Can you provide IE and Chrome versions you're using? Also if you could provide your code, which is affected by the problem, that would be very helpful.

**Comment by statesman4** [comment]
Thank you for your response. I am using IE 11. Oddly enough it may be my computer. I tried the above demo on my computer where I was experiencing the problem but it appears to be working fine at my work computer, although same version of IE. I will close the issue.

Thank you
