### ISSUE TITLE
event width on day view

### ISSUE THREAD

**Issue by yasserht** [mattlewis92/angular-bootstrap-calendar#602]
![capture](https://cloud.githubusercontent.com/assets/25863820/26765736/f96d94b0-498a-11e7-9420-6eaf6787f0a4.PNG)
Hello Im using more than one calendar. How can I change the width of the event? 
Thanks

**Comment by burtek** [comment]
You want to change default width or only one event's width? On all calendars or only one of them? Provide more info and a plunker with your existing code to work on.

**Comment by yasserht** [comment]
I want to change default width of the event, now it's 150px I wanna make it 230px
this is a default plunker 
http://plnkr.co/edit/bulY001LRgh5dWrlnVzJ?p=preview

**Comment by burtek** [comment]
The default one is http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview, I asked for your code with multiple calendars. In which view you want this?

**Comment by yasserht** [comment]
it's a big code I can't make a plunker of it, but I want to change the default width of it, I believe it's the same thing. Thank you

**Comment by burtek** [comment]
In which view you want this?

**Comment by yasserht** [comment]
just day view

**Comment by burtek** [comment]
You have to add `day-view-event-width` parameter with your width (i.e. `day-view-event-width="230"`) to `<mwl-calendar>` html tag, like [here](http://plnkr.co/edit/GUgcFjFWN9E3eUM4t7VR?p=preview).

**Comment by yasserht** [comment]
Thank you so much @burtek
