### ISSUE TITLE
multiple calendars

### ISSUE THREAD

**Issue by mark4485** [mattlewis92/angular-bootstrap-calendar#604]
Thank you for the awesome calendar, Im using two calendars in my project and im getting data from a rest api as followed `TaskService.query()
                 .$promise
                 .finally(function() {
                      $rootScope.isBusy = false;

                  })
                 .then(function(r) {

                vm.externalEvents = r.data.map(function(apiEvent) {
                   return {
                             title: apiEvent.title,
                             id: apiEvent.id,
                             type: 'warning',
                             user: apiEvent.user,
                             duration: apiEvent.duration,
                             priority: apiEvent.priority,
                             color: calendarConfig.colorTypes.warning,
                             draggable: true
                                };
                        });`
everything works fine for external events, but for events on the calendar ( vm.events) I couldn't separate them according to the user id i get from api. Is there a way to do so ?

**Comment by mattlewis92** [comment]
You should be able to use `.filter`?:
```
vm.externalEvents = r.data
  .filter(apiEvent => apiEvent.user.id === currentUser.id)
  .map(function(apiEvent) {
               return {
                         title: apiEvent.title,
                         id: apiEvent.id,
                         type: 'warning',
                         user: apiEvent.user,
                         duration: apiEvent.duration,
                         priority: apiEvent.priority,
                         color: calendarConfig.colorTypes.warning,
                         draggable: true
                            };
                    });`
```
