### ISSUE TITLE
dateclicked callback always takes you to day view and is not overridable

### ISSUE THREAD

**Issue by Kradothar** [mattlewis92/angular-bootstrap-calendar#605]
### Bug description / Feature request:
If you click on the date number, the day view is brought up. In my current usage I want to completely disable the day view, but it is not possible to override this through configuration currently. I think this is because the list of next views is hard coded so that from month and week, we always go to a day. 

`	    vm.dateClicked = function(date) {

	      var rawDate = moment(date).toDate();

	      var nextView = {
	        year: 'month',
	        month: 'day',
	        week: 'day'
	      };

	      if (vm.onViewChangeClick({calendarDate: rawDate, calendarNextView: nextView[vm.view]}) !== false) {
	        vm.changeView(nextView[vm.view], rawDate);
	      }

	    };`

Would it be possible to add the option to override this hard coded list?

### Versions

Angular:  v1.5.8

Calendar library: v0.24.0

Browser name and version: any

**Comment by burtek** [comment]
I guess the only solution would be to manually edit source and recompile the project yourself.

**Comment by mattlewis92** [comment]
If you return false from the on-view-change-click callback then it will disable this automatic view changing and you can implement the logic however you want. There is a demo of how to disable the month view here (same principal applies to the day view): https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=disabling-views
