### ISSUE TITLE
Internationalization issue in day view

### ISSUE THREAD

**Issue by maitrerobert** [mattlewis92/angular-bootstrap-calendar#606]
### Bug description / Feature request:
When I translate the calendar with i18n the hours in day view are still in english : for example 8pm instead of 20:00. Same issue in your internationalization example.

### Versions

Angular: 1.6.2

Calendar library: 0.28.0

Browser name and version: Chrome 59

**Comment by burtek** [comment]
In your controller include `calendarConfig` dependency and set `calendarConfig.dateFormats.hour = 'HH:mm'`. You can do that also via [angular's config](https://github.com/mattlewis92/angular-bootstrap-calendar#configuring-the-calendar-default-config).

The hours are not controlled by translation system (i18n in this case), and so they can only be changed by `calendarConfig.dateFormats.hour` setting.
