### ISSUE TITLE
interact js not working on deployment 

### ISSUE THREAD

**Issue by mark4485** [mattlewis92/angular-bootstrap-calendar#607]
Hello, Im using your calendar as a scheduler, the problem is interact js was working perfectly locally, but it stopped working on server, I installed it with bower. Do you have any idea why?

**Comment by burtek** [comment]
Check if interactjs  on server got installed to the same directory as locally (relatively to the project root). Also check in browser console for any errors

**Comment by mark4485** [comment]
@burtek Im using gulp so I can't check the directory

**Comment by burtek** [comment]
Are there any errors shown by browser?

**Comment by mark4485** [comment]
DevTools failed to parse SourceMap: https://dev-dot-portal-dot-piblo-pro.appspot.com/maps/scripts/vendor-e0086e94e6.js.map
DevTools failed to parse SourceMap: https://dev-dot-portal-dot-piblo-pro.appspot.com/maps/scripts/app-f0d0061726.js.map
vendor-e0086e94e6.js:46 2462d61cd06cda6f27667cabb39e18faf6242918
vendor-e0086e94e6.js:46 Bootstrap calendar: Event is missing the startsAt field []
this is what i get

**Comment by burtek** [comment]
Are you sure interactJS gets loaded? It looks to me as if was a problem with a framework you're using...

**Comment by mattlewis92** [comment]
Closing due to lack of response / seems like an issue with build tooling rather than this library,
