### ISSUE TITLE
When i change previous and next buttons in a month  first day of the month is selecting

### ISSUE THREAD

**Issue by sunithajanapareddy** [mattlewis92/angular-bootstrap-calendar#609]
![date](https://user-images.githubusercontent.com/19980424/27267942-b407e8ea-54c9-11e7-955b-929329b4916a.png)

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by sunithajanapareddy** [comment]
please can i know the solution for it

**Comment by burtek** [comment]
Do you need help with `angular-bootstrap-calendar` or `bootstrap-ui-datetime-picker`? This is support of the first one, not the second one. If you really need help with this calendar project, please specify the problem, as I cannot understand it.

**Comment by mattlewis92** [comment]
Closing due to lack of response
