### ISSUE TITLE
Bootstrap dependency requires jQuery

### ISSUE THREAD

**Issue by efantasia** [mattlewis92/angular-bootstrap-calendar#61]
Would it be possible to use https://github.com/fyockm/bootstrap-css-only in place of bootstrap? Bootstrap has jQuery as a dependency (https://github.com/twbs/bootstrap/blob/master/bower.json).

**Comment by mattlewis92** [comment]
Why not just not include jquery and the bootstrap js files? If you're auto injecting the files with gulp, grunt etc you can set dependency overrides in the bower.json file. I don't really like the idea of using bootstrap-css-only as it depends on the author to keep the repo updated with the main bootstrap repo.

**Comment by efantasia** [comment]
Fair nuff - I'll do that. Thanks!
