### ISSUE TITLE
Hide Edit/Delete button

### ISSUE THREAD

**Issue by vterry** [mattlewis92/angular-bootstrap-calendar#610]
###  Feature request:

Hey, I think is a good idea to have a feature for hide edit and delete buttons based on user authorities. If it exists, there is a documentation showing how to use that?

Bests.

**Comment by burtek** [comment]
"hide edit and delete buttons based on user authorities" - can you please be more specific?

**Comment by vterry** [comment]
If u look at this example: [http://imageshack.com/a/img924/2151/2B6Uuj.png](url) you will see that bellow the week, there is a list of events with two small buttons to edit event or delete it. I think its a good idea hide this options for common users, making the calendar able only to viewing for them.

**Comment by burtek** [comment]
You have to define those actions explicitly. They are controlled by `event.actions` field, as described [here](https://github.com/mattlewis92/angular-bootstrap-calendar#events-required-attribute). Solution: add them only when you need them ;)
