### ISSUE TITLE
Hide week number box

### ISSUE THREAD

**Issue by AfarsheziF** [mattlewis92/angular-bootstrap-calendar#611]
Hi there,
Is it possible to hide the week number box? I've tried to hide .cal-week-box with no luck /:
Thanks!

**Comment by burtek** [comment]
Have you tried hiding `#cal-week-box`? It's the id, not the class. `#cal-week-box { display: none !important; }` works for me :)

The other idea would be to edit `calendarMonthCell.html` template and remove lines 40-42.

**Comment by AfarsheziF** [comment]
#cal-week-box { display: none !important; } working!
Thanks :)!

**Comment by MargaretKrutikova** [comment]
The only thing that made it work for me was setting ```display: none``` on ```.cal-week-box-cell```. The markup has probably changed in the last version ...
