### ISSUE TITLE
Problem on drag event

### ISSUE THREAD

**Issue by leonvelicea** [mattlewis92/angular-bootstrap-calendar#613]
### Bug description / Feature request:
The error occours while moving and event from a day to another, and more precisly on the drop event.
I am using this calendar as a schedular and while it still functions even with this error it's not really that nice. If you need more information please let me know.
Stacktrace:
Uncaught TypeError: Cannot set property 'endDate' of undefined
    at Object.o.onDragSelectEnd (mwlCalendarMonth.js:136)
    at fn (eval at compile (angular.js:15358), <anonymous>:4:235)
    at HTMLDivElement.<anonymous> (mwlDragSelect.js:12)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.q.handle (jquery.min.js:3)

### Versions

Angular:  1.6.4

Calendar library: 0.29.0

Browser name and version:  Chrome Version 58.0.3029.110 (64-bit)

**Comment by mattlewis92** [comment]
I can't reproduce this on any of the demos, are you able to provide a plunker that reproduces it? Thanks!

**Comment by leonvelicea** [comment]
Unfortunetly I cannot provide a plunker , I would have to decouple a lot of code.
I am sure that I am not doing something OK, I could not see the problem elsewhere. 
I will try to figure this out and I will let you know how this can be reproduced.

**Comment by mattlewis92** [comment]
OK no worries 😄
