### ISSUE TITLE
Dragging event also fires range selection

### ISSUE THREAD

**Issue by trks1970** [mattlewis92/angular-bootstrap-calendar#614]
When dragging an event forward (eg: to a date after the current date in month view) on-date-range-select and on-event-times-changed are both invoked.
Is there a possibility to distinguish if range selection occured because of a drag or without an event being dragged?

**Comment by burtek** [comment]
First of all - @mattlewis92, should `on-date-range-select ` really be invoked in this case?

**Comment by trks1970** [comment]
No, that would of course be the preferred case.
It should only be invoked, without a drag.

**Comment by mattlewis92** [comment]
This does look like a bug, the date range select simply shouldn't be invoked when dragging an event. Plunker: http://plnkr.co/edit/ykLjQN0uXyGBPBU16E6o?p=preview

**Comment by mattlewis92** [comment]
I've just cut `0.29.3` which should fix this, LMK if it works for you 😄

**Comment by trks1970** [comment]
Aye, it does work. Thanks for the quick fix.

**Comment by mattlewis92** [comment]
That's great to hear! 😀
