### ISSUE TITLE
rrules are not recognized

### ISSUE THREAD

**Issue by reshadf** [mattlewis92/angular-bootstrap-calendar#618]
### Bug description / Feature request:
I have the following setup

```                        
var rule = rrulestr(response['recursOn']);
vm.events.push({
         title: response['title'],
         rrule: rule
});
```

It prints out everything correctly in Console, however, the calendar is giving the following message: 

>"Event is missing the startsAt field"
>{title: "Gym", rrule: RRule ...}

This results in the event showing up only once on just the current DateTime. 

Is it somehow not recognizing RRule ? 

### Versions

Angular: 1.6.4

Calendar library: 0.29.3 

Browser name and version: Safari 10.1.1 (12603.2.4)

**Comment by mattlewis92** [comment]
You have to use the rrule lib for generating the events yourself in a format the calendar expects: https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=recurring-events
