### ISSUE TITLE
templates not found error

### ISSUE THREAD

**Issue by deepaucksharma** [mattlewis92/angular-bootstrap-calendar#619]
After following the steps mentioned, when I try to use the mwl calendar directive I get following error - 

Error: [$compile:tpload] http://errors.angularjs.org/1.4.9/$compile/tpload?p0=mwl%2FcalendarDayView.html&p1=404&p2=Not%20Found
Error: [$compile:tpload] http://errors.angularjs.org/1.4.9/$compile/tpload?p0=mwl%2Fcalendar.html&p1=404&p2=Not%20Found
Error: [$compile:tpload] http://errors.angularjs.org/1.4.9/$compile/tpload?p0=mwl%2FcalendarHourList.html&p1=404&p2=Not%20Found
Error: [$compile:tpload] http://errors.angularjs.org/1.4.9/$compile/tpload?p0=mwl%2FcalendarMonthCell.html&p1=404&p2=Not%20Found
Error: [$compile:tpload] http://errors.angularjs.org/1.4.9/$compile/tpload?p0=mwl%2FcalendarMonthView.html&p1=404&p2=Not%20Found
Error: [$compile:tpload] http://errors.angularjs.org/1.4.9/$compile/tpload?p0=mwl%2FcalendarMonthCellEvents.html&p1=404&p2=Not%20Found
Error: [$compile:tpload] http://errors.angularjs.org/1.4.9/$compile/tpload?p0=mwl%2FcalendarSlideBox.html&p1=404&p2=Not%20Found
Error: [$compile:tpload] http://errors.angularjs.org/1.4.9/$compile/tpload?p0=mwl%2FcalendarYearView.html&p1=404&p2=Not%20Found
The requested information does not exist
Error: [$compile:tpload] http://errors.angularjs.org/1.4.9/$compile/tpload?p0=mwl%2FcalendarWeekView.html&p1=404&p2=Not%20Found

**Comment by burtek** [comment]
Looks like you did not put templates where the directive expects them to be. How did you install mwl-calendar?

**Comment by deepaucksharma** [comment]
added it to bower dependences, the templates are under the dist folder in components folder. But the directive expects it at some other location.

**Comment by burtek** [comment]
Well... They should be in `src/`:

![image](https://user-images.githubusercontent.com/2940958/27861484-5377e61e-6181-11e7-920a-9e6b87719de9.png)

**Comment by mattlewis92** [comment]
It sounds like you're including the wrong bundle that doesn't have the templates included, make sure you're including the one ending in `-tpls.js`: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/dist/js/angular-bootstrap-calendar-tpls.js
