### ISSUE TITLE
Removing Badge Numbers

### ISSUE THREAD

**Issue by mani3202** [mattlewis92/angular-bootstrap-calendar#621]
I don't want to display badge numbers in month view please help me ?

**Comment by burtek** [comment]
Do you mean #611?

**Comment by mani3202** [comment]
I have one event in my todays date so its display both event and badge also.badge in the sense in the top of number it display 1 .i want to hide this feature how can i do this

**Comment by burtek** [comment]
For all days or only today?

**Comment by mani3202** [comment]
For all days

**Comment by burtek** [comment]
CSS rule `small.cal-events-num.badge{ display: none; }` works for me.
