### ISSUE TITLE
Problem Importing calendar in my project

### ISSUE THREAD

**Issue by mztikz** [mattlewis92/angular-bootstrap-calendar#623]
Hey I am trying to use Angular Calendar in my project,
I have the calendar shown but there is a few problems which I can't understand why they occur,
I have done everything like the "Kitchen" Demo and I even made a simpler one w/o all the buttons ..
Yet when I click on a day with Event ( Task) on it , It reach the timeSpanClicked function and toggle the events info bar on all the rows with the same tasks/events,
I will provide a picture tommorow morning first thing since I don't have it at the moment but I was wondering if there any guess why it happens..
![image](https://user-images.githubusercontent.com/12010477/28378759-f7c05510-6cb9-11e7-8829-9b279f89358c.png)
The picture is taken from the demo , 
and the black bar is shown always on-top of the columns ..
like its always open, and when I click it toggles the same bar on all the rows..
Thanks alot from advanced.

**Comment by burtek** [comment]
Hi,

I do not quite understand the problem you have. Could you please provide a plunker showing the problem?

**Comment by mztikz** [comment]
I  dont think I can provide plunker atm but I have pictures with my code providing anything you want I did exactly like the demo example shows nothing more nothing less,
Thats the problem where there is a black line on all rows : 
![tmp](https://user-images.githubusercontent.com/12010477/28404451-086dfae8-6d32-11e7-80a8-cbce9c570002.png)
thats the problem when I click on the event at the saturday , it shows on all rows same events
![tmp2](https://user-images.githubusercontent.com/12010477/28404463-19e8f8fe-6d32-11e7-9955-8d7771f0e38e.png)

and thats the code:
Typescript : 
![tmp5](https://user-images.githubusercontent.com/12010477/28404477-2b74c954-6d32-11e7-91d8-59e78d26d215.png)

![tmp4](https://user-images.githubusercontent.com/12010477/28404468-20ee7ff2-6d32-11e7-8470-a1f2789aca7c.png)

Html:
![tmp3](https://user-images.githubusercontent.com/12010477/28404487-32e222c2-6d32-11e7-84d0-5b577dbbba86.png)

Thanks alot from advanced.

**Comment by burtek** [comment]
@mattlewis92? I'm lost here...

**Comment by mztikz** [comment]
I have found the problem it seems like there was a missing css if you want to watch it : 
![dsfsdfdf](https://user-images.githubusercontent.com/12010477/28412827-07870be4-6d4e-11e7-9aac-35f4c2c2ec4a.png)

**Comment by mattlewis92** [comment]
It looks like you're not including the bootstrap CSS which is why it's not working.
