### ISSUE TITLE
Collapse can not open when click

### ISSUE THREAD

**Issue by zhengcongyin** [mattlewis92/angular-bootstrap-calendar#625]
### Bug description / Feature request:
Hi,
Your project is awesome. However, I found that the collapse can not open when clicked the calendar.
The version of UI.Bootstrap is 2.5.0. Could you help me with this issue? Thanks in advanced.

### Versions

Angular:  1.6.2

Calendar library: 0.29.3

Browser name and version: angular-bootstrap-calendar 0.29.3

**Comment by burtek** [comment]
Everything's working fine for me. Could you provide plunker showing the problem? What broswser do you use? Did you try other browsers?

**Comment by zhengcongyin** [comment]
I integrated with my asp.net project. I doubt that I can provide the code in plunker. The problem is that the collapse never show neither load the calendar or click. 
The angular dependency injector look like this: 
    'ngAnimate',
    "ui.router",
    'ui.utils',
    "ui.jq",
    'ui.grid',
    'ui.grid.pagination',
    "oc.lazyLoad",
    "ngSanitize",
    'angularFileUpload',
    'daterangepicker',
    'angularMoment',
    'frapontillo.bootstrap-switch',
    'abp',
    'mwl.calendar',
    "ui.bootstrap"

Do you think any one block the collapse? 
It works fine at my other project, which includes the following lib:
        'ngAnimate',
        'ngSanitize',
        'mwl.calendar',
        'ui.router',
        'ui.bootstrap',
        'ui.jq',
        'abp'

Thanks!

**Comment by zhengcongyin** [comment]
I have tried chrome/ firefox/ Edge.

**Comment by burtek** [comment]
Do you get any errors in browser console?

**Comment by zhengcongyin** [comment]
Nope. I wonder if it has been blocked by some other css. However, I tried to add a button with collapse. It works fine.

**Comment by burtek** [comment]
Try commenting out different JS libs and CSS stylesheets and see which one is at fault

**Comment by zhengcongyin** [comment]
I figured it out by changing cell-auto-open-disabled from "true " to "false"
