### ISSUE TITLE
Allow image thumbnails as well as colors for an event

### ISSUE THREAD

**Issue by aarohmankad** [mattlewis92/angular-bootstrap-calendar#626]
### Versions

Angular: 1.5.8

Calendar library: 0.23.0

Browser name and version: (irrelevant)

**Comment by burtek** [comment]
Colors are [supported](https://github.com/mattlewis92/angular-bootstrap-calendar#events-required-attribute) at this moment. As for thumbnails - I can't really see how they would work (how big, in which view...?). @mattlewis92?

You can try and create such functionality yourself and add it to the library.

**Comment by mattlewis92** [comment]
I would recommend just using a [custom template](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=custom-templates) for this, replacing the event dots with images etc. It's not something I plan on supporting in the core lib though.
