### ISSUE TITLE
The calendar date is not correct

### ISSUE THREAD

**Issue by zhengcongyin** [mattlewis92/angular-bootstrap-calendar#628]
### Bug description / Feature request:
I just found the calendar Date is not correct. In your calendar, 2017-07-31 is Tuesday. In fact, it is Monday. Could you give me any hint to fix this problem 

### Versions

Angular: 1.6.6

Calendar library: 0.29.3

Browser name and version: 0.29.3

**Comment by burtek** [comment]
It looks ok to me. Did you notice the first column is Sunday, not Monday? If the bug only appears on your computer, could you provide screenshot?

**Comment by zhengcongyin** [comment]
Thanks for your prompt reply. I attached the screen shot below. You can see 2017-07-31 is Tuesday, which is not correct. And on my computer, the first column is Monday.
![image](https://user-images.githubusercontent.com/10716937/28800658-3bb65c54-7680-11e7-828c-312bf4833037.png)

**Comment by burtek** [comment]
Well, on the screenshot it's even Wednesday, not Tuesday. Which is still odd. Does the example you linked in first post also produce this bug?

**Comment by zhengcongyin** [comment]
The plunker is not my code. I use your calendar in my asp.net project. I console.log viewDate, it is correct. I have no idea which part control this.

**Comment by burtek** [comment]
I guess we'll have to wait and see if @mattlewis92 has any idea, 'cause I give up here...
