### ISSUE TITLE
how to call custom service on click of events and fetch the calendar data through that custom service

### ISSUE THREAD

**Issue by SheethalRamesh** [mattlewis92/angular-bootstrap-calendar#629]

**Comment by burtek** [comment]
Use `on-event-click="vm.eventClicked(calendarEvent)"` as shown [here](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=kitchen-sink) and in your controller assign service (or service method) to `vm.eventClicked`, i.e.: `vm.eventClicked = myService.eventClicked;`.

Is this the answer you needed or do you need something else?

**Comment by SheethalRamesh** [comment]
How to bind the data from the backend to calendar event?

**Comment by burtek** [comment]
I don't understand what you want to achieve. You want to be able to modify the clicked event from the service and return it to the calendar?

**Comment by SheethalRamesh** [comment]
Yes that is what i need. On click of an event, a dialog box should open and whatever data entered inside dialog box should be binded on the calendar event.

**Comment by burtek** [comment]
The `event` argument has `calendarEventId` field which is the event's index in `vm.events`. It's enough to call the service method with two arguments to be able to modify clicked event service-side:

```javascript
vm.eventClicked = function(event) {
    vm.events = myService.eventClicked(event, vm.events);
}
```

Or even:

```javascript
vm.eventClicked = function(event) {
    vm.events[event.calendarEventId] = myService.eventClicked(vm.events[event.calendarEventId]);
}
```

**Comment by SheethalRamesh** [comment]
Will work on it.. Thanks a lot!!!!

**Comment by burtek** [comment]
No problem. Should you need more help just post again in this thread, there is no need to open new one :)
