### ISSUE TITLE
Can't See Calendar Title

### ISSUE THREAD

**Issue by sameer22** [mattlewis92/angular-bootstrap-calendar#63]
I just started to play with control. 

Angularjs version is 1.3.15. I'm not able to view calendar title (2015 / Week 17 of 2015 etc). Can someone suggest?

Thanks

**Comment by mattlewis92** [comment]
Can you post some code up?

**Comment by sameer22** [comment]
HTML is as below

<div>


        <mwl-calendar events="events"
                      view="calendarView"
                      view-title="calendarTitle"
                      current-day="calendarDay"
                      on-event-click="eventClicked(calendarEvent)"
                      on-edit-event-click="eventEdited(calendarEvent)"
                      on-delete-event-click="eventDeleted(calendarEvent)"
                      auto-open="true">
        </mwl-calendar>

        <button class="btn btn-primary"
                ng-click="calendarView='year'">
            Year
        </button>
        <button class="btn btn-primary"
                ng-click="calendarView='month'">
            Month
        </button>
        <button class="btn btn-primary"
                ng-click="calendarView='week'">
            Week
        </button>
        <button class="btn btn-primary"
                ng-click="calendarView='day'">
            Day
        </button>

    </div>
    <div>
        <button class="btn btn-primary"
                mwl-date-modifier
                date="calendarDay"
                decrement="calendarView">
            Previous
        </button>

        <button class="btn btn-default"
                mwl-date-modifier
                date="calendarDay"
                set-to-today>
            Today
        </button>

        <button class="btn btn-primary"
                mwl-date-modifier
                date="calendarDay"
                increment="calendarView">
            Next
        </button>
    </div>

**Comment by mattlewis92** [comment]
That's the current master docs for an as yet unreleased version. See [here](https://github.com/mattlewis92/angular-bootstrap-calendar/tree/0.9.2) for the current stable docs. Maybe adapt your code from [the demo](http://mattlewis92.github.io/angular-bootstrap-calendar/).
