### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: $uibModalProvider <- $uibModal <- alert

### ISSUE THREAD

**Issue by Abdou00** [mattlewis92/angular-bootstrap-calendar#631]
Hello,
### Bug description / Feature request:

I added the angular-bootstrap-calendar in my [MeanJS](http://meanjs.org/) project, I integrated the demo template and all displayed but I have a problem with the opening of the modal when I click on an event I ' Error:

Error: [$injector:unpr] Unknown provider: $uibModalProvider <- $uibModal <- alert

I also have a problem with different views (year, month, ...) when I click on the buttons it does not matter the view does not change and the console does not return error.

Do you have any idea what is causing these problems?

### Versions

Angular: ~1.3

Calendar library:  v0.29.3 

Browser name and version: Chrome | Version 59.0.3071.115

**Comment by Abdou00** [comment]
I solved the problem with modal this was due to the fact that $ uibModal has been renamed $ modal.

**Comment by Abdou00** [comment]
I still do not understand why my calendar still does not display the different views (month, day, ....)

**Comment by burtek** [comment]
any plunker with code?

**Comment by Abdou00** [comment]
This is the code of the demo version as it is
