### ISSUE TITLE
How to better personalize a calendar?

### ISSUE THREAD

**Issue by abarbaro** [mattlewis92/angular-bootstrap-calendar#632]
Hi,
I'm trying to use angular-bootstrap-calendar and create a calendar where a user can select multiple dates in one go and add an event to the selected range. So far, following the documentation, I can create a custom template for a monthly cell or allow a user to select a range of dates. Unfortunately, as soon as I try to mix the two things I cannot select the range anymore but the custom template is working fine. I have created the calendar in this way

```
<mwl-calendar
    view="calendarView"
    view-date="viewDate"
    events="prices"
    view-title="calendarTitle"
    on-event-click="eventClicked(calendarEvent)"
    on-event-times-changed="calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
    custom-template-urls="{calendarMonthCell: 'customMonthCell.html'}"
    on-date-range-select="rangeSelected(calendarRangeStartDate, calendarRangeEndDate)"
    cell-is-open="true"
    cell-modifier="cellModifier(calendarCell)">
</mwl-calendar>
```
Can anyone show me a plunker working example please?

[Plunker example](http://plnkr.co/edit/VHkbUEkrOcmnhiPOPbc4)

I have this question before on StackOverflow but no luck so far.

Thanks

**Comment by mattlewis92** [comment]
Ah I think that example is a bit out of date, if you base your custom template from the [latest master version](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarMonthCell.html) it should give you the behaviour you're after 😄

**Comment by abarbaro** [comment]
Hi,
do you have time to create a working example please? I'm not able to do it.

Thanks
