### ISSUE TITLE
How can I set the calendar's timezone?

### ISSUE THREAD

**Issue by wootwoot1234** [mattlewis92/angular-bootstrap-calendar#634]
I posted this question on [stackoverflow](https://stackoverflow.com/questions/45616357/set-calendar-timezone-in-angular-bootstrap-calendar), as suggested, but haven't gotten any responses so I thought I would go to the source, I hope that's ok.

I'm using angular-bootstrap-calendar to display the calendar of an short term rental listing. Currently, the calendar displays the dates in the timezone of the browser but the user isn't always in the same timezone as the listing they are managing.

How can I set the calendar's timezone so that it shows the dates in the timezone of the listing and not the timezone of the bowser?

**Comment by burtek** [comment]
How do you acquire the data for calendar? Do you include that in the JS file, or do you use some kind of API?

**Comment by mattlewis92** [comment]
To do this you would need to use the [moment timezone](https://momentjs.com/timezone/) plugin to manipulate the dates passed to the calendar:
```
const userTimezone = 'America/Los_Angeles';
vm.events = [
  {
        title: 'An event',
        color: calendarConfig.colorTypes.warning,
        startsAt: moment().tz(userTimezone).startOf('week').subtract(2, 'days').add(8, 'hours').toDate(),
        endsAt: moment().tz(userTimezone).startOf('week').add(1, 'week').add(9, 'hours').toDate()
  }
];
```
