### ISSUE TITLE
How to hide decrement button for past month ? 

### ISSUE THREAD

**Issue by athimannil** [mattlewis92/angular-bootstrap-calendar#636]
Is there any option in the angular-bootstrap-calendar to disable `decrement="calendarView"` for past months ?

Demo: http://plnkr.co/edit/LE4F4U7AnnD3tjM9ZH4G?p=preview

**Comment by burtek** [comment]
Check [this comment](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/596#issuecomment-302118055).
