### ISSUE TITLE
BUG -- Month view , extra slidebox stand

### ISSUE THREAD

**Issue by spinningtool** [mattlewis92/angular-bootstrap-calendar#638]
Hello,

Firstly, I want to thank you for great calendar. The year view part was so useful for me. I had to need moth view and used it. But the problem that I realized; If a day has more than one event and when slidebox is open and you pass to next month but current month is 5 week row and the next month is 6 week row (for example November to December) , the empty gray slidebox div is formed and this never removed until refresh the page. This happens not only my project, also happen the demo.   

I just realized , the problem could caused by the scroll bar or the calendar witdh chaning.

### Bug description / Feature request:

When pass to 5 week row month to 6 week row month , adding empy slide box. Also if the next month has a event or events , when clicking to open day to slide , also filled to extra slide box.
the screenshots below
![bug1](https://user-images.githubusercontent.com/31131283/29458516-40d83a58-8428-11e7-9abe-fb2f58a5ec3a.PNG)
![bug](https://user-images.githubusercontent.com/31131283/29458507-3a5d1eb4-8428-11e7-9575-74abcb52f5a2.PNG)
![bug2](https://user-images.githubusercontent.com/31131283/29458569-76202266-8428-11e7-9512-a5aeab70cade.PNG)

### Versions

Angular: 

Calendar library: 
latest version

Browser name and version: 
Google Chrome , latest version

**Comment by burtek** [comment]
It looks like a bug to me. However: Could you provide dataset (plunker) with data that causes the bug, so that I'm able to further research this problem?

**Comment by spinningtool** [comment]
You can try it in demo. Add an event in November 1 and pass to next month. You can see the problem. Dataset does not matter

**Comment by burtek** [comment]
Got it. Actual steps to reproduce on the [kitchen-sink example](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=kitchen-sink):

1. Add event on November 1st
2. Go to November and click on the 1st to open the slidebox
3. Go to December.

@mattlewis92

**Comment by spinningtool** [comment]
Absolutely that. This blank slide box just shown the first week days on month
