### ISSUE TITLE
Change direction of days

### ISSUE THREAD

**Issue by eliadvertman** [mattlewis92/angular-bootstrap-calendar#639]
Hello,

because my project is in hebrew (we write from right to left),
i need to switch the direction of the days from right to left, 

how can i do that?

**Comment by burtek** [comment]
The only way I can think of would be to write own view templates based on original templates.

**Comment by eliadvertman** [comment]
Is there any tutorial for that?

**Comment by burtek** [comment]
Just have a look at original templates - it's just HTML code with angularJS tags.
