### ISSUE TITLE
Multiple months in page

### ISSUE THREAD

**Issue by maxborgatti** [mattlewis92/angular-bootstrap-calendar#641]
Is it possible to place e.g. three months in a page? I did give it a try adding multiple mwl-calendar-month-view but with no luck

I think that on mobile devices will be useful to simply scroll top bottom for next months. Is there any way to achieve this?

**Comment by burtek** [comment]
What was your problem with adding multiple calendars? It should work once configured correctly... [Plunker example](http://plnkr.co/edit/t3HJl685gxpwsNa1wULV?p=info) (may not work 100% correctly as I wrote it on my "smart"phone, but should give you the idea)

**Comment by mattlewis92** [comment]
Closing in favour of https://github.com/mattlewis92/angular-calendar/issues/322
