### ISSUE TITLE
All Events Show in the Current Year

### ISSUE THREAD

**Issue by s2jrchoi** [mattlewis92/angular-bootstrap-calendar#642]
All the events are currently showing in the same current year.  When I go to the previous/next year, the same events show up.  What am I doing wrong?  

My dates come in like this:
rawDate = 2018-09-18T04:00:00Z

Then I convert the date as a Date: 
convertedDate = new Date(rawDate);
Mon Sep 18 2018 00:00:00 GMT-0400 (Eastern Daylight Time)

And this 2018 date shows in the 2017 calendar year.

Please help!  Thank you!

**Comment by mattlewis92** [comment]
Please can you share a plunker or something similar that reproduces your problem as its hard to understand what's going on from the snippet you posted. You can fork a starting plunker from any of the [demos](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=kitchen-sink). Thanks! 😄

**Comment by mattlewis92** [comment]
Closing due to lack of response
