### ISSUE TITLE
On-event-click does not work for all day events

### ISSUE THREAD

**Issue by gintsgints** [mattlewis92/angular-bootstrap-calendar#644]
### Bug description:
When create all day event and specify on-event-click. Event is not fired for all day events.

### Link to minimally-working plunker that reproduces the issue
http://plnkr.co/edit/t8pOG2OB0SZawzMojtHQ?p=preview

### Versions
Angular:
1.6.0
Calendar library:
0.29.3
Browser name and version:
Chrome

**Comment by burtek** [comment]
Thanks for bug report. Working on it.

**Comment by burtek** [comment]
Fix is waiting for mattlewis92 to accept PR.

**Comment by burtek** [comment]
As a temporary work-around you can modify the template as [shown here](https://github.com/mattlewis92/angular-bootstrap-calendar/pull/645/commits/cc48a75858fba6b38c9e8939b1fed7e83a77642a).

**Comment by gintsgints** [comment]
Thanks!
