### ISSUE TITLE
calendarUtils.js.map routing exception

### ISSUE THREAD

**Issue by barralta** [mattlewis92/angular-bootstrap-calendar#646]
### Bug description / Feature request:
I'm just trying a little demo. I've installed version 0.30 but the calendar isn't rendered.
I'm getting this error : 
No route found for "GET /bower_components/angular-bootstrap-calendar/dist/js/calendarUtils.js.map

### Versions
Angular: 1.4.7
Calendar library: 0.30.0
Browser name and version: Chrome 60.0.3112.113

Any idea? Thanks

**Comment by burtek** [comment]
Where did you put project's JS files? Also, how do you include them?

**Comment by barralta** [comment]
Yes, I've included them. I've used bower to install so it's in bower's directory that's in /bower_components/angular-bootstrap-calendar

Thanks!!

**Comment by burtek** [comment]
So all you need is:

`<link href="bower_components/angular-bootstrap-calendar/dist/css/angular-bootstrap-calendar.min.css" rel="stylesheet">
<script src="bower_components/angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls.min.js"></script>`

as per [#installation](https://github.com/mattlewis92/angular-bootstrap-calendar#installation). It should work correcty with that piece of code. Is that the piece you have?

**Comment by barralta** [comment]
Sorry, I've been using :

<script src="bower_components/angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar.js"></script>

I've changed it and works just fine!

Thansk so much and sorry again

**Comment by burtek** [comment]
No need to be sorry :) Glad we solved it.
