### ISSUE TITLE
Hours in week view

### ISSUE THREAD

**Issue by karbonn** [mattlewis92/angular-bootstrap-calendar#65]
Hi
How can i display hours in week view like hours in day view?

**Comment by mattlewis92** [comment]
There isn't a way to do this, I will gladly accept a PR that adds the functionality though :)

**Comment by karbonn** [comment]
I can do a PR but do you have any hints on how to build it ?

I'm discovering Angular so it is hard for me to design things...

Actually the Week view display events in a row, so we have to change that into columns, am I right ?

May I create a new directive ? What kind of template sould I use ? What existing directives can I take advantage of ?

Thanks !

**Comment by mattlewis92** [comment]
The development setup instructions can be found in the readme.

You could probably re-use the day view directive and repeat it 7 times over for each day of the week and use some CSS to make it work properly.

Or if you don't mind the jquery dependency you could use the [angular-ui calendar](http://angular-ui.github.io/ui-calendar/) which is a lot more feature complete than this one.

**Comment by mattlewis92** [comment]
Experimental support for this is now possible, however it doesn't support event end times as it got really hard to implement. It can be turned on by setting:
```
calendarConfigProvider.showTimesOnWeekView(true);
```

**Comment by wescopeland** [comment]
When I enable times on the week view, the starting time is set to 12AM. Is there any way to configure the range of times displayed?

**Comment by jo1vulin** [comment]
Hi,

has anything additional been done on this subject?

Thank you

**Comment by neghani** [comment]
I have used the plug in one of my project, I had to display schedules around 3k in each view I had done some alterations to the original code to be responsive with the data size. I don't know how to PR and update the code in GitHub can you help me.

**Comment by neghani** [comment]
Also grouping schedules with same date and time has also done in my code need a way to update plugin.

**Comment by neghani** [comment]
Grouping has done*
