### ISSUE TITLE
Feature Request: Ability to drag and drop between calendars

### ISSUE THREAD

**Issue by jmsunseri** [mattlewis92/angular-bootstrap-calendar#650]
### Feature request:
The ability to drag between calendars.  It's sort of weird that I can apply the mwl-draggable property to an external object and drag it all over the screen but if i want to drag an existing event which also has mwl-draggable= true I can drag it outside of it's current calendar.

I'm trying to implement my own version of the week view with hours since the existing one seemed to be lacking and this is my stumbling block

###Plunker

http://plnkr.co/edit/ZPYoKalCYJFxORhnhALE?p=preview

### Versions

Angular: 1.6.6

Calendar library: 0.30.0

Browser name and version: Chrome ( Latest )

**Comment by burtek** [comment]
One idea was presented in #595 (using interactjs global listener), the idea was also suggested in #288. Maybe those threads can help you?

**Comment by jmsunseri** [comment]
I guess I can see how that would allow me to drop the event in the appropriate calendar but the event disappears and hides under the other calendars when dragging it.  Do I need to do something to the event cell?

**Comment by burtek** [comment]
Rather with `overflow` and/or `z-index` ;)

**Comment by jmsunseri** [comment]
I tried to modify the template to set setting the z-index and overflow in my custom template but it still falls behind the other cals.  

http://plnkr.co/edit/ZPYoKalCYJFxORhnhALE?p=preview

**Comment by bwobbones** [comment]
#595 has something of an explanation of how I achieved this

**Comment by mattlewis92** [comment]
Looks like this was already solved here: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/595#issuecomment-340076690 Thanks for your sharing your solution! 😄
