### ISSUE TITLE
How to Display Event Titles instead of color dots

### ISSUE THREAD

**Issue by mAkshata** [mattlewis92/angular-bootstrap-calendar#654]
### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
The short answer is you can't, but if you don't use event end dates you may be able to use a [custom month cell template](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=custom-templates) to change how events are displayed, but YMMV.
