### ISSUE TITLE
A bug appears in case you have start/end date in recurring events

### ISSUE THREAD

**Issue by irfan** [mattlewis92/angular-bootstrap-calendar#655]
### Bug description
A bug appears in case you have start/end date in recurring events, a lot of events created in the first day.
I got your recurring-events example and just added the lines below:
```
{
      start: new Date(),
      end: new Date(),
      title: 'Daily',
      color: colors.red,
      rrule: {
        freq: RRule.DAILY,
        byweekday: [RRule.MO, RRule.SU, RRule.WE, RRule.TU]
      }
    }
```
The 2 lines below added to the example above:
```
      start: new Date(),
      end: new Date(),
```

### Working plunker that reproduces the issue 
http://plnkr.co/edit/zda0isH8vF0uamikctlX?p=preview

As you know, no one save recurring events separated in a database, you create an event and set it as "recurring event" in your calendar, so in your calendar, you will have start/end date by default.

### Dirty solution:
I think there should be better solution than deleting start end properties manually like:
```
delete event.start;
delete event.end;
```

**Comment by burtek** [comment]
If I'm not mistaken, you're using `angular-calendar` which is a different project, available [here](https://github.com/mattlewis92/angular-calendar) ;)
