### ISSUE TITLE
iam unable to implement it in angularcli can anyone help me

### ISSUE THREAD

**Issue by rnkpareek** [mattlewis92/angular-bootstrap-calendar#656]
### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by burtek** [comment]
Closed for duplicate (#657)

**Comment by rnkpareek** [comment]
i want to implement in angular 4 using the cli .but this link dnt have any
component or ts file.

**Comment by burtek** [comment]
@rnkpareek angular-calendar project for angular 2+ is [here](https://github.com/mattlewis92/angular-calendar). This is AngularJS project.
