### ISSUE TITLE
i cant see the calendar properly

### ISSUE THREAD

**Issue by yael1996** [mattlewis92/angular-bootstrap-calendar#660]
the calendar desplaied like this : 
Sunday
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
26
27
28
29
30
31
1
2
and so on...

**Comment by mattlewis92** [comment]
Hi there,

It sounds like you're not including the stylesheets for this library.

Hope that helps! 😄

**Comment by yael1996** [comment]
thanks!
