### ISSUE TITLE
lost element on-event-times-changed

### ISSUE THREAD

**Issue by adonisnowman** [mattlewis92/angular-bootstrap-calendar#661]
angular-bootstrap-calendar-master/dist/js/angular-bootstrap-calendar-tpls.js

row 1996  module.exports = "<div class=\"cal-week-box\"....
in mwl-calendar-hour-list lost element on-event-times-changed

on-event-times-changed=\"vm.onEventTimesChanged\"\n

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Sorry I'm not really sure I follow you, please could you attach a minimal plunker that demonstrates your issue. Thanks!
