### ISSUE TITLE
I need a good way to modify the height of the rows in the dayview

### ISSUE THREAD

**Issue by jmsunseri** [mattlewis92/angular-bootstrap-calendar#663]
### Feature request:
I need a good way to modify the height of the rows in the dayview.  I've tried setting in css
.cal-day-box .cal-day-hour-part { height: 20px; }
 and that sets the row high visually correctly but the events doesn't seem to respect these new row sizes at all.

Is there a combination of things I need to modify in my custom day view template and define in JS to accomplish this?

### Link to minimally-working plunker that reproduces the issue (starter template: 

sorry no link at this time

### Versions

Angular: v1.6.6

Calendar library: version v0.30.0

Browser name and version:

**Comment by mattlewis92** [comment]
I believe https://github.com/mattlewis92/angular-bootstrap-calendar/pull/652 should give you what you're after once it lands 😄
