### ISSUE TITLE
Translating week

### ISSUE THREAD

**Issue by HeikkiYlipaavalniemi** [mattlewis92/angular-bootstrap-calendar#68]
Hi,

Just a quick question. I am still using version 0.9.2 but is it possible to translate the title for week view?

At the moment week view title is displayed as:
Week 18 of 2015

Could this be somehow translated?

**Comment by mattlewis92** [comment]
See the [0.9.2](https://github.com/mattlewis92/angular-bootstrap-calendar/tree/0.9.2#calendar-week-title-label) docs
