### ISSUE TITLE
openEvents not refreshed for year or month views on events change

### ISSUE THREAD

**Issue by ptrckc** [mattlewis92/angular-bootstrap-calendar#75]
If i remove an event from the underlying events on a day that has been opened (and the slide box is showing), the view will reflect the change, ie the badge count and dots, but the event remains in the list on the slide box. Looks like an issue with not refreshing openEvents

**Comment by mattlewis92** [comment]
Thanks for reporting these bugs, I'll get them fixed on the weekend :)
