### ISSUE TITLE
Event template

### ISSUE THREAD

**Issue by amellini** [mattlewis92/angular-bootstrap-calendar#76]
Hi, thank you for the component, really useful and simple, this is not a real issue but a question, how can i customize the event template (especially in Day mode) to show more information than 'title'?

**Comment by mattlewis92** [comment]
You can use a [decorator](http://angular-tips.com/blog/2013/09/experiment-decorating-directives/) to change the day view template url like so:

```javascript
app.config(function($provide) {
  $provide.decorator('mwlCalendarDayDirective', function($delegate) {
    var directive = $delegate[0];
    directive.templateUrl = 'URL_TO_YOUR_DAY_VIEW_TEMPLATE.html';
    return $delegate;
  });
});
```

Then just copy [the template](https://raw.githubusercontent.com/mattlewis92/angular-bootstrap-calendar/master/src/templates/calendarDayView.html) into your project to the path you set with the decorator and change whatever you want :)

**Comment by pkeuter** [comment]
For some reason this gives a $compile:multidir error. 

https://docs.angularjs.org/error/$compile/multidir?p0=mwlCalendarDay&p1=mwlCalendarDay&p2=template&p3=

**Comment by mattlewis92** [comment]
It's because the calendar no longer uses templateUrl and instead uses an inline template. Try doing `delete directiveConfig.template`

**Comment by pkeuter** [comment]
Thanks for the update. This works perfectly.
