### ISSUE TITLE
I cannot get it to work

### ISSUE THREAD

**Issue by soylomass** [mattlewis92/angular-bootstrap-calendar#77]
The template structure loads, but nothing is shown, I can see the Html with the debugger, for example the ng-repeat "... in vm.view", but it seems there is no data in vm.view.

**Comment by soylomass** [comment]
It was that I didn't set the current-day. It should show any error instead of not showing anything!

**Comment by mattlewis92** [comment]
Agreed, fixed in 0.10.2
