### ISSUE TITLE
Rename 'view' attr for directive

### ISSUE THREAD

**Issue by mayusha** [mattlewis92/angular-bootstrap-calendar#78]
It would be nice to rename "view" attribute since it causes the issues when man use it with angular ui-router.

Error: $compile:multidir
Multiple Directive Resource Contention

**Comment by mattlewis92** [comment]
That's odd, as the ui-router namespaces their directives with the ui- prefix. I will have a play with it tonight and see if I can find a fix.

**Comment by mattlewis92** [comment]
I can't seem to reproduce the error you're experiencing. Any chance you could create a (plunkr)[http://plnkr.co/] or something similar to show me the error you're experiencing.

**Comment by mayusha** [comment]
Ok. I will create a (plunkr) when have a minute.

**Comment by mattlewis92** [comment]
Thanks!

**Comment by mattlewis92** [comment]
It's definitely working with the ui-router, [here's an example](http://plnkr.co/edit/NnxC6rVHrPXsgm3ye75e?p=preview) with the ui.router module loaded it it's working fine. I'm 99% sure it's a bug your end, but if you're still having problems and can give me a plunker then I'll happily assist.
