### ISSUE TITLE
openEvents not refreshed in addition of new event

### ISSUE THREAD

**Issue by ptrckc** [mattlewis92/angular-bootstrap-calendar#79]
Similar to #75 with deleted events not being removed, new events added to a day with it toggled as open do not appear until the date is reclicked or changed and then come back to.

Your demo shows this issue - just add a new event, set the date to the current date, and you'll see an extra circle shown versus the number of listed events in the open accordion. Click the calendar date and the new event will appear.

**Comment by mattlewis92** [comment]
Should be fixed in 0.10.3
