### ISSUE TITLE
Close/filter calendarSlideBox from external function 

### ISSUE THREAD

**Issue by gazman99** [mattlewis92/angular-bootstrap-calendar#81]
Is it possible to close the calendarSlideBox from an external function?
Is it possible to filter shown events  if the calendarSlideBox is currently open?

I have a set of filters on the side of my app that update calender events based on their selections but if I have the calendarSlideBox already open this does not update?

any ideas?

**Comment by mattlewis92** [comment]
There isn't currently a way to close the slide box from an external function.

If you upgrade to 0.10.3 I put some fixes in on the weekend so that the events list in the calendar slide box will auto update when events are added or removed.

**Comment by gazman99** [comment]
thanks, that would be good. Also in day view could you add a horizontal scroll in to cater for multiple events on a certain day.

**Comment by mattlewis92** [comment]
Sure thing, I'll add that in the next version.
