### ISSUE TITLE
Default date and times

### ISSUE THREAD

**Issue by gazman99** [mattlewis92/angular-bootstrap-calendar#82]
Is it possible to specify a week# to default the month view to??

Is it possible to specify a start/end time for the day view?

**Comment by mattlewis92** [comment]
To change the week number, use moment to alter the date that you pass to the current-day attribute. i.e. in your controller do:
``` 
moment($scope.whateverYourDateVariableIs).week(weekNumber);
```

You can use the day-view-start and day-view-end attributes to change the day view start and end times. See the [docs](https://github.com/mattlewis92/angular-bootstrap-calendar) for how to use them or the demo for an example.

**Comment by gazman99** [comment]
Awesome. Amazing quick responses. +1
