### ISSUE TITLE
Overriding the ng-include templates & Controlling Calendar Month Views height

### ISSUE THREAD

**Issue by el-besto** [mattlewis92/angular-bootstrap-calendar#84]
Hi Again - Quick question about template overrides. I saw your response to a [similar issue that involves overriding the entire template of the directive](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/76)

__Basically, I want to override the calendarMonthDay template__ that is included (ng-include) in the calendarMonth directive. To move around what is displayed in the square. 

Is there a simple way to get this override done without modifying the source? I could just fork it and make the change, and recompile a new dist, but if there is a simpler way I am all ears.

Moreover, I noticed that when I did the decorator override the calendar seems a bit slower. Are there performance impacts when using this sort of override? If performance is a primary concern, would I be better off just forking, modifying and gulp building a new dist? I know its ultimately up to me, but thought I'd get the authors input as well before making my decision.

__Last question is about calendar height sizing__ I want the calendar to be much smaller, but try as I might to manipulate via css, the overall height seems to depend on variables declared on compilation of the directive. Any help here would be greatly appreciated, but not necessary.

Thanks again, 
Angelo

**Comment by mattlewis92** [comment]
You can either use a script tag or the $templateCache service to override the template, as documented [here](https://docs.angularjs.org/api/ng/service/$templateCache).

The decorator shouldn't make the calendar slower. AFAIK using decorators has no performance impact as all you're doing is changing a property of an object.

I'm not too sure how you would go about changing the height of the calendar. Maybe use !important in your css to force the rule?
