### ISSUE TITLE
Recurring Event

### ISSUE THREAD

**Issue by mamalias23** [mattlewis92/angular-bootstrap-calendar#86]
How can I add recurring event? example birthday where it happens every year..

**Comment by mattlewis92** [comment]
There isn't currently a way to do this. I'll give it some thought on the best way to add it.

**Comment by mamalias23** [comment]
Thanks, do you have any idea on how to do this in a hack way?

**Comment by mattlewis92** [comment]
Well you could repeat the event several times in the events array

**Comment by mamalias23** [comment]
Yes, but this will slow down the performance.. anyways, thank you.. I will do this for now

**Comment by ajajansari** [comment]
Recurring on Weekdays is possible, like only on Monday, Wednesday & Friday
