### ISSUE TITLE
Angular is not defined

### ISSUE THREAD

**Issue by laugmo** [mattlewis92/angular-bootstrap-calendar#89]
Hello Matt,

I have created my own meanjs project and installed all the recomended modules and directives, as well as the dependencies listed in the documentation section, however, whenever I try to load the calendar I get a console error stating that Angular is not defined and that the mwl.calendar module is not found. Have you got any clue on what might be wrong and how to fix it?? I have even downloaded your project and received the same error when attempting to compile the code. I would really appreciate your help, thanks

**Comment by mattlewis92** [comment]
Hi there,

Please can you share some sample code with me that replicates the error then we'll go from there. Thanks!

**Comment by laugmo** [comment]
We have not added any code, we just installed the calendar using the guide in the documentation section and although we have the angular link in the header of the view where the calendar is being added we are receiving the angular is not defined error which causes the Module 'mwl.calendar' not to be recognized:
    Uncaught ReferenceError: angular is not defined 
    angular-bootstrap-calendar-tpls.js:765

    Uncaught Error: [$injector:modulerr] Failed to instantiate module proyectointegrador due to:
    Error: [$injector:modulerr] Failed to instantiate module mwl.calendar due to:
    Error: [$injector:nomod] Module 'mwl.calendar' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
    http://errors.angularjs.org/1.2.26/$injector/nomod?p0=mwl.calendar
        at http://localhost:3000/lib/angular/angular.js:78:12
        at http://localhost:3000/lib/angular/angular.js:1677:17
        at ensure (http://localhost:3000/lib/angular/angular.js:1601:38)
        at module (http://localhost:3000/lib/angular/angular.js:1675:14)
        at http://localhost:3000/lib/angular/angular.js:3878:22
        at forEach (http://localhost:3000/lib/angular/angular.js:325:18)
        at loadModules (http://localhost:3000/lib/angular/angular.js:3872:5)
        at http://localhost:3000/lib/angular/angular.js:3879:40
        at forEach (http://localhost:3000/lib/angular/angular.js:325:18)
        at loadModules (http://localhost:3000/lib/angular/angular.js:3872:5)
        at createInjector (http://localhost:3000/lib/angular/angular.js:3812:11)
    http://errors.angularjs.org/1.2.26/$injector/modulerr?p0=mwl.calendar&p1=Er…%20(http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangular%2Fangular.js%3A3812%3A11)
        at http://localhost:3000/lib/angular/angular.js:78:12
        at http://localhost:3000/lib/angular/angular.js:3906:15
        at forEach (http://localhost:3000/lib/angular/angular.js:325:18)
        at loadModules (http://localhost:3000/lib/angular/angular.js:3872:5)
        at http://localhost:3000/lib/angular/angular.js:3879:40
        at forEach (http://localhost:3000/lib/angular/angular.js:325:18)
        at loadModules (http://localhost:3000/lib/angular/angular.js:3872:5)
        at createInjector (http://localhost:3000/lib/angular/angular.js:3812:11)
        at doBootstrap (http://localhost:3000/lib/angular/angular.js:1444:20)
        at Object.bootstrap (http://localhost:3000/lib/angular/angular.js:1459:12)
    http://errors.angularjs.org/1.2.26/$injector/modulerr?p0=proyectointegrador…%20(http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangular%2Fangular.js%3A1459%3A12) 
    angular.js:78

**Comment by mattlewis92** [comment]
Are you including my calendar code before your code which instantiates the `proyectointegrador` module?

**Comment by laugmo** [comment]
proyectointegrador is not a module it is the name of the whole project, would it help if I upload the project to github for you to see it?

**Comment by mattlewis92** [comment]
Yes please that would be great

**Comment by laugmo** [comment]
We have changed the links and angular no longer returns an error, so the error I included in my previous entry is no longer received, Thanks!  however, now we are getting this error. :

The value passed to the view attribute of the calendar is not set

The value passed to current-day attribute of the calendar is not set

Is there something we should add for it to work?

**Comment by mattlewis92** [comment]
Yes you need to set those variables. See the documentation:
https://github.com/mattlewis92/angular-bootstrap-calendar

An example controller:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/docs/scripts/demo.js

**Comment by CJBrew** [comment]
I've got the same problem. It would have been nice to see how it was fixed...

**Comment by mattlewis92** [comment]
At a guess it's because you're including the script files in the wrong order. It needs to be angular, then this calendar / any other vendor files, then your code

**Comment by CJBrew** [comment]
I think I found the issue, and I'm almost too embarrassed to say... 

```javascript
...
//= require angular-file-upload
//= require angular-rails-templates
//= moment/min/moment.min
//= angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar
//= require myApp
//= require_tree .
```

Anyway, I'm now seeing the following error on starting Rails

`ActionController::RoutingError (No route matches [GET] "/assets/angular-bootstrap-calendar/dist/js/calendarUtils.js.map"):`

**Comment by mattlewis92** [comment]
Oops, that shouldn't be included, it will be fixed in the next release: https://github.com/mattlewis92/angular-bootstrap-calendar/commit/25b131b65ac54edd62cd3618e0d14a2bfe3246f5
