### ISSUE TITLE
[Question] change calendar cell color

### ISSUE THREAD

**Issue by koz1ma** [mattlewis92/angular-bootstrap-calendar#94]
Hi,
I'm using this calendar in my work and it's a great player(thanks for making it).
Sorry for post this here but i already search in the documentation and didn't found anything related with this. There is any way where i can change the calendar cell color or add a class according to a event attribute? The cssClass attribute is just for the event popup window and not the calendar cell.
Thanks

**Comment by mattlewis92** [comment]
There isn't a way of doing this, it's quite tricky to do as the calendar cells are generated automatically and decoupled from events. Certain classes are already added to cells like so:
```
{
    'cal-day-outmonth': !day.inMonth,
    'cal-day-inmonth': day.inMonth,
    'cal-day-weekend': day.isWeekend,
    'cal-day-past': day.isPast,
    'cal-day-today': day.isToday,
    'cal-day-future': day.isFuture
}
```

What's your use case, maybe I can think of a nice solution or I'm happy to accept a PR :)

**Comment by koz1ma** [comment]
I have a table of events and with a boolean available attribute, and in case this attribute is true i want to show all calendar cells between startsAt and endsAt with green background(just like the current day color). I'm still trying to find a way to do this. If i make a solution i will make a PR :)
Thanks

**Comment by mattlewis92** [comment]
Sorry about the late reply on this one, I've come up with a nice way of implementing this which I'll release in 0.12 later today.

Relevant commit: https://github.com/mattlewis92/angular-bootstrap-calendar/commit/86d5bcfdc8325f4a24c26d5b51b292614abd714a
