### ISSUE TITLE
Custom first day of week in month view

### ISSUE THREAD

**Issue by pcavanaugh** [mattlewis92/angular-bootstrap-calendar#95]
Currently the first day of the week in month view is Sunday. This feature request would make it possible to choose which day to set as the first day of the week.

Let me know if I missed something in the documentation and this is already possible. Also, I'd be happy to work on this one myself.

**Comment by mattlewis92** [comment]
As the calendar uses moment for everything you can just set this option in moment like so:
```
moment.locale('en', {
  week : {
    dow : 1 // Monday is the first day of the week
  }
});
```
