### ISSUE TITLE
Week View Events Jump Vertically When Dragging

### ISSUE THREAD

**Issue by mgjensen** [mattlewis92/angular-bootstrap-calendar#96]
In day view, event objects that were given a top value (by having a start time occurring after the day's begin time) retain that value when switching to week view. Attempting to drag any of the affected events results in behavior as seen in the screenshot below.

I was able to fix this locally by deleting `event.top` in the `filterEventsInPeriod.map` function in `angular-bootstrap-tpls.js` (roughly line 200 in release 0.11.2)
 
![calendar bug](https://cloud.githubusercontent.com/assets/10212412/8334121/77e30488-1a53-11e5-95c4-0f2611c610e2.png)

**Comment by allbto2** [comment]
+1

**Comment by mattlewis92** [comment]
It should now be fixed in 0.11.3. Let me know if you're still having issues :)
