### ISSUE TITLE
[Feature] Being able to edit the range of event in week view

### ISSUE THREAD

**Issue by allbto2** [mattlewis92/angular-bootstrap-calendar#97]
Your calendar is awesome, modern, pretty, works great.

I would be very happy to implement it for my company. But they require to be able to edit the range of an event on the week view (like FullCalendar kinda).

Do you plan to implement it anytime ?

Thanks in advance !

**Comment by mattlewis92** [comment]
The library used for drag and drop also supports resizing of objects as well so I guess it wouldn't be too difficult to implement. Will try and find some time over the weekend to add it.

**Comment by mattlewis92** [comment]
Done in https://github.com/mattlewis92/angular-bootstrap-calendar/commit/fba268747a311fb519b82dcd99b30c9c2e5c3279 and will be released in 0.12
